//:First Aid
// Generated file, do not edit
var langTexts={
	title: "First Aid",
	back: "Back",
	continent: "Continent",
	emergency_fire: "Fire",
	emergency_medical: "Medical",
	emergency_police: "Police",
	emergency_cancelcard: "Deactive your Bankcards",
	emergency_local: "local numbers",
	emergency_nosystem: "no system",
	emergency_radioonly: "only radio telephones",
	emergency_none: "--",
	emergency_or: "or",
	emergency_mobile: "mobile",
	emergency_tourist: "tourists"
};
var langMenu=[
	{h: "#aid_disclaimer", t: "# Disclaimer + Info!"},
	{h: "#numbers", t: "# Emergency Calls"},
	{h: "#aid_general", t: "# General Conduct"},
	{h: "#aid_allergic", t: "Allergic Reaction"},
	{h: "#aid_amputation", t: "Amputation"},
	{h: "#aid_animalbite", t: "Animal bite"},
	{h: "#aid_apnoea", t: "Apnoea"},
	{h: "#aid_asthma", t: "Asthma"},
	{h: "#aid_backinjury", t: "Back Injury"},
	{h: "#aid_birth", t: "Birth"},
	{h: "#aid_bleedinglight", t: "Bleeding (light)"},
	{h: "#aid_bleedingsevere", t: "Bleeding (severe)"},
	{h: "#aid_brainconcussion", t: "Brain Concussion"},
	{h: "#aid_apnoea", t: "Breathing"},
	{h: "#aid_asthma", t: "Breathlessness"},
	{h: "#aid_burningslight", t: "Burning (slight)"},
	{h: "#aid_burningsevere", t: "Burning (severe)"},
	{h: "#aid_checkbreathing", t: "Check Breathing"},
	{h: "#aid_chemicalburn", t: "Chemical Burn"},
	{h: "#aid_chemicalburneyes", t: "Chemical Burn (Eyes)"},
	{h: "#aid_resuscitation", t: "Chest Compression"},
	{h: "#aid_suffocation", t: "Choking"},
	{h: "#aid_dangerzone", t: "Danger Zone (Rescue)"},
	{h: "#aid_diabeticcoma", t: "Diabetic Coma"},
	{h: "#aid_diarrhoea", t: "Diarrhoea"},
	{h: "#aid_drowning", t: "Drowning"},
	{h: "#aid_electricityaccident", t: "Electricity Accident"},
	{h: "#aid_emergencycall", t: "Emergency Call"},
	{h: "#aid_epilepsy", t: "Epilepsy"},
	{h: "#aid_eyeinjury", t: "Eye Injury"},
	{h: "#aid_fracture", t: "Fracture"},
	{h: "#aid_frostbitemild", t: "Frostbite (mild)"},
	{h: "#aid_frostbitesevere", t: "Frostbite (severe)"},
	{h: "#aid_heartattack", t: "Heart Attack"},
	{h: "#aid_diabeticcoma", t: "Hyperglycaemia (sugar)"},
	{h: "#aid_hyperthermia", t: "Hyperthermia (hot body)"},
	{h: "#aid_hypoglycaemia", t: "Hypoglycaemia (low sugar)"},
	{h: "#aid_hypothermia", t: "Hypothermia (cool body)"},
	{h: "#aid_icerescue", t: "Ice Rescue"},
	{h: "#aid_insectstings", t: "Insect stings"},
	{h: "#aid_nosebleeding", t: "Nosebleeding"},
	{h: "#aid_poisining", t: "Poisoning"},
	{h: "#aid_resuscitation", t: "Reanimation"},
	{h: "#aid_recoveryposition", t: "Recovery Position"},
	{h: "#aid_resuscitation", t: "Resuscitation"},
	{h: "#aid_safeguardaccident", t: "Safeguard Accident"},
	{h: "#aid_shock", t: "Shock"},
	{h: "#aid_skullfracture", t: "Skull fracture"},
	{h: "#aid_snakebite", t: "Snakebite"},
	{h: "#aid_sos", t: "SOS"},
	{h: "#aid_backinjury", t: "Spinal fracture"},
	{h: "#aid_sprain", t: "Sprain + Strain"},
	{h: "#aid_stroke", t: "Stroke"},
	{h: "#aid_suffocation", t: "Suffocation (Choking)"},
	{h: "#aid_sunburn", t: "Sunburn"},
	{h: "#aid_sunstroke", t: "Sunstroke"},
	{h: "#aid_suffocation", t: "Swallow/Choking"},
	{h: "#aid_safeguardaccident", t: "Traffic Accident"},
	{h: "#aid_unconsciouswithbreath", t: "Unconscious with breathing"},
	{h: "#aid_unconsciouswithoutbreath", t: "Unconscious without breathing"},
	{h: "#aid_vomiting", t: "Vomiting"},
	{h: "tel:112", t: "Call Emergency 112"}
];
var langSections={
	aid_disclaimer: [
		{k: "title", t: "Disclaimer + Info"},
		{k: "subsection", t: "Software"},
		{k: "description", t: "First Aid on your Mobile"},
		{k: "description", t: "Copyright: Kai Kajus Noack"},
		{k: "description", t: "Licence: Creative Commons"},
		{k: "image", i: "cc88x31"},
		{k: "description", t: "This program is supposed to give information on first aid. However, it does not represent a substitute to a first aid course. It rather serves you refreshing your already acquired knowledge."},
		{k: "description", t: "Illustrations © Med4Teens"},
		{k: "subsection", t: "Disclaimer"},
		{k: "description", t: "Please note that I take no responsibility for consequences resulting from the use of the software."},
		{k: "description", t: "ANY LIABILITY IS EXCLUDED!"},
		{k: "description", t: "USE AT YOUR OWN RISK!"},
		{k: "description", t: "In all emergencies, please seek professional help immediately."},
		{k: "subsection", t: "To save one life is to have saved the world."}
	],
	aid_general: [
		{k: "title", t: "General Conduct"},
		{k: "step", p: [{t: "Always perform first aid. You cannot make any mistakes."}]},
		{k: "step", p: [{t: "Always pay attention to your own safety."}]},
		{k: "step", p: [{t: "Examine the situation and secure the accident place."}]},
		{k: "step", p: [{t: "Emergency call + First Aid measures!"}]},
		{k: "step", p: [{t: "If there are several casualties, the treatment of the most harmed has priority."}]},
		{k: "step", p: [{t: "Always try to calm down the person concerned. Stay calm yourself!"}]},
		{k: "step", p: [{t: "If possible lay her/him down comfortably. Never give alcohol, nicotine or drugs to a person who is the victim of an accident."}]}
	],
	aid_allergic: [
		{k: "title", t: "Allergic Reaction", i: "aid046"},
		{k: "step", p: [{t: "Phone for an ambulance immediately."}]},
		{k: "step", p: [{t: "Try to calm down the casualty and let him sit comfortable."}]},
		{k: "step", p: [{t: "Remove allergic causing matter (e.g. sting of a bee) carefully."}]},
		{k: "step", p: [{t: "Cool affected skin (wet compress, ice)."}]},
		{k: "image", i: "aid046ice"},
		{k: "step", p: [{t: "If casualty has an antidote, he should use it (help him)."}]},
		{k: "step", p: [{t: "Monitor casualty's condition until ambulance arrives."}]},
		{k: "step", p: [{t: "If casualty loses consciousness or breathing stops, follow appropriate instructions!"}]},
		{k: "image", i: "aid077"}
	],
	aid_amputation: [
		{k: "title", t: "Amputation"},
		{k: "description", t: "Amputated body part can be reattached again. Goal: Keep amputated part cool until you arrive at hospital. "},
		{k: "step", p: [{t: "Calm the person, lay him/her down, and cover with blanket."}]},
		{k: "step", p: [{t: "Stop the bleeding, see 'Bleeding (severe)' and 'Shock'."}]},
		{k: "step", p: [{t: "Wrap amputated part in a clean and dry cloth, and put it into a waterproof plastic bag. "}]},
		{k: "step", p: [{t: "Close this plastic bag and put it into another plastic bag, that contains cool water/ice. "}]},
		{k: "step", p: [{t: "Do not give alcohol, cigarettes or food to casualty (in case of a surgery with anaesthesia in hospital). "}]},
		{k: "step", p: [{t: "Do not freeze the amputated part (just keep it cool). "}]},
		{k: "step", p: [{t: "Call emergency or drive casualty to hospital yourself."}]}
	],
	aid_animalbite: [
		{k: "title", t: "Animal bite", i: "aid047"},
		{k: "description", t: " Attention: High danger of infection. Result could be infection, tetanus, rabies."},
		{k: "step", p: [{t: "Wash wound with hot soapy water."}]},
		{k: "image", i: "aid049"},
		{k: "step", p: [{t: "Afterwards disinfect the wound."}]},
		{k: "step", p: [{t: "If there is severe bleeding, elevate the person's upper body."}]},
		{k: "step", p: [{t: "Apply an aseptic bandage."}]},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Go to a hospital or call emergency doctor."}]}
	],
	aid_apnoea: [
		{k: "title", t: "Apnoea"},
		{k: "description", t: " No breathing sounds or breath movements, noticeable discolouration of the skin."},
		{k: "step", p: [{t: "Emergency call."}]},
		{k: "step", p: [{t: "Lay casualty on his/her back."}]},
		{k: "step", p: [{t: "Remove any substances from the mouth and throat. Stretch head backwards."}]},
		{k: "image", i: "aid067"},
		{k: "step", p: [{t: "Pinch the nose, so that nose is closed."}]},
		{k: "image", i: "aid010"},
		{k: "step", p: [{t: "Take a deep breath and put your mouth onto the mouth of the casualty, that no air can leak."}]},
		{k: "image", i: "aid011"},
		{k: "step", p: [{t: "Breath out slowly and fully."}]},
		{k: "step", p: [{t: "If without success: Do breathing as long as ambulance arrives."}]}
	],
	aid_asthma: [
		{k: "title", t: "Asthma"},
		{k: "description", t: "Heavy breathlessness. Wheezing respiratory noise. Anxieties."},
		{k: "step", p: [{t: "Calm the person. Stay calm yourself!"}]},
		{k: "step", p: [{t: "Loosen clothing."}]},
		{k: "step", p: [{t: "Let casualty sit and lean forward, encourage him/her to breath slowly and deeply."}]},
		{k: "step", p: [{t: "If casualty has an inhalator, he should use it (help him). After 5-10 min it should take effect."}]},
		{k: "image", i: "aid074"},
		{k: "step", p: [{t: "If there is no improvement: Use inhalator every 5 min until ambulance arrives."}]},
		{k: "step", p: [{t: "Emergency call."}]},
		{k: "step", p: [{t: "If apnoea (cessation of breathing) occurs, follow instructions given for "}, {t: "apnoea", h: "#aid_apnoea"}, {t: "."}]}
	],
	aid_backinjury: [
		{k: "title", t: "Back Injury"},
		{k: "description", t: " Pain in the back, numb arms and legs."},
		{k: "step", p: [{t: "Do not move the casualty!!"}]},
		{k: "image", i: "aid064"},
		{k: "step", p: [{t: "Hold the head so that the person lies still (keep their head stationary)"}]},
		{k: "image", i: "aid065"},
		{k: "step", p: [{t: "Stabilize the casualty with bolsters on either side."}]},
		{k: "step", p: [{t: "Calm the person."}]},
		{k: "step", p: [{t: "Emergency call, point out the back injury."}]}
	],
	aid_birth: [
		{k: "title", t: "Birth"},
		{k: "description", t: " Outflow of amniotic fluid. Contraction pains occur. Unexpected birth."},
		{k: "image", i: "aid025"},
		{k: "step", p: [{t: "Pay attention to privacy and keep calm! - Emergency call."}]},
		{k: "step", p: [{t: "Let the pregnant woman bare the lower part of her body, and sit down on a sterile underlay with spread legs."}]},
		{k: "step", p: [{t: "Angle the knees. Pull up the legs. Position the basin slightly upward. - Birth is a natural process and runs mostly without complications."}]},
		{k: "step", p: [{t: "Calm the woman, let her concentrate on her breathing: Breathe in through nose, breathe out through mouth (in normal speed)."}]},
		{k: "step", p: [{t: "Rhythm of pressing: Take a deep breath, hold breath, and press. As soon as the baby's head appears, support by taking hold of it with both of your hands."}]},
		{k: "image", i: "aid021"},
		{k: "image", i: "aid022"},
		{k: "step", p: [{t: "After the childbirth: Hold the baby on a slant with head down to liberate the airways from amniotic fluid. (You may have to suck out the fluid from the baby's nose by mouth.) The baby must breathe and cry!"}]},
		{k: "step", p: [{t: "Bind off the umbilical cord 30 cm away from the child (can also be done in hospital). Keep the vagina of the mother sterile."}]},
		{k: "image", i: "aid023"},
		{k: "step", p: [{t: "Dry the baby and keep it warm. Note the time and drive to the hospital."}]}
	],
	aid_bleedinglight: [
		{k: "title", t: "Bleeding (light)", i: "aid082"},
		{k: "description", t: " Goal: Stop the bleeding."},
		{k: "step", p: [{t: "Do not touch the wound (danger of infection)."}]},
		{k: "step", p: [{t: "Do not treat wound with powder, salves or sprays."}]},
		{k: "step", p: [{t: "Wound treatment: cover with sterile material and a bandage."}]},
		{k: "image", i: "aid098"},
		{k: "step", p: [{t: "For slight bleeding a plaster is often sufficient."}]},
		{k: "step", p: [{t: "If wound is large-scale, use a wound cover and a bandage. Do not apply bandage too tight, as a stasis can lead to increased bleeding."}]},
		{k: "image", i: "aid084"},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Note: Wounds as a result of the bite from a rabid animal have to be washed with soapy solution."}]},
		{k: "image", i: "aid049"}
	],
	aid_bleedingsevere: [
		{k: "title", t: "Bleeding (severe)"},
		{k: "description", t: " Splashing, pulsating blood. Danger: Choking because of blood loss, infections, death. Goal: Stop the bleeding."},
		{k: "step", p: [{t: "Remove clothes (cut if necessary) and reveal wound."}]},
		{k: "step", p: [{t: "Wrap a bandage or, if necessary, a garment with pressure around the wound."}]},
		{k: "image", i: "aid086"},
		{k: "step", p: [{t: "Exert pressure for at least 10 min."}]},
		{k: "step", p: [{t: "If bandage is soaked with blood, do not remove it. Instead wrap another bandage/garment around it."}]},
		{k: "step", p: [{t: "Place the affected limb (if not broken) higher than the heart to reduce amount of blood pressure. If possible lay down casualty."}]},
		{k: "step", p: [{t: "If bleeding does not stop, keep pressure on wound, and set additional pressure point on wound: For a bleeding of the forearm compress the upper arm (press vein at inner side of arm, in the middle of elbow and arm-pit, using your fingers). For bleeding of leg, set pressure point in groin (press vein at crook of groin, where artery leads over pelvic bone, using the ball of your hand)."}]},
		{k: "image", i: "aid089"},
		{k: "image", i: "aid092"},
		{k: "step", p: [{t: "Call emergency doctor immediately."}]},
		{k: "step", p: [{t: "As soon as bleeding is under control: Initiate anti-shocking measures."}]},
		{k: "image", i: "aid093"}
	],
	aid_brainconcussion: [
		{k: "title", t: "Brain Concussion"},
		{k: "description", t: " Headache, nausea, vomiting. Impaired vision. Unconsciousness can occur."},
		{k: "image", i: "aid035a"},
		{k: "step", p: [{t: "Lay down person concerned."}]},
		{k: "step", p: [{t: "Emergency call."}]},
		{k: "description", t: " If bleeding from head:"},
		{k: "step", p: [{t: "Lay down casualty, with the head elevated (on pillow)."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Do wound-treatment (use head-bandage)."}]},
		{k: "step", p: [{t: "Emergency call."}]}
	],
	aid_burningslight: [
		{k: "title", t: "Burning (slight)"},
		{k: "description", t: " Redness of skin. Mild swellings. Pain."},
		{k: "step", p: [{t: "Hold area involved under cool water."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Apply wet bandage loosely."}]}
	],
	aid_burningsevere: [
		{k: "title", t: "Burning (severe)"},
		{k: "description", t: " Spotted white-red areas, blistering. Skin loses fluid. Deep damage of tissue. Strong pain or no pain (because of burned nerves)."},
		{k: "image", i: "aid097"},
		{k: "step", p: [{t: "Remove clothes as much as possible."}]},
		{k: "step", p: [{t: "Cool burned body parts with water (about 15°C, 59°F) up to 10 min, until pain reduces."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "If burning is extensive, just use wet cloths to cool."}]},
		{k: "step", p: [{t: "Emergency call."}]},
		{k: "step", p: [{t: "After cooling, do the wound treatment: Use a sterile dressing. Do not apply fluids (no creams, oils, ointments etc.). Do not pierce the blisters."}]},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Control breathing and consciousness of the person until emergency doctor arrives."}]}
	],
	aid_checkbreathing: [
		{k: "title", t: "Check Breathing"},
		{k: "step", p: [{t: "Check breathing sounds."}]},
		{k: "step", p: [{t: "Diagnose breathing in the upper abdomen (lay your hand on it)."}]},
		{k: "image", i: "aid027"},
		{k: "step", p: [{t: "Sense breathing at nose and mouth."}]}
	],
	aid_chemicalburneyes: [
		{k: "title", t: "Chemical Burn (Eyes)"},
		{k: "step", p: [{t: "Emergency call, point out chemicals."}]},
		{k: "step", p: [{t: "Flush eye with much water. Cover healthy eye during flushing."}]},
		{k: "step", p: [{t: "Lead the water jet from inner angle of eye to outer angle of eye. Clean for at least 20 min under clear water."}]},
		{k: "image", i: "aid019"},
		{k: "step", p: [{t: "Close both eyes of the casualty and bind with wet cloth."}]},
		{k: "image", i: "aid020"},
		{k: "step", p: [{t: "Monitor condition until ambulance arrives."}]}
	],
	aid_chemicalburn: [
		{k: "title", t: "Chemical Burn"},
		{k: "description", t: " Injury of tissue."},
		{k: "image", i: "aid095"},
		{k: "step", p: [{t: "Mind self-protection!"}]},
		{k: "step", p: [{t: "Act quickly and wash the burned locations."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Emergency call."}]},
		{k: "step", p: [{t: "If there is a chemical burn of the digestive tract, particularly the mouth and throat, drink a lot of water."}]},
		{k: "step", p: [{t: "Do not cause vomiting!"}]}
	],
	aid_dangerzone: [
		{k: "title", t: "Danger Zone (Rescue)"},
		{k: "step", p: [{t: "Grip execution: Position one arm of the injured in front of his/her chest, and get behind him/her."}]},
		{k: "step", p: [{t: "Put your hands under the shoulders of the wounded, grabbing the angled arm."}]},
		{k: "step", p: [{t: "Pull back and carry the person into safety."}]},
		{k: "image", i: "aid001"},
		{k: "image", i: "aid007"}
	],
	aid_diabeticcoma: [
		{k: "title", t: "Diabetic Coma"},
		{k: "description", t: " Blood sugar level is too high (resp. lack of insulin)."},
		{k: "description", t: " Symptoms: Thirst, frequent urination, nausea, vomit. Breath smells of fruits/wine."},
		{k: "step", p: [{t: "Call emergency."}]},
		{k: "step", p: [{t: "Support casualty (if confirmed as diabetic) taking insulin."}]},
		{k: "image", i: "aid016"},
		{k: "step", p: [{t: "Recovery position.", h: "#aid_recoveryposition"}, {t: " (No further possibilities for the first aider.)"}]},
		{k: "step", p: [{t: "Monitor the condition of the casualty until emergency doctor arrives."}]}
	],
	aid_diarrhoea: [
		{k: "title", t: "Diarrhoea"},
		{k: "description", t: "Reaction to contaminated food, infection of intestine or disorder. Stool is diluted, slimy or bloody."},
		{k: "step", p: [{t: "Danger for the circulation because of dehydration and loss of salt!"}]},
		{k: "step", p: [{t: "Give liquids (tea, water)."}]},
		{k: "step", p: [{t: "If there are strong disorders call the emergency doctor."}]}
	],
	aid_drowning: [
		{k: "title", t: "Drowning"},
		{k: "step", p: [{t: "Call emergency. Ask people next to you for help."}]},
		{k: "image", i: "aid032"},
		{k: "step", p: [{t: "Rescue person out of water!"}]},
		{k: "image", i: "aid033"},
		{k: "image", i: "aid034"},
		{k: "step", p: [{t: "If casualty is breathing: "}, {t: "Recovery position.", h: "#aid_recoveryposition"}, {t: " Keep him/her warm (cover). Monitor condition until emergency doctor arrives."}]},
		{k: "step", p: [{t: "If casualty is not breathing: Immediately start with "}, {t: "resuscitation!", h: "#aid_resuscitation"}, {t: " (Ejecting water from the lungs is useless.)"}]}
	],
	aid_electricityaccident: [
		{k: "title", t: "Electricity Accident"},
		{k: "step", p: [{t: "Firstly interrupt the electricity supply!"}]},
		{k: "image", i: "aid045plug"},
		{k: "image", i: "aid045"},
		{k: "step", p: [{t: "Danger: Unconsciousness, apnoea."}]},
		{k: "step", p: [{t: "A - Unconsciousness with breathing", h: "#aid_unconsciouswithbreath"}]},
		{k: "step", p: [{t: "B - Unconsciousness without breathing", h: "#aid_unconsciouswithoutbreath"}]},
		{k: "image", i: "aid042"},
		{k: "image", i: "aid043"}
	],
	aid_emergencycall: [
		{k: "title", t: "Emergency Call"},
		{k: "step", p: [{t: "Dial 112 with the next available phone (USA: 911). Always possible and for free! Do not hesitate to call for an ambulance!"}]},
		{k: "step", p: [{t: "On the phone you must provide the following information:"}]},
		{k: "step", p: [{t: "- What has happened "}]},
		{k: "step", p: [{t: "- Where (accident place) "}]},
		{k: "step", p: [{t: "- How many casualties "}]},
		{k: "step", p: [{t: "- What kind of injuries. "}]},
		{k: "step", p: [{t: "Afterwards wait for further instructions or queries."}]}
	],
	aid_epilepsy: [
		{k: "title", t: "Epilepsy"},
		{k: "description", t: " Rigid body, clenched fists, pressed jaw, twitching in limbs or face. Rolling eyes. Salivation. Unconsciousness possible."},
		{k: "image", i: "aid058"},
		{k: "step", p: [{t: "Do not hold the casualty or restrain their movement."}]},
		{k: "step", p: [{t: "Lay the casualty on a soft base (cushion), remove close objects to prevent self-injury."}]},
		{k: "step", p: [{t: "Calm down the casualty. Loosen clothing, provide freedom to breath."}]},
		{k: "step", p: [{t: "If casualty vomits, turn their head to the side so that vomit can drain."}]},
		{k: "step", p: [{t: "Keep airways clear. Danger of swallowing the tongue."}]},
		{k: "step", p: [{t: "Recovery Position", h: "#aid_recoveryposition"}, {t: " + Emergency call. Continue monitoring the casualty's condition."}]},
		{k: "step", p: [{t: "Keep other people at distance."}]}
	],
	aid_eyeinjury: [
		{k: "title", t: "Eye Injury"},
		{k: "step", p: [{t: "Leave object in the eye of casualty, do not remove it."}]},
		{k: "step", p: [{t: "Keep eyes motionless to avoid further injuries. Do not touch the eye."}]},
		{k: "step", p: [{t: "If eye is bleeding, cover it with a compress or a sterile gauze."}]},
		{k: "image", i: "aid020"},
		{k: "step", p: [{t: "Cool the eye with a cold pad (reduces swelling, bleeding stops quicker)."}]},
		{k: "step", p: [{t: "Emergency call or drive casualty to hospital yourself."}]}
	],
	aid_fracture: [
		{k: "title", t: "Fracture"},
		{k: "description", t: " Symptoms: Unnatural position and movability of bone. Deformation. Painful movement, touch-sensitive."},
		{k: "image", i: "aid104"},
		{k: "step", p: [{t: "Avoid movements!"}]},
		{k: "step", p: [{t: "Emergency call."}]},
		{k: "step", p: [{t: "Immobilize the fractured bone, i.e. bolster material around bone tightly. Keep position of the bone."}]},
		{k: "image", i: "aid107"},
		{k: "step", p: [{t: "If fracture is open, cover the wound with sterile material."}]},
		{k: "image", i: "aid106"}
	],
	aid_frostbitemild: [
		{k: "title", t: "Frostbite (mild)"},
		{k: "description", t: " Paleness, swellings. Danger for blood supply."},
		{k: "step", p: [{t: "Move casualty into a warm area."}]},
		{k: "step", p: [{t: "Get away from cold, remove cold clothes, dry person."}]},
		{k: "step", p: [{t: "Warm up with lukewarm water and with body heat of the helper."}]},
		{k: "step", p: [{t: "Give warm drink (tea). No alcohol!"}]},
		{k: "image", i: "aid040"}
	],
	aid_frostbitesevere: [
		{k: "title", t: "Frostbite (severe)"},
		{k: "description", t: " Cold hard skin, grey-white, blistering, tissue dies off. Danger for blood supply!"},
		{k: "image", i: "aid096"},
		{k: "step", p: [{t: "Go to warm area."}]},
		{k: "step", p: [{t: "Wound treatment/covering."}]},
		{k: "step", p: [{t: "Give a sugary drink."}]},
		{k: "step", p: [{t: "Do not rub the casualty to warm them!"}]},
		{k: "step", p: [{t: "Emergency call."}]}
	],
	aid_heartattack: [
		{k: "title", t: "Heart Attack"},
		{k: "description", t: " Heavy, more than 5 min lasting pressure and pain in the chest, particularly radiating in the arms/shoulders. Anxiety, paleness, cold sweat. Possibly nausea, shortness of breath."},
		{k: "image", i: "aid076"},
		{k: "image", i: "aid083"},
		{k: "step", p: [{t: "Emergency call! Point out the supposed heart attack."}]},
		{k: "step", p: [{t: "Position with the upper body elevated. Loosen tight clothing. Do not give drugs or drinks."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Talk calmly to the person concerned."}]},
		{k: "step", p: [{t: "Control consciousness and breathing."}]},
		{k: "step", p: [{t: "Give aspirin if available."}]},
		{k: "step", p: [{t: "If person becomes unconscious, start "}, {t: "resuscitation", h: "#aid_resuscitation"}, {t: "."}]}
	],
	aid_hypoglycaemia: [
		{k: "title", t: "Hypoglycaemia (low sugar)"},
		{k: "description", t: "Blood sugar level is below minimum value (because of overdose of insulin or insufficient intake of food)."},
		{k: "description", t: "Symptoms: Paleness, nervousness, hunger, shivering, sweating."},
		{k: "image", i: "aid018"},
		{k: "step", p: [{t: "Make sure that the person is a diabetic (look for a diabetic badge)."}]},
		{k: "step", p: [{t: "Emergency call."}]},
		{k: "step", p: [{t: "Give a sugary drink and dextrose/glucose (if there are no problems in swallowing)."}]},
		{k: "image", i: "aid017"},
		{k: "step", p: [{t: "If person is conscious and breathing: "}, {t: "Recovery position.", h: "#aid_recoveryposition"}, {t: " Monitor breathing of the person. If apnoea appears, start with breath giving."}]},
		{k: "step", p: [{t: "If there is breathing, you can put a lump of sugar into the cheek pouch, push from outside against it."}]}
	],
	aid_hyperthermia: [
		{k: "title", t: "Hyperthermia (hot body)"},
		{k: "description", t: " Thirst, weakness, disorientation, nausea, confusion, strong sweating, hot skin."},
		{k: "image", i: "aid035"},
		{k: "step", p: [{t: "Emergency call."}]},
		{k: "step", p: [{t: "Find a cool shady place (room with air conditioning preferable)."}]},
		{k: "step", p: [{t: "Lay down person, elevate legs. Loosen clothing."}]},
		{k: "image", i: "aid078"},
		{k: "step", p: [{t: "Cool skin with cold water or lay on cold towels."}]},
		{k: "step", p: [{t: "Give plenty of water or juices to drink."}]}
	],
	aid_hypothermia: [
		{k: "title", t: "Hypothermia (cool body)"},
		{k: "description", t: " Cold shiver, drowsiness, exhaustion up to unconsciousness. Cold pale skin. Slow pulse, weak heartbeat."},
		{k: "image", i: "aid014"},
		{k: "step", p: [{t: "Go to a warm area/room."}]},
		{k: "step", p: [{t: "Call emergency."}]},
		{k: "step", p: [{t: "Increase body temperature (cover and body-to-body-contact)."}]},
		{k: "step", p: [{t: "Remove wet clothes and put on warm clothes. Cover with blankets or other covers. Cover the head."}]},
		{k: "step", p: [{t: "Give hot tea, soup or hot water to drink. No alcohol! Keep person awake."}]},
		{k: "image", i: "aid039"},
		{k: "image", i: "aid040"},
		{k: "step", p: [{t: "Monitor casualty's condition until emergency doctor arrives. If person becomes unconscious, initiate resuscitation:"}]},
		{k: "step", p: [{t: "A - Unconsciousness with breathing", h: "#aid_unconsciouswithbreath"}]},
		{k: "step", p: [{t: "B - Unconsciousness without breathing", h: "#aid_unconsciouswithoutbreath"}]}
	],
	aid_icerescue: [
		{k: "title", t: "Ice Rescue"},
		{k: "description", t: " Pay attention to your own safety. Danger: Drowning, Hypothermia."},
		{k: "step", p: [{t: "Ask other people for help. Call for an emergency ambulance."}]},
		{k: "step", p: [{t: "Rescue via ladder, board or bar. Weight must be distributed evenly."}]},
		{k: "step", p: [{t: "Crawl carefully on your front along the support (if possible roped to a stable point) with a pole or similar tool."}]},
		{k: "image", i: "aid041"},
		{k: "step", p: [{t: "Reach to the person with the pole or other tool (not your hand!), encourage him/her to take hold of it and pull him/her out."}]},
		{k: "step", p: [{t: "Crawl backwards back to the edge."}]},
		{k: "step", p: [{t: "First-Aid measures."}]},
		{k: "step", p: [{t: "Self-rescue possible: If ice is solid, you can distribute your weight on the ice and pull yourself out. Crawl flat on your front to the edge. If ice is fragile, try to break the ice piece by piece up to the edge."}]}
	],
	aid_insectstings: [
		{k: "title", t: "Insect stings", i: "aid046"},
		{k: "description", t: " Swelling, skin rash, burning feeling, weakness, difficult breathing, decreased consciousness, tachycardia."},
		{k: "step", p: [{t: "Remove sting carefully (with a tweezer). Do not squeeze the sting as this could inject more venom."}]},
		{k: "step", p: [{t: "Cool concerned spot (apply a cold compress)."}]},
		{k: "step", p: [{t: "Concerned area should be kept lower than the heart to slow circulation of the venom."}]},
		{k: "step", p: [{t: "If stung in mouth/jaw area: Suck ice-cream, and apply a cold compress around throat."}]},
		{k: "image", i: "aid046ice"},
		{k: "step", p: [{t: "If severe problems, notably difficulty in breathing or decreased consciousness, occur, call an ambulance immediately."}]}
	],
	aid_nosebleeding: [
		{k: "title", t: "Nosebleeding"},
		{k: "description", t: " Burst small artery in the nose."},
		{k: "step", p: [{t: "Sit the person down, leaning slightly forward. Keep head straight."}]},
		{k: "step", p: [{t: "Do not position the person flat, as head over height of heart slows down bleeding."}]},
		{k: "step", p: [{t: "Place cooling material round neck (wet cloth)."}]},
		{k: "step", p: [{t: "Pinch nostrils together until bleeding stops (for 10 min)."}]},
		{k: "step", p: [{t: "Afterwards do not strain the nose (no snorting)."}]},
		{k: "step", p: [{t: "If severe problems occur or bleeding cannot be stopped, call emergency doctor."}]}
	],
	aid_poisining: [
		{k: "title", t: "Poisoning", i: "aid052"},
		{k: "description", t: " Confusion, hallucinations, enlarged pupils, fever, cramps. Unconsciousness."},
		{k: "step", p: [{t: "Only give antidotes if you are accompanied by a trained medic."}]},
		{k: "image", i: "aid056"},
		{k: "step", p: [{t: "Do not give drinks. Do not cause vomiting."}]},
		{k: "step", p: [{t: "Emergency call + point out the poisoning!"}]},
		{k: "step", p: [{t: "Safeguard rest of poison and the vomit!"}]},
		{k: "image", i: "aid054a"},
		{k: "step", p: [{t: "If casualty is conscious and breathing: "}, {t: "Recovery position.", h: "#aid_recoveryposition"}, {t: " Monitor condition until emergency doctor arrives."}]},
		{k: "step", p: [{t: "If casualty is not breathing: Immediately start with "}, {t: "resuscitation!", h: "#aid_resuscitation"}, {t: " Free mouth from vomit beforehand."}]}
	],
	aid_recoveryposition: [
		{k: "title", t: "Recovery Position"},
		{k: "step", p: [{t: "Lay casualty on her/his back, straighten legs. Knee beside him/her."}]},
		{k: "step", p: [{t: "Place arm nearest to you at a right angle to the body."}]},
		{k: "step", p: [{t: "Pull arm furthest from you across the chest and place the back of the hand against cheek."}]},
		{k: "image", i: "aid008"},
		{k: "step", p: [{t: "Get the far knee, pull it to your side, and lay it on the ground. Position the leg at a right angle. Keep casualty's hand under the cheek of the person."}]},
		{k: "step", p: [{t: "Make sure the airways are free."}]},
		{k: "step", p: [{t: "Open mouth slightly, and position the head to the side so that vomit can drain. Check breathing."}]},
		{k: "image", i: "aid009"},
		{k: "step", p: [{t: "Control the casualty's condition until the emergency doctor arrives."}]},
		{k: "description", t: "Recovery position for babies:"},
		{k: "image", i: "aid028"}
	],
	aid_resuscitation: [
		{k: "title", t: "Resuscitation"},
		{k: "subsection", t: "#Heart Massage"},
		{k: "step", p: [{t: "Lay casualty on his/her back. Kneel beside person."}]},
		{k: "step", p: [{t: "Bare the chest."}]},
		{k: "step", p: [{t: "Place the heel of the hand in the middle of the chest (just over sternum)."}]},
		{k: "image", i: "aid013"},
		{k: "step", p: [{t: "Place other hand on the back of the hand which is already in position."}]},
		{k: "step", p: [{t: "Extend your arms and elbows."}]},
		{k: "image", i: "aid003"},
		{k: "step", p: [{t: "Press 5 cm deep into the person's chest (power comes from upper part of the body) and release."}]},
		{k: "step", p: [{t: "Push 30 times in a row shortly and strongly!"}]},
		{k: "subsection", t: "#Breathing"},
		{k: "step", p: [{t: "Remove any substances out of mouth and throat. Stretch head backwards."}]},
		{k: "image", i: "aid067"},
		{k: "step", p: [{t: "Pinch the nose together, so that nose is closed."}]},
		{k: "image", i: "aid010"},
		{k: "step", p: [{t: "Take a deep breath and put your mouth onto the mouth of the casualty, that no air can leak."}]},
		{k: "image", i: "aid011"},
		{k: "step", p: [{t: "Do mouth-to-mouth breathing two times (breath out slowly and fully)."}]},
		{k: "step", p: [{t: "Afterwards do heart massage again."}]},
		{k: "description", t: "Repeat heart massage + mouth-breathing until the emergency doctor arrives."},
		{k: "image", i: "aid012"},
		{k: "subsection", t: "Resuscitation (Baby)"},
		{k: "step", p: [{t: "Only use two fingers:"}]},
		{k: "image", i: "aid029"},
		{k: "step", p: [{t: "Do not breath too strong:"}]},
		{k: "image", i: "aid030"}
	],
	aid_safeguardaccident: [
		{k: "title", t: "Safeguard Accident"},
		{k: "step", p: [{t: "Stop your own car 50-100 m behind the accident site (if you are on a highway or country road). Switch on warning lights. Put on high visibility vest."}]},
		{k: "step", p: [{t: "Position the warning triangle before the accident site. Attention: If accident is on a curve position the warning triangle before the curve!"}]},
		{k: "image", i: "aid111"},
		{k: "step", p: [{t: "Ask other people for their help."}]},
		{k: "step", p: [{t: "Open the door of the accident car (if jammed, prise it open using a car jack). Turn off ignition."}]},
		{k: "step", p: [{t: "Rescue the accident victim: Unstrap seat-belt, move seat backwards. Free the casualty out of the car "}, {t: "by rescue grip", h: "#aid_dangerzone"}, {t: "."}]},
		{k: "image", i: "aid001"},
		{k: "step", p: [{t: "Emergency call."}]},
		{k: "step", p: [{t: "Proceed with first aid measures."}]}
	],
	aid_shock: [
		{k: "title", t: "Shock"},
		{k: "description", t: " Circulatory disorder by poor oxygen supply in the body."},
		{k: "description", t: "Cause: Loss of fluid, reduced blood volume."},
		{k: "description", t: "Symptoms: Paleness, cold skin, cold sweat, anxiety."},
		{k: "step", p: [{t: "Eliminate the cause of the shock (e.g. stop the fluid loss, bind the wound)!"}]},
		{k: "step", p: [{t: "Lay the wounded person on a blanket, raising the legs. Calm the person."}]},
		{k: "image", i: "aid078"},
		{k: "step", p: [{t: "Emergency call."}]},
		{k: "step", p: [{t: "If difficulties in breathing or consciousness, initiate "}, {t: "resuscitation", h: "#aid_resuscitation"}, {t: "."}]}
	],
	aid_skullfracture: [
		{k: "title", t: "Skull fracture"},
		{k: "description", t: " Light bleeding from nose, mouth or ear. Often open wounds on skull."},
		{k: "step", p: [{t: "Keep the airways free."}]},
		{k: "step", p: [{t: "If conscious: Let the injured sit with head bowed forwards. Avoid further movements!"}]},
		{k: "step", p: [{t: "If unconscious: "}, {t: "Recovery position", h: "#aid_recoveryposition"}, {t: " (no pressure on wound of head)."}]},
		{k: "step", p: [{t: "Emergency call."}]},
		{k: "step", p: [{t: "Apply head bandage."}]},
		{k: "step", p: [{t: "If difficulties in breathing or consciousness, initiate "}, {t: "resuscitation", h: "#aid_resuscitation"}, {t: "."}]}
	],
	aid_snakebite: [
		{k: "title", t: "Snakebite", i: "aid051"},
		{k: "description", t: " Puncture wound the size of a pin, severe pains, swelling, purple colour. Circulatory disturbance, danger of shock."},
		{k: "step", p: [{t: "Steady the wounded part of the body."}]},
		{k: "step", p: [{t: "Apply cold material around bite wound."}]},
		{k: "step", p: [{t: "Take measures against shock."}]},
		{k: "step", p: [{t: "Emergency call."}]}
	],
	aid_sos: [
		{k: "title", t: "SOS"},
		{k: "step", p: [{t: "Signal: 3x short, 3x long, 3x short."}]},
		{k: "step", p: [{t: "Optically (strobe light, flashlight), or acoustically (signal whistle, knocking)."}]}
	],
	aid_sprain: [
		{k: "title", t: "Sprain + Strain"},
		{k: "description", t: " Pain, swelling (bruise), loss of function, deformation of the limb."},
		{k: "step", p: [{t: "Place the injured part of the body in the position most comfortable for the casualty."}]},
		{k: "step", p: [{t: "Cool (using ice packs)."}]},
		{k: "step", p: [{t: "If possible, position the injured part elevated."}]},
		{k: "step", p: [{t: "Go to hospital or call emergency doctor."}]}
	],
	aid_stroke: [
		{k: "title", t: "Stroke"},
		{k: "description", t: " Sudden feeling of paralysis or numbness (face, arm, leg), disturbances in language understanding, vision problems, disturbed consciousness, severe headache. Problems in breathing and swallowing, loss of control over bladder and intestine."},
		{k: "image", i: "aid059"},
		{k: "step", p: [{t: "Emergency call!"}]},
		{k: "step", p: [{t: "Loosen tight clothing. Do not give drugs or drinks."}]},
		{k: "step", p: [{t: "Sit or lay down person concerned comfortably. Calm him/her!"}]},
		{k: "step", p: [{t: "Control consciousness and breathing."}]},
		{k: "step", p: [{t: "If difficulties in breathing or consciousness, initiate "}, {t: "resuscitation.", h: "#aid_resuscitation"}]}
	],
	aid_suffocation: [
		{k: "title", t: "Suffocation (Choking)"},
		{k: "description", t: " Insufficient oxygen supply. Trachea closed. Danger: Apnoea."},
		{k: "description", t: "Symptoms: Wheezing respiratory noise, cough stimulus, shortness of breath, skin discolouration."},
		{k: "image", i: "aid066"},
		{k: "step", p: [{t: "Immediate action! Let the person concerned cough very strongly."}]},
		{k: "step", p: [{t: "Strike strongly with a flat hand on the back between the shoulder blades (lay babies on your forearm, with head down)."}]},
		{k: "image", i: "aid068"},
		{k: "image", i: "aid031"},
		{k: "step", p: [{t: "If without success: Stand behind person, arms around waist, bow slightly forward."}]},
		{k: "step", p: [{t: "Clench your fist, position it at height of person's stomach, and take it with your other hand."}]},
		{k: "image", i: "aid069"},
		{k: "step", p: [{t: "In embrace use both hands to give a hard blow upwards towards stomach (as if you would try to lift the person)."}]},
		{k: "step", p: [{t: "Repeat this up to 5 times! Airways should get free from object."}]},
		{k: "step", p: [{t: "Emergency call."}]},
		{k: "step", p: [{t: "If first aid measure is unsuccessful at first, keep on doing it until emergency doctor arrives."}]}
	],
	aid_sunburn: [
		{k: "title", t: "Sunburn"},
		{k: "step", p: [{t: "Remove affected person from direct sunlight. Avoid further sun."}]},
		{k: "step", p: [{t: "Drink much water to stop dehydration."}]},
		{k: "step", p: [{t: "If there is a serious sunburn (blisters, redness, pain), seek medical advice."}]},
		{k: "step", p: [{t: "If the skin is just lightly red, it can be cooled with wet compresses. Use after-sun lotion or gel."}]}
	],
	aid_sunstroke: [
		{k: "title", t: "Sunstroke"},
		{k: "description", t: " Hot red head, cool skin, sickness, headache, dizziness. Cause: Irritation of the cerebral membrane."},
		{k: "image", i: "aid035"},
		{k: "step", p: [{t: "Go to a cool place (shadow) and position the upper body of the person up."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Cool the head with wet blankets."}]},
		{k: "step", p: [{t: "Emergency call, keep controlling the breathing."}]},
		{k: "step", p: [{t: "If conscious: Give cool drink if applicable."}]},
		{k: "step", p: [{t: "If apnoea appears, start with breathing:"}]},
		{k: "step", p: [{t: "Go on with Breath Giving!", h: "#aid_apnoea"}]},
		{k: "image", i: "aid036"}
	],
	aid_unconsciouswithbreath: [
		{k: "title", t: "Unconscious with breathing"},
		{k: "description", t: "No reaction on loudly asking, no response on shaking. Breathing does exist."},
		{k: "image", i: "aid057"},
		{k: "step", p: [{t: "If there are people next to you ask for help."}]},
		{k: "step", p: [{t: "Recovery position.", h: "#aid_recoveryposition"}, {t: " Open mouth and position head this way that vomit can drain."}]},
		{k: "image", i: "aid008"},
		{k: "image", i: "aid009"},
		{k: "step", p: [{t: "Emergency call."}]}
	],
	aid_unconsciouswithoutbreath: [
		{k: "title", t: "Unconscious without breathing"},
		{k: "step", p: [{t: "No reaction of casualty, no breathing."}]},
		{k: "image", i: "aid057"},
		{k: "step", p: [{t: "Initiate Resuscitation.", h: "#aid_resuscitation"}]}
	],
	aid_vomiting: [
		{k: "title", t: "Vomiting"},
		{k: "description", t: " Arises from nausea. Stomach empties itself. Causes: Infection, poisoning, ulcer, drugs, bad food, pregnancy."},
		{k: "image", i: "aid054"},
		{k: "step", p: [{t: "Danger for the circulation because of dehydration and loss of salt!"}]},
		{k: "step", p: [{t: "Give liquids (tea, water)."}]},
		{k: "step", p: [{t: "If there are strong disorders, bloody or continuous vomiting, call the emergency doctor."}]}
	]
};
var langContinents=[
	{i: "Africa", t: "Africa"},
	{i: "Asia", t: "Asia"},
	{i: "Europe", t: "Europe"},
	{i: "Northamerica", t: "North-/Central-America"},
	{i: "Oceania", t: "Oceania"},
	{i: "Southamerica", t: "South-America"}
];
var langCountries=[
	{i: "afghanistan", t: "Afghanistan"},
	{i: "albania", t: "Albania"},
	{i: "algeria", t: "Algeria"},
	{i: "andorra", t: "Andorra"},
	{i: "angola", t: "Angola"},
	{i: "antiguaandbarbuda", t: "Antigua and Barbuda"},
	{i: "argentina", t: "Argentina"},
	{i: "armenia", t: "Armenia"},
	{i: "australia", t: "Australia"},
	{i: "austria", t: "Austria"},
	{i: "azerbaijan", t: "Azerbaijan"},
	{i: "bahamas", t: "Bahamas"},
	{i: "bahrain", t: "Bahrain"},
	{i: "bangladesh", t: "Bangladesh"},
	{i: "barbados", t: "Barbados"},
	{i: "belarus", t: "Belarus"},
	{i: "belgium", t: "Belgium"},
	{i: "belize", t: "Belize"},
	{i: "benin", t: "Benin"},
	{i: "bhutan", t: "Bhutan"},
	{i: "bolivia", t: "Bolivia"},
	{i: "bosniaandherzegovina", t: "Bosnia and Herzegovina"},
	{i: "botswana", t: "Botswana"},
	{i: "brazil", t: "Brazil"},
	{i: "brunei", t: "Brunei"},
	{i: "bulgaria", t: "Bulgaria"},
	{i: "burkinafaso", t: "Burkina Faso"},
	{i: "burundi", t: "Burundi"},
	{i: "cambodia", t: "Cambodia"},
	{i: "cameroon", t: "Cameroon"},
	{i: "canada", t: "Canada"},
	{i: "capeverde", t: "Cape Verde"},
	{i: "caymanislands", t: "Cayman Islands"},
	{i: "centralafricanrepublic", t: "Central African Republic"},
	{i: "chad", t: "Chad"},
	{i: "chile", t: "Chile"},
	{i: "china", t: "China"},
	{i: "colombia", t: "Colombia"},
	{i: "comoros", t: "Comoros"},
	{i: "congodemocraticrepublic", t: "Congo (Democratic Republic)"},
	{i: "congorepublic", t: "Congo (Republic)"},
	{i: "costarica", t: "Costa Rica"},
	{i: "croatia", t: "Croatia"},
	{i: "cuba", t: "Cuba"},
	{i: "cyprus", t: "Cyprus"},
	{i: "czechrepublic", t: "Czech Republic"},
	{i: "denmark", t: "Denmark"},
	{i: "djibouti", t: "Djibouti"},
	{i: "dominica", t: "Dominica"},
	{i: "dominicanrepublic", t: "Dominican Republic"},
	{i: "easttimor", t: "East Timor"},
	{i: "ecuador", t: "Ecuador"},
	{i: "egypt", t: "Egypt"},
	{i: "elsalvador", t: "El Salvador"},
	{i: "equatorialguinea", t: "Equatorial Guinea"},
	{i: "eritrea", t: "Eritrea"},
	{i: "estonia", t: "Estonia"},
	{i: "ethiopia", t: "Ethiopia"},
	{i: "fiji", t: "Fiji"},
	{i: "finland", t: "Finland"},
	{i: "france", t: "France"},
	{i: "gabon", t: "Gabon"},
	{i: "gambia", t: "Gambia"},
	{i: "georgia", t: "Georgia"},
	{i: "germany", t: "Germany"},
	{i: "ghana", t: "Ghana"},
	{i: "greece", t: "Greece"},
	{i: "greenland", t: "Greenland"},
	{i: "grenada", t: "Grenada"},
	{i: "guatemala", t: "Guatemala"},
	{i: "guinea", t: "Guinea"},
	{i: "guinea-bissau", t: "Guinea-Bissau"},
	{i: "guyana", t: "Guyana"},
	{i: "haiti", t: "Haiti"},
	{i: "honduras", t: "Honduras"},
	{i: "hongkong", t: "Hong Kong"},
	{i: "hungary", t: "Hungary"},
	{i: "iceland", t: "Iceland"},
	{i: "india", t: "India"},
	{i: "indonesia", t: "Indonesia"},
	{i: "iran", t: "Iran"},
	{i: "iraq", t: "Iraq"},
	{i: "ireland", t: "Ireland"},
	{i: "israel", t: "Israel"},
	{i: "italy", t: "Italy"},
	{i: "ivorycoast", t: "Ivory Coast"},
	{i: "jamaica", t: "Jamaica"},
	{i: "japan", t: "Japan"},
	{i: "jordan", t: "Jordan"},
	{i: "kazakhstan", t: "Kazakhstan"},
	{i: "kenya", t: "Kenya"},
	{i: "kiribati", t: "Kiribati"},
	{i: "kosovo", t: "Kosovo"},
	{i: "kurdistan", t: "Kurdistan"},
	{i: "kuwait", t: "Kuwait"},
	{i: "kyrgyzstan", t: "Kyrgyzstan"},
	{i: "laos", t: "Laos"},
	{i: "latvia", t: "Latvia"},
	{i: "lebanon", t: "Lebanon"},
	{i: "lesotho", t: "Lesotho"},
	{i: "liberia", t: "Liberia"},
	{i: "libya", t: "Libya"},
	{i: "liechtenstein", t: "Liechtenstein"},
	{i: "lithuania", t: "Lithuania"},
	{i: "luxembourg", t: "Luxembourg"},
	{i: "macau", t: "Macau"},
	{i: "macedonia", t: "Macedonia"},
	{i: "madagascar", t: "Madagascar"},
	{i: "malawi", t: "Malawi"},
	{i: "malaysia", t: "Malaysia"},
	{i: "maldives", t: "Maldives"},
	{i: "mali", t: "Mali"},
	{i: "malta", t: "Malta"},
	{i: "marshallislands", t: "Marshall Islands"},
	{i: "mauritania", t: "Mauritania"},
	{i: "mauritius", t: "Mauritius"},
	{i: "mayotte", t: "Mayotte"},
	{i: "mexico", t: "Mexico"},
	{i: "micronesia", t: "Micronesia"},
	{i: "moldova", t: "Moldova"},
	{i: "monaco", t: "Monaco"},
	{i: "mongolia", t: "Mongolia"},
	{i: "montenegro", t: "Montenegro"},
	{i: "morocco", t: "Morocco"},
	{i: "mozambique", t: "Mozambique"},
	{i: "myanmar", t: "Myanmar"},
	{i: "namibia", t: "Namibia"},
	{i: "nauru", t: "Nauru"},
	{i: "nepal", t: "Nepal"},
	{i: "netherlands", t: "Netherlands"},
	{i: "newzealand", t: "New Zealand"},
	{i: "nicaragua", t: "Nicaragua"},
	{i: "niger", t: "Niger"},
	{i: "nigeria", t: "Nigeria"},
	{i: "northkorea", t: "North Korea"},
	{i: "norway", t: "Norway"},
	{i: "oman", t: "Oman"},
	{i: "pakistan", t: "Pakistan"},
	{i: "palau", t: "Palau"},
	{i: "panama", t: "Panama"},
	{i: "papuanewguinea", t: "Papua New Guinea"},
	{i: "paraguay", t: "Paraguay"},
	{i: "peru", t: "Peru"},
	{i: "philippines", t: "Philippines"},
	{i: "poland", t: "Poland"},
	{i: "portugal", t: "Portugal"},
	{i: "qatar", t: "Qatar"},
	{i: "reunion", t: "Réunion"},
	{i: "romania", t: "Romania"},
	{i: "russia", t: "Russia"},
	{i: "rwanda", t: "Rwanda"},
	{i: "sahrawiarabdemocraticrepublic", t: "Sahrawi Arab Democratic Republic"},
	{i: "stkittsandnevis", t: "Saint Kitts and Nevis"},
	{i: "stlucia", t: "Saint Lucia"},
	{i: "saintpierreandmiquelon", t: "Saint Pierre and Miquelon"},
	{i: "stvincentandgrenadines", t: "Saint Vincent and Grenadines"},
	{i: "samoa", t: "Samoa"},
	{i: "sanmarino", t: "San Marino"},
	{i: "saotomeandprincipe", t: "Sao Tomé and Principe"},
	{i: "saudiarabia", t: "Saudi Arabia"},
	{i: "senegal", t: "Senegal"},
	{i: "serbia", t: "Serbia"},
	{i: "seychelles", t: "Seychelles"},
	{i: "sierraleone", t: "Sierra Leone"},
	{i: "singapore", t: "Singapore"},
	{i: "slovakia", t: "Slovakia"},
	{i: "slovenia", t: "Slovenia"},
	{i: "solomonislands", t: "Solomon Islands"},
	{i: "somalia", t: "Somalia"},
	{i: "southafrica", t: "South Africa"},
	{i: "southkorea", t: "South Korea (Republic Korea)"},
	{i: "spain", t: "Spain"},
	{i: "srilanka", t: "Sri Lanka"},
	{i: "sudan", t: "Sudan"},
	{i: "suriname", t: "Suriname"},
	{i: "swaziland", t: "Swaziland"},
	{i: "sweden", t: "Sweden"},
	{i: "switzerland", t: "Switzerland"},
	{i: "syria", t: "Syria"},
	{i: "taiwan", t: "Taiwan"},
	{i: "tajikistan", t: "Tajikistan"},
	{i: "tanzania", t: "Tanzania"},
	{i: "thailand", t: "Thailand"},
	{i: "togo", t: "Togo"},
	{i: "tonga", t: "Tonga"},
	{i: "trinidadandtobago", t: "Trinidad and Tobago"},
	{i: "tunisia", t: "Tunisia"},
	{i: "turkey", t: "Turkey"},
	{i: "turkmenistan", t: "Turkmenistan"},
	{i: "tuvalu", t: "Tuvalu"},
	{i: "uganda", t: "Uganda"},
	{i: "ukraine", t: "Ukraine"},
	{i: "unitedarabemirates", t: "United Arab Emirates"},
	{i: "unitedkingdom", t: "United Kingdom"},
	{i: "unitedstatesofamerica", t: "United States of America"},
	{i: "uruguay", t: "Uruguay"},
	{i: "uzbekistan", t: "Uzbekistan"},
	{i: "vanuatu", t: "Vanuatu"},
	{i: "vaticancity", t: "Vatican City"},
	{i: "venezuela", t: "Venezuela"},
	{i: "vietnam", t: "Vietnam"},
	{i: "yemen", t: "Yemen"},
	{i: "zambia", t: "Zambia"},
	{i: "zimbabwe", t: "Zimbabwe"}
];
