//:您的手機急救指引
// Generated file, do not edit
var langTexts={
	title: "您的手機急救指引",
	back: "〈Back〉",
	continent: "〈Continent〉",
	emergency_fire: "〈Fire〉",
	emergency_medical: "〈Medical〉",
	emergency_police: "〈Police〉",
	emergency_cancelcard: "",
	emergency_local: "〈local numbers〉",
	emergency_nosystem: "〈no system〉",
	emergency_radioonly: "〈only radio telephones〉",
	emergency_none: "〈--〉",
	emergency_or: "〈or〉",
	emergency_mobile: "〈mobile〉",
	emergency_tourist: "〈tourists〉"
};
var langMenu=[
	{h: "#aid_disclaimer", t: "# 免責聲明及一般資訊"},
	{h: "#numbers", t: "# 緊急電話號碼"},
	{h: "#aid_general", t: "# 一般指引 "},
	{h: "#aid_sos", t: "SOS救援中心 "},
	{h: "#aid_backinjury", t: "背部/頸椎創傷 "},
	{h: "#aid_icerescue", t: "冰救援 "},
	{h: "#aid_snakebite", t: "毒蛇咬傷 "},
	{h: "#aid_diarrhoea", t: "腹瀉 "},
	{h: "#aid_fracture", t: "骨折 "},
	{h: "#aid_asthma", t: "呼吸急促"},
	{h: "#aid_apnoea", t: "呼吸問題 "},
	{h: "#aid_apnoea", t: "呼吸暫停 "},
	{h: "#aid_chemicalburn", t: "化學性燒傷 "},
	{h: "#aid_chemicalburneyes", t: "化學燒傷（眼睛） "},
	{h: "#aid_backinjury", t: "脊柱骨折 "},
	{h: "#aid_safeguardaccident", t: "交通事故 "},
	{h: "#aid_insectstings", t: "昆蟲螫傷 "},
	{h: "#aid_nosebleeding", t: "流鼻血 "},
	{h: "#aid_sprain", t: "扭傷應變 "},
	{h: "#aid_sunburn", t: "日炙 "},
	{h: "#aid_safeguardaccident", t: "事故現場安全 "},
	{h: "#aid_diabeticcoma", t: "糖尿病昏迷 "},
	{h: "#aid_asthma", t: "哮喘 "},
	{h: "#aid_resuscitation", t: "心外壓 "},
	{h: "#aid_heartattack", t: "心臟病發 "},
	{h: "#aid_shock", t: "休克 "},
	{h: "#aid_hypoglycaemia", t: "血糖過低 "},
	{h: "#aid_diabeticcoma", t: "血糖過高 "},
	{h: "#aid_eyeinjury", t: "眼外傷 "},
	{h: "#aid_suffocation", t: "燕子/窒息 "},
	{h: "#aid_drowning", t: "遇溺"},
	{h: "#aid_suffocation", t: "窒息 "},
	{h: "#aid_poisining", t: "中毒 "},
	{h: "#aid_sunstroke", t: "中暑 "},
	{h: "#aid_stroke", t: "中風 "},
	{h: "#aid_animalbite", t: "動物咬傷 "},
	{h: "#aid_vomiting", t: "嘔吐 "},
	{h: "#aid_bleedingsevere", t: "嚴重出血 "},
	{h: "#aid_frostbitesevere", t: "嚴重凍傷 "},
	{h: "#aid_burningsevere", t: "嚴重燒傷。 "},
	{h: "#aid_recoveryposition", t: "復原臥式 "},
	{h: "#aid_resuscitation", t: "復甦 "},
	{h: "#aid_amputation", t: "斷肢"},
	{h: "#aid_checkbreathing", t: "檢查呼吸 "},
	{h: "#aid_unconsciouswithbreath", t: "無意識同呼吸 "},
	{h: "#aid_unconsciouswithoutbreath", t: "無意識無呼吸 "},
	{h: "#aid_epilepsy", t: "癲癇 "},
	{h: "#aid_dangerzone", t: "緊急撤離危險區 "},
	{h: "#aid_birth", t: "緊急接生 "},
	{h: "#aid_emergencycall", t: "緊急電話 "},
	{h: "#aid_brainconcussion", t: "腦震盪 "},
	{h: "#aid_electricityaccident", t: "觸電"},
	{h: "#aid_frostbitemild", t: "輕度凍傷 "},
	{h: "#aid_bleedinglight", t: "輕微出血 "},
	{h: "#aid_burningslight", t: "輕微燒傷/熨傷 "},
	{h: "#aid_allergic", t: "過敏反應 "},
	{h: "#aid_skullfracture", t: "顱骨骨折 "},
	{h: "#aid_hypothermia", t: "體溫失調 (體溫過低)"},
	{h: "#aid_hyperthermia", t: "體溫失調（體溫過高） "},
	{h: "tel:112", t: "〈Call Emergency 112〉"}
];
var langSections={
	aid_disclaimer: [
		{k: "title", t: "免責聲明及一般資訊"},
		{k: "subsection", t: "軟件"},
		{k: "description", t: "您的手機急救指引"},
		{k: "description", t: "版權所有：Kai Kajus Noack，柏林"},
		{k: "description", t: "〈Translators: …〉"},
		{k: "description", t: "版權：共享創作"},
		{k: "image", i: "cc88x31"},
		{k: "description", t: "這份指引能提供急救知識，但請注意，它並不能夠替代急救課程，它只能提供資訊讓你溫故知新。"},
		{k: "description", t: "〈Illustrations〉 © Med4Teens"},
		{k: "subsection", t: "免責聲明"},
		{k: "description", t: "請注意，我們不承擔因使用此軟件而造成的任何責任。"},
		{k: "description", t: "〈ANY LIABILITY IS EXCLUDED!〉"},
		{k: "description", t: "使用者需自行承擔風險！"},
		{k: "description", t: "在任何緊急情況下，應立即尋求專業醫療協助。"},
		{k: "subsection", t: "救人一命等於挽救了世界。"}
	],
	aid_general: [
		{k: "title", t: "一般指引 "},
		{k: "step", p: [{t: "務必施行急救。你不能犯任何錯誤。"}]},
		{k: "step", p: [{t: "必須時刻注意自己的安全。"}]},
		{k: "step", p: [{t: "檢查事故的狀況和確定現場環境安全。"}]},
		{k: "step", p: [{t: "報警求助+現場急救！"}]},
		{k: "step", p: [{t: "如果現場有多名傷者，應根據其傷勢決定處理的先後次序，先處理最危急的傷病者。"}]},
		{k: "step", p: [{t: "最重要是自己保持鎮定，並嘗試安慰傷者及其他人士！"}]},
		{k: "step", p: [{t: "如果可能的話，嘗試將傷者置於一舒適的臥姿。不要給予傷者含酒精之飲料、尼古丁或藥物。"}]}
	],
	aid_allergic: [
		{k: "title", t: "過敏反應 ", i: "aid046"},
		{k: "step", p: [{t: "立即報警尋求緊急醫療援助。"}]},
		{k: "step", p: [{t: "嘗試令傷病者冷靜，並讓其舒適的坐下。。"}]},
		{k: "step", p: [{t: "如果可以的話，小心的移除引起過敏的物質（如蜜蜂的螫刺）。"}]},
		{k: "step", p: [{t: "以冷敷法（冷水，冰塊等）敷在傷處，減少不適 。"}]},
		{k: "image", i: "aid046ice"},
		{k: "step", p: [{t: "如果傷病者有解毒劑，協助傷病者使用該藥物。"}]},
		{k: "step", p: [{t: "在救護車到達前，小心監察傷者的狀況。"}]},
		{k: "step", p: [{t: "如果傷病者失去意識或停止呼吸，遵循適當的指示。"}]},
		{k: "image", i: "aid077"}
	],
	aid_amputation: [
		{k: "title", t: "斷肢"},
		{k: "description", t: "傷者的斷肢是有機會能重新接上的。 急救目標: 保持斷肢冷凍直至送抵醫院。"},
		{k: "step", p: [{t: "安慰傷者，置傷者於臥姿，為傷者保暖。"}]},
		{k: "step", p: [{t: "嘗試止血。用磞帶，或需要時用潔淨的衣服充當敷料壓住傷口止血。詳見「嚴重出血」及「休克」。"}]},
		{k: "step", p: [{t: "用潔淨和乾的布料包裹傷肢，將傷肢放入一個防水的塑膠袋;或直接將傷肢放入防水的塑膠袋。"}]},
		{k: "step", p: [{t: "緊封此塑膠袋，並將其放入另一個有冰塊或冷水的塑膠袋 (不要讓傷肢直接接觸冰塊或水)。"}]},
		{k: "step", p: [{t: "不要給予傷者酒精飲品、煙或食物。"}]},
		{k: "step", p: [{t: "不要過份冷凍傷肢，只要保持低溫即可。"}]},
		{k: "step", p: [{t: "報警或將傷者緊急送院。"}]}
	],
	aid_animalbite: [
		{k: "title", t: "動物咬傷 ", i: "aid047"},
		{k: "description", t: "注意：有很高的感染風險，甚至可能會出現破傷風或狂犬病。"},
		{k: "step", p: [{t: "用暖肥皂水清洗傷口。"}]},
		{k: "image", i: "aid049"},
		{k: "step", p: [{t: "及後消毒傷口。"}]},
		{k: "step", p: [{t: "如果有嚴重出血，扶起傷者的上身。"}]},
		{k: "step", p: [{t: "使用無菌敷料和繃帶包紮傷口。"}]},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "立即將傷者送往醫院或尋求緊急醫療協助。"}]}
	],
	aid_apnoea: [
		{k: "title", t: "呼吸暫停 "},
		{k: "description", t: "沒有呼吸聲音和呼吸動作，明顯的膚色轉變。"},
		{k: "step", p: [{t: "立即報警尋求緊急醫療援助。"}]},
		{k: "step", p: [{t: "將傷者置於臥姿。"}]},
		{k: "step", p: [{t: "使傷者頭部後抑。清除傷者口腔及喉嚨中的異物。"}]},
		{k: "image", i: "aid067"},
		{k: "step", p: [{t: "用手指緊掐傷者鼻孔，使其鼻孔緊閉。"}]},
		{k: "image", i: "aid010"},
		{k: "step", p: [{t: "深呼吸，接著用口密封傷者口部。"}]},
		{k: "image", i: "aid011"},
		{k: "step", p: [{t: "慢慢吹氣，時間約為兩秒。"}]},
		{k: "step", p: [{t: "如果未能讓他自行呼吸，繼續施行人工呼吸，直至救護車到達。"}]}
	],
	aid_asthma: [
		{k: "title", t: "哮喘 "},
		{k: "description", t: "嚴重呼吸困難。喘息呼吸的聲音。焦慮。"},
		{k: "step", p: [{t: "保持自己和傷病者冷靜。"}]},
		{k: "step", p: [{t: "解鬆阻礙呼吸的衣服。"}]},
		{k: "step", p: [{t: "讓傷病者坐下並向前傾，讓傷病者慢慢的深呼吸。"}]},
		{k: "step", p: [{t: "協助傷病者取用噴霧吸入器。病者情況應該在5-10分鐘內改善 。"}]},
		{k: "image", i: "aid074"},
		{k: "step", p: [{t: "如果病人情況沒有改善，每5分鐘協助其使用噴霧吸入器，直至救護車到達。"}]},
		{k: "step", p: [{t: "立即報警尋求醫療援助。"}]},
		{k: "step", p: [{t: "如果傷病者停止呼吸，立即施行人工呼吸（見「呼吸暫停」）。"}, {t: "〈+〉", h: "#aid_apnoea"}]}
	],
	aid_backinjury: [
		{k: "title", t: "背部/頸椎創傷 "},
		{k: "description", t: "背部疼痛，肢體沒有反應或麻木。"},
		{k: "step", p: [{t: "切勿移動傷者！"}]},
		{k: "image", i: "aid064"},
		{k: "step", p: [{t: "用手穩定傷者的頭部。"}]},
		{k: "image", i: "aid065"},
		{k: "step", p: [{t: "固定傷病者，不應作任何移動。"}]},
		{k: "step", p: [{t: "安慰傷者。"}]},
		{k: "step", p: [{t: "立即尋求緊急醫療援助，並告知救護人員傷者有頸椎創傷。"}]}
	],
	aid_birth: [
		{k: "title", t: "緊急接生 "},
		{k: "description", t: "羊水不斷滲出。子宮收縮和出現陣痛。突發的分娩。"},
		{k: "image", i: "aid025"},
		{k: "step", p: [{t: "注意產婦的隱私。保持鎮定，安慰產婦。立即報警召喚醫護人員。"}]},
		{k: "step", p: [{t: "協助產婦清除下身衣物，坐在潔淨的墊子上，分開雙腿。"}]},
		{k: "step", p: [{t: "兩膝屈曲。將產道向上。分娩是自然的過程，通常過程會比較順利。"}]},
		{k: "step", p: [{t: "安慰產婦，並指示她專注在其呼吸上：要用正常速度從鼻吸氣，從口呼氣。"}]},
		{k: "step", p: [{t: "分娩的節奏：深呼吸，盡量屏氣，然後向下用力。當嬰兒的頭部娩出後，用雙手支撐其頭部。"}]},
		{k: "image", i: "aid021"},
		{k: "image", i: "aid022"},
		{k: "step", p: [{t: "分娩後：傾斜嬰兒使其頭部向下以便排出氣道內的羊水。你可能需要自行從其鼻腔吸出嬰兒氣道內的液體。無論如何都必須令嬰兒有呼吸！"}]},
		{k: "step", p: [{t: "在距離嬰兒30cm處把臍帶打結綁好（可以在醫院才做）。同時保持產婦陰道清潔。"}]},
		{k: "image", i: "aid023"},
		{k: "step", p: [{t: "拭乾嬰兒身體，並注意為嬰兒保溫。記下出生時間並安排盡快送院。"}]}
	],
	aid_bleedinglight: [
		{k: "title", t: "輕微出血 ", i: "aid082"},
		{k: "description", t: "急救目標：止血。"},
		{k: "step", p: [{t: "請勿觸摸傷口（有傷口感染的風險） 。"}]},
		{k: "step", p: [{t: "不要以粉末、藥膏或噴霧劑治理傷口。"}]},
		{k: "step", p: [{t: "以消毒敷料和磞帶包紮傷口"}]},
		{k: "image", i: "aid098"},
		{k: "step", p: [{t: "一般的輕微出血用黏性敷料便以足夠。"}]},
		{k: "step", p: [{t: "。"}]},
		{k: "image", i: "aid084"},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "注意：如傷口是被患狂犬病的動物造成的，則必須用肥皂水清洗。"}]},
		{k: "image", i: "aid049"}
	],
	aid_bleedingsevere: [
		{k: "title", t: "嚴重出血 "},
		{k: "description", t: "噴出的血液。危險：因為出血而做成的窒息、傷口感染，死亡。 急救目標：止血。"},
		{k: "step", p: [{t: "立即尋求緊急醫療援助。"}]},
		{k: "step", p: [{t: "應先帶上手套。揭開衣服並露出傷口(有需要時適當的剪開傷者的衣服)。"}]},
		{k: "image", i: "aid086"},
		{k: "step", p: [{t: "用磞帶，或需要時用潔淨的衣服充當敷料壓住傷口止血"}]},
		{k: "step", p: [{t: "施加壓力，至少10分鐘。"}]},
		{k: "step", p: [{t: "如果敷料被血液浸透，不要移去，並應該直接在最上層加上敷料。"}]},
		{k: "step", p: [{t: "如果沒有骨折，則升高受傷肢體至高於心臟的位置，以減低血壓。如果可行的話將傷者置於臥姿。"}]},
		{k: "image", i: "aid089"},
		{k: "image", i: "aid092"},
		{k: "step", p: [{t: "如果流血不止，保持對傷口的壓力，並在止血點施加壓力：上肢-前臂受傷（用你的手指壓住內側手臂的動脈，在肘部和軀幹中間） 。下肢-(止血點在傷肢那一邊的腹股溝，用你的手掌壓住腹股溝的動脈） 。"}]},
		{k: "step", p: [{t: "當出血受到控制後，採取預防哽咽的措施。"}]},
		{k: "image", i: "aid093"}
	],
	aid_brainconcussion: [
		{k: "title", t: "腦震盪 "},
		{k: "description", t: "頭痛，噁心，嘔吐等症狀。視線變得模糊。可能失去意識。"},
		{k: "image", i: "aid035a"},
		{k: "step", p: [{t: "置傷者於臥姿。"}]},
		{k: "step", p: [{t: "立即報警尋求緊急醫療援助。"}]},
		{k: "description", t: "如果頭部出血："},
		{k: "step", p: [{t: "置傷者於臥姿，用枕頭等墊高頭部 。"}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "處理傷口 。"}]},
		{k: "step", p: [{t: "立即報警尋求緊急醫療援助。"}]}
	],
	aid_burningslight: [
		{k: "title", t: "輕微燒傷/熨傷 "},
		{k: "description", t: "發紅的皮膚。輕度腫脹。傷處有痛楚。"},
		{k: "step", p: [{t: "用流動的冷水冷卻傷處。"}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "用濕繃帶鬆的包裹傷處 (切勿緊緊的包紮傷處)。"}]}
	],
	aid_burningsevere: [
		{k: "title", t: "嚴重燒傷。 "},
		{k: "description", t: "傷處有白、紅色的斑點，出現水泡。皮膚失去體液。組織嚴重受損，出現強烈的疼痛或不痛（因為燒傷神經） 。"},
		{k: "image", i: "aid097"},
		{k: "step", p: [{t: "盡量除去傷處的衣服 (切勿強行撕開黏著傷處的衣服)。"}]},
		{k: "step", p: [{t: "用流動的冷水冷卻傷處 (大概15°C, 59°F) 大約十分鐘，直至痛楚消退。"}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "如有大範圍燒傷，用濕布覆蓋在上。"}]},
		{k: "step", p: [{t: "立即尋求緊急醫療援助。"}]},
		{k: "step", p: [{t: "冷卻後的傷口做處理：使用無菌敷料。不要使用藥用乳膏，油，藥膏等 。不要刺破水泡。"}]},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "監控傷者的呼吸和清醒程度直至救護人員到達。"}]}
	],
	aid_checkbreathing: [
		{k: "title", t: "檢查呼吸 "},
		{k: "step", p: [{t: "檢查呼吸的聲音。"}]},
		{k: "step", p: [{t: "用手放在上腹，判斷是否有呼吸 。"}]},
		{k: "image", i: "aid027"},
		{k: "step", p: [{t: "感覺傷者口、鼻有否呼吸。"}]}
	],
	aid_chemicalburneyes: [
		{k: "title", t: "化學燒傷（眼睛） "},
		{k: "step", p: [{t: "立即尋求緊急醫療援助，並告知有化學品燒傷。"}]},
		{k: "step", p: [{t: "用水沖洗受感染的眼，覆蓋並防止水濺到另一邊的眼。"}]},
		{k: "step", p: [{t: "水由內側向外側沖洗，最少沖洗20分鐘。"}]},
		{k: "image", i: "aid019"},
		{k: "step", p: [{t: "讓傷者閉上雙眼並用濕的敷料覆蓋。"}]},
		{k: "image", i: "aid020"},
		{k: "step", p: [{t: "監察傷者的狀況直至救護人員抵達。"}]}
	],
	aid_chemicalburn: [
		{k: "title", t: "化學性燒傷 "},
		{k: "description", t: "損傷的組織。"},
		{k: "image", i: "aid095"},
		{k: "step", p: [{t: "切記注意自身安全！"}]},
		{k: "step", p: [{t: "迅速行動，用大量清水清洗傷處 (注意不要濺到本來沒污染的地方)。"}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "立即報警尋求緊急醫療援助。"}]},
		{k: "step", p: [{t: "如果食道或口腔有化學性燒傷，讓傷者飲用大量清水。"}]},
		{k: "step", p: [{t: "不要嘗試使傷者嘔吐！"}]}
	],
	aid_dangerzone: [
		{k: "title", t: "緊急撤離危險區 "},
		{k: "step", p: [{t: "拖運法: 急救員處於傷病者後方，將傷病者其中一手臂放於其胸前。"}]},
		{k: "step", p: [{t: "雙手穿過傷病者腋下，抓緊他的手腕和前臂。"}]},
		{k: "step", p: [{t: "用力向後拖行，將傷病者帶到安全地方。"}]},
		{k: "image", i: "aid001"},
		{k: "image", i: "aid007"}
	],
	aid_diabeticcoma: [
		{k: "title", t: "糖尿病昏迷 "},
		{k: "description", t: "血糖水平過高（缺乏胰島素） 。"},
		{k: "description", t: "症狀：口渴，尿頻，噁心，嘔吐。呼吸氣味中帶有水果或葡萄酒的氣味。"},
		{k: "step", p: [{t: "立即報警尋求緊急醫療援助。"}]},
		{k: "step", p: [{t: "如確定為糖尿病患者，協助他取用胰島素。"}]},
		{k: "image", i: "aid016"},
		{k: "step", p: [{t: "置傷者於復原臥式。 （急救員沒有進一步措施可以採取。 ）"}, {t: "〈+〉", h: "#aid_recoveryposition"}]},
		{k: "step", p: [{t: "監察傷病者狀況直至救護人員抵達。"}]}
	],
	aid_diarrhoea: [
		{k: "title", t: "腹瀉 "},
		{k: "description", t: "對於食物中毒、腸道感染或疾病的反應。糞便稀釋、黏滑或帶血。"},
		{k: "step", p: [{t: "血液循環可能因過度脫水及鹽份嚴重流失而受到影響！"}]},
		{k: "step", p: [{t: "給予傷病者飲料（如茶、水等） 。"}]},
		{k: "step", p: [{t: "如果傷病者有嚴重不適，立即尋求緊急醫療援助。"}]}
	],
	aid_drowning: [
		{k: "title", t: "遇溺"},
		{k: "step", p: [{t: "立即報警尋求緊急醫療援助，並要求旁人幫忙。"}]},
		{k: "image", i: "aid032"},
		{k: "step", p: [{t: "將遇溺者從水中救出！"}]},
		{k: "image", i: "aid033"},
		{k: "image", i: "aid034"},
		{k: "step", p: [{t: "如果遇溺者有呼吸：置其於復原臥式。覆蓋傷者身體以保暖。監察傷病者狀況直至救護人員抵達。"}, {t: "〈+〉", h: "#aid_recoveryposition"}]},
		{k: "step", p: [{t: "如果遇溺者沒有呼吸：立即開始復甦！（從肺部迫出傷者吞下的水是沒有作用的。）"}, {t: "〈+〉", h: "#aid_resuscitation"}]}
	],
	aid_electricityaccident: [
		{k: "title", t: "觸電"},
		{k: "step", p: [{t: "立即切斷電源！"}]},
		{k: "image", i: "aid045plug"},
		{k: "image", i: "aid045"},
		{k: "step", p: [{t: "危險：失去意識，呼吸暫停。"}]},
		{k: "step", p: [{t: "A -無意識但有呼吸", h: "#aid_unconsciouswithbreath"}]},
		{k: "step", p: [{t: " B-無意識無呼吸", h: "#aid_unconsciouswithoutbreath"}]},
		{k: "image", i: "aid042"},
		{k: "image", i: "aid043"}
	],
	aid_emergencycall: [
		{k: "title", t: "緊急電話 "},
		{k: "step", p: [{t: "用最近可用的電話撥120報警（歐洲：112，美國：911）。電話總是能接通而且是免費的！不要猶豫，要求緊急醫療協助！"}]},
		{k: "step", p: [{t: "在通話中你必須提供下列資料："}]},
		{k: "step", p: [{t: "發生了什麼事、"}]},
		{k: "step", p: [{t: "事故地點、"}]},
		{k: "step", p: [{t: "傷病者的數目、"}]},
		{k: "step", p: [{t: "傷病者的傷勢及狀況。"}]},
		{k: "step", p: [{t: "然後等待進一步的指示或當值人員的問題。"}]}
	],
	aid_epilepsy: [
		{k: "title", t: "癲癇 "},
		{k: "description", t: "僵硬的身體，握緊拳頭，下顎向下壓，四肢或面部肌肉抽搐。眼睛無意識的轉動。流涎。不省人事。"},
		{k: "image", i: "aid058"},
		{k: "step", p: [{t: "不要按著傷病者或限制他們的行動。"}]},
		{k: "step", p: [{t: "將傷病者置於一軟墊上。移開四周的物件，以防止傷病者對自己做成傷害。"}]},
		{k: "step", p: [{t: "安慰傷病者。解鬆緊身的衣服，確保能自由呼吸。"}]},
		{k: "step", p: [{t: "如果傷病者嘔吐，將其頭部側向一方讓其嘔吐物流出。"}]},
		{k: "step", p: [{t: "保持氣道暢通，防止其舌頭向下滑。"}]},
		{k: "step", p: [{t: "置傷病者於復原臥式，並立即報警尋求緊急醫療援助。監察傷病者的狀況直至救護人員抵達。"}, {t: "〈+〉", h: "#aid_recoveryposition"}]},
		{k: "step", p: [{t: "請其他人保持距離。"}]}
	],
	aid_eyeinjury: [
		{k: "title", t: "眼外傷 "},
		{k: "step", p: [{t: "不要試圖移除眼球的異物。"}]},
		{k: "step", p: [{t: "不要轉動眼球，囑咐傷者保持眼睛靜止。亦不要觸摸眼睛。"}]},
		{k: "step", p: [{t: "如果眼球出血，用溼敷布或無菌紗布覆蓋。"}]},
		{k: "image", i: "aid020"},
		{k: "step", p: [{t: "用冷凍墊冷卻受傷的眼睛（減輕腫脹，更快止血） 。"}]},
		{k: "step", p: [{t: "立即報警尋求緊急醫療援助或將傷者緊急送院。"}]}
	],
	aid_fracture: [
		{k: "title", t: "骨折 "},
		{k: "description", t: "症狀：異常的姿態及動作。肢體變形。活動時有痛楚，有觸痛。"},
		{k: "image", i: "aid104"},
		{k: "step", p: [{t: "避免活動！"}]},
		{k: "step", p: [{t: "立即尋求緊急醫療援助。"}]},
		{k: "step", p: [{t: "固定傷肢 - 用墊子在傷肢四周做支撐。保持傷肢在同一個位置。"}]},
		{k: "image", i: "aid107"},
		{k: "step", p: [{t: "如果是有創骨折，用敷料覆蓋傷口。"}]},
		{k: "image", i: "aid106"}
	],
	aid_frostbitemild: [
		{k: "title", t: "輕度凍傷 "},
		{k: "description", t: "臉色蒼白，腫脹。血液循環受威脅。"},
		{k: "step", p: [{t: "將傷者移到較溫暖的位置。"}]},
		{k: "step", p: [{t: "盡量不要留在寒冷的地方，除去濕冷的衣服，抹乾傷病者的身體。"}]},
		{k: "step", p: [{t: "用溫水和急救員的體溫協助傷病者回復體溫。"}]},
		{k: "step", p: [{t: "給予傷病者暖的飲料(如茶等)。不要給予傷病者酒精飲品！"}]},
		{k: "image", i: "aid040"}
	],
	aid_frostbitesevere: [
		{k: "title", t: "嚴重凍傷 "},
		{k: "description", t: "冷而且僵硬皮膚，皮膚表層呈灰白色。出現水泡，皮膚組織壞死。血液循環受威脅！"},
		{k: "image", i: "aid096"},
		{k: "step", p: [{t: "將傷者移到較溫暖的地方。"}]},
		{k: "step", p: [{t: "處理傷口。"}]},
		{k: "step", p: [{t: "給予傷者暖的含糖飲料。"}]},
		{k: "step", p: [{t: "不要試圖摩擦傷病者以提升其體溫！"}]},
		{k: "step", p: [{t: "立即報警尋求緊急醫療援助。"}]}
	],
	aid_heartattack: [
		{k: "title", t: "心臟病發 "},
		{k: "description", t: "心臟有嚴重、持久的壓力和痛楚，可能持續5分鐘以上。特別是在肩膀和上肢。焦慮，臉色蒼白，皮膚濕冷。可能有噁心，呼吸急促。"},
		{k: "image", i: "aid076"},
		{k: "image", i: "aid083"},
		{k: "step", p: [{t: "立即報警尋求緊急醫療援助，並告知傷病者懷疑心臟病突發。"}]},
		{k: "step", p: [{t: "將傷病者放成半坐臥姿勢，用物件支持頭與肩。解鬆緊身的衣物。不要給予傷病者飲料和藥物。"}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "冷靜的與傷病者對話，安慰傷病者。"}]},
		{k: "step", p: [{t: "檢查呼吸和意識水平。"}]},
		{k: "step", p: [{t: "如傷病者有亞士匹靈而又是清醒的話，讓其嚼碎一粒藥片吞下。"}]},
		{k: "step", p: [{t: "如傷病者失去呼吸或脈搏，立即施行復甦（見「復甦」）。"}, {t: "〈+〉", h: "#aid_resuscitation"}]}
	],
	aid_hypoglycaemia: [
		{k: "title", t: "血糖過低 "},
		{k: "description", t: "血糖水平低於最低值（因為身體有過量的胰島素或沒有足夠的食物攝入量） 。"},
		{k: "description", t: "症狀：臉色蒼白，緊張，飢餓，發抖，出汗。"},
		{k: "image", i: "aid018"},
		{k: "step", p: [{t: "確認傷病者是否患有糖尿病（尋找相關的醫療手鐲或醫療咭） 。"}]},
		{k: "step", p: [{t: "立即報警尋求緊急醫療援助。"}]},
		{k: "step", p: [{t: "給予傷病者含糖飲料和葡萄糖（如果傷病者是清醒的、亦沒有吞嚥問題的話） 。"}]},
		{k: "image", i: "aid017"},
		{k: "step", p: [{t: "如果傷病者有呼吸而是清醒的，置其於復原臥式，監察呼吸狀況。如果傷病者停止呼吸，施行人工呼吸（見「呼吸暫停」）。"}, {t: "〈+〉", h: "#aid_recoveryposition"}]},
		{k: "step", p: [{t: "如果傷病者有呼吸，你可以把一塊糖放在傷病者的頰囊，從外面向內反複推動。但必需監禁傷病者狀況，切勿讓糖塊掉下阻塞氣道。"}]}
	],
	aid_hyperthermia: [
		{k: "title", t: "體溫失調（體溫過高） "},
		{k: "description", t: "口渴，無力，迷失方向，感到噁心，意識模糊及感到混亂，嚴重出汗，皮膚發熱發紅。"},
		{k: "image", i: "aid035"},
		{k: "step", p: [{t: "立即報警尋求緊急醫療援助。"}]},
		{k: "step", p: [{t: "將傷病者置於陰涼處（最好是有室內空調的地方) 。"}]},
		{k: "step", p: [{t: "讓傷病者平臥，提高雙腳。鬆開緊身的衣服。"}]},
		{k: "image", i: "aid078"},
		{k: "step", p: [{t: "用冷水協助降溫或讓其臥在冰涼的毛巾上。"}]},
		{k: "step", p: [{t: "給予傷病者大量清水或果汁等飲料。"}]}
	],
	aid_hypothermia: [
		{k: "title", t: "體溫失調 (體溫過低)"},
		{k: "description", t: "發抖，嗜睡，體力透支甚至昏迷。皮膚濕冷蒼白。脈搏緩慢而微弱。"},
		{k: "image", i: "aid014"},
		{k: "step", p: [{t: "將傷病者置於一比較溫暖的地方。"}]},
		{k: "step", p: [{t: "立即報警尋求緊急醫療援助。"}]},
		{k: "step", p: [{t: "協助傷病者回復體溫（蓋暖和需要時利用急救員的體溫)"}]},
		{k: "step", p: [{t: "移去傷病者身上濕冷的衣服，並協助傷病者穿上保暖衣物。為傷者蓋暖，尤其注意頭部保溫。"}]},
		{k: "step", p: [{t: "給予傷病者熱飲，如茶、暖水等。切勿給予傷病者酒精飲品！盡量使傷病者保持清醒。"}]},
		{k: "image", i: "aid039"},
		{k: "image", i: "aid040"},
		{k: "step", p: [{t: "監察傷病者狀況直至救援人員抵達。如傷病者失去意識，立即開始復甦："}]},
		{k: "step", p: [{t: "A-無意識但有呼吸", h: "#aid_unconsciouswithbreath"}]},
		{k: "step", p: [{t: "B-無意識及無呼吸", h: "#aid_unconsciouswithoutbreath"}]}
	],
	aid_icerescue: [
		{k: "title", t: "冰救援 "},
		{k: "description", t: "急救員必需注意自身安全。危險: 遇溺、體溫過低。"},
		{k: "step", p: [{t: "要求旁人協助，並立即報警召喚救援人員。"}]},
		{k: "step", p: [{t: "利用梯子、木板、棒子等物拯救傷病者。注意要平均分佈重量。"}]},
		{k: "step", p: [{t: "用腹部爬行，並用竿等工具作支撐（如果可行的話，可用繩索將自己和一固定點聯繫起來）。"}]},
		{k: "image", i: "aid041"},
		{k: "step", p: [{t: "用工具（而不是你的手！）觸碰傷病者，指示他拿穩它，然後把他拉出來。"}]},
		{k: "step", p: [{t: "向後爬行回到冰的邊緣。"}]},
		{k: "step", p: [{t: "施行急救措施。"}]},
		{k: "step", p: [{t: "自救的可能：如果冰是固體，您可以借用自己的體重施力在冰上，並把自己拉出來，然後爬行到冰的邊緣；如果冰是脆弱的，試圖一點一點地打破冰塊直到到達冰的邊緣。"}]}
	],
	aid_insectstings: [
		{k: "title", t: "昆蟲螫傷 ", i: "aid046"},
		{k: "description", t: "腫脹，皮疹，灼熱的感覺，乏力，呼吸困難，意識下降，室性心動過速。"},
		{k: "step", p: [{t: "小心的用鑷子移除嵌入皮膚的螫刺。注意切勿擠壓毒囊，否則可能將殘餘的毒素注入傷者體內。"}]},
		{k: "step", p: [{t: "冷敷有關部位 。"}]},
		{k: "step", p: [{t: "被螫傷的部位應該置於低於心臟的位置，以減慢毒素流動的速度。"}]},
		{k: "step", p: [{t: "如果口部或顎骨附近被螫傷，讓傷者將冷凍的食物(如冰琪淋)放在口裡。並在喉部作冷敷，減低因喉部腫脹導致呼吸困難的危險。"}]},
		{k: "image", i: "aid046ice"},
		{k: "step", p: [{t: "如果傷者有嚴重不適，尤其如果傷者有呼吸困難或意識降低的徵狀，立即報警尋求緊急醫療援助。"}]}
	],
	aid_nosebleeding: [
		{k: "title", t: "流鼻血 "},
		{k: "description", t: "鼻孔內血管破裂。"},
		{k: "step", p: [{t: "讓傷者坐下，微微向前傾。"}]},
		{k: "step", p: [{t: "盡量不要讓傷者躺下，因為頭部處於心臟上方能夠令出血減慢。"}]},
		{k: "step", p: [{t: "冷敷前額，這能讓血管收縮而減慢出血。"}]},
		{k: "step", p: [{t: "捏住鼻骨下柔軟部位十分鐘 。"}]},
		{k: "step", p: [{t: "止血後囑咐傷者別擤鼻或挖鼻孔引致再次出血。"}]},
		{k: "step", p: [{t: "如果傷病者有嚴重不適或出血二十分鐘後仍不能停止，立即尋求緊急醫療援助。"}]}
	],
	aid_poisining: [
		{k: "title", t: "中毒 ", i: "aid052"},
		{k: "description", t: "混亂，產生幻覺，瞳孔放大，發燒，抽筋。失去意識。"},
		{k: "step", p: [{t: "只有在專業醫護人員指示下，方可給予傷病者解毒劑。"}]},
		{k: "image", i: "aid056"},
		{k: "step", p: [{t: "不要給飲料。不要催吐。"}]},
		{k: "step", p: [{t: "報警求助及並告知救護人員傷者中毒！"}]},
		{k: "step", p: [{t: "保存剩餘的毒物和嘔吐物並交予救護人員！"}]},
		{k: "image", i: "aid054a"},
		{k: "step", p: [{t: "如果傷亡有意識和呼吸：置傷者於復原臥式。監察傷病者狀況直至救護人員抵達。"}, {t: "〈+〉", h: "#aid_recoveryposition"}]},
		{k: "step", p: [{t: "如果傷員沒有呼吸：立即施行復甦（見「復甦」）！但要事先要清除口中的嘔吐物。"}, {t: "〈+〉", h: "#aid_resuscitation"}]}
	],
	aid_recoveryposition: [
		{k: "title", t: "復原臥式 "},
		{k: "step", p: [{t: "讓傷病者仰臥，伸直雙腿。急救員跪在傷病者身邊。"}]},
		{k: "step", p: [{t: "將傷病者較靠近急救員的一隻手臂拉開，與其身體成直角。"}]},
		{k: "step", p: [{t: "將較遠的手臂拉過胸部，並使手背背對臉頰。"}]},
		{k: "image", i: "aid008"},
		{k: "step", p: [{t: "將較遠的膝蓋拉向急救員，並把它置在地面上，使雙腳成直角。保持傷病者的手在其臉頰之下。"}]},
		{k: "step", p: [{t: "確保氣道暢通。"}]},
		{k: "step", p: [{t: "使其嘴巴微張，並傾側頭部使嘔吐可以流走。檢查呼吸。"}]},
		{k: "image", i: "aid009"},
		{k: "step", p: [{t: "監察傷病者狀況直至救援人員抵達。"}]},
		{k: "description", t: "〈Recovery position for babies:〉"},
		{k: "image", i: "aid028"}
	],
	aid_resuscitation: [
		{k: "title", t: "復甦 "},
		{k: "subsection", t: "# 心外壓"},
		{k: "step", p: [{t: "讓傷病者仰臥。急救員跪在傷病者身邊。"}]},
		{k: "step", p: [{t: "〈Bare the chest.〉"}]},
		{k: "step", p: [{t: "〈Place the heel of the hand in the middle of the chest (just over sternum).〉"}]},
		{k: "image", i: "aid013"},
		{k: "step", p: [{t: "另一方面廣場上包後面的手已經在的位置。"}]},
		{k: "step", p: [{t: "擠壓你的武器和胳膊肘。"}]},
		{k: "image", i: "aid003"},
		{k: "step", p: [{t: "按5厘米深到人的胸部（權力來自上身）和釋放。"}]},
		{k: "step", p: [{t: "推30次連續不久，並強烈！"}]},
		{k: "subsection", t: "# 煙"},
		{k: "step", p: [{t: "伸展頭到脖子上。刪除物質的嘴巴和喉嚨。"}]},
		{k: "image", i: "aid067"},
		{k: "step", p: [{t: "推進兩翼的鼻子在一起，因此，鼻子是封閉。"}]},
		{k: "image", i: "aid010"},
		{k: "step", p: [{t: "深呼吸，把你的嘴到口的人員傷亡，沒有空氣洩漏。"}]},
		{k: "image", i: "aid011"},
		{k: "step", p: [{t: "不要嘴對嘴呼吸的2倍（呼吸緩慢並充分） 。"}]},
		{k: "step", p: [{t: "後來做心臟按摩一次。"}]},
		{k: "description", t: "重複心臟按摩口呼吸，直到抵達急診醫生。"},
		{k: "image", i: "aid012"},
		{k: "subsection", t: "〈Resuscitation (Baby)〉"},
		{k: "step", p: [{t: "〈Only use two fingers:〉"}]},
		{k: "image", i: "aid029"},
		{k: "step", p: [{t: "〈Do not breath too strong:〉"}]},
		{k: "image", i: "aid030"}
	],
	aid_safeguardaccident: [
		{k: "title", t: "事故現場安全 "},
		{k: "step", p: [{t: "在事故現場後方50-100米停車（如果您是在高速公路或鄉間道路）。開啟警示燈。穿上反光衣。"}]},
		{k: "step", p: [{t: "將三角形警示燈放在事故現場後方。注意：如果事故現場是位於彎道上，將警示燈置於彎道前。"}]},
		{k: "image", i: "aid111"},
		{k: "step", p: [{t: "要求旁人協助。"}]},
		{k: "step", p: [{t: "打開肇事車輛的車門。如果未能順利打開，使用千斤頂。關掉引擎並拉起手動煞車(制動器)。"}]},
		{k: "step", p: [{t: "救出傷病者： Unstrap安全帶，座椅向後移動。自由傷亡的汽車救援抓地力。"}, {t: "〈+〉", h: "#aid_dangerzone"}]},
		{k: "image", i: "aid001"},
		{k: "step", p: [{t: "立即報警召喚救援人員。"}]},
		{k: "step", p: [{t: "為傷病者施行急救。"}]}
	],
	aid_shock: [
		{k: "title", t: "休克 "},
		{k: "description", t: "循環系統疾病的貧困氧氣供應的機構。"},
		{k: "description", t: "原因：流體損失，降低血量。"},
		{k: "description", t: "症狀：臉色蒼白，皮膚冷，冒冷汗，焦慮。"},
		{k: "step", p: [{t: "消除造成的衝擊（如停止流失的液體，具有約束力的傷口） ！"}]},
		{k: "step", p: [{t: "受傷者躺在毯子上，雙腿的立場了。平靜的人。"}]},
		{k: "image", i: "aid078"},
		{k: "step", p: [{t: "緊急呼籲。"}]},
		{k: "step", p: [{t: "如果呼吸困難或意識，開始復甦。"}, {t: "〈+〉", h: "#aid_resuscitation"}]}
	],
	aid_skullfracture: [
		{k: "title", t: "顱骨骨折 "},
		{k: "description", t: "輕出血的鼻子，嘴巴或耳朵。開放性傷口往往在頭骨。"},
		{k: "step", p: [{t: "保持呼吸道免費的。"}]},
		{k: "step", p: [{t: "如果意識到：讓傷者坐在一起低著頭前鋒。避免進一步的動作！"}]},
		{k: "step", p: [{t: "如果無意識：恢復立場（沒有壓力，傷口的頭） 。"}, {t: "〈+〉", h: "#aid_recoveryposition"}]},
		{k: "step", p: [{t: "緊急呼籲。"}]},
		{k: "step", p: [{t: "適用於頭部纏著繃帶。"}]},
		{k: "step", p: [{t: "如果呼吸困難或意識，開始復甦。"}, {t: "〈+〉", h: "#aid_resuscitation"}]}
	],
	aid_snakebite: [
		{k: "title", t: "毒蛇咬傷 ", i: "aid051"},
		{k: "description", t: "標點傷口大小的針，嚴重的疼痛，腫脹，紫色。循環系統紊亂，休克的危險。"},
		{k: "step", p: [{t: "穩態受傷的身體部分。"}]},
		{k: "step", p: [{t: "適用於冷戰信封周圍咬的傷口。"}]},
		{k: "step", p: [{t: "措施防止休克。"}]},
		{k: "step", p: [{t: "緊急呼籲。"}]}
	],
	aid_sos: [
		{k: "title", t: "SOS救援中心 "},
		{k: "step", p: [{t: "信號： 3短，長3倍， 3倍短。"}]},
		{k: "step", p: [{t: "光（閃光燈，手電筒） ，或聽覺（信號哨子，敲） 。"}]}
	],
	aid_sprain: [
		{k: "title", t: "扭傷應變 "},
		{k: "description", t: "疼痛，腫脹（瘀傷） ，喪失功能，變形的肢體。"},
		{k: "step", p: [{t: "穩態受傷的身體部分只有在最舒適的位置的人員傷亡。"}]},
		{k: "step", p: [{t: "冷（用冰袋） 。"}]},
		{k: "step", p: [{t: "如果可能的話，立場受害國的一部分升高。"}]},
		{k: "step", p: [{t: "去醫院或醫生的緊急呼籲。"}]}
	],
	aid_stroke: [
		{k: "title", t: "中風 "},
		{k: "description", t: "突然感覺癱瘓或麻木（臉部，手臂，腿部） ，動亂的語言理解，視力問題，不安的意識，嚴重頭痛。問題的呼吸和吞嚥，失去控制膀胱和腸道。"},
		{k: "image", i: "aid059"},
		{k: "step", p: [{t: "緊急呼叫！"}]},
		{k: "step", p: [{t: "放鬆緊張的衣服，不給藥物或飲料。"}]},
		{k: "step", p: [{t: "坐或躺在舒適有關的人。平靜的他/她！"}]},
		{k: "step", p: [{t: "控制意識和呼吸。"}]},
		{k: "step", p: [{t: "如果呼吸困難或意識，開始復甦。"}, {t: "〈+〉", h: "#aid_resuscitation"}]}
	],
	aid_suffocation: [
		{k: "title", t: "窒息 "},
		{k: "description", t: "氧氣供應不足。氣管封閉。危險：窒息。"},
		{k: "description", t: "症狀：哮喘呼吸噪音，刺激咳嗽，呼吸急促，皮膚變色。"},
		{k: "image", i: "aid066"},
		{k: "step", p: [{t: "立即行動！讓有關的人咳嗽非常強烈。"}]},
		{k: "step", p: [{t: "罷工強烈的單位手的背面之間的肩胛骨（躺在嬰兒在您的前臂，頭部向下） 。"}]},
		{k: "image", i: "aid068"},
		{k: "image", i: "aid031"},
		{k: "step", p: [{t: "如果沒有成功：站在後面的人，摟著腰，低頭略有前進。"}]},
		{k: "step", p: [{t: "幹你的拳頭，位置在身高的人的肚子，並採取與您的另一方面。"}]},
		{k: "image", i: "aid069"},
		{k: "step", p: [{t: "在接受使用兩手給予沉重打擊方向向上胃（當您將設法解除人） 。"}]},
		{k: "step", p: [{t: "重複此了5倍！航空公司應免費從對象。"}]},
		{k: "step", p: [{t: "緊急呼籲。"}]},
		{k: "step", p: [{t: "如果急救措施是不成功的繼續做，直到醫生來應急。"}]}
	],
	aid_sunburn: [
		{k: "title", t: "日炙 "},
		{k: "step", p: [{t: "刪除受影響的人從陽光直接照射。避免進一步的太陽。"}]},
		{k: "step", p: [{t: "喝大量的水停止脫水。"}]},
		{k: "step", p: [{t: "如果有一個嚴重的陽光燒傷（水皰，紅腫，疼痛） ，求醫。"}]},
		{k: "step", p: [{t: "如果皮膚只是輕輕紅，它可以冷卻濕信封。使用後，太陽洗劑或凝膠。"}]}
	],
	aid_sunstroke: [
		{k: "title", t: "中暑 "},
		{k: "description", t: "紅頭熱，冷的皮膚，疾病，頭痛，頭暈。原因：刺激腦細胞膜。"},
		{k: "image", i: "aid035"},
		{k: "step", p: [{t: "轉到一個酷地方（影子）和位置，上身的人了。"}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "頭部冷濕毯子。"}]},
		{k: "step", p: [{t: "緊急呼叫，隨時控制呼吸。"}]},
		{k: "step", p: [{t: "如果意識到：給飲料降溫，如果適用。"}]},
		{k: "step", p: [{t: "如果出現呼吸暫停，呼吸開始："}]},
		{k: "step", p: [{t: "去同呼吸讓！", h: "#aid_apnoea"}]},
		{k: "image", i: "aid036"}
	],
	aid_unconsciouswithbreath: [
		{k: "title", t: "無意識同呼吸 "},
		{k: "description", t: "沒有反應，大聲地問，沒有反應，顫抖。呼吸確實存在。"},
		{k: "image", i: "aid057"},
		{k: "step", p: [{t: "如果還有人在你身邊尋求幫助。"}]},
		{k: "step", p: [{t: "回收的立場。開放的嘴和頭部的位置這種方式，嘔吐可以流失。"}, {t: "〈+〉", h: "#aid_recoveryposition"}]},
		{k: "image", i: "aid008"},
		{k: "image", i: "aid009"},
		{k: "step", p: [{t: "緊急呼籲。"}]}
	],
	aid_unconsciouswithoutbreath: [
		{k: "title", t: "無意識無呼吸 "},
		{k: "step", p: [{t: "沒有人員傷亡的反應，沒有呼吸。"}]},
		{k: "image", i: "aid057"},
		{k: "step", p: [{t: "開始復甦。"}, {t: "〈+〉", h: "#aid_resuscitation"}]}
	],
	aid_vomiting: [
		{k: "title", t: "嘔吐 "},
		{k: "description", t: "源自噁心。胃清空本身。原因：感染，中毒，潰瘍，毒品，不良食物，懷孕。"},
		{k: "image", i: "aid054"},
		{k: "step", p: [{t: "危險的流通，因為脫水和損失的鹽！"}]},
		{k: "step", p: [{t: "給予液體（茶，水） 。"}]},
		{k: "step", p: [{t: "如果有強大的障礙，血腥或持續嘔吐緊急呼叫醫生。"}]}
	]
};
var langContinents=[
	{i: "Africa", t: "〈Africa〉"},
	{i: "Asia", t: "〈Asia〉"},
	{i: "Europe", t: "〈Europe〉"},
	{i: "Northamerica", t: "〈North-/Central-America〉"},
	{i: "Oceania", t: "〈Oceania〉"},
	{i: "Southamerica", t: "〈South-America〉"}
];
var langCountries=[
	{i: "afghanistan", t: "〈Afghanistan〉"},
	{i: "albania", t: "〈Albania〉"},
	{i: "algeria", t: "〈Algeria〉"},
	{i: "andorra", t: "〈Andorra〉"},
	{i: "angola", t: "〈Angola〉"},
	{i: "antiguaandbarbuda", t: "〈Antigua and Barbuda〉"},
	{i: "argentina", t: "〈Argentina〉"},
	{i: "armenia", t: "〈Armenia〉"},
	{i: "australia", t: "〈Australia〉"},
	{i: "austria", t: "〈Austria〉"},
	{i: "azerbaijan", t: "〈Azerbaijan〉"},
	{i: "bahamas", t: "〈Bahamas〉"},
	{i: "bahrain", t: "〈Bahrain〉"},
	{i: "bangladesh", t: "〈Bangladesh〉"},
	{i: "barbados", t: "〈Barbados〉"},
	{i: "belarus", t: "〈Belarus〉"},
	{i: "belgium", t: "〈Belgium〉"},
	{i: "belize", t: "〈Belize〉"},
	{i: "benin", t: "〈Benin〉"},
	{i: "bhutan", t: "〈Bhutan〉"},
	{i: "bolivia", t: "〈Bolivia〉"},
	{i: "bosniaandherzegovina", t: "〈Bosnia and Herzegovina〉"},
	{i: "botswana", t: "〈Botswana〉"},
	{i: "brazil", t: "〈Brazil〉"},
	{i: "brunei", t: "〈Brunei〉"},
	{i: "bulgaria", t: "〈Bulgaria〉"},
	{i: "burkinafaso", t: "〈Burkina Faso〉"},
	{i: "burundi", t: "〈Burundi〉"},
	{i: "cambodia", t: "〈Cambodia〉"},
	{i: "cameroon", t: "〈Cameroon〉"},
	{i: "canada", t: "〈Canada〉"},
	{i: "capeverde", t: "〈Cape Verde〉"},
	{i: "caymanislands", t: "〈Cayman Islands〉"},
	{i: "centralafricanrepublic", t: "〈Central African Republic〉"},
	{i: "chad", t: "〈Chad〉"},
	{i: "chile", t: "〈Chile〉"},
	{i: "china", t: "〈China〉"},
	{i: "colombia", t: "〈Colombia〉"},
	{i: "comoros", t: "〈Comoros〉"},
	{i: "congodemocraticrepublic", t: "〈Congo (Democratic Republic)〉"},
	{i: "congorepublic", t: "〈Congo (Republic)〉"},
	{i: "costarica", t: "〈Costa Rica〉"},
	{i: "croatia", t: "〈Croatia〉"},
	{i: "cuba", t: "〈Cuba〉"},
	{i: "cyprus", t: "〈Cyprus〉"},
	{i: "czechrepublic", t: "〈Czech Republic〉"},
	{i: "denmark", t: "〈Denmark〉"},
	{i: "djibouti", t: "〈Djibouti〉"},
	{i: "dominicanrepublic", t: "〈Dominican Republic〉"},
	{i: "dominica", t: "〈Dominica〉"},
	{i: "easttimor", t: "〈East Timor〉"},
	{i: "ecuador", t: "〈Ecuador〉"},
	{i: "egypt", t: "〈Egypt〉"},
	{i: "elsalvador", t: "〈El Salvador〉"},
	{i: "equatorialguinea", t: "〈Equatorial Guinea〉"},
	{i: "eritrea", t: "〈Eritrea〉"},
	{i: "estonia", t: "〈Estonia〉"},
	{i: "ethiopia", t: "〈Ethiopia〉"},
	{i: "fiji", t: "〈Fiji〉"},
	{i: "finland", t: "〈Finland〉"},
	{i: "france", t: "〈France〉"},
	{i: "gabon", t: "〈Gabon〉"},
	{i: "gambia", t: "〈Gambia〉"},
	{i: "georgia", t: "〈Georgia〉"},
	{i: "germany", t: "〈Germany〉"},
	{i: "ghana", t: "〈Ghana〉"},
	{i: "greece", t: "〈Greece〉"},
	{i: "greenland", t: "〈Greenland〉"},
	{i: "grenada", t: "〈Grenada〉"},
	{i: "guatemala", t: "〈Guatemala〉"},
	{i: "guinea-bissau", t: "〈Guinea-Bissau〉"},
	{i: "guinea", t: "〈Guinea〉"},
	{i: "guyana", t: "〈Guyana〉"},
	{i: "haiti", t: "〈Haiti〉"},
	{i: "honduras", t: "〈Honduras〉"},
	{i: "hongkong", t: "〈Hong Kong〉"},
	{i: "hungary", t: "〈Hungary〉"},
	{i: "iceland", t: "〈Iceland〉"},
	{i: "india", t: "〈India〉"},
	{i: "indonesia", t: "〈Indonesia〉"},
	{i: "iran", t: "〈Iran〉"},
	{i: "iraq", t: "〈Iraq〉"},
	{i: "ireland", t: "〈Ireland〉"},
	{i: "israel", t: "〈Israel〉"},
	{i: "italy", t: "〈Italy〉"},
	{i: "ivorycoast", t: "〈Ivory Coast〉"},
	{i: "jamaica", t: "〈Jamaica〉"},
	{i: "japan", t: "〈Japan〉"},
	{i: "jordan", t: "〈Jordan〉"},
	{i: "kazakhstan", t: "〈Kazakhstan〉"},
	{i: "kenya", t: "〈Kenya〉"},
	{i: "kiribati", t: "〈Kiribati〉"},
	{i: "kosovo", t: "〈Kosovo〉"},
	{i: "kurdistan", t: "〈Kurdistan〉"},
	{i: "kuwait", t: "〈Kuwait〉"},
	{i: "kyrgyzstan", t: "〈Kyrgyzstan〉"},
	{i: "laos", t: "〈Laos〉"},
	{i: "latvia", t: "〈Latvia〉"},
	{i: "lebanon", t: "〈Lebanon〉"},
	{i: "lesotho", t: "〈Lesotho〉"},
	{i: "liberia", t: "〈Liberia〉"},
	{i: "libya", t: "〈Libya〉"},
	{i: "liechtenstein", t: "〈Liechtenstein〉"},
	{i: "lithuania", t: "〈Lithuania〉"},
	{i: "luxembourg", t: "〈Luxembourg〉"},
	{i: "macau", t: "〈Macau〉"},
	{i: "macedonia", t: "〈Macedonia〉"},
	{i: "madagascar", t: "〈Madagascar〉"},
	{i: "malawi", t: "〈Malawi〉"},
	{i: "malaysia", t: "〈Malaysia〉"},
	{i: "maldives", t: "〈Maldives〉"},
	{i: "mali", t: "〈Mali〉"},
	{i: "malta", t: "〈Malta〉"},
	{i: "marshallislands", t: "〈Marshall Islands〉"},
	{i: "mauritania", t: "〈Mauritania〉"},
	{i: "mauritius", t: "〈Mauritius〉"},
	{i: "mayotte", t: "〈Mayotte〉"},
	{i: "mexico", t: "〈Mexico〉"},
	{i: "micronesia", t: "〈Micronesia〉"},
	{i: "moldova", t: "〈Moldova〉"},
	{i: "monaco", t: "〈Monaco〉"},
	{i: "mongolia", t: "〈Mongolia〉"},
	{i: "montenegro", t: "〈Montenegro〉"},
	{i: "morocco", t: "〈Morocco〉"},
	{i: "mozambique", t: "〈Mozambique〉"},
	{i: "myanmar", t: "〈Myanmar〉"},
	{i: "namibia", t: "〈Namibia〉"},
	{i: "nauru", t: "〈Nauru〉"},
	{i: "nepal", t: "〈Nepal〉"},
	{i: "netherlands", t: "〈Netherlands〉"},
	{i: "newzealand", t: "〈New Zealand〉"},
	{i: "nicaragua", t: "〈Nicaragua〉"},
	{i: "nigeria", t: "〈Nigeria〉"},
	{i: "niger", t: "〈Niger〉"},
	{i: "northkorea", t: "〈North Korea〉"},
	{i: "norway", t: "〈Norway〉"},
	{i: "oman", t: "〈Oman〉"},
	{i: "pakistan", t: "〈Pakistan〉"},
	{i: "palau", t: "〈Palau〉"},
	{i: "panama", t: "〈Panama〉"},
	{i: "papuanewguinea", t: "〈Papua New Guinea〉"},
	{i: "paraguay", t: "〈Paraguay〉"},
	{i: "peru", t: "〈Peru〉"},
	{i: "philippines", t: "〈Philippines〉"},
	{i: "poland", t: "〈Poland〉"},
	{i: "portugal", t: "〈Portugal〉"},
	{i: "qatar", t: "〈Qatar〉"},
	{i: "reunion", t: "〈Réunion〉"},
	{i: "romania", t: "〈Romania〉"},
	{i: "russia", t: "〈Russia〉"},
	{i: "rwanda", t: "〈Rwanda〉"},
	{i: "sahrawiarabdemocraticrepublic", t: "〈Sahrawi Arab Democratic Republic〉"},
	{i: "stkittsandnevis", t: "〈Saint Kitts and Nevis〉"},
	{i: "stlucia", t: "〈Saint Lucia〉"},
	{i: "saintpierreandmiquelon", t: "〈Saint Pierre and Miquelon〉"},
	{i: "stvincentandgrenadines", t: "〈Saint Vincent and Grenadines〉"},
	{i: "samoa", t: "〈Samoa〉"},
	{i: "sanmarino", t: "〈San Marino〉"},
	{i: "saotomeandprincipe", t: "〈Sao Tomé and Principe〉"},
	{i: "saudiarabia", t: "〈Saudi Arabia〉"},
	{i: "senegal", t: "〈Senegal〉"},
	{i: "serbia", t: "〈Serbia〉"},
	{i: "seychelles", t: "〈Seychelles〉"},
	{i: "sierraleone", t: "〈Sierra Leone〉"},
	{i: "singapore", t: "〈Singapore〉"},
	{i: "slovakia", t: "〈Slovakia〉"},
	{i: "slovenia", t: "〈Slovenia〉"},
	{i: "solomonislands", t: "〈Solomon Islands〉"},
	{i: "somalia", t: "〈Somalia〉"},
	{i: "southafrica", t: "〈South Africa〉"},
	{i: "southkorea", t: "〈South Korea (Republic Korea)〉"},
	{i: "spain", t: "〈Spain〉"},
	{i: "srilanka", t: "〈Sri Lanka〉"},
	{i: "sudan", t: "〈Sudan〉"},
	{i: "suriname", t: "〈Suriname〉"},
	{i: "swaziland", t: "〈Swaziland〉"},
	{i: "sweden", t: "〈Sweden〉"},
	{i: "switzerland", t: "〈Switzerland〉"},
	{i: "syria", t: "〈Syria〉"},
	{i: "taiwan", t: "〈Taiwan〉"},
	{i: "tajikistan", t: "〈Tajikistan〉"},
	{i: "tanzania", t: "〈Tanzania〉"},
	{i: "thailand", t: "〈Thailand〉"},
	{i: "togo", t: "〈Togo〉"},
	{i: "tonga", t: "〈Tonga〉"},
	{i: "trinidadandtobago", t: "〈Trinidad and Tobago〉"},
	{i: "tunisia", t: "〈Tunisia〉"},
	{i: "turkey", t: "〈Turkey〉"},
	{i: "turkmenistan", t: "〈Turkmenistan〉"},
	{i: "tuvalu", t: "〈Tuvalu〉"},
	{i: "uganda", t: "〈Uganda〉"},
	{i: "ukraine", t: "〈Ukraine〉"},
	{i: "unitedarabemirates", t: "〈United Arab Emirates〉"},
	{i: "unitedkingdom", t: "〈United Kingdom〉"},
	{i: "unitedstatesofamerica", t: "〈United States of America〉"},
	{i: "uruguay", t: "〈Uruguay〉"},
	{i: "uzbekistan", t: "〈Uzbekistan〉"},
	{i: "vanuatu", t: "〈Vanuatu〉"},
	{i: "vaticancity", t: "〈Vatican City〉"},
	{i: "venezuela", t: "〈Venezuela〉"},
	{i: "vietnam", t: "〈Vietnam〉"},
	{i: "yemen", t: "〈Yemen〉"},
	{i: "zambia", t: "〈Zambia〉"},
	{i: "zimbabwe", t: "〈Zimbabwe〉"}
];
