//:Primeiros Socorros
// Generated file, do not edit
var langTexts={
	title: "Primeiros Socorros",
	back: "Voltar",
	continent: "Continente",
	emergency_fire: "Bombeiros",
	emergency_medical: "Médico",
	emergency_police: "Polícia",
	emergency_cancelcard: "",
	emergency_local: "local números",
	emergency_nosystem: "não obrigatórias",
	emergency_radioonly: "apenas telefones de rádio",
	emergency_none: "--",
	emergency_or: "or",
	emergency_mobile: "móvel",
	emergency_tourist: "turistas"
};
var langMenu=[
	{h: "#aid_disclaimer", t: "# Aviso Legal"},
	{h: "#numbers", t: "# Chamadas de emergência"},
	{h: "#aid_general", t: "# Conduta Geral"},
	{h: "#aid_electricityaccident", t: "Acidente com Electricidade"},
	{h: "#aid_safeguardaccident", t: "Acidente de Tráfego"},
	{h: "#aid_snakebite", t: "Acidente ofídico"},
	{h: "#aid_resuscitation", t: "A compressão do tórax"},
	{h: "#aid_drowning", t: "Afogamento"},
	{h: "#aid_diabeticcoma", t: "A hiperglicemia (açúcar)"},
	{h: "#aid_hypoglycaemia", t: "A hipoglicemia (níveis baixos de açúcar)"},
	{h: "#aid_hypothermia", t: "A hipotermia (corpo frio)"},
	{h: "#aid_amputation", t: "Amputação"},
	{h: "#aid_apnoea", t: "Apnéia"},
	{h: "#aid_suffocation", t: "Asfixia"},
	{h: "#aid_asthma", t: "Asma"},
	{h: "#aid_heartattack", t: "Ataque do coração"},
	{h: "#aid_stroke", t: "Ataque Súbito"},
	{h: "#aid_checkbreathing", t: "Checar Respiração"},
	{h: "#aid_shock", t: "Choque"},
	{h: "#aid_diabeticcoma", t: "Coma diabético"},
	{h: "#aid_brainconcussion", t: "Concussão no cerébro"},
	{h: "#aid_diarrhoea", t: "Diarreia"},
	{h: "#aid_asthma", t: "Dispnéia"},
	{h: "#aid_suffocation", t: "Engasgado"},
	{h: "#aid_poisining", t: "Envenenamento"},
	{h: "#aid_epilepsy", t: "Epilepsia"},
	{h: "#aid_sprain", t: "Esforços + distenção"},
	{h: "#aid_fracture", t: "Fratura"},
	{h: "#aid_skullfracture", t: "Fratura Craniana"},
	{h: "#aid_backinjury", t: "Fratura Espinhal"},
	{h: "#aid_hyperthermia", t: "Hipertermia (calor corporal)"},
	{h: "#aid_unconsciouswithbreath", t: "Inconsciência com respiração"},
	{h: "#aid_unconsciouswithoutbreath", t: "Inconsciência sem respirar"},
	{h: "#aid_sunstroke", t: "Insolação"},
	{h: "#aid_backinjury", t: "Lesões nas Costas"},
	{h: "#aid_eyeinjury", t: "Lesões oculares"},
	{h: "#aid_emergencycall", t: "Ligar para emergência"},
	{h: "#aid_animalbite", t: "Mordida de Animal"},
	{h: "#aid_birth", t: "Nascimento"},
	{h: "#aid_insectstings", t: "Picadas de Insetos"},
	{h: "#aid_recoveryposition", t: "Posição de Recuperação"},
	{h: "#aid_frostbitesevere", t: "Queimadura por frio grave"},
	{h: "#aid_frostbitemild", t: "Queimadura por frio leve"},
	{h: "#aid_chemicalburn", t: "Queimadura Quimica"},
	{h: "#aid_chemicalburneyes", t: "Queimadura Quimica (Olhos)"},
	{h: "#aid_burningsevere", t: "Queimaduras Graves"},
	{h: "#aid_burningslight", t: "Queimaduras Ligeiras"},
	{h: "#aid_sunburn", t: "Queimadura solar"},
	{h: "#aid_allergic", t: "Reação alérgica"},
	{h: "#aid_resuscitation", t: "Reanimação"},
	{h: "#aid_icerescue", t: "Resgate no gelo"},
	{h: "#aid_apnoea", t: "Respiração"},
	{h: "#aid_bleedingsevere", t: "Sangramento grave"},
	{h: "#aid_bleedinglight", t: "Sangramento leve"},
	{h: "#aid_nosebleeding", t: "Sangramento no Nariz"},
	{h: "#aid_safeguardaccident", t: "Segurança em Acidente"},
	{h: "#aid_sos", t: "SOS"},
	{h: "#aid_vomiting", t: "Vômito"},
	{h: "#aid_dangerzone", t: "Zona de Perigo (Resgate)"},
	{h: "tel:112", t: "Ligue para emergência 112"}
];
var langSections={
	aid_disclaimer: [
		{k: "title", t: "Aviso Legal"},
		{k: "subsection", t: "Software "},
		{k: "description", t: "Primeiros Socorros no seu celular"},
		{k: "description", t: "Copyright: Kai Kajus Noack"},
		{k: "description", t: "Tradutor: Lucas Daniel Souza de Medeiros"},
		{k: "description", t: "Licença: Creative Commons"},
		{k: "image", i: "cc88x31"},
		{k: "description", t: "Este programa tem o propósito de dar informações sobre primeiros socorros. No entanto, elas não substituem nenhum curso. É algo que serve para atualizar o conhecimento já adquirido."},
		{k: "description", t: "Figuras © Med4Teens"},
		{k: "subsection", t: "Disclaimer "},
		{k: "description", t: "Por favor note que eu não me responsabilizo pelas consequências resultantes da utilização do software."},
		{k: "description", t: "Qualquer responsabilidade é excluída!"},
		{k: "description", t: "Utilização por sua conta e risco!"},
		{k: "description", t: "Em todas as situações de emergência, por favor procurar ajuda profissional imediatamente."},
		{k: "subsection", t: "Salvar uma vida, é ter salvado o mundo."}
	],
	aid_general: [
		{k: "title", t: "Conduta Geral"},
		{k: "step", p: [{t: "Realizar sempre os primeiros socorros. Você não pode cometer erros."}]},
		{k: "step", p: [{t: "Prestar sempre atenção à sua própria segurança."}]},
		{k: "step", p: [{t: "Analisar a situação e garantir segurança no lugar do acidente."}]},
		{k: "step", p: [{t: "Chamada de emergência + Primeiros Socorros!"}]},
		{k: "step", p: [{t: "Se existirem várias vítimas, o tratamento dos mais prejudicados tem prioridade."}]},
		{k: "step", p: [{t: "Tente acalmar a vítima. Fique calmo você também!"}]},
		{k: "step", p: [{t: "Se possível deitá-lo(a) confortavelmente. Nunca dê álcool, nicotina ou drogas para uma pessoa."}]}
	],
	aid_allergic: [
		{k: "title", t: "Reação alérgica", i: "aid046"},
		{k: "step", p: [{t: "Telefone para uma ambulância imediatamente."}]},
		{k: "step", p: [{t: "Tente acalmar a vítima e deixá-lo sentar-se confortavelmente."}]},
		{k: "step", p: [{t: "Remover a causa da alergia (por exemplo um férrão de abelha) cuidadosamente."}]},
		{k: "step", p: [{t: "Esfrie a pele afetada (compressa úmida, gelo)."}]},
		{k: "image", i: "aid046ice"},
		{k: "step", p: [{t: "Se tiver um antídoto, ele deve usá-lo (ajude-o)."}]},
		{k: "step", p: [{t: "Monitore a condição da vítima até a ambulância chegar."}]},
		{k: "step", p: [{t: "Se o acidentado perder a consciência ou a respiração parar, siga instruções apropriadas!"}]},
		{k: "image", i: "aid077"}
	],
	aid_amputation: [
		{k: "title", t: "Amputação"},
		{k: "description", t: "A parte do corpo amputada pode ser recolocada. Objetivo: Manter a parte amputada arrefecida até chegar ao hospital."},
		{k: "step", p: [{t: "Acalmar a pessoa, deitá-lo(a) para baixo, e cobrir com cobertor."}]},
		{k: "step", p: [{t: "Parar o sangramento, consulte 'Hemorragia (grave)' e 'Choque'."}]},
		{k: "step", p: [{t: "Embrulhe a parte amputada em um pano limpo e seco, e colocá-la em um saco plástico impermeável."}]},
		{k: "step", p: [{t: "Fechar este saco plástico e colocá-lo em outro saco plástico, que contenha água fria/gelo."}]},
		{k: "step", p: [{t: "Não dê álcool, cigarros ou alimentos à vítima (no caso de uma cirurgia com anestesia no hospital)."}]},
		{k: "step", p: [{t: "Não congele a parte amputada, (apenas mantenha fria)."}]},
		{k: "step", p: [{t: "Ligue para emergência ou por ultimo leve-a ao hospital sozinho."}]}
	],
	aid_animalbite: [
		{k: "title", t: "Mordida de Animal", i: "aid047"},
		{k: "description", t: "Atenção: alto risco de infecção. Resultado poderia dar infecção, tétano, ou raiva."},
		{k: "step", p: [{t: "Lavar ferida com água quente sabão."}]},
		{k: "image", i: "aid049"},
		{k: "step", p: [{t: "Depois desinfecte a ferida."}]},
		{k: "step", p: [{t: "Se houver hemorragia grave, elevar a parte superior do corpo da pessoa."}]},
		{k: "step", p: [{t: "Aplicar um curativo asséptico."}]},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Vá a um hospital ou ligue para emergência."}]}
	],
	aid_apnoea: [
		{k: "title", t: "Apnéia"},
		{k: "description", t: "Sem sons ou movimentos respiratórios, perceptível descoloração da pele."},
		{k: "step", p: [{t: "Chamada de emergência."}]},
		{k: "step", p: [{t: "Deite o acidentado de costas."}]},
		{k: "step", p: [{t: "Estique a cabeça pra trás. Remover objetos da boca e da garganta."}]},
		{k: "image", i: "aid067"},
		{k: "step", p: [{t: "Puxe o nariz e verifique se está fechado."}]},
		{k: "image", i: "aid010"},
		{k: "step", p: [{t: "Respire fundo e encaixe a boca na boca do acidentado, de forma que não possa vazar ar."}]},
		{k: "image", i: "aid011"},
		{k: "step", p: [{t: "Respire fora devagar e completamente."}]},
		{k: "step", p: [{t: "Senão tiver sucesso: Faça respiração até a ambulância chegar."}]}
	],
	aid_asthma: [
		{k: "title", t: "Asma"},
		{k: "description", t: "Grande dificuldade em respirar. Chiado ruído respiratório. Ansiedades."},
		{k: "step", p: [{t: "Acalme à pessoa. Fique calmo você também!"}]},
		{k: "step", p: [{t: "Afrouxar roupas."}]},
		{k: "step", p: [{t: "Deixe o acidentado sentar inclinado para frente, mande-o respirar devagar e profundamente."}]},
		{k: "step", p: [{t: "Se ocasionalmente tiver um inalador, ele deve usá-lo (ajude-o). 5-10 min após a utilização deverá fazer efeito."}]},
		{k: "image", i: "aid074"},
		{k: "step", p: [{t: "Caso não haja melhora: Use o inalador a cada 5 min até ambulância chegar."}]},
		{k: "step", p: [{t: "Chamada de emergência."}]},
		{k: "step", p: [{t: "Se houver "}, {t: "apnéia", h: "#aid_apnoea"}, {t: ", comece com a respiração."}]}
	],
	aid_backinjury: [
		{k: "title", t: "Lesões nas Costas"},
		{k: "description", t: "Dor nas costas, braços e pernas dormentes."},
		{k: "step", p: [{t: "Não mova o acidentado!!"}]},
		{k: "image", i: "aid064"},
		{k: "step", p: [{t: "Segure a cabeça do jeito que estiver, mantendo a pessoa estável (manter a sua cabeça parado)"}]},
		{k: "image", i: "aid065"},
		{k: "step", p: [{t: "Estabilizar o acidentado com travesseiros na lateral."}]},
		{k: "step", p: [{t: "Acalme à vitima."}]},
		{k: "step", p: [{t: "Ligue para emergência, lembre-se de salientar o tipo de lesão."}]}
	],
	aid_birth: [
		{k: "title", t: "Nascimento"},
		{k: "description", t: "Saída de líquido amniótico. Contração, ocorrerá dores. Nascimento inesperado."},
		{k: "image", i: "aid025"},
		{k: "step", p: [{t: "Preste atenção à privacidade e mantenha a calma! - Ligue para a emergência."}]},
		{k: "step", p: [{t: "Deixar a mulher grávida nua apenas parte inferior do seu corpo, e sente-se em local estéril sobre um calço com as pernas dobradas."}]},
		{k: "step", p: [{t: "Dobre os joelhos. Suba as pernas. Posição da bacia ligeiramente ascendente. - O parto é um processo natural e ocorrerá sem complicações."}]},
		{k: "step", p: [{t: "Mantenha a mulher calma, deixe-a concentrar-se na propria respiração: inspire através do nariz, e expire da boca para fora (em velocidade normal)."}]},
		{k: "step", p: [{t: "Ritmo de pressionamento: Respire fundo, mantenha respiração, e pressione. Logo que a cabeça do bebê aparecer, apoie-o, segurando-o com ambas as mãos."}]},
		{k: "image", i: "aid021"},
		{k: "image", i: "aid022"},
		{k: "step", p: [{t: "Após o parto: Segure o bebê cuidadosamente com cabeça para baixo para liberar as vias aéreas e saida de líquido amniótico. (Talvez você tenha que sugar para fora o fluido a partir da boca do bebê pelo nariz.) O bebê deve respirar e chorar!"}]},
		{k: "step", p: [{t: "Amarrar o cordão umbilical 30 centímetros de distância da criança (também pode ser feito no hospital). Mantenha a vagina da mãe estéril."}]},
		{k: "image", i: "aid023"},
		{k: "step", p: [{t: "Seque o bebê e o mantenha aquecido. Anote a hora e leve-a para o hospital."}]}
	],
	aid_bleedinglight: [
		{k: "title", t: "Sangramento leve", i: "aid082"},
		{k: "description", t: "Objetivo: Parar o sangramento."},
		{k: "step", p: [{t: "Não toque na ferida (risco de infecção)."}]},
		{k: "step", p: [{t: "Não se trata ferida com pó ou sprays."}]},
		{k: "step", p: [{t: "Rratamento da ferida: utilize material estéril e uma bandagem."}]},
		{k: "image", i: "aid098"},
		{k: "step", p: [{t: "Para pequenas hemorragias é freqüentemente suficiente um tamponamento."}]},
		{k: "step", p: [{t: "Se for uma grande hemorragia usar uma atadura e cobrir com uma bandagem. Não se aplica à bandagem apertado como uma imobilização, pode levar ao aumento das hemorragias."}]},
		{k: "image", i: "aid084"},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Nota: Ferimentos de raiva têm que ser lavadas com solução de sabão."}]},
		{k: "image", i: "aid049"}
	],
	aid_bleedingsevere: [
		{k: "title", t: "Sangramento grave"},
		{k: "description", t: "Salpicos, sangue pulsante. Perigo: Pode engasgar por causa da perda de sangue, infecções, a morte. Objetivo: Parar o sangramento."},
		{k: "step", p: [{t: "Remover roupas (cortar se necessário) e amostrar ferida."}]},
		{k: "step", p: [{t: "Enrole uma gaze ou se necessário, uma peça com a pressão em torno da ferida."}]},
		{k: "image", i: "aid086"},
		{k: "step", p: [{t: "Exercer pressão por pelo menos 10 min."}]},
		{k: "step", p: [{t: "Se for as bandagens ficarem encharcadas com sangue, não remova-as. Em vez disso, enrole outra bandagem / vestuário em torno do ferimento."}]},
		{k: "step", p: [{t: "Conservar o membro afetado (caso não esteja quebrado) mais elevado do que o coração para reduzir a quantidade de pressão arterial. Se possível deitar à viima."}]},
		{k: "step", p: [{t: "Se não parar de sangrar, manter a pressão sobre a ferida, e defina mais um ponto de pressão na ferida: Para uma hemorragia do antebraço comprima o braço (Pressione na face interna da veia do braço, no meio do cotovelo e na dobra do braço, utilizando seus dedos). Sangramento na perna deve-se fazer pressão de ponto no inguinal (pressione na veia da virilha trafulha, artéria onde leva mais de osso ilíaco, utilizando a sua palma da mão)."}]},
		{k: "image", i: "aid089"},
		{k: "image", i: "aid092"},
		{k: "step", p: [{t: "Ligue para emergência médico imediatamente."}]},
		{k: "step", p: [{t: "Assim que o sangramento estiver sob controle: Iniciar medidas anti-asfixiante."}]},
		{k: "image", i: "aid093"}
	],
	aid_brainconcussion: [
		{k: "title", t: "Concussão no cerébro"},
		{k: "description", t: "Dores de cabeça, náuseas, vômitos. Visão deficiente. Inconsciência pode ocorrer."},
		{k: "image", i: "aid035a"},
		{k: "step", p: [{t: "Olhar desinteressado ou vago (ao infinito)."}]},
		{k: "step", p: [{t: "Chame a emergência."}]},
		{k: "description", t: "Se sangrar a cabeça:"},
		{k: "step", p: [{t: "Posicione a vítima, em uma posição de cabeça elevada (no travesseiro)."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Faça tratamento de ferida (utilize bandagem estéril)."}]},
		{k: "step", p: [{t: "Ligue para emergência."}]}
	],
	aid_burningslight: [
		{k: "title", t: "Queimaduras Ligeiras"},
		{k: "description", t: "Vermelhidão da pele. Leve inchaço. Dor."},
		{k: "step", p: [{t: "Mantenha a área queimada sob água fria."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Aplicar curativo molhado folgadamente."}]}
	],
	aid_burningsevere: [
		{k: "title", t: "Queimaduras Graves"},
		{k: "description", t: "Manchas de vermelho-branco e areas com formação de bolhas. A pele perde fluido. Danos profundos de tecido. Forte dor ou sem dor (por causa dos nervos queimados)."},
		{k: "image", i: "aid097"},
		{k: "step", p: [{t: "Remover as roupas tanto quanto possível."}]},
		{k: "step", p: [{t: "Refrigere as partes do corpo queimado com água (cerca de 15 ° C, 59 ° F) por até 10 minutos, até a dor diminuir."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Em casos em que a queimadura for extensa, utilize toalhas molhadas para esfriar."}]},
		{k: "step", p: [{t: "Ligue para emergência."}]},
		{k: "step", p: [{t: "Após o resfriamento da ferida: Use um curativo estéril. Não aplique qualquer fluido (sem cremes, óleos, pomadas, etc.) Não furar as bolhas."}]},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Controle a respiração e consciência da pessoa até a chegada da emergência."}]}
	],
	aid_checkbreathing: [
		{k: "title", t: "Checar Respiração"},
		{k: "step", p: [{t: "Verifique sons respiratórios."}]},
		{k: "step", p: [{t: "Diagnosticar a respiração na parte superior do abdómen (leigos a sua mão sobre ela)."}]},
		{k: "image", i: "aid027"},
		{k: "step", p: [{t: "No sentido respiração boca e nariz."}]}
	],
	aid_chemicalburneyes: [
		{k: "title", t: "Queimadura Quimica (Olhos)"},
		{k: "step", p: [{t: "Ligue para emergência, leve a embalagem do produto químico, 'pois o mesmo tem telefone especifico para casos de acidentes.'"}]},
		{k: "step", p: [{t: "Lave os olhos com muita água. Cubra algum olho saudável durante a lavagem."}]},
		{k: "step", p: [{t: "Conduzir o jato de água do ângulo interior do olho ao ângulo exterior do olho. Limpe durante pelo menos 20 minutos sob água."}]},
		{k: "image", i: "aid019"},
		{k: "step", p: [{t: "Fechar os dois olhos da vitima e cobri-lo com pano úmido."}]},
		{k: "image", i: "aid020"},
		{k: "step", p: [{t: "Monitore as condições até a ambulância chegar."}]}
	],
	aid_chemicalburn: [
		{k: "title", t: "Queimadura Quimica"},
		{k: "description", t: "Lesões de tecido."},
		{k: "image", i: "aid095"},
		{k: "step", p: [{t: "Mente auto-defesa!"}]},
		{k: "step", p: [{t: "Agir rapidamente e lavar os locais queimados."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Ligar para emergência."}]},
		{k: "step", p: [{t: "Se há uma queimadura química no sistema digestivo uma das maneiras é beber muita água."}]},
		{k: "step", p: [{t: "Não provocar vômitos!"}]}
	],
	aid_dangerzone: [
		{k: "title", t: "Zona de Perigo (Resgate)"},
		{k: "step", p: [{t: "Realização: Posicione os braços da vitima na frente de seu peito, e ficar por trás dele / dela."}]},
		{k: "step", p: [{t: "Coloque as mãos sob os ombros dos feridos, agarrando o braço de forma angular."}]},
		{k: "step", p: [{t: "Puxar para trás e levar a pessoa em segurança."}]},
		{k: "image", i: "aid001"},
		{k: "image", i: "aid007"}
	],
	aid_diabeticcoma: [
		{k: "title", t: "Coma diabético"},
		{k: "description", t: "Nível de açúcar no sangue for demasiado elevado (falta de insulina)."},
		{k: "description", t: "Sintomas: Sede, freqüência urinária, náuseas, vômitos. Respiração com cheiro de frutas / vinho."},
		{k: "step", p: [{t: "Ligue para emergência."}]},
		{k: "step", p: [{t: "Ajude a vitima (se for assegurada diabéticos) a tomar insulina."}]},
		{k: "image", i: "aid016"},
		{k: "step", p: [{t: "Posição de recuperação.", h: "#aid_recoveryposition"}, {t: " (Não existem posições para os primeiros socorros.)"}]},
		{k: "step", p: [{t: "Monitorar a condição da vitima até que chegue médico de emergência."}]}
	],
	aid_diarrhoea: [
		{k: "title", t: "Diarreia"},
		{k: "description", t: "Reação para alimentos contaminados, a infecção do intestino ou distúrbio. Fezes é diluído, viscosas ou sanguinolenta."},
		{k: "step", p: [{t: "Perigo para a circulação devido à desidratação e perda de sal!"}]},
		{k: "step", p: [{t: "Dê líquidos (chá, água)."}]},
		{k: "step", p: [{t: "Se houver fortes perturbações levar ao médico de emergência."}]}
	],
	aid_drowning: [
		{k: "title", t: "Afogamento"},
		{k: "step", p: [{t: "Chamada de emergência. Pergunte as pessoas próximas a você para ajudar."}]},
		{k: "image", i: "aid032"},
		{k: "step", p: [{t: "Resgate a pessoa para fora da água!"}]},
		{k: "image", i: "aid033"},
		{k: "image", i: "aid034"},
		{k: "step", p: [{t: "Se a vitima estiver respirando: "}, {t: "Posição de recuperação", h: "#aid_recoveryposition"}, {t: ". Mantenha-o quente (cubra-o). Monitore seu estado até a chegada da ambulancia."}]},
		{k: "step", p: [{t: "Se a vitima não estiver respirando: Comece imediatamente com a "}, {t: "reanimação", h: "#aid_resuscitation"}, {t: "! (Remover a água dos pulmões é inútil.)"}]}
	],
	aid_electricityaccident: [
		{k: "title", t: "Acidente com Electricidade"},
		{k: "step", p: [{t: "Em primeiro lugar interromper o fornecimento de electricidade!"}]},
		{k: "image", i: "aid045plug"},
		{k: "image", i: "aid045"},
		{k: "step", p: [{t: "Perigo: inconsciência, apneia."}]},
		{k: "step", p: [{t: "A - inconsciência com a respiração", h: "#aid_unconsciouswithbreath"}]},
		{k: "step", p: [{t: "B - inconsciência sem respirar", h: "#aid_unconsciouswithoutbreath"}]},
		{k: "image", i: "aid042"},
		{k: "image", i: "aid043"}
	],
	aid_emergencycall: [
		{k: "title", t: "Ligar para emergência"},
		{k: "step", p: [{t: "Disque 193 (bombeiros) 192 (SAMU). Sempre que possível, é de graça! Não hesite em ligar para uma ambulância!"}]},
		{k: "step", p: [{t: "Ao telefonar você deve fornecer as seguintes informações:"}]},
		{k: "step", p: [{t: "- O que tem acontecido"}]},
		{k: "step", p: [{t: "- Onde (lugar do acidente)"}]},
		{k: "step", p: [{t: "- Quantas vitimas "}]},
		{k: "step", p: [{t: "- Que tipo de lesões."}]},
		{k: "step", p: [{t: "Posteriormente espere para novas investigações. "}]}
	],
	aid_epilepsy: [
		{k: "title", t: "Epilepsia"},
		{k: "description", t: "Corpo rígido, punhos fechados , mandíbula pressionada, contração muscular nos membros ou face. Olhos revirando. Salivação. possível inconsciência ."},
		{k: "image", i: "aid058"},
		{k: "step", p: [{t: "Não segure a vitima ou o seu movimento."}]},
		{k: "step", p: [{t: "Coloque a vitima em uma base suave (almofadas), remover objetos proximos para evitar auto-lesão."}]},
		{k: "step", p: [{t: "Acalme a vitima. Afrouxar roupas, dar liberdade de respiração."}]},
		{k: "step", p: [{t: "Se a vitima vômitar, vire a cabeça para o lado que o vômito possa escorrer."}]},
		{k: "step", p: [{t: "Manter vias aéreas claro. Risco de engolir a língua."}]},
		{k: "step", p: [{t: "Posição recuperação", h: "#aid_recoveryposition"}, {t: ": chame a emergência. Continuar a monitorar o estado da vítima."}]},
		{k: "step", p: [{t: "Mantenha os curiosos à distância."}]}
	],
	aid_eyeinjury: [
		{k: "title", t: "Lesões oculares"},
		{k: "step", p: [{t: "Deixe objeto no olho da vitima, não remova-o!"}]},
		{k: "step", p: [{t: "Mantenha os olhos sem se mexer para evitar novas lesões. Não toque no olho."}]},
		{k: "step", p: [{t: "Se olho está sangrando, cubra-o com uma compressa ou uma gaze estéril."}]},
		{k: "image", i: "aid020"},
		{k: "step", p: [{t: "Mantenha o olho com uma almofada fria (reduz edema, estanca a hemorragia mais rápido)."}]},
		{k: "step", p: [{t: "Ligue para emergência ou leve-o por si mesmo."}]}
	],
	aid_fracture: [
		{k: "title", t: "Fratura"},
		{k: "description", t: "Sintomas: Posição deslocada e mobilidade do osso. Deformação. Movimento doloroso, sensível ao toque."},
		{k: "image", i: "aid104"},
		{k: "step", p: [{t: "Evite movimentos!"}]},
		{k: "step", p: [{t: "Ligar para emergencia."}]},
		{k: "step", p: [{t: "Imobilizar o osso fraturado, ou seja, imobilizar o local apoiado-o firmemente. Manter a posição do osso."}]},
		{k: "image", i: "aid107"},
		{k: "step", p: [{t: "Se for fratura aberta, cobrir a ferida com material estéril."}]},
		{k: "image", i: "aid106"}
	],
	aid_frostbitemild: [
		{k: "title", t: "Queimadura por frio leve"},
		{k: "description", t: "Palidez, inchaços. Perigo para a irrigação sanguínea."},
		{k: "step", p: [{t: "Leve à vitima para uma zona quente."}]},
		{k: "step", p: [{t: "Afaste-se de frio, retire roupas frio, seque a pessoa."}]},
		{k: "step", p: [{t: "Aquecer com água morna e com o calor do corpo do ajudante."}]},
		{k: "step", p: [{t: "Dar bebida quente (chá). Nenhum álcool!"}]},
		{k: "image", i: "aid040"}
	],
	aid_frostbitesevere: [
		{k: "title", t: "Queimadura por frio grave"},
		{k: "description", t: "Pele extremamente fria, cinza-branca, bolhas, tecido morto. Perigo para o fornecimento de sangue!"},
		{k: "image", i: "aid096"},
		{k: "step", p: [{t: "Ir para a área quente."}]},
		{k: "step", p: [{t: "Tratamento ferida / cobertura."}]},
		{k: "step", p: [{t: "Dê uma bebida açucarada."}]},
		{k: "step", p: [{t: "Não esfregue a vitima com material quente!"}]},
		{k: "step", p: [{t: "Chame a emergência."}]}
	],
	aid_heartattack: [
		{k: "title", t: "Ataque do coração"},
		{k: "description", t: "Pesados, com duração superior a 5 min de pressão e dor no peito, especialmente irradiando nos braços/ombros. Ansiedade, palidez, sudorese fria. Eventualmente, náuseas, falta de ar."},
		{k: "image", i: "aid076"},
		{k: "image", i: "aid083"},
		{k: "step", p: [{t: "Chame a emergência e peça o 'DEA'(desfribilador externo automatico)! Avise sobre o suposto ataque cardíaco."}]},
		{k: "step", p: [{t: "Posicione a parte superior do corpo elevada. Afrouxar roupas apertadas. Não dê drogas ou bebidas."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Calmamente conversar com a pessoa em causa."}]},
		{k: "step", p: [{t: "Controle a consciência e respiração."}]},
		{k: "step", p: [{t: "Dê a aspirina se disponível."}]},
		{k: "step", p: [{t: "Se pessoa estiver inconsciente iniciar a "}, {t: "reanimação", h: "#aid_resuscitation"}, {t: "."}]}
	],
	aid_hypoglycaemia: [
		{k: "title", t: "A hipoglicemia (níveis baixos de açúcar)"},
		{k: "description", t: "Nível de açúcar no sangue está abaixo valor mínimo (porcausa de overdose de insulina suficiente ou não ingestão de alimentos)."},
		{k: "description", t: "Sintomas: Palidez, nervosismo, a fome, arrepios, suores."},
		{k: "image", i: "aid018"},
		{k: "step", p: [{t: "Certifique-se de que a pessoa é diabética (procure por um crachá de diabético)."}]},
		{k: "step", p: [{t: "Chame a emergência."}]},
		{k: "step", p: [{t: "Dê uma bebida açucarada e dextrose/glicose (se não houver problemas de deglutição)."}]},
		{k: "image", i: "aid017"},
		{k: "step", p: [{t: "Se pessoa está consciente e respira: "}, {t: "Posição de recuperação", h: "#aid_recoveryposition"}, {t: ". Monitore a respiração da pessoa. Se houver apneia, dê início com a respiração."}]},
		{k: "step", p: [{t: "Se não houver respiração, você pode colocar um pouco de açúcar na bochecha, empurre a partir de fora contra ele."}]}
	],
	aid_hyperthermia: [
		{k: "title", t: "Hipertermia (calor corporal)"},
		{k: "description", t: "Sede, fraqueza, desorientação, náuseas, confusão, forte sudorese, pele quente."},
		{k: "image", i: "aid035"},
		{k: "step", p: [{t: "Chame a emergência."}]},
		{k: "step", p: [{t: "Encontre um lugar fresco (sala com ar condicionado preferível)."}]},
		{k: "step", p: [{t: "Fixar pessoa, elevar as pernas. Afrouxar roupas."}]},
		{k: "image", i: "aid078"},
		{k: "step", p: [{t: "Arrefecer a pele com muita água ou passar toalha umida."}]},
		{k: "step", p: [{t: "Dê muita água ou sucos para beber."}]}
	],
	aid_hypothermia: [
		{k: "title", t: "A hipotermia (corpo frio)"},
		{k: "description", t: "Arrepio frio, sonolência, cansaço, até inconsciência. Cor de pele pálida. Pulso lento, batimento cardíaco fraco."},
		{k: "image", i: "aid014"},
		{k: "step", p: [{t: "Vá a uma área quente/sala."}]},
		{k: "step", p: [{t: "Chamar a emergência."}]},
		{k: "step", p: [{t: "Pare de impacto do frio. Aumente da temperatura corporal (cubra e faça contato corpo-a-corpo)."}]},
		{k: "step", p: [{t: "Remover roupas molhadas e colocar roupas quentes. Cobrir a cabeça."}]},
		{k: "step", p: [{t: "Dá chá quente, sopa quente ou água para beber. Nenhum álcool! Manter a pessoa acordada."}]},
		{k: "image", i: "aid039"},
		{k: "image", i: "aid040"},
		{k: "step", p: [{t: "Monitore a condição da vitima até que a emergencia chegue. Se pessoa ficar inconsciente, inicie a reanimação:"}]},
		{k: "step", p: [{t: "A - inconsciência com a respiração", h: "#aid_unconsciouswithbreath"}]},
		{k: "step", p: [{t: "B - inconsciência sem respirar", h: "#aid_unconsciouswithoutbreath"}]}
	],
	aid_icerescue: [
		{k: "title", t: "Resgate no gelo"},
		{k: "description", t: "Preste atenção à sua própria segurança. Perigo: Afogamento, hipotermia."},
		{k: "step", p: [{t: "Resgate via escada de bordo ou corda. O peso deve ser distribuído amplamente."}]},
		{k: "step", p: [{t: "Chame outras pessoas para ajudar. Deixe uma pessoa responsavel por chamar a ambulância."}]},
		{k: "step", p: [{t: "Rastejar cuidadosamente sobre sua barriga (se possível até um ponto estável) com a ferramenta para a violação."}]},
		{k: "image", i: "aid041"},
		{k: "step", p: [{t: "Manuseie sobre a vitima a distância da ferramenta, (não é a sua mão!) E puxe-a para fora."}]},
		{k: "step", p: [{t: "Rastejar para trás de volta para a beira."}]},
		{k: "step", p: [{t: "Primeiros socorros."}]},
		{k: "step", p: [{t: "Possível auto-salvamento: Se o gelo é sólido pode-se distribuir o seu peso sobre o gelo e puxe-se. Rastejar em sua barriga para a beira. Se gelo for frágil, pode tentar quebrar o gelo pedaço por pedaço até a beira."}]}
	],
	aid_insectstings: [
		{k: "title", t: "Picadas de Insetos", i: "aid046"},
		{k: "description", t: "Inchaço, vermelhidão, sensação de queimor, fraqueza, dificuldade respiratória, diminuição da consciência, taquicardia."},
		{k: "step", p: [{t: "Retire com cuidado o ferrão (com uma pinça). Não aperte o ferrão pois assim poderia injetar mais veneno."}]},
		{k: "step", p: [{t: "Refrigerar o local da causa (aplicar uma compressa fria)."}]},
		{k: "step", p: [{t: "Área em questão deve ser mantida mais baixo do que o coração a fim de diminuir a circulação do veneno."}]},
		{k: "step", p: [{t: "Se a picada for na area boca-queixo: Abuse de gelados, e aplique uma compressa fria em torno da garganta."}]},
		{k: "image", i: "aid046ice"},
		{k: "step", p: [{t: "Se ocorrerem problemas graves chamar uma ambulância."}]}
	],
	aid_nosebleeding: [
		{k: "title", t: "Sangramento no Nariz"},
		{k: "description", t: "Rompeu uma pequena artéria na ponta do nariz."},
		{k: "step", p: [{t: "Sente a pessoa com o sangramento, um pouco virada pra frente. Manter a cabeça reta."}]},
		{k: "step", p: [{t: "Não coloque a pessoa deitada, mantenha a cabeça acima do nivel do coração, para assim cessar o sangramento lentamente."}]},
		{k: "step", p: [{t: "Enrole o pescoço com pano frio."}]},
		{k: "step", p: [{t: "Pressione as narinas juntas até que estanque a hemorragia (por 10 min)."}]},
		{k: "step", p: [{t: "Depois não assoe o nariz (sem sopros violentos)."}]},
		{k: "step", p: [{t: "Se ocorrerem problemas graves ou sangramento não puder ser parado, chame a emergência médica."}]}
	],
	aid_poisining: [
		{k: "title", t: "Envenenamento", i: "aid052"},
		{k: "description", t: "Confusão, alucinações, pupilas dilatadas, febre, cãinbras. Inconsciência."},
		{k: "step", p: [{t: "Só dar antídotos, se forem acompanhados por um médico treinado."}]},
		{k: "image", i: "aid056"},
		{k: "step", p: [{t: "Não dê bebidas. Não provocar vômitos."}]},
		{k: "step", p: [{t: "Chame a emergência anotar o tipo do envenenamento!"}]},
		{k: "step", p: [{t: "Guardar os restos do veneno e vomitar!"}]},
		{k: "image", i: "aid054a"},
		{k: "step", p: [{t: "Se vítima está consciente e respira: Manter em "}, {t: "posição de recuperação", h: "#aid_recoveryposition"}, {t: ". Monitore o estado da vitima ate a chegada da ambulância."}]},
		{k: "step", p: [{t: "Se a vítima não estiver respirando: Começar imediatamente com "}, {t: "reanimação", h: "#aid_resuscitation"}, {t: "! Limpe a boca de vômito de antemão."}]}
	],
	aid_recoveryposition: [
		{k: "title", t: "Posição de Recuperação"},
		{k: "step", p: [{t: "Coloque a vitima sobre as suas costas, posiciona as pernas. Joelho para baixo ao lado."}]},
		{k: "step", p: [{t: "Coloque o braço mais próximo a você em um ângulo reto com o corpo."}]},
		{k: "step", p: [{t: "Puxar braço mais afastado do peito e coloque as costas da mão contra a bochecha."}]},
		{k: "image", i: "aid008"},
		{k: "step", p: [{t: "Pegue o joelho longe, puxe-o para seu lado, e estabelecem-lo no chão. Posição da perna direita em um ângulo. Manter a mão sobre a bochecha da vitima."}]},
		{k: "step", p: [{t: "Certifique-se as vias aéreas estão livres."}]},
		{k: "step", p: [{t: "Boca ligeiramente aberta, e a posição da cabeça de forma que o vômito possa escorrer. Confira a respiração."}]},
		{k: "image", i: "aid009"},
		{k: "step", p: [{t: "Controle o estado da vitima até que a emergência chegue."}]},
		{k: "description", t: "Posição de recuperação para bebês:"},
		{k: "image", i: "aid028"}
	],
	aid_resuscitation: [
		{k: "title", t: "Reanimação"},
		{k: "subsection", t: "# Massagem no Coração"},
		{k: "step", p: [{t: "Deite a vitima de frente. Ajoelhe-se ao lado."}]},
		{k: "step", p: [{t: "Retire qualquer roupa que cubra o peito(regiao do coracao)."}]},
		{k: "step", p: [{t: "Coloque uma mão aberta no meio do peito (um pouco acima do esterno)."}]},
		{k: "image", i: "aid013"},
		{k: "step", p: [{t: "Colocar a outra mão sobre as costas da mão, que já está na posição correta."}]},
		{k: "step", p: [{t: "Estique os seus braços e cotovelos."}]},
		{k: "image", i: "aid003"},
		{k: "step", p: [{t: "Pressione 5 cm de profundidade no tórax da vitima (a força vem da parte superior do corpo) e solte."}]},
		{k: "step", p: [{t: "Pressione 30 vezes em uma linha em breve e forte!"}]},
		{k: "subsection", t: "# Respiração"},
		{k: "step", p: [{t: "Estique a cabeça para trás do pescoço. Remover substâncias para fora da boca e da garganta."}]},
		{k: "image", i: "aid067"},
		{k: "step", p: [{t: "Empurre as abas do nariz em conjunto, de forma que nariz fique fechado."}]},
		{k: "image", i: "aid010"},
		{k: "step", p: [{t: "Respire fundo e coloque a boca na boca da vitima, de forma que não pode vazar ar."}]},
		{k: "image", i: "aid011"},
		{k: "step", p: [{t: "Fazer a respiração boca-a-boca duas vezes (respiração lenta e totalmente fora)."}]},
		{k: "step", p: [{t: "Depois fazer massagem cardíaca novamente."}]},
		{k: "description", t: "Repita a massagem cardíaca, respiração boca até a chegada da ambulância."},
		{k: "image", i: "aid012"},
		{k: "subsection", t: "Ressuscitação (Bebê)"},
		{k: "step", p: [{t: "Use apenas dois dedos:"}]},
		{k: "image", i: "aid029"},
		{k: "step", p: [{t: "Não respire muito forte:"}]},
		{k: "image", i: "aid030"}
	],
	aid_safeguardaccident: [
		{k: "title", t: "Segurança em Acidente"},
		{k: "step", p: [{t: "Pare com seu próprio carro 50-100m atrás do local do acidente, (se você estiver em uma rodovia). Ligue os alertas. Ponha colentede visibilidade."}]},
		{k: "step", p: [{t: "Posicione o triângulo de aviso antes do local do acidente. Atenção: Se o acidente é uma curva posicione o triângulo de aviso antes da curva!"}]},
		{k: "image", i: "aid111"},
		{k: "step", p: [{t: "Peça ajuda à outras pessoas."}]},
		{k: "step", p: [{t: "Abrir a porta do carro da vitima. Desligue ignição."}]},
		{k: "step", p: [{t: "Socorro às vítimas do acidente: soltar o cinto de segurança, mova o assento para trás. Deixe a remoção da vitima de dentro do carro "}, {t: "pelo pessoal de resgate", h: "#aid_dangerzone"}, {t: "."}]},
		{k: "image", i: "aid001"},
		{k: "step", p: [{t: "Chame a emergência."}]},
		{k: "step", p: [{t: "Prossiga com os primeiros socorros."}]}
	],
	aid_shock: [
		{k: "title", t: "Choque"},
		{k: "description", t: "Distúrbio circulatório pela fraca oferta de oxigênio no organismo."},
		{k: "description", t: "Causa: Perda de líquido, reduzido volume sanguíneo."},
		{k: "description", t: "Sintomas: Palidez, pele fria, suor frio, ansiedade."},
		{k: "step", p: [{t: "Eliminar a causa do choque (por exemplo, parar a perda de fluido, vincular a ferida)!"}]},
		{k: "step", p: [{t: "Estabelecer os feridos em um cobertor, a posição das pernas para cima. Manter a vitima calma."}]},
		{k: "image", i: "aid078"},
		{k: "step", p: [{t: "Chame a emergência."}]},
		{k: "step", p: [{t: "Se notar dificuldades em respirar ou consciência, iniciar "}, {t: "reanimação", h: "#aid_resuscitation"}, {t: "."}]}
	],
	aid_skullfracture: [
		{k: "title", t: "Fratura Craniana"},
		{k: "description", t: "Aspectos: sangramentos fora do nariz, boca ou ouvido. Muitas vezes existem feridas abertas no crânio."},
		{k: "step", p: [{t: "Mantenha as vias aéreas livres."}]},
		{k: "step", p: [{t: "Se consciente: Sente com os feridos curvando a cabeça para frente. Evitar maiores movimentos!"}]},
		{k: "step", p: [{t: "Se inconsciente: "}, {t: "Posição de Recuperação", h: "#aid_recoveryposition"}, {t: " (sem pressão sobre a ferida da cabeça)."}]},
		{k: "step", p: [{t: "Chame a emergência."}]},
		{k: "step", p: [{t: "Aplicar curativo na cabeça."}]},
		{k: "step", p: [{t: "Se as dificuldades em respirar ou consciência, iniciar "}, {t: "reanimação", h: "#aid_resuscitation"}, {t: "."}]}
	],
	aid_snakebite: [
		{k: "title", t: "Acidente ofídico", i: "aid051"},
		{k: "description", t: "Ferimento no tamanho de um alfinete, dor severa, edema, cor púrpura. Distúrbio circulatório, perigo de choque."},
		{k: "step", p: [{t: "Estabilize a parte do corpo ferida."}]},
		{k: "step", p: [{t: "Aplicar compressa fria ao redor da ferida."}]},
		{k: "step", p: [{t: "Utilize medidas contra choque."}]},
		{k: "step", p: [{t: "Chame a emergência."}]}
	],
	aid_sos: [
		{k: "title", t: "SOS"},
		{k: "step", p: [{t: "Sinal: 3x curto, longas 3x, 3x curto."}]},
		{k: "step", p: [{t: "Visualmente (luz estrobo, lanterna), ou acusticamente (sinal de apito, bater)."}]}
	],
	aid_sprain: [
		{k: "title", t: "Esforços + distenção"},
		{k: "description", t: "Dor, inchaço (contusão), perda da função, deformação do membro."},
		{k: "step", p: [{t: "Imobilize a parte lesada do corpo apenas na posição mais confortável para a vitima."}]},
		{k: "step", p: [{t: "Resfriar (utilizando bolsa de gelo)."}]},
		{k: "step", p: [{t: "Se possível, elevar a parte lesada."}]},
		{k: "step", p: [{t: "Ir para o hospital ou chamar a emergência médica."}]}
	],
	aid_stroke: [
		{k: "title", t: "Ataque Súbito"},
		{k: "description", t: "Súbita sensação de dormência ou paralisia (face, braços, pernas), perturbações da linguagem compreensão, a visão problemas de consciência perturbada, uma forte dor de cabeça. Problemas na respiração e deglutição, perda de controle sobre a bexiga e intestino."},
		{k: "image", i: "aid059"},
		{k: "step", p: [{t: "Chame a emergência!"}]},
		{k: "step", p: [{t: "Afrouxar roupas apertadas, não dê drogas ou bebidas."}]},
		{k: "step", p: [{t: "Sentar ou deita-lo confortavelmente. Acalme-o!"}]},
		{k: "step", p: [{t: "Controle consciência e respiração."}]},
		{k: "step", p: [{t: "Se sentir dificuldades em respirar ou consciência, iniciar "}, {t: "reanimação", h: "#aid_resuscitation"}, {t: "."}]}
	],
	aid_suffocation: [
		{k: "title", t: "Asfixia"},
		{k: "description", t: "A insuficiência de oxigénio. Traquéia fechou. Perigo: apneia."},
		{k: "description", t: "Sintomas: ofegante ruído respiratório, tosse constante, falta de ar, descoloração da pele."},
		{k: "image", i: "aid066"},
		{k: "step", p: [{t: "Ação imediata! Deixa a pessoa aflita com tosse muito forte."}]},
		{k: "step", p: [{t: "Bata firmemente com uma mão nas costas plana entre as escápulas."}]},
		{k: "image", i: "aid068"},
		{k: "image", i: "aid031"},
		{k: "step", p: [{t: "Se sem sucesso: Fique atrás da vitima, braços em volta da cintura, curvar ligeiramente para frente."}]},
		{k: "step", p: [{t: "Firmar o seu punho, posição que tinha à altura do estômago da pessoa, e levá-la com a outra mão."}]},
		{k: "image", i: "aid069"},
		{k: "step", p: [{t: "Ao abraçar usar as duas mãos para dar um duro golpe para cima em direção O estômago (seria como tentar levantar a pessoa)."}]},
		{k: "step", p: [{t: "Repita até 5-vezes! Vias respiratórias devem ficar isentas do objeto."}]},
		{k: "step", p: [{t: "Chamada de emergência."}]},
		{k: "step", p: [{t: "Se os primeiros socorros não for bem-sucedido, continue à fazê-lo até que chegue a emergência."}]}
	],
	aid_sunburn: [
		{k: "title", t: "Queimadura solar"},
		{k: "step", p: [{t: "Retire a pessoa afectada a partir de luz solar direta. Evitar maiores exposições."}]},
		{k: "step", p: [{t: "Beba muita água para reparar a desidratação."}]},
		{k: "step", p: [{t: "Se existir uma grave queimadura solar (bolhas, vermelhidão, dor), procurar um médico."}]},
		{k: "step", p: [{t: "Se a pele tiver um leve vermelho, ela pode ser arrefecida com toalha molhada. Usar gel ou loção após o a exposição."}]}
	],
	aid_sunstroke: [
		{k: "title", t: "Insolação"},
		{k: "description", t: "Cabeça quente vermelho, pele fria, de doença, de cabeça, tontura. Causa: irritação da membrana cerebral."},
		{k: "image", i: "aid035"},
		{k: "step", p: [{t: "Vá para um lugar frio (sombra) e colocar a parte superior do corpo da pessoa para cima."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Esfriar a cabeça com cobertores molhados."}]},
		{k: "step", p: [{t: "Chame a emergência, mantenha o controle da respiração."}]},
		{k: "step", p: [{t: "Se consciente: Ministre bebida fresca, se aplicável."}]},
		{k: "step", p: [{t: "Se aparecer apneia, inicie a respiração:"}]},
		{k: "step", p: [{t: "Vá em frente dê-lhe respiração!", h: "#aid_apnoea"}]},
		{k: "image", i: "aid036"}
	],
	aid_unconsciouswithbreath: [
		{k: "title", t: "Inconsciência com respiração"},
		{k: "description", t: "Nenhuma reação em voz alta a perguntas, sem resposta sobre agitação. Existe apenas respiração."},
		{k: "image", i: "aid057"},
		{k: "step", p: [{t: "Se há pessoas próximas a você peça ajuda."}]},
		{k: "step", p: [{t: "Posição de recuperação", h: "#aid_recoveryposition"}, {t: ". Boca aberta de maneira que o vômito possa escorrer."}]},
		{k: "image", i: "aid008"},
		{k: "image", i: "aid009"},
		{k: "step", p: [{t: "Chame a emergência."}]}
	],
	aid_unconsciouswithoutbreath: [
		{k: "title", t: "Inconsciência sem respirar"},
		{k: "step", p: [{t: "Nenhuma reação da vítima, sem respirar."}]},
		{k: "image", i: "aid057"},
		{k: "step", p: [{t: "Inicie "}, {t: "Reanimação.", h: "#aid_resuscitation"}]}
	],
	aid_vomiting: [
		{k: "title", t: "Vômito"},
		{k: "description", t: "Surge a partir de náuseas. Estômago esvazia por si mesmo. Causas: Infecção, intoxicação, úlcera, drogas, comida ruim, ou gravidez."},
		{k: "image", i: "aid054"},
		{k: "step", p: [{t: "Perigo para a circulação devido à desidratação e perda de sal!"}]},
		{k: "step", p: [{t: "Dê líquidos (chá, água)."}]},
		{k: "step", p: [{t: "Se houver fortes perturbações, com sangue ou vômitos contínuos chame a emergência médica."}]}
	]
};
var langContinents=[
	{i: "Africa", t: "África"},
	{i: "Northamerica", t: "América do Norte/Central"},
	{i: "Southamerica", t: "América do Sul"},
	{i: "Asia", t: "Ásia"},
	{i: "Europe", t: "Europa"},
	{i: "Oceania", t: "Oceania"}
];
var langCountries=[
	{i: "bosniaandherzegovina", t: "A Bósnia e Herzegovina"},
	{i: "croatia", t: "A Croácia"},
	{i: "afghanistan", t: "Afeganistão"},
	{i: "southafrica", t: "África do Sul"},
	{i: "albania", t: "Albânia"},
	{i: "germany", t: "Alemanha"},
	{i: "andorra", t: "Andorra"},
	{i: "angola", t: "Angola"},
	{i: "antiguaandbarbuda", t: "Antígua e Barbuda"},
	{i: "saudiarabia", t: "Arábia Saudita"},
	{i: "algeria", t: "Argélia"},
	{i: "argentina", t: "Argentina"},
	{i: "armenia", t: "Armênia"},
	{i: "australia", t: "Austrália"},
	{i: "austria", t: "Áustria"},
	{i: "azerbaijan", t: "Azerbaijão"},
	{i: "bahamas", t: "Bahamas"},
	{i: "bangladesh", t: "Bangladesh"},
	{i: "barbados", t: "Barbados"},
	{i: "bahrain", t: "Barém"},
	{i: "belgium", t: "Bélgica"},
	{i: "belize", t: "Belize"},
	{i: "benin", t: "Benin"},
	{i: "belarus", t: "Bielorrússia"},
	{i: "bolivia", t: "Bolívia"},
	{i: "botswana", t: "Botsuana"},
	{i: "brazil", t: "Brasil"},
	{i: "brunei", t: "Brunei"},
	{i: "bulgaria", t: "Bulgária"},
	{i: "burkinafaso", t: "Burkina Faso"},
	{i: "burundi", t: "Burundi"},
	{i: "bhutan", t: "Butão"},
	{i: "capeverde", t: "Cabo Verde"},
	{i: "cameroon", t: "Camarões"},
	{i: "cambodia", t: "Camboja"},
	{i: "canada", t: "Canadá"},
	{i: "qatar", t: "Catar"},
	{i: "kazakhstan", t: "Cazaquistão"},
	{i: "centralafricanrepublic", t: "Central Africano República"},
	{i: "chad", t: "Chade"},
	{i: "chile", t: "Chile"},
	{i: "china", t: "China"},
	{i: "cyprus", t: "Chipre"},
	{i: "vaticancity", t: "Cidade do Vaticano"},
	{i: "singapore", t: "Cingapura"},
	{i: "colombia", t: "Colômbia"},
	{i: "comoros", t: "Comoros"},
	{i: "congorepublic", t: "Congo (República)"},
	{i: "congodemocraticrepublic", t: "Congo (República Democrática)"},
	{i: "northkorea", t: "Coréia do Norte"},
	{i: "southkorea", t: "Coréia do Sul (República da Coreia)"},
	{i: "ivorycoast", t: "Costa do Marfim"},
	{i: "costarica", t: "Costa Rica"},
	{i: "cuba", t: "Cuba"},
	{i: "kurdistan", t: "Curdistão"},
	{i: "denmark", t: "Dinamarca"},
	{i: "djibouti", t: "Djibuti"},
	{i: "dominica", t: "Dominica"},
	{i: "egypt", t: "Egito"},
	{i: "elsalvador", t: "El Salvador"},
	{i: "unitedarabemirates", t: "Emirados Árabes Unidos"},
	{i: "ecuador", t: "Equador"},
	{i: "eritrea", t: "Eritréia"},
	{i: "slovakia", t: "Eslováquia"},
	{i: "slovenia", t: "Eslovénia"},
	{i: "spain", t: "Espanha"},
	{i: "unitedstatesofamerica", t: "Estados Unidos da América"},
	{i: "estonia", t: "Estónia"},
	{i: "ethiopia", t: "Etiópia"},
	{i: "fiji", t: "Fiji"},
	{i: "philippines", t: "Filipinas"},
	{i: "finland", t: "Finlândia"},
	{i: "france", t: "França"},
	{i: "gabon", t: "Gabão"},
	{i: "gambia", t: "Gâmbia"},
	{i: "ghana", t: "Gana"},
	{i: "georgia", t: "Geórgia"},
	{i: "grenada", t: "Granada"},
	{i: "greece", t: "Grécia"},
	{i: "greenland", t: "Gronelândia"},
	{i: "guatemala", t: "Guatemala"},
	{i: "guyana", t: "Guiana"},
	{i: "guinea", t: "Guiné"},
	{i: "guinea-bissau", t: "Guiné-Bissau"},
	{i: "equatorialguinea", t: "Guiné Equatorial"},
	{i: "haiti", t: "Haiti"},
	{i: "netherlands", t: "Holanda"},
	{i: "honduras", t: "Honduras"},
	{i: "hongkong", t: "Hong Kong"},
	{i: "hungary", t: "Hungria"},
	{i: "yemen", t: "Iêmen"},
	{i: "caymanislands", t: "Ilhas Cayman"},
	{i: "marshallislands", t: "Ilhas Marshall"},
	{i: "solomonislands", t: "Ilhas Salomão"},
	{i: "india", t: "Índia"},
	{i: "indonesia", t: "Indonésia"},
	{i: "iran", t: "Irão"},
	{i: "iraq", t: "Iraque"},
	{i: "ireland", t: "Irlanda"},
	{i: "iceland", t: "Islândia"},
	{i: "israel", t: "Israel"},
	{i: "italy", t: "Itália"},
	{i: "jamaica", t: "Jamaica"},
	{i: "japan", t: "Japão"},
	{i: "jordan", t: "Jordânia"},
	{i: "kiribati", t: "Kiribati"},
	{i: "kosovo", t: "Kosovo"},
	{i: "kuwait", t: "Kuwait"},
	{i: "laos", t: "Laos"},
	{i: "lesotho", t: "Lesoto"},
	{i: "latvia", t: "Letónia"},
	{i: "lebanon", t: "Líbano"},
	{i: "liberia", t: "Libéria"},
	{i: "libya", t: "Líbia"},
	{i: "liechtenstein", t: "Liechtenstein"},
	{i: "lithuania", t: "Lituânia"},
	{i: "luxembourg", t: "Luxemburgo"},
	{i: "macau", t: "Macau"},
	{i: "macedonia", t: "Macedónia"},
	{i: "madagascar", t: "Madagascar"},
	{i: "malaysia", t: "Malásia"},
	{i: "malawi", t: "Malauí"},
	{i: "maldives", t: "Maldivas"},
	{i: "mali", t: "Mali"},
	{i: "malta", t: "Malta"},
	{i: "morocco", t: "Marrocos"},
	{i: "mauritius", t: "Maurício"},
	{i: "mauritania", t: "Mauritânia"},
	{i: "mayotte", t: "Mayotte"},
	{i: "mexico", t: "México"},
	{i: "micronesia", t: "Micronésia"},
	{i: "mozambique", t: "Moçambique"},
	{i: "moldova", t: "Moldávia"},
	{i: "monaco", t: "Mônaco"},
	{i: "mongolia", t: "Mongólia"},
	{i: "montenegro", t: "Montenegro"},
	{i: "myanmar", t: "Myanmar"},
	{i: "namibia", t: "Namíbia"},
	{i: "nauru", t: "Nauru"},
	{i: "nepal", t: "Nepal"},
	{i: "nicaragua", t: "Nicarágua"},
	{i: "niger", t: "Níger"},
	{i: "nigeria", t: "Nigéria"},
	{i: "norway", t: "Noruega"},
	{i: "newzealand", t: "Nova Zelândia"},
	{i: "oman", t: "Omã"},
	{i: "srilanka", t: "O Sri Lanka"},
	{i: "palau", t: "Palau"},
	{i: "panama", t: "Panamá"},
	{i: "papuanewguinea", t: "Papua Nova Guiné"},
	{i: "pakistan", t: "Paquistão"},
	{i: "paraguay", t: "Paraguai"},
	{i: "peru", t: "Peru"},
	{i: "poland", t: "Polônia"},
	{i: "portugal", t: "Portugal"},
	{i: "kenya", t: "Quênia"},
	{i: "kyrgyzstan", t: "Quirguistão"},
	{i: "unitedkingdom", t: "Reino Unido"},
	{i: "sahrawiarabdemocraticrepublic", t: "República Árabe Saaraui Democrática"},
	{i: "czechrepublic", t: "República Checa"},
	{i: "dominicanrepublic", t: "República Dominicana"},
	{i: "reunion", t: "Reunião"},
	{i: "romania", t: "Romênia"},
	{i: "rwanda", t: "Ruanda"},
	{i: "russia", t: "Rússia"},
	{i: "stlucia", t: "Saint Pierre e Miquelon"},
	{i: "samoa", t: "Samoa"},
	{i: "sanmarino", t: "San Marino"},
	{i: "stkittsandnevis", t: "Santa Lúcia"},
	{i: "saintpierreandmiquelon", t: "São Cristóvão e Nevis"},
	{i: "saotomeandprincipe", t: "São Tomé e Príncipe"},
	{i: "stvincentandgrenadines", t: "São Vicente e Granadinas"},
	{i: "senegal", t: "Senegal"},
	{i: "sierraleone", t: "Serra Leoa"},
	{i: "serbia", t: "Sérvia"},
	{i: "seychelles", t: "Seychelles"},
	{i: "syria", t: "Síria"},
	{i: "somalia", t: "Somália"},
	{i: "swaziland", t: "Suazilândia"},
	{i: "sudan", t: "Sudão"},
	{i: "sweden", t: "Suécia"},
	{i: "switzerland", t: "Suíça"},
	{i: "suriname", t: "Suriname"},
	{i: "thailand", t: "Tailândia"},
	{i: "taiwan", t: "Taiwan"},
	{i: "tajikistan", t: "Tajiquistão"},
	{i: "tanzania", t: "Tanzânia"},
	{i: "easttimor", t: "Timor Leste"},
	{i: "togo", t: "Togo"},
	{i: "tonga", t: "Tonga"},
	{i: "trinidadandtobago", t: "Trinidad e Tobago"},
	{i: "tunisia", t: "Tunísia"},
	{i: "turkmenistan", t: "Turquemenistão"},
	{i: "turkey", t: "Turquia"},
	{i: "tuvalu", t: "Tuvalu"},
	{i: "ukraine", t: "Ucrânia"},
	{i: "uganda", t: "Uganda"},
	{i: "uruguay", t: "Uruguai"},
	{i: "uzbekistan", t: "Uzbequistão"},
	{i: "vanuatu", t: "Vanuatu"},
	{i: "venezuela", t: "Venezuela"},
	{i: "vietnam", t: "Vietnã"},
	{i: "zambia", t: "Zâmbia"},
	{i: "zimbabwe", t: "Zimbabué"}
];
