//:Primeros Auxilios
// Generated file, do not edit
var langTexts={
	title: "Primeros Auxilios",
	back: "〈Back〉",
	continent: "〈Continent〉",
	emergency_fire: "〈Fire〉",
	emergency_medical: "〈Medical〉",
	emergency_police: "〈Police〉",
	emergency_cancelcard: "",
	emergency_local: "〈local numbers〉",
	emergency_nosystem: "〈no system〉",
	emergency_radioonly: "〈only radio telephones〉",
	emergency_none: "〈--〉",
	emergency_or: "〈or〉",
	emergency_mobile: "〈mobile〉",
	emergency_tourist: "〈tourists〉"
};
var langMenu=[
	{h: "#aid_disclaimer", t: "# Descargo de Información"},
	{h: "#numbers", t: "# Llamadas de emergencia"},
	{h: "#aid_general", t: "# General Conducta"},
	{h: "#aid_drowning", t: "Ahogamiento"},
	{h: "#aid_amputation", t: "Amputación"},
	{h: "#aid_apnoea", t: "Apnea"},
	{h: "#aid_suffocation", t: "Asfixia"},
	{h: "#aid_asthma", t: "Asma"},
	{h: "#aid_heartattack", t: "Ataque al corazón"},
	{h: "#aid_stroke", t: "Carrera"},
	{h: "#aid_brainconcussion", t: "Cerebro Concusión"},
	{h: "#aid_diabeticcoma", t: "Coma diabético"},
	{h: "#aid_checkbreathing", t: "Comprobar la respiración"},
	{h: "#aid_frostbitesevere", t: "Congelación grave"},
	{h: "#aid_frostbitemild", t: "Congelación leve"},
	{h: "#aid_safeguardaccident", t: "De accidentes de tráfico"},
	{h: "#aid_resuscitation", t: "De compresión de pecho"},
	{h: "#aid_diarrhoea", t: "Diarrea"},
	{h: "#aid_electricityaccident", t: "Electricidad de accidentes"},
	{h: "#aid_epilepsy", t: "Epilepsia"},
	{h: "#aid_sprain", t: "Esguince de la cepa"},
	{h: "#aid_asthma", t: "Falta de aliento"},
	{h: "#aid_fracture", t: "Fractura"},
	{h: "#aid_skullfracture", t: "Fractura de cráneo"},
	{h: "#aid_backinjury", t: "Fractura espinal"},
	{h: "#aid_suffocation", t: "Golondrina / Asfixia"},
	{h: "#aid_burningsevere", t: "Grabación de graves"},
	{h: "#aid_burningslight", t: "Grabación de luz"},
	{h: "#aid_bleedingsevere", t: "Hemorragia grave"},
	{h: "#aid_bleedinglight", t: "Hemorragia luz"},
	{h: "#aid_icerescue", t: "Hielo de rescate"},
	{h: "#aid_hyperthermia", t: "Hipertermia (calor corporal)"},
	{h: "#aid_unconsciouswithbreath", t: "Inconsciencia con la respiración"},
	{h: "#aid_unconsciouswithoutbreath", t: "Inconsciencia sin respirar"},
	{h: "#aid_poisining", t: "Intoxicación"},
	{h: "#aid_diabeticcoma", t: "La hiperglucemia (azúcar)"},
	{h: "#aid_hypoglycaemia", t: "La hipoglucemia (baja de azúcar)"},
	{h: "#aid_hypothermia", t: "La hipotermia (frío cuerpo)"},
	{h: "#aid_sunburn", t: "Las quemaduras de sol"},
	{h: "#aid_eyeinjury", t: "Lesión en el ojo"},
	{h: "#aid_emergencycall", t: "Llamada de emergencia"},
	{h: "#aid_animalbite", t: "Mordedura de animal"},
	{h: "#aid_birth", t: "Nacimiento"},
	{h: "#aid_nosebleeding", t: "Nosebleeding"},
	{h: "#aid_insectstings", t: "Picaduras de insectos"},
	{h: "#aid_recoveryposition", t: "Posición de recuperación"},
	{h: "#aid_chemicalburn", t: "Quemaduras químicas"},
	{h: "#aid_chemicalburneyes", t: "Quemaduras químicas (Ojos)"},
	{h: "#aid_allergic", t: "Reacción alérgica"},
	{h: "#aid_resuscitation", t: "Reanimación"},
	{h: "#aid_apnoea", t: "Respirar"},
	{h: "#aid_resuscitation", t: "Resucitación"},
	{h: "#aid_safeguardaccident", t: "Salvaguardia de accidentes"},
	{h: "#aid_shock", t: "Shock"},
	{h: "#aid_snakebite", t: "Snakebite"},
	{h: "#aid_sos", t: "SOS"},
	{h: "#aid_sunstroke", t: "Sunstroke"},
	{h: "#aid_backinjury", t: "Volver lesiones"},
	{h: "#aid_vomiting", t: "Vómitos"},
	{h: "#aid_dangerzone", t: "Zona de Peligro"},
	{h: "tel:112", t: "〈Call Emergency 112〉"}
];
var langSections={
	aid_disclaimer: [
		{k: "title", t: "Descargo de Información"},
		{k: "subsection", t: "Software"},
		{k: "description", t: "Primeros auxilios en el teléfono móvil"},
		{k: "description", t: "Copyright: Kai Kajus Noack"},
		{k: "description", t: "〈Translators: …〉"},
		{k: "description", t: "Licencia: Creative Commons"},
		{k: "image", i: "cc88x31"},
		{k: "description", t: "Este programa se supone que debe dar información sobre primeros auxilios. Sin embargo, no representa un sustituto de un curso de primeros auxilios. Es más bien refrescante que sirve a su conocimiento ya adquirido."},
		{k: "description", t: "〈Illustrations〉 © Med4Teens"},
		{k: "subsection", t: "Cláusula de exención de responsabilidad"},
		{k: "description", t: "Tenga en cuenta que no tienen la responsabilidad de las consecuencias derivadas del uso del software."},
		{k: "description", t: "Cualquier responsabilidad queda excluido!"},
		{k: "description", t: "Utilizar a su propio riesgo!"},
		{k: "description", t: "En todas las situaciones de emergencia, por favor busque ayuda profesional inmediatamente."},
		{k: "subsection", t: "Para salvar una vida es haber salvado el mundo."}
	],
	aid_general: [
		{k: "title", t: "General Conducta"},
		{k: "step", p: [{t: "Siempre realizar los primeros auxilios. Usted no puede hacer todos los errores."}]},
		{k: "step", p: [{t: "Siempre prestar atención a su propia seguridad."}]},
		{k: "step", p: [{t: "Examinar la situación y asegurar el lugar del accidente."}]},
		{k: "step", p: [{t: "Primera llamada de emergencia las medidas de ayuda!"}]},
		{k: "step", p: [{t: "Si hay varias bajas, el tratamiento de los más perjudicados tiene prioridad."}]},
		{k: "step", p: [{t: "Siempre trate de calmar a la persona en cuestión. Mantenga la calma usted mismo!"}]},
		{k: "step", p: [{t: "Si es posible establecer él / ella cómodamente. Nunca le dé alcohol, nicotina o drogas a una persona."}]}
	],
	aid_allergic: [
		{k: "title", t: "Reacción alérgica", i: "aid046"},
		{k: "step", p: [{t: "Teléfono para una ambulancia de inmediato."}]},
		{k: "step", p: [{t: "Trate de calmar la víctima y le permitirá sentarse cómodo."}]},
		{k: "step", p: [{t: "Eliminar alérgicas causando cuestión (por ejemplo, un palo de la abeja) cuidadosamente."}]},
		{k: "step", p: [{t: "Enfriar la piel afectada (compresa húmeda, el hielo)."}]},
		{k: "image", i: "aid046ice"},
		{k: "step", p: [{t: "En caso de siniestro tiene un antídoto, debe usarlo (le ayuda)."}]},
		{k: "step", p: [{t: "Monitor de condición de víctimas hasta que llegue ambulancia."}]},
		{k: "step", p: [{t: "En caso de siniestro o pierde la conciencia de respiración se detiene, siga las instrucciones!"}]},
		{k: "image", i: "aid077"}
	],
	aid_amputation: [
		{k: "title", t: "Amputación"},
		{k: "description", t: "Amputarle parte del cuerpo puede ser reattached nuevo. Objetivo: Mantener amputarle parte enfriar hasta que llegue a un hospital."},
		{k: "step", p: [{t: "La calma a la persona, sentar él hacia abajo, y cubierta con una manta."}]},
		{k: "step", p: [{t: "Detener la hemorragia, consulte 'Sangrado (grave)' y 'Shock'."}]},
		{k: "step", p: [{t: "Envuelva la parte amputada en un paño limpio y seco, y ponerlo en una bolsa de plástico impermeable."}]},
		{k: "step", p: [{t: "Cerrar esta bolsa de plástico y ponerla en otra bolsa de plástico, que contiene agua fría y hielo."}]},
		{k: "step", p: [{t: "No le dé alcohol, cigarrillos o comida a un siniestro (en el caso de una cirugía con anestesia en el hospital)."}]},
		{k: "step", p: [{t: "No congelar la amputación parcial (sólo le mantenga fresco)."}]},
		{k: "step", p: [{t: "Llamada de emergencia o unidad de urgencias al hospital mismo."}]}
	],
	aid_animalbite: [
		{k: "title", t: "Mordedura de animal", i: "aid047"},
		{k: "description", t: "Atención: Alto riesgo de infección. Resultado podría ser pus, el tétanos, la rabia."},
		{k: "step", p: [{t: "Lave la herida con jabón agua caliente."}]},
		{k: "image", i: "aid049"},
		{k: "step", p: [{t: "Después de utilizar la desinfección de heridas."}]},
		{k: "step", p: [{t: "Si hay hemorragia grave, elevar a la persona de la parte superior del cuerpo."}]},
		{k: "step", p: [{t: "Aplicar un vendaje aséptico."}]},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Ir a un hospital de emergencia o llame al médico."}]}
	],
	aid_apnoea: [
		{k: "title", t: "Apnea"},
		{k: "description", t: "No respirar los sonidos o movimientos de la respiración, notable decoloración de la piel."},
		{k: "step", p: [{t: "Llamada de emergencia."}]},
		{k: "step", p: [{t: "Laicos siniestro en la espalda."}]},
		{k: "step", p: [{t: "Estirar la cabeza en el cuello. Eliminar las sustancias de la boca y la garganta."}]},
		{k: "image", i: "aid067"},
		{k: "step", p: [{t: "Push ala de la nariz juntos, de modo que la nariz está cerrado."}]},
		{k: "image", i: "aid010"},
		{k: "step", p: [{t: "Respira hondo y ponga su boca sobre la boca de la víctima, que no puede fugas de aire."}]},
		{k: "image", i: "aid011"},
		{k: "step", p: [{t: "Aliento a cabo lentamente y totalmente."}]},
		{k: "step", p: [{t: "Si, sin éxito: hacer la respiración mientras llega una ambulancia."}]}
	],
	aid_asthma: [
		{k: "title", t: "Asma"},
		{k: "description", t: "Falta de aliento pesado. Sibilancias respiratorias ruido. Ansiedades."},
		{k: "step", p: [{t: "Calma la persona. Mantenga la calma usted mismo!"}]},
		{k: "step", p: [{t: "Afloje las prendas de vestir."}]},
		{k: "step", p: [{t: "Que siniestro sentarse y apoyarse hacia adelante, pedir a respirar lenta y profundamente."}]},
		{k: "step", p: [{t: "Si tiene un siniestro inhalatoria, debe usarlo (le ayuda). Después de 5-10 min debería tener efecto."}]},
		{k: "image", i: "aid074"},
		{k: "step", p: [{t: "Si no hay mejora: Utilice inhalatoria cada 5 min hasta que llegue ambulancia."}]},
		{k: "step", p: [{t: "Llamada de emergencia."}]},
		{k: "step", p: [{t: "Si aparece apnea, comience con la respiración."}, {t: "〈+〉", h: "#aid_apnoea"}]}
	],
	aid_backinjury: [
		{k: "title", t: "Volver lesiones"},
		{k: "description", t: "Dolor en la parte posterior, entumecido los brazos y las piernas."},
		{k: "step", p: [{t: "No mueva a la víctima!"}]},
		{k: "image", i: "aid064"},
		{k: "step", p: [{t: "Mantenga la cabeza la forma en que la persona se encuentra estable (mantener la cabeza inmóvil)"}]},
		{k: "image", i: "aid065"},
		{k: "step", p: [{t: "Estabilizar el siniestro con potencia en el lateral."}]},
		{k: "step", p: [{t: "Calma la persona."}]},
		{k: "step", p: [{t: "Llamada de emergencia, señalar las lesiones en la espalda."}]}
	],
	aid_birth: [
		{k: "title", t: "Nacimiento"},
		{k: "description", t: "Salida de líquido amniótico. Contracción se producen dolores. Inesperado nacimiento."},
		{k: "image", i: "aid025"},
		{k: "step", p: [{t: "Preste atención a la vida privada y mantener la calma! - Llamada de emergencia."}]},
		{k: "step", p: [{t: "Que la mujer embarazada al desnudo la parte inferior de su cuerpo, y sentarse en una estéril con la base de propagación piernas."}]},
		{k: "step", p: [{t: "Ángulo de las rodillas. Tire hacia arriba las piernas. Posición de la cuenca ligeramente al alza. - El nacimiento es un proceso natural y ejecuta la mayoría sin complicaciones."}]},
		{k: "step", p: [{t: "Calma la mujer, la dejó concentrarse en su respiración: Inhale a través de la nariz, exhale por la boca (en velocidad normal)."}]},
		{k: "step", p: [{t: "Ritmo de la apremiante: Tome una respiración profunda, aguante la respiración, y la prensa. Tan pronto como la cabeza del bebé aparece, por el acaparamiento de apoyo con las dos manos."}]},
		{k: "image", i: "aid021"},
		{k: "image", i: "aid022"},
		{k: "step", p: [{t: "Después del parto: Sostenga el bebé slantly con la cabeza hacia abajo para liberar las vías respiratorias de líquido amniótico. (Tal vez usted debe aspirar el líquido fuera de la nariz del bebé por la boca.) El bebé debe respirar y llorar!"}]},
		{k: "step", p: [{t: "Enlazar fuera del cordón umbilical de 30 cm de distancia del niño (también puede hacerse en el hospital). Portada de la vagina de la madre estéril."}]},
		{k: "image", i: "aid023"},
		{k: "step", p: [{t: "Secar el bebé y mantenerlo caliente. Tenga en cuenta el tiempo y conducir al hospital."}]}
	],
	aid_bleedinglight: [
		{k: "title", t: "Hemorragia luz", i: "aid082"},
		{k: "description", t: "Objetivo: detener la hemorragia."},
		{k: "step", p: [{t: "No toque la herida (peligro de infección)."}]},
		{k: "step", p: [{t: "No tratar la herida con polvo, sprays o salves."}]},
		{k: "step", p: [{t: "Tratamiento de la herida con material estéril y un vendaje."}]},
		{k: "image", i: "aid098"},
		{k: "step", p: [{t: "Por un poco de yeso sangrado es a menudo suficiente."}]},
		{k: "step", p: [{t: "Si la herida es en gran escala el uso cubrir una herida y un vendaje. No se aplican a vendaje apretado, como un estancamiento puede conducir a un aumento en el sangrado."}]},
		{k: "image", i: "aid084"},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Nota: Las heridas de la rabia han de ser lavados con solución de jabón."}]},
		{k: "image", i: "aid049"}
	],
	aid_bleedingsevere: [
		{k: "title", t: "Hemorragia grave"},
		{k: "description", t: "Salpicaduras, la sangre palpitante. Peligro: Choke debido a la pérdida de sangre, las infecciones, la muerte. Objetivo: detener la hemorragia."},
		{k: "step", p: [{t: "Quitar la ropa (corte si es necesario) y ponen de manifiesto la herida."}]},
		{k: "step", p: [{t: "Envuelva un vendaje si es necesario o una prenda de vestir con la presión alrededor de la herida."}]},
		{k: "image", i: "aid086"},
		{k: "step", p: [{t: "Ejercer presión en favor de al menos 10 min."}]},
		{k: "step", p: [{t: "Si es vendaje empapado de sangre, no quitarla. En lugar de recapitulación otro vendaje / prendas de vestir a su alrededor."}]},
		{k: "step", p: [{t: "Almacén de la extremidad afectada (si no está roto) superior a la del corazón para reducir la cantidad de la presión arterial. Si es posible establecer un siniestro."}]},
		{k: "step", p: [{t: "Si la hemorragia no se detiene, mantener la presión sobre la herida, y establecer, además, punto de presión sobre la herida: Para una hemorragia del antebrazo comprimir la parte superior del brazo (vena de prensa en cara interna de brazo, en medio de codo y brazo a cielo, a través de su dedos). Para sangrado de la pierna establecidos punto de presión en la ingle (vena de prensa en las malas de la ingle, la arteria que lleva más de la pelvis ósea, utilizando su bola de la mano)."}]},
		{k: "image", i: "aid089"},
		{k: "image", i: "aid092"},
		{k: "step", p: [{t: "Llame al médico de urgencias de inmediato."}]},
		{k: "step", p: [{t: "Tan pronto como la hemorragia está bajo control: Iniciar las medidas de ahogo."}]},
		{k: "image", i: "aid093"}
	],
	aid_brainconcussion: [
		{k: "title", t: "Cerebro Concusión"},
		{k: "description", t: "Dolor de cabeza, náuseas, vómitos. Problemas de visión. Puede producirse la inconsciencia."},
		{k: "image", i: "aid035a"},
		{k: "step", p: [{t: "Establecen persona de que se trate."}]},
		{k: "step", p: [{t: "Llamada de emergencia."}]},
		{k: "description", t: "Si el sangrado en la cabeza:"},
		{k: "step", p: [{t: "Establecer un siniestro, la posición de la cabeza elevada (sobre almohadas)."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Do herida-tratamiento (uso de la cabeza del vendaje)."}]},
		{k: "step", p: [{t: "Llamada de emergencia."}]}
	],
	aid_burningslight: [
		{k: "title", t: "Grabación de luz"},
		{k: "description", t: "Enrojecimiento de la piel. Hinchazones leves. Dolor."},
		{k: "step", p: [{t: "Mantenga la zona en cuestión en virtud de agua fría."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Aplicar vendaje ligeramente húmedo."}]}
	],
	aid_burningsevere: [
		{k: "title", t: "Grabación de graves"},
		{k: "description", t: "Manchada de blanco y rojo las zonas, ampollas. La piel pierde líquido. Profundo daño de los tejidos. Fuerte dolor o sin dolor (a causa de los nervios quemados)."},
		{k: "image", i: "aid097"},
		{k: "step", p: [{t: "Quitar la ropa tanto como sea posible."}]},
		{k: "step", p: [{t: "Enfriar quemaron partes del cuerpo con el agua (alrededor de 15 ° C, 59 ° F) hasta 10 minutos, hasta que el dolor disminuye."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Si la quema es amplia, sólo tiene que utilizar trapos húmedos para que se enfríen."}]},
		{k: "step", p: [{t: "Llamada de emergencia."}]},
		{k: "step", p: [{t: "Después de enfriar hacer el tratamiento de la herida: Utilice un apósito estéril. No aplique líquidos (sin cremas, aceites, ungüentos, etc.) No perforar las vesículas."}]},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Control de la respiración y la conciencia de la persona hasta que llega médico de emergencia."}]}
	],
	aid_checkbreathing: [
		{k: "title", t: "Comprobar la respiración"},
		{k: "step", p: [{t: "Compruebe la respiración sonidos."}]},
		{k: "step", p: [{t: "Diagnosticar la respiración en la parte superior del abdomen (poner la mano sobre él)."}]},
		{k: "image", i: "aid027"},
		{k: "step", p: [{t: "Sentido de respiración en la nariz y la boca."}]}
	],
	aid_chemicalburneyes: [
		{k: "title", t: "Quemaduras químicas (Ojos)"},
		{k: "step", p: [{t: "Llamada de emergencia, señalan los productos químicos."}]},
		{k: "step", p: [{t: "Enjuague los ojos con mucha agua. Portada ojo sano durante el lavado."}]},
		{k: "step", p: [{t: "Llevar a la chorro de agua de ángulo interior del ojo al ángulo exterior del ojo. Limpieza de al menos 20 minutos bajo el agua clara."}]},
		{k: "image", i: "aid019"},
		{k: "step", p: [{t: "Cierre ambos ojos de la víctima y se unen con paño húmedo."}]},
		{k: "image", i: "aid020"},
		{k: "step", p: [{t: "Monitor de estado hasta que llegue ambulancia."}]}
	],
	aid_chemicalburn: [
		{k: "title", t: "Quemaduras químicas"},
		{k: "description", t: "Lesiones de los tejidos."},
		{k: "image", i: "aid095"},
		{k: "step", p: [{t: "Mente auto-protección!"}]},
		{k: "step", p: [{t: "Actuar con rapidez y de lavado de los lugares quemados."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Llamada de emergencia."}]},
		{k: "step", p: [{t: "Si hay una quemadura química de la digestión formas beber mucha agua."}]},
		{k: "step", p: [{t: "No causa vómitos!"}]}
	],
	aid_dangerzone: [
		{k: "title", t: "Zona de Peligro"},
		{k: "step", p: [{t: "Grip ejecución: Posición del brazo de un herido en la frente de su pecho, y llegar detrás de él / ella."}]},
		{k: "step", p: [{t: "Ponga sus manos bajo los hombros de los heridos, el acaparamiento de la ángulo del brazo."}]},
		{k: "step", p: [{t: "Retirar y llevar a la persona en la seguridad."}]},
		{k: "image", i: "aid001"},
		{k: "image", i: "aid007"}
	],
	aid_diabeticcoma: [
		{k: "title", t: "Coma diabético"},
		{k: "description", t: "Nivel de azúcar en la sangre es demasiado alto (o la falta de insulina)."},
		{k: "description", t: "Síntomas: sed, micción frecuente, náuseas, vómito. Aliento huele a frutas y vino."},
		{k: "step", p: [{t: "Llame a emergencia."}]},
		{k: "step", p: [{t: "Apoyo siniestro (si se garantiza la diabetes) el tratamiento con insulina."}]},
		{k: "image", i: "aid016"},
		{k: "step", p: [{t: "Recuperación de posición. (No hay más posibilidades de ayudar a la primera.)"}, {t: "〈+〉", h: "#aid_recoveryposition"}]},
		{k: "step", p: [{t: "Monitorear el estado de la víctima hasta el médico de urgencias llega."}]}
	],
	aid_diarrhoea: [
		{k: "title", t: "Diarrea"},
		{k: "description", t: "Sickliness de los alimentos, la infección del intestino o el desorden. Las heces se diluye, o baboso sangriento."},
		{k: "step", p: [{t: "Peligro para la circulación a causa de la deshidratación y la pérdida de sal!"}]},
		{k: "step", p: [{t: "Dar líquidos (té, agua)."}]},
		{k: "step", p: [{t: "Si existen fuertes trastornos llamar al médico de urgencias."}]}
	],
	aid_drowning: [
		{k: "title", t: "Ahogamiento"},
		{k: "step", p: [{t: "Llame a emergencia. Pregúntele a la gente a tu lado para ayudar."}]},
		{k: "image", i: "aid032"},
		{k: "step", p: [{t: "Rescate persona fuera del agua!"}]},
		{k: "image", i: "aid033"},
		{k: "image", i: "aid034"},
		{k: "step", p: [{t: "Si la respiración es siniestro: la posición de recuperación. Mantenga le caliente (cubrir). Monitor de estado de emergencia hasta el médico llega."}, {t: "〈+〉", h: "#aid_recoveryposition"}]},
		{k: "step", p: [{t: "En caso de siniestro no está respirando: iniciar inmediatamente con la reanimación! (Emitir de agua de los pulmones es inútil.)"}, {t: "〈+〉", h: "#aid_resuscitation"}]}
	],
	aid_electricityaccident: [
		{k: "title", t: "Electricidad de accidentes"},
		{k: "step", p: [{t: "En primer lugar interrumpir el suministro de electricidad!"}]},
		{k: "image", i: "aid045plug"},
		{k: "image", i: "aid045"},
		{k: "step", p: [{t: "Peligro: inconsciencia, apnea."}]},
		{k: "step", p: [{t: "A - inconsciencia con la respiración", h: "#aid_unconsciouswithbreath"}]},
		{k: "step", p: [{t: "B - inconsciencia, sin respiración", h: "#aid_unconsciouswithoutbreath"}]},
		{k: "image", i: "aid042"},
		{k: "image", i: "aid043"}
	],
	aid_emergencycall: [
		{k: "title", t: "Llamada de emergencia"},
		{k: "step", p: [{t: "Marque el 112 con el siguiente teléfono disponible (EE.UU.: 911). Siempre es posible y gratis! No dude en llamar a una ambulancia! "}]},
		{k: "step", p: [{t: "En el teléfono, debe proporcionar la siguiente información:"}]},
		{k: "step", p: [{t: "- ¿Qué ha ocurrido"}]},
		{k: "step", p: [{t: "- ¿Dónde (lugar de accidente)"}]},
		{k: "step", p: [{t: "- ¿Cuántas bajas"}]},
		{k: "step", p: [{t: "- ¿Qué tipo de lesiones"}]},
		{k: "step", p: [{t: "Después de esperar a nuevas investigaciones."}]}
	],
	aid_epilepsy: [
		{k: "title", t: "Epilepsia"},
		{k: "description", t: "Cuerpo rígido, clenched puños, presiona la mandíbula, Espasmos en las extremidades o la cara. Rolling ojos. Salivación. Inconsciencia posible."},
		{k: "image", i: "aid058"},
		{k: "step", p: [{t: "No se acerque el siniestro o limitar sus movimientos."}]},
		{k: "step", p: [{t: "Coloque la víctima sobre una base blanda (colchón), eliminar los objetos cercanos a impedir la libre de lesiones."}]},
		{k: "step", p: [{t: "Calma el siniestro. Afloje las prendas de vestir, el establecimiento de la libre respiración."}]},
		{k: "step", p: [{t: "Si víctima vomita, gire la cabeza hacia el lado que puede vomitar desagüe."}]},
		{k: "step", p: [{t: "Mantenga las vías respiratorias claras. Peligro de tragar la lengua."}]},
		{k: "step", p: [{t: "Posición de recuperación de llamada de emergencia. Continuar el seguimiento de la víctima de la enfermedad."}, {t: "〈+〉", h: "#aid_recoveryposition"}]},
		{k: "step", p: [{t: "Mantenga a otras personas a distancia."}]}
	],
	aid_eyeinjury: [
		{k: "title", t: "Lesión en el ojo"},
		{k: "step", p: [{t: "Dejar objetos en el ojo del siniestro, no quitarla."}]},
		{k: "step", p: [{t: "Mantenga los ojos inmóviles para evitar nuevas lesiones. No toque el ojo."}]},
		{k: "step", p: [{t: "Si los ojos es la hemorragia, y cúbralo con una compresa o una gasa estéril."}]},
		{k: "image", i: "aid020"},
		{k: "step", p: [{t: "Enfriar el ojo con una almohadilla fría (reduce la hinchazón, el sangrado se detiene más rápido)."}]},
		{k: "step", p: [{t: "Llamada de emergencia o en coche al hospital por ti mismo."}]}
	],
	aid_fracture: [
		{k: "title", t: "Fractura"},
		{k: "description", t: "Síntomas: Antinatural posición y la movilidad de los huesos. Deformación. El movimiento penoso, táctil."},
		{k: "image", i: "aid104"},
		{k: "step", p: [{t: "Evite los movimientos!"}]},
		{k: "step", p: [{t: "Llamada de emergencia."}]},
		{k: "step", p: [{t: "Inmovilizar la fractura ósea, es decir, fortalecer el hueso alrededor de material herméticamente. Mantenga la posición de los huesos."}]},
		{k: "image", i: "aid107"},
		{k: "step", p: [{t: "Si la fractura es abierta, cubrir la herida estéril."}]},
		{k: "image", i: "aid106"}
	],
	aid_frostbitemild: [
		{k: "title", t: "Congelación leve"},
		{k: "description", t: "Palidez, hinchazones. Peligro para el suministro de sangre."},
		{k: "step", p: [{t: "Traiga un siniestro en una zona cálida."}]},
		{k: "step", p: [{t: "¡Aléjate de frío, quite la ropa de frío, sequedad de la persona."}]},
		{k: "step", p: [{t: "Calentamiento con agua tibia y con el calor del cuerpo de la ayudante."}]},
		{k: "step", p: [{t: "Dar bebida caliente (té). No alcohol!"}]},
		{k: "image", i: "aid040"}
	],
	aid_frostbitesevere: [
		{k: "title", t: "Congelación grave"},
		{k: "description", t: "Piel fría, dura, gris-blanco, ampollas, el tejido muere. Peligro para el suministro de sangre!"},
		{k: "image", i: "aid096"},
		{k: "step", p: [{t: "Ir a la zona caliente."}]},
		{k: "step", p: [{t: "Tratamiento de heridas / que cubre."}]},
		{k: "step", p: [{t: "Dar una bebida azucarada."}]},
		{k: "step", p: [{t: "No frote la víctima caliente!"}]},
		{k: "step", p: [{t: "Llamada de emergencia."}]}
	],
	aid_heartattack: [
		{k: "title", t: "Ataque al corazón"},
		{k: "description", t: "Pesados, más de 5 min duradera la presión y el dolor en el pecho, en particular, radiante en los brazos / hombros. Ansiedad, palidez, sudor frío. Posiblemente, náuseas, falta de aliento."},
		{k: "image", i: "aid076"},
		{k: "image", i: "aid083"},
		{k: "step", p: [{t: "Llamada de emergencia! Señale el supuesto ataque al corazón."}]},
		{k: "step", p: [{t: "Coloque la parte superior del cuerpo elevada. Aflojar las ropas apretadas. No le dé bebidas o drogas."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Calmingly hablar a la persona en cuestión."}]},
		{k: "step", p: [{t: "Control de la conciencia y la respiración."}]},
		{k: "step", p: [{t: "Dar aspirina si está disponible."}]},
		{k: "step", p: [{t: "Si la persona es inconsciente comenzar con la reanimación."}, {t: "〈+〉", h: "#aid_resuscitation"}]}
	],
	aid_hypoglycaemia: [
		{k: "title", t: "La hipoglucemia (baja de azúcar)"},
		{k: "description", t: "Nivel de azúcar en la sangre está por debajo de valor mínimo (a causa de sobredosis de insulina suficiente o no la ingesta de alimentos)."},
		{k: "description", t: "Síntomas: Palidez, nerviosismo, el hambre, escalofríos, sudor."},
		{k: "image", i: "aid018"},
		{k: "step", p: [{t: "Asegúrese de que la persona es una persona diabética (buscar una insignia diabéticos)."}]},
		{k: "step", p: [{t: "Llamada de emergencia."}]},
		{k: "step", p: [{t: "Dar una bebida con azúcar y la dextrosa / glucosa (si no hay problemas en la deglución)."}]},
		{k: "image", i: "aid017"},
		{k: "step", p: [{t: "Si la persona está consciente y respira: posición de recuperación. Monitor de la respiración de la persona. Si aparece apnea, comience con respiración dar."}, {t: "〈+〉", h: "#aid_recoveryposition"}]},
		{k: "step", p: [{t: "Si hay respiración, usted puede poner un trozo de azúcar en la mejilla la valija diplomática, el impulso desde el exterior en contra de ella."}]}
	],
	aid_hyperthermia: [
		{k: "title", t: "Hipertermia (calor corporal)"},
		{k: "description", t: "Sed, debilidad, desorientación, náuseas, confusión, sudoración fuerte, piel caliente."},
		{k: "image", i: "aid035"},
		{k: "step", p: [{t: "Llamada de emergencia."}]},
		{k: "step", p: [{t: "Buscar un lugar sombrío fresco (habitación con aire acondicionado preferible)."}]},
		{k: "step", p: [{t: "Fijar en la persona, elevar las piernas. Afloje las prendas de vestir."}]},
		{k: "image", i: "aid078"},
		{k: "step", p: [{t: "Enfriar la piel con mucha agua o sentar en frío toallas."}]},
		{k: "step", p: [{t: "Dar mucha agua o jugos para beber."}]}
	],
	aid_hypothermia: [
		{k: "title", t: "La hipotermia (frío cuerpo)"},
		{k: "description", t: "Tiritar de frío, somnolencia, agotamiento, hasta la inconsciencia. Cole piel pálida. Pulso lento, débil latido del corazón."},
		{k: "image", i: "aid014"},
		{k: "step", p: [{t: "Ir a una zona caliente / habitación."}]},
		{k: "step", p: [{t: "Llame a emergencia."}]},
		{k: "step", p: [{t: "Detener el impacto de frío. Aumentar la temperatura corporal (tapa y cuerpo a cuerpo-contacto)."}]},
		{k: "step", p: [{t: "Quitar la ropa húmeda y poner en ropa de abrigo. Ponga en las cubiertas. Cubra la cabeza."}]},
		{k: "step", p: [{t: "Dar té caliente, sopa o agua caliente para beber. No alcohol! Mantenga persona despierta."}]},
		{k: "image", i: "aid039"},
		{k: "image", i: "aid040"},
		{k: "step", p: [{t: "Monitor de condición de víctimas hasta el médico de urgencias llega. Si la persona es inconsciente, iniciar la reanimación:"}]},
		{k: "step", p: [{t: "A - inconsciencia con la respiración", h: "#aid_unconsciouswithbreath"}]},
		{k: "step", p: [{t: "B - inconsciencia, sin respiración", h: "#aid_unconsciouswithoutbreath"}]}
	],
	aid_icerescue: [
		{k: "title", t: "Hielo de rescate"},
		{k: "description", t: "Preste atención a su propia seguridad. Peligro: ahogamiento, hipotermia."},
		{k: "step", p: [{t: "Rescate a través de escalera, bordo o bar. Peso debe ser distribuido generalizada."}]},
		{k: "step", p: [{t: "Pregunte a otras personas en busca de ayuda. Que llame a una ambulancia de emergencia."}]},
		{k: "step", p: [{t: "Rastrear cuidadosamente en su vientre (si es posible cordada) junto con la herramienta a la violación."}]},
		{k: "image", i: "aid041"},
		{k: "step", p: [{t: "Parte, la víctima de la distancia de la herramienta (no la mano!) Y tire de él."}]},
		{k: "step", p: [{t: "Rastrear hacia atrás de nuevo al borde."}]},
		{k: "step", p: [{t: "Primeros auxilios."}]},
		{k: "step", p: [{t: "Auto-rescate posible: Si el hielo es sólido puede distribuir su peso sobre el hielo y tire de ti. Rastrear plana en su vientre al borde. Si el hielo es frágil, tratar de romper el hielo pieza por pieza hasta el borde."}]}
	],
	aid_insectstings: [
		{k: "title", t: "Picaduras de insectos", i: "aid046"},
		{k: "description", t: "Hinchazón, erupción de la piel, sensación de ardor, debilidad, dificultad para respirar, disminución de conciencia, taquicardia."},
		{k: "step", p: [{t: "Stringer quitar con cuidado (con una pinza). No apriete el aguijón, ya que esto podría inyectar más veneno."}]},
		{k: "step", p: [{t: "Enfriar en cuestión in situ (aplicar una compresa fría)."}]},
		{k: "step", p: [{t: "Preocupada por la zona debería mantenerse inferior al corazón para disminuir la circulación del veneno."}]},
		{k: "step", p: [{t: "Si puntada en la boca-mandíbula-zona: Chupe de helados, y aplicar una compresa fría en torno a la garganta."}]},
		{k: "image", i: "aid046ice"},
		{k: "step", p: [{t: "Si se producen graves problemas llame a una ambulancia."}]}
	],
	aid_nosebleeding: [
		{k: "title", t: "Nosebleeding"},
		{k: "description", t: "Bursted arteria pequeña en la punta de la nariz."},
		{k: "step", p: [{t: "Siéntate sangrado persona, ajustada ligeramente hacia adelante. Mantenga la cabeza recta."}]},
		{k: "step", p: [{t: "No posición de la persona plana, como la cabeza más de altura del corazón disminuye la hemorragia."}]},
		{k: "step", p: [{t: "Fría sobre el cuello."}]},
		{k: "step", p: [{t: "Apretar las fosas nasales juntos hasta sangrado se detiene (de 10 min)."}]},
		{k: "step", p: [{t: "Después de no tensar la nariz (no inhalación)."}]},
		{k: "step", p: [{t: "Si se producen graves problemas de sangrado o no puede detenerse, llame al médico de urgencias."}]}
	],
	aid_poisining: [
		{k: "title", t: "Intoxicación", i: "aid052"},
		{k: "description", t: "Confusión, alucinaciones, grandes alumnos, fiebre, calambres. Inconsciencia."},
		{k: "step", p: [{t: "Sólo dar antídotos si están acompañados por un médico capacitado."}]},
		{k: "image", i: "aid056"},
		{k: "step", p: [{t: "No le dé bebidas. No causa el vómito."}]},
		{k: "step", p: [{t: "Llamada de emergencia señalar el envenenamiento!"}]},
		{k: "step", p: [{t: "Salvaguardar restos de veneno y el vómito!"}]},
		{k: "image", i: "aid054a"},
		{k: "step", p: [{t: "En caso de siniestro y es consciente de la respiración: posición de recuperación. Monitor de estado de emergencia hasta el médico llega."}, {t: "〈+〉", h: "#aid_recoveryposition"}]},
		{k: "step", p: [{t: "En caso de siniestro no está respirando: iniciar inmediatamente con la reanimación! Libre boca antes de vomitar."}, {t: "〈+〉", h: "#aid_resuscitation"}]}
	],
	aid_recoveryposition: [
		{k: "title", t: "Posición de recuperación"},
		{k: "step", p: [{t: "Laicos siniestro sobre su espalda, enderezar las piernas. Al lado de la rodilla hacia abajo."}]},
		{k: "step", p: [{t: "Coloque el brazo más cercano a usted en un ángulo recto al cuerpo."}]},
		{k: "step", p: [{t: "Tire el brazo más de ti en el pecho y colocar el dorso de la mano contra la mejilla."}]},
		{k: "image", i: "aid008"},
		{k: "step", p: [{t: "Accede a la medida de rodilla, tire de ella a su lado, y sentar en el suelo. Coloque la pierna en un ángulo recto. Mantenga la mano de un siniestro en la mejilla de la persona."}]},
		{k: "step", p: [{t: "Asegúrese de que las vías respiratorias son gratuitos."}]},
		{k: "step", p: [{t: "Abrir la boca ligeramente, y la posición de la cabeza de esta manera que el vómito puede drenar. Compruebe la respiración."}]},
		{k: "image", i: "aid009"},
		{k: "step", p: [{t: "Control de la víctima la condición de emergencia hasta que el médico llega."}]},
		{k: "description", t: "〈Recovery position for babies:〉"},
		{k: "image", i: "aid028"}
	],
	aid_resuscitation: [
		{k: "title", t: "Resucitación"},
		{k: "subsection", t: "# Masaje cardíaco"},
		{k: "step", p: [{t: "Laicos siniestro en la espalda. Arrodillarse al lado de la persona."}]},
		{k: "step", p: [{t: "Desnudo el pecho."}]},
		{k: "step", p: [{t: "Coloque una mano bala en el centro del pecho (esternón poco más)."}]},
		{k: "image", i: "aid013"},
		{k: "step", p: [{t: "Lugar otra parte bala en la parte posterior de la mano que ya está en la posición."}]},
		{k: "step", p: [{t: "Alarga sus brazos y los codos."}]},
		{k: "image", i: "aid003"},
		{k: "step", p: [{t: "Presione 5 cm de profundidad en el pecho de la persona (el poder viene de la parte superior del cuerpo) y la liberación."}]},
		{k: "step", p: [{t: "Push 30-veces en una fila en breve y enérgicamente!"}]},
		{k: "subsection", t: "# Respirar"},
		{k: "step", p: [{t: "Estirar la cabeza en el cuello. Eliminar las sustancias de la boca y la garganta."}]},
		{k: "image", i: "aid067"},
		{k: "step", p: [{t: "Push alas de la nariz juntos, de modo que la nariz está cerrado."}]},
		{k: "image", i: "aid010"},
		{k: "step", p: [{t: "Respira hondo y ponga su boca sobre la boca de la víctima, que no puede fugas de aire."}]},
		{k: "image", i: "aid011"},
		{k: "step", p: [{t: "Do boca a boca para respirar dos veces (la respiración lentamente y totalmente)."}]},
		{k: "step", p: [{t: "Después de hacer masaje cardíaco de nuevo."}]},
		{k: "description", t: "Repita el masaje cardíaco, respiración boca hasta que el médico de urgencias llega."},
		{k: "image", i: "aid012"},
		{k: "subsection", t: "〈Resuscitation (Baby)Recovery position for babies:〉"},
		{k: "step", p: [{t: "〈Only use two fingers:〉"}]},
		{k: "image", i: "aid029"},
		{k: "step", p: [{t: "〈Do not breath too strong:〉"}]},
		{k: "image", i: "aid030"}
	],
	aid_safeguardaccident: [
		{k: "title", t: "Salvaguardia de accidentes"},
		{k: "step", p: [{t: "Detener su propio coche 50-100 m por detrás del lugar del accidente (si usted está en una autopista o carretera). Encienda las luces de alerta. Ponga en chaleco de alta visibilidad."}]},
		{k: "step", p: [{t: "Coloque el triángulo de advertencia antes del lugar del accidente. Atención: Si el accidente es una curva en la posición del triángulo antes de la curva!"}]},
		{k: "image", i: "aid111"},
		{k: "step", p: [{t: "Pregunte a otras personas por su ayuda."}]},
		{k: "step", p: [{t: "Abre la puerta del accidente de coche (si es tenso, la empresa abierta utilizando un coche jack). Apague la ignición."}]},
		{k: "step", p: [{t: "El rescate de la víctima: Unstrap del cinturón de seguridad, mueva el asiento hacia atrás. Libre el siniestro del coche de salvamento agarre."}, {t: "〈+〉", h: "#aid_dangerzone"}]},
		{k: "image", i: "aid001"},
		{k: "step", p: [{t: "Llamada de emergencia."}]},
		{k: "step", p: [{t: "Proceder con las medidas de primeros auxilios."}]}
	],
	aid_shock: [
		{k: "title", t: "Shock"},
		{k: "description", t: "Trastorno circulatorio por la falta de suministro de oxígeno en el cuerpo."},
		{k: "description", t: "Causa: Pérdida de líquido, la reducción de volumen de sangre."},
		{k: "description", t: "Los síntomas: palidez, piel fría, sudor frío, ansiedad."},
		{k: "step", p: [{t: "Eliminar la causa de la crisis (por ejemplo, detener la pérdida de fluidos, obligar a la herida)!"}]},
		{k: "step", p: [{t: "Sentar a los heridos en una manta, la posición de las piernas. Calma la persona."}]},
		{k: "image", i: "aid078"},
		{k: "step", p: [{t: "Llamada de emergencia."}]},
		{k: "step", p: [{t: "En caso de dificultad en la respiración o la conciencia, iniciar la reanimación."}, {t: "〈+〉", h: "#aid_resuscitation"}]}
	],
	aid_skullfracture: [
		{k: "title", t: "Fractura de cráneo"},
		{k: "description", t: "Ligeras hemorragias de la nariz, la boca o los oídos. A menudo heridas abiertas en el cráneo."},
		{k: "step", p: [{t: "Mantenga las vías respiratorias libres."}]},
		{k: "step", p: [{t: "Si consciente: Que el lesionado sentarse con la cabeza inclinó hacia delante. Evitar nuevos movimientos!"}]},
		{k: "step", p: [{t: "Si inconsciente: posición de recuperación (no hay presión sobre la herida de la cabeza)."}, {t: "〈+〉", h: "#aid_recoveryposition"}]},
		{k: "step", p: [{t: "Llamada de emergencia."}]},
		{k: "step", p: [{t: "Aplicar vendaje cabeza."}]},
		{k: "step", p: [{t: "En caso de dificultad en la respiración o la conciencia, iniciar la reanimación."}, {t: "〈+〉", h: "#aid_resuscitation"}]}
	],
	aid_snakebite: [
		{k: "title", t: "Snakebite", i: "aid051"},
		{k: "description", t: "Marcan la herida en el tamaño de un alfiler, graves dolores, hinchazón, color morado. Circulatorio perturbación, peligro de choque."},
		{k: "step", p: [{t: "Constante a los heridos parte del cuerpo."}]},
		{k: "step", p: [{t: "Aplicar frío sobres en torno a morder la herida."}]},
		{k: "step", p: [{t: "Medidas contra el shock."}]},
		{k: "step", p: [{t: "Llamada de emergencia."}]}
	],
	aid_sos: [
		{k: "title", t: "SOS"},
		{k: "step", p: [{t: "Signal: 3x corto, largo 3x, 3x corto."}]},
		{k: "step", p: [{t: "Óptica (luz estroboscópica, linterna), o acústica (señal de silbato, llamando)."}]}
	],
	aid_sprain: [
		{k: "title", t: "Esguince de la cepa"},
		{k: "description", t: "Dolor, hinchazón (moretón), la pérdida de la función, la deformación de la extremidad."},
		{k: "step", p: [{t: "Constante la parte lesionada del cuerpo sólo en la posición más cómoda para el siniestro."}]},
		{k: "step", p: [{t: "Enfriar (utilizando bolsas de hielo)."}]},
		{k: "step", p: [{t: "Si es posible, la posición de la parte lesionada elevada."}]},
		{k: "step", p: [{t: "Ir al hospital o llame al médico de urgencias."}]}
	],
	aid_stroke: [
		{k: "title", t: "Carrera"},
		{k: "description", t: "Repentina sensación de entumecimiento o parálisis (cara, brazo, pierna), alteraciones en el lenguaje la comprensión, problemas de visión, perturbado la conciencia, dolor de cabeza. Problemas para respirar y tragar, pérdida de control sobre la vejiga y el intestino."},
		{k: "image", i: "aid059"},
		{k: "step", p: [{t: "Llamada de emergencia!"}]},
		{k: "step", p: [{t: "Aflojar las ropas apretadas, no dar medicamentos o bebidas."}]},
		{k: "step", p: [{t: "Siéntese o establecer cómodamente persona de que se trate. Calma él / ella!"}]},
		{k: "step", p: [{t: "Control de la conciencia y la respiración."}]},
		{k: "step", p: [{t: "En caso de dificultad en la respiración o la conciencia, iniciar la reanimación."}, {t: "〈+〉", h: "#aid_resuscitation"}]}
	],
	aid_suffocation: [
		{k: "title", t: "Asfixia"},
		{k: "description", t: "Insuficiente suministro de oxígeno. Tráquea cerrada. Peligro: Apnea."},
		{k: "description", t: "Síntomas: respiratorias ruido sibilante, tos estímulo, falta de aliento, decoloración de la piel."},
		{k: "image", i: "aid066"},
		{k: "step", p: [{t: "La acción inmediata! Deje que la persona interesada tos muy fuerte."}]},
		{k: "step", p: [{t: "Strike firmemente con una mano plana sobre la espalda entre los hombros (los bebés determinar en su antebrazo, con la cabeza hacia abajo)."}]},
		{k: "image", i: "aid068"},
		{k: "image", i: "aid031"},
		{k: "step", p: [{t: "Si, sin éxito: Stand detrás de la persona, los brazos alrededor de la cintura, inclinarse ligeramente hacia adelante."}]},
		{k: "step", p: [{t: "Clench su puño, la posición en altura de la persona del estómago, y tomar con su otra mano."}]},
		{k: "image", i: "aid069"},
		{k: "step", p: [{t: "En abrazo usar ambas manos para dar un duro golpe al alza dirección de estómago (como si se tratar de levantar a la persona)."}]},
		{k: "step", p: [{t: "Repita este hasta 5 veces! Airways debe recibir libre de objeto."}]},
		{k: "step", p: [{t: "Llamada de emergencia."}]},
		{k: "step", p: [{t: "Si el primer medida de ayuda se pierda seguir haciéndolo hasta el médico de urgencias llega."}]}
	],
	aid_sunburn: [
		{k: "title", t: "Las quemaduras de sol"},
		{k: "step", p: [{t: "Retire a la persona afectada de la luz solar directa. Evitar más sol."}]},
		{k: "step", p: [{t: "Beba mucha agua para poner fin a la deshidratación."}]},
		{k: "step", p: [{t: "Si hay una quemadura grave Domingo (ampollas, enrojecimiento, dolor), buscar ayuda médica."}]},
		{k: "step", p: [{t: "Si la piel es sólo ligeramente de color rojo, puede ser enfriado con sobres húmedo. Domingo usar después de loción o gel."}]}
	],
	aid_sunstroke: [
		{k: "title", t: "Sunstroke"},
		{k: "description", t: "Rojo cabeza caliente, enfriar la piel, enfermedad, dolor de cabeza, mareos. Causa: irritación de la membrana cerebral."},
		{k: "image", i: "aid035"},
		{k: "step", p: [{t: "Ir a un lugar fresco (sombra) y la posición de la parte superior del cuerpo de la persona arriba."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Enfriar la cabeza con mantas mojadas."}]},
		{k: "step", p: [{t: "Llamada de emergencia, mantener el control de la respiración."}]},
		{k: "step", p: [{t: "Si consciente: Dar bebida fría, si procede."}]},
		{k: "step", p: [{t: "Si aparece apnea, comience con respiración:"}]},
		{k: "step", p: [{t: "Vamos con el aliento Dar!", h: "#aid_apnoea"}]},
		{k: "image", i: "aid036"}
	],
	aid_unconsciouswithbreath: [
		{k: "title", t: "Inconsciencia con la respiración"},
		{k: "description", t: "No reacción en preguntar en voz alta, no hay respuesta en agitación. Respirar no existen."},
		{k: "image", i: "aid057"},
		{k: "step", p: [{t: "Si hay personas a tu lado para pedir ayuda."}]},
		{k: "step", p: [{t: "Recuperación de posición. Abrir la boca y la posición de la cabeza de esta manera que el vómito puede drenar."}, {t: "〈+〉", h: "#aid_recoveryposition"}]},
		{k: "image", i: "aid008"},
		{k: "image", i: "aid009"},
		{k: "step", p: [{t: "Llamada de emergencia."}]}
	],
	aid_unconsciouswithoutbreath: [
		{k: "title", t: "Inconsciencia sin respirar"},
		{k: "step", p: [{t: "No reacción de la víctima, no respirar."}]},
		{k: "image", i: "aid057"},
		{k: "step", p: [{t: "Iniciar la reanimación."}, {t: "〈+〉", h: "#aid_resuscitation"}]}
	],
	aid_vomiting: [
		{k: "title", t: "Vómitos"},
		{k: "description", t: "Surge de las náuseas. Se vacía el estómago. Causas: La infección, envenenamiento, úlcera, las drogas, la mala alimentación, el embarazo."},
		{k: "image", i: "aid054"},
		{k: "step", p: [{t: "Peligro para la circulación a causa de la deshidratación y la pérdida de sal!"}]},
		{k: "step", p: [{t: "Dar líquidos (té, agua)."}]},
		{k: "step", p: [{t: "Si existen fuertes trastornos, sangre o vómitos continuos llamar al médico de urgencias."}]}
	]
};
var langContinents=[
	{i: "Africa", t: "〈Africa〉"},
	{i: "Asia", t: "〈Asia〉"},
	{i: "Europe", t: "〈Europe〉"},
	{i: "Northamerica", t: "〈North-/Central-America〉"},
	{i: "Oceania", t: "〈Oceania〉"},
	{i: "Southamerica", t: "〈South-America〉"}
];
var langCountries=[
	{i: "afghanistan", t: "〈Afghanistan〉"},
	{i: "albania", t: "〈Albania〉"},
	{i: "algeria", t: "〈Algeria〉"},
	{i: "andorra", t: "〈Andorra〉"},
	{i: "angola", t: "〈Angola〉"},
	{i: "antiguaandbarbuda", t: "〈Antigua and Barbuda〉"},
	{i: "argentina", t: "〈Argentina〉"},
	{i: "armenia", t: "〈Armenia〉"},
	{i: "australia", t: "〈Australia〉"},
	{i: "austria", t: "〈Austria〉"},
	{i: "azerbaijan", t: "〈Azerbaijan〉"},
	{i: "bahamas", t: "〈Bahamas〉"},
	{i: "bahrain", t: "〈Bahrain〉"},
	{i: "bangladesh", t: "〈Bangladesh〉"},
	{i: "barbados", t: "〈Barbados〉"},
	{i: "belarus", t: "〈Belarus〉"},
	{i: "belgium", t: "〈Belgium〉"},
	{i: "belize", t: "〈Belize〉"},
	{i: "benin", t: "〈Benin〉"},
	{i: "bhutan", t: "〈Bhutan〉"},
	{i: "bolivia", t: "〈Bolivia〉"},
	{i: "bosniaandherzegovina", t: "〈Bosnia and Herzegovina〉"},
	{i: "botswana", t: "〈Botswana〉"},
	{i: "brazil", t: "〈Brazil〉"},
	{i: "brunei", t: "〈Brunei〉"},
	{i: "bulgaria", t: "〈Bulgaria〉"},
	{i: "burkinafaso", t: "〈Burkina Faso〉"},
	{i: "burundi", t: "〈Burundi〉"},
	{i: "cambodia", t: "〈Cambodia〉"},
	{i: "cameroon", t: "〈Cameroon〉"},
	{i: "canada", t: "〈Canada〉"},
	{i: "capeverde", t: "〈Cape Verde〉"},
	{i: "caymanislands", t: "〈Cayman Islands〉"},
	{i: "centralafricanrepublic", t: "〈Central African Republic〉"},
	{i: "chad", t: "〈Chad〉"},
	{i: "chile", t: "〈Chile〉"},
	{i: "china", t: "〈China〉"},
	{i: "colombia", t: "〈Colombia〉"},
	{i: "comoros", t: "〈Comoros〉"},
	{i: "congodemocraticrepublic", t: "〈Congo (Democratic Republic)〉"},
	{i: "congorepublic", t: "〈Congo (Republic)〉"},
	{i: "costarica", t: "〈Costa Rica〉"},
	{i: "croatia", t: "〈Croatia〉"},
	{i: "cuba", t: "〈Cuba〉"},
	{i: "cyprus", t: "〈Cyprus〉"},
	{i: "czechrepublic", t: "〈Czech Republic〉"},
	{i: "denmark", t: "〈Denmark〉"},
	{i: "djibouti", t: "〈Djibouti〉"},
	{i: "dominicanrepublic", t: "〈Dominican Republic〉"},
	{i: "dominica", t: "〈Dominica〉"},
	{i: "easttimor", t: "〈East Timor〉"},
	{i: "ecuador", t: "〈Ecuador〉"},
	{i: "egypt", t: "〈Egypt〉"},
	{i: "elsalvador", t: "〈El Salvador〉"},
	{i: "equatorialguinea", t: "〈Equatorial Guinea〉"},
	{i: "eritrea", t: "〈Eritrea〉"},
	{i: "estonia", t: "〈Estonia〉"},
	{i: "ethiopia", t: "〈Ethiopia〉"},
	{i: "fiji", t: "〈Fiji〉"},
	{i: "finland", t: "〈Finland〉"},
	{i: "france", t: "〈France〉"},
	{i: "gabon", t: "〈Gabon〉"},
	{i: "gambia", t: "〈Gambia〉"},
	{i: "georgia", t: "〈Georgia〉"},
	{i: "germany", t: "〈Germany〉"},
	{i: "ghana", t: "〈Ghana〉"},
	{i: "greece", t: "〈Greece〉"},
	{i: "greenland", t: "〈Greenland〉"},
	{i: "grenada", t: "〈Grenada〉"},
	{i: "guatemala", t: "〈Guatemala〉"},
	{i: "guinea-bissau", t: "〈Guinea-Bissau〉"},
	{i: "guinea", t: "〈Guinea〉"},
	{i: "guyana", t: "〈Guyana〉"},
	{i: "haiti", t: "〈Haiti〉"},
	{i: "honduras", t: "〈Honduras〉"},
	{i: "hongkong", t: "〈Hong Kong〉"},
	{i: "hungary", t: "〈Hungary〉"},
	{i: "iceland", t: "〈Iceland〉"},
	{i: "india", t: "〈India〉"},
	{i: "indonesia", t: "〈Indonesia〉"},
	{i: "iran", t: "〈Iran〉"},
	{i: "iraq", t: "〈Iraq〉"},
	{i: "ireland", t: "〈Ireland〉"},
	{i: "israel", t: "〈Israel〉"},
	{i: "italy", t: "〈Italy〉"},
	{i: "ivorycoast", t: "〈Ivory Coast〉"},
	{i: "jamaica", t: "〈Jamaica〉"},
	{i: "japan", t: "〈Japan〉"},
	{i: "jordan", t: "〈Jordan〉"},
	{i: "kazakhstan", t: "〈Kazakhstan〉"},
	{i: "kenya", t: "〈Kenya〉"},
	{i: "kiribati", t: "〈Kiribati〉"},
	{i: "kosovo", t: "〈Kosovo〉"},
	{i: "kurdistan", t: "〈Kurdistan〉"},
	{i: "kuwait", t: "〈Kuwait〉"},
	{i: "kyrgyzstan", t: "〈Kyrgyzstan〉"},
	{i: "laos", t: "〈Laos〉"},
	{i: "latvia", t: "〈Latvia〉"},
	{i: "lebanon", t: "〈Lebanon〉"},
	{i: "lesotho", t: "〈Lesotho〉"},
	{i: "liberia", t: "〈Liberia〉"},
	{i: "libya", t: "〈Libya〉"},
	{i: "liechtenstein", t: "〈Liechtenstein〉"},
	{i: "lithuania", t: "〈Lithuania〉"},
	{i: "luxembourg", t: "〈Luxembourg〉"},
	{i: "macau", t: "〈Macau〉"},
	{i: "macedonia", t: "〈Macedonia〉"},
	{i: "madagascar", t: "〈Madagascar〉"},
	{i: "malawi", t: "〈Malawi〉"},
	{i: "malaysia", t: "〈Malaysia〉"},
	{i: "maldives", t: "〈Maldives〉"},
	{i: "mali", t: "〈Mali〉"},
	{i: "malta", t: "〈Malta〉"},
	{i: "marshallislands", t: "〈Marshall Islands〉"},
	{i: "mauritania", t: "〈Mauritania〉"},
	{i: "mauritius", t: "〈Mauritius〉"},
	{i: "mayotte", t: "〈Mayotte〉"},
	{i: "mexico", t: "〈Mexico〉"},
	{i: "micronesia", t: "〈Micronesia〉"},
	{i: "moldova", t: "〈Moldova〉"},
	{i: "monaco", t: "〈Monaco〉"},
	{i: "mongolia", t: "〈Mongolia〉"},
	{i: "montenegro", t: "〈Montenegro〉"},
	{i: "morocco", t: "〈Morocco〉"},
	{i: "mozambique", t: "〈Mozambique〉"},
	{i: "myanmar", t: "〈Myanmar〉"},
	{i: "namibia", t: "〈Namibia〉"},
	{i: "nauru", t: "〈Nauru〉"},
	{i: "nepal", t: "〈Nepal〉"},
	{i: "netherlands", t: "〈Netherlands〉"},
	{i: "newzealand", t: "〈New Zealand〉"},
	{i: "nicaragua", t: "〈Nicaragua〉"},
	{i: "nigeria", t: "〈Nigeria〉"},
	{i: "niger", t: "〈Niger〉"},
	{i: "northkorea", t: "〈North Korea〉"},
	{i: "norway", t: "〈Norway〉"},
	{i: "oman", t: "〈Oman〉"},
	{i: "pakistan", t: "〈Pakistan〉"},
	{i: "palau", t: "〈Palau〉"},
	{i: "panama", t: "〈Panama〉"},
	{i: "papuanewguinea", t: "〈Papua New Guinea〉"},
	{i: "paraguay", t: "〈Paraguay〉"},
	{i: "peru", t: "〈Peru〉"},
	{i: "philippines", t: "〈Philippines〉"},
	{i: "poland", t: "〈Poland〉"},
	{i: "portugal", t: "〈Portugal〉"},
	{i: "qatar", t: "〈Qatar〉"},
	{i: "reunion", t: "〈Réunion〉"},
	{i: "romania", t: "〈Romania〉"},
	{i: "russia", t: "〈Russia〉"},
	{i: "rwanda", t: "〈Rwanda〉"},
	{i: "sahrawiarabdemocraticrepublic", t: "〈Sahrawi Arab Democratic Republic〉"},
	{i: "stkittsandnevis", t: "〈Saint Kitts and Nevis〉"},
	{i: "stlucia", t: "〈Saint Lucia〉"},
	{i: "saintpierreandmiquelon", t: "〈Saint Pierre and Miquelon〉"},
	{i: "stvincentandgrenadines", t: "〈Saint Vincent and Grenadines〉"},
	{i: "samoa", t: "〈Samoa〉"},
	{i: "sanmarino", t: "〈San Marino〉"},
	{i: "saotomeandprincipe", t: "〈Sao Tomé and Principe〉"},
	{i: "saudiarabia", t: "〈Saudi Arabia〉"},
	{i: "senegal", t: "〈Senegal〉"},
	{i: "serbia", t: "〈Serbia〉"},
	{i: "seychelles", t: "〈Seychelles〉"},
	{i: "sierraleone", t: "〈Sierra Leone〉"},
	{i: "singapore", t: "〈Singapore〉"},
	{i: "slovakia", t: "〈Slovakia〉"},
	{i: "slovenia", t: "〈Slovenia〉"},
	{i: "solomonislands", t: "〈Solomon Islands〉"},
	{i: "somalia", t: "〈Somalia〉"},
	{i: "southafrica", t: "〈South Africa〉"},
	{i: "southkorea", t: "〈South Korea (Republic Korea)〉"},
	{i: "spain", t: "〈Spain〉"},
	{i: "srilanka", t: "〈Sri Lanka〉"},
	{i: "sudan", t: "〈Sudan〉"},
	{i: "suriname", t: "〈Suriname〉"},
	{i: "swaziland", t: "〈Swaziland〉"},
	{i: "sweden", t: "〈Sweden〉"},
	{i: "switzerland", t: "〈Switzerland〉"},
	{i: "syria", t: "〈Syria〉"},
	{i: "taiwan", t: "〈Taiwan〉"},
	{i: "tajikistan", t: "〈Tajikistan〉"},
	{i: "tanzania", t: "〈Tanzania〉"},
	{i: "thailand", t: "〈Thailand〉"},
	{i: "togo", t: "〈Togo〉"},
	{i: "tonga", t: "〈Tonga〉"},
	{i: "trinidadandtobago", t: "〈Trinidad and Tobago〉"},
	{i: "tunisia", t: "〈Tunisia〉"},
	{i: "turkey", t: "〈Turkey〉"},
	{i: "turkmenistan", t: "〈Turkmenistan〉"},
	{i: "tuvalu", t: "〈Tuvalu〉"},
	{i: "uganda", t: "〈Uganda〉"},
	{i: "ukraine", t: "〈Ukraine〉"},
	{i: "unitedarabemirates", t: "〈United Arab Emirates〉"},
	{i: "unitedkingdom", t: "〈United Kingdom〉"},
	{i: "unitedstatesofamerica", t: "〈United States of America〉"},
	{i: "uruguay", t: "〈Uruguay〉"},
	{i: "uzbekistan", t: "〈Uzbekistan〉"},
	{i: "vanuatu", t: "〈Vanuatu〉"},
	{i: "vaticancity", t: "〈Vatican City〉"},
	{i: "venezuela", t: "〈Venezuela〉"},
	{i: "vietnam", t: "〈Vietnam〉"},
	{i: "yemen", t: "〈Yemen〉"},
	{i: "zambia", t: "〈Zambia〉"},
	{i: "zimbabwe", t: "〈Zimbabwe〉"}
];
