//:První Pomoc
// Generated file, do not edit
var langTexts={
	title: "První Pomoc",
	back: "Zpět",
	continent: "Kontinent",
	emergency_fire: "Hasiči",
	emergency_medical: "Záchranná lékařská pomoc",
	emergency_police: "Policie",
	emergency_cancelcard: "",
	emergency_local: "místní čísla",
	emergency_nosystem: "nesystémové",
	emergency_radioonly: "pouze radiotelefony",
	emergency_none: "--",
	emergency_or: "nebo",
	emergency_mobile: "mobily",
	emergency_tourist: "turisté"
};
var langMenu=[
	{h: "#aid_disclaimer", t: "# Zřeknutí se odpovědnosti + informace"},
	{h: "#numbers", t: "# Tísňová volání"},
	{h: "#aid_general", t: "# Obecné chování"},
	{h: "#aid_allergic", t: "Alergická reakce"},
	{h: "#aid_amputation", t: "Amputace"},
	{h: "#aid_asthma", t: "Astma"},
	{h: "#aid_unconsciouswithoutbreath", t: "Bezvědomí bez dýchání"},
	{h: "#aid_unconsciouswithbreath", t: "Bezvědomí s dýcháním"},
	{h: "#aid_diabeticcoma", t: "Diabetické koma"},
	{h: "#aid_safeguardaccident", t: "Dopravní nehoda"},
	{h: "#aid_apnoea", t: "Dýchání"},
	{h: "#aid_epilepsy", t: "Epilepsie"},
	{h: "#aid_snakebite", t: "Hadí uštknutí"},
	{h: "#aid_diabeticcoma", t: "Hyperglykémie (nadbytek cukru)"},
	{h: "#aid_hypoglycaemia", t: "Hypoglykémie (nedostatek cukru)"},
	{h: "#aid_checkbreathing", t: "Kontrola dýchání"},
	{h: "#aid_bleedinglight", t: "Krvácení - lehké"},
	{h: "#aid_bleedingsevere", t: "Krvácení - vážné"},
	{h: "#aid_nosebleeding", t: "Krvácení z nosu"},
	{h: "#aid_stroke", t: "Mozková mrtvice"},
	{h: "#aid_dangerzone", t: "Nebezpečná zóna (záchrana)"},
	{h: "#aid_frostbitemild", t: "Omrzliny mírné"},
	{h: "#aid_frostbitesevere", t: "Omrzliny vážné"},
	{h: "#aid_poisining", t: "Otrava"},
	{h: "#aid_brainconcussion", t: "Otřes mozku"},
	{h: "#aid_resuscitation", t: "Oživování"},
	{h: "#aid_insectstings", t: "Pobodání hmyzem"},
	{h: "#aid_hypothermia", t: "Podchlazení (studené tělo)"},
	{h: "#aid_animalbite", t: "Pokousání zvířetem"},
	{h: "#aid_chemicalburn", t: "Popálení chemikáliemi"},
	{h: "#aid_chemicalburneyes", t: "Popálení chemikáliemi (oči)"},
	{h: "#aid_backinjury", t: "Poranění míchy"},
	{h: "#aid_eyeinjury", t: "Poranění očí"},
	{h: "#aid_backinjury", t: "Poranění páteře"},
	{h: "#aid_birth", t: "Porod"},
	{h: "#aid_diarrhoea", t: "Průjem"},
	{h: "#aid_resuscitation", t: "Resuscitace"},
	{h: "#aid_shock", t: "Šok"},
	{h: "#aid_sos", t: "SOS"},
	{h: "#aid_burningslight", t: "Spáleniny (lehké)"},
	{h: "#aid_burningsevere", t: "Spáleniny (vážné)"},
	{h: "#aid_sunburn", t: "Spáleniny od slunce"},
	{h: "#aid_suffocation", t: "Spolknutí předmětu/ Dušení"},
	{h: "#aid_heartattack", t: "Srdeční infarkt"},
	{h: "#aid_recoveryposition", t: "Stabilizovaná poloha"},
	{h: "#aid_resuscitation", t: "Stlačování hrudníku"},
	{h: "#aid_sunstroke", t: "Tepelný úpal"},
	{h: "#aid_emergencycall", t: "Tísňové volání"},
	{h: "#aid_drowning", t: "Tonutí"},
	{h: "#aid_suffocation", t: "Udušení (Dušení)"},
	{h: "#aid_electricityaccident", t: "Úraz elektřinou"},
	{h: "#aid_hyperthermia", t: "Vyčerpání z přehřátí (horké tělo)"},
	{h: "#aid_sprain", t: "Vymknutí a přetažení vazů"},
	{h: "#aid_safeguardaccident", t: "Zabezpečení místa nehody"},
	{h: "#aid_icerescue", t: "Záchrana z ledu"},
	{h: "#aid_apnoea", t: "Zástava dechu"},
	{h: "#aid_fracture", t: "Zlomenina"},
	{h: "#aid_skullfracture", t: "Zlomenina lebky"},
	{h: "#aid_asthma", t: "Ztížené dýchání"},
	{h: "#aid_vomiting", t: "Zvracení"},
	{h: "tel:112", t: "Volejte záchrannou službu 112"}
];
var langSections={
	aid_disclaimer: [
		{k: "title", t: "Zřeknutí se odpovědnosti + informace"},
		{k: "subsection", t: "Software"},
		{k: "description", t: "První pomoc ve vašem mobilu"},
		{k: "description", t: "Copyright: Kai Kajus Noack"},
		{k: "description", t: "Translator: Pavel Prokeš"},
		{k: "description", t: "License: Creative Commons"},
		{k: "image", i: "cc88x31"},
		{k: "description", t: "Tento program má poskytovat informace o první pomoci. Nepředstavuje však náhradu za kurz první pomoci. Poslouží vám spíše k osvěžení vašich již získaných znalostí."},
		{k: "description", t: "Obrázky © Med4Teens"},
		{k: "subsection", t: "Zřeknutí se zodpovědnosti"},
		{k: "description", t: "Dovoluji si upozornit, že nepřebírám žádnou odpovědnost za následky vyplývající z použití tohoto programu."},
		{k: "description", t: "JAKÁKOLIV ODPOVĚDNOST JE VYLOUČENA!"},
		{k: "description", t: "POUŽITÍ NA VLASTNÍ RIZIKO!"},
		{k: "description", t: "Ve všech naléhavých případech, vyhledejte prosím ihned odbornou pomoc."},
		{k: "subsection", t: "Zachránit jeden život je jako zachránit svět."}
	],
	aid_general: [
		{k: "title", t: "Obecné chování"},
		{k: "step", p: [{t: "Vždy poskytujte první pomoc. Nemůžete udělat žádné chyby."}]},
		{k: "step", p: [{t: "Vždy věnujte pozornost vlastnímu bezpečí."}]},
		{k: "step", p: [{t: "Posuďte situaci a zajistěte místo nehody."}]},
		{k: "step", p: [{t: "Volejte záchrannou službu a provádějte úkony první pomoci."}]},
		{k: "step", p: [{t: "Pokud je více obětí, přednostně ošetřujte nejvíce postižené."}]},
		{k: "step", p: [{t: "Vždy se pokuste uklidnit dotyčné osoby. Sám zůstaňte klidný."}]},
		{k: "step", p: [{t: "Je-li to možné, oběť pohodlně položte. Osobám postiženým nehodou nikdy nedávejte alkohol, nikotin, nebo léky."}]}
	],
	aid_allergic: [
		{k: "title", t: "Alergická reakce", i: "aid046"},
		{k: "step", p: [{t: "Volejte okamžitě záchrannou službu."}]},
		{k: "step", p: [{t: "Pokuste se uklidnit oběť a pomožte jí pohodlně se posadit."}]},
		{k: "step", p: [{t: "Opatrně odstraňte látky způsobující alergii (např. včelí žihadlo)."}]},
		{k: "step", p: [{t: "Ochlazujte postiženou pokožku (mokré obklady, led)."}]},
		{k: "image", i: "aid046ice"},
		{k: "step", p: [{t: "Pokud má oběť protilék, měla by ho použít (pomozte jí)"}]},
		{k: "step", p: [{t: "Do příjezdu záchranné služby kontrolujte stav oběti."}]},
		{k: "step", p: [{t: "Pokud oběť ztratí vědomí, nebo se zastaví dýchání, řiďte se příslušnými pokyny."}]},
		{k: "image", i: "aid077"}
	],
	aid_amputation: [
		{k: "title", t: "Amputace"},
		{k: "description", t: "Amputovaná část těla může být opětovně chirurgicky připojena. Cíle: Do příjezdu do nemocnice udržet amputovanou část v chladu."},
		{k: "step", p: [{t: "Uklidněte osobu, položte jí na zem a přikryjte pokrývkou."}]},
		{k: "step", p: [{t: "Zastavte krvácení viz 'Krvácení (vážné)' a 'Šok'."}]},
		{k: "step", p: [{t: "Amputovanou část zabalte do čisté a suché látky a vložte do vodovzdorného plastového sáčku."}]},
		{k: "step", p: [{t: "Tento sáček uzavřete a vložte do dalšího plastového sáčku obsahujícího studenou vodu, nebo led."}]},
		{k: "step", p: [{t: "Oběti nepodávejte alkohol, cigarety, nebo jídlo (pro případ že bude v nemocnici proveden chirurgický zákrok s celkovou anestézií)."}]},
		{k: "step", p: [{t: "Amputovanou část nezmrazujte, (pouze ji udržujte v chladu)."}]},
		{k: "step", p: [{t: "Volejte záchrannou službu, nebo odvezte postiženého do nemocnice sám."}]}
	],
	aid_animalbite: [
		{k: "title", t: "Pokousání zvířetem", i: "aid047"},
		{k: "description", t: "Pozor: Vysoké nebezpečí infekce. Následkem může být hnisání, tetanus, nebo vzteklina."},
		{k: "step", p: [{t: "Zranění omyjte horkou mýdlovou vodou."}]},
		{k: "image", i: "aid049"},
		{k: "step", p: [{t: "Následně zranění vydesinfikujte."}]},
		{k: "step", p: [{t: "Pokud postižený silně krvácí, zvedněte jeho horní část těla."}]},
		{k: "step", p: [{t: "Přiložte sterilní obvaz."}]},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Jděte do nemocnice, nebo zavolejte pohotovostního lékaře."}]}
	],
	aid_apnoea: [
		{k: "title", t: "Zástava dechu"},
		{k: "description", t: "Chybí zvuky dýchání a pohyby hrudníku, je viditelná změna barvy pokožky."},
		{k: "step", p: [{t: "Volejte záchrannou službu."}]},
		{k: "step", p: [{t: "Položte oběť na záda."}]},
		{k: "step", p: [{t: "Z úst a krku odstraňte cizí předměty. Zakloňte jí hlavu."}]},
		{k: "image", i: "aid067"},
		{k: "step", p: [{t: "Stiskněte nos prsty tak, aby byl uzavřen."}]},
		{k: "image", i: "aid010"},
		{k: "step", p: [{t: "Zhluboka se nadechněte a přiložte svá ústa na ústa oběti tak, aby vzduch neunikal."}]},
		{k: "image", i: "aid011"},
		{k: "step", p: [{t: "Pomalu a naplno vdechujte."}]},
		{k: "step", p: [{t: "Nemáte-li úspěch: Vdechujte tak dlouho dokud nedorazí záchranka."}]}
	],
	aid_asthma: [
		{k: "title", t: "Astma"},
		{k: "description", t: "Silná dušnost. Hvízdavé zvuky dýchání. Obavy."},
		{k: "step", p: [{t: "Uklidněte osobu. Sám zůstaňte klidný."}]},
		{k: "step", p: [{t: "Uvolněte postiženému oděv."}]},
		{k: "step", p: [{t: "Posaďte postiženého a nakloňte ho dopředu. Povzbuzujte ho, aby dýchal pomalu a zhluboka."}]},
		{k: "step", p: [{t: "Pokud má postižený inhalátor, měl by ho použít (pomožte mu). Účinek by se měl dostavit za 5 až 10 minut."}]},
		{k: "image", i: "aid074"},
		{k: "step", p: [{t: "Pokud nenastane zlepšení: Až do příjezdu záchranky používejte inhalátor každých 5 minut."}]},
		{k: "step", p: [{t: "Volejte záchrannou službu."}]},
		{k: "step", p: [{t: "Pokud se zastaví dýchání, řiďte se pokyny pro "}, {t: "zástavu dechu", h: "#aid_apnoea"}, {t: "."}]}
	],
	aid_backinjury: [
		{k: "title", t: "Poranění páteře"},
		{k: "description", t: "Bolest v zádech, ztuhlost rukou a nohou."},
		{k: "step", p: [{t: "S postiženým nehýbejte!!"}]},
		{k: "image", i: "aid064"},
		{k: "step", p: [{t: "Držte hlavu oběti tak, aby ležela stabilně (hlavu držte pevně)."}]},
		{k: "image", i: "aid065"},
		{k: "step", p: [{t: "Oběť stabilizujte polštářky položenými z obou stran."}]},
		{k: "step", p: [{t: "Uklidňujte postiženého."}]},
		{k: "step", p: [{t: "Volejte záchrannou službu. Oznamte podezření na poranění páteře."}]}
	],
	aid_birth: [
		{k: "title", t: "Porod"},
		{k: "description", t: "Odtok plodové vody. Nastávají bolestivé stahy. Neočekávaný porod."},
		{k: "image", i: "aid025"},
		{k: "step", p: [{t: "Věnujte pozornost soukromí rodičky a zachovávejte klid. Volejte záchrannou službu."}]},
		{k: "step", p: [{t: "Umožněte těhotné ženě obnažit si dolní polovinu těla a sednout si na sterilní podložku s roztaženými nohama."}]},
		{k: "step", p: [{t: "Ohněte kolena. Zvedněte nohy nahoru. Pánev předsuňte lehce vzhůru. Porod je přirozený proces a probíhá většinou bez komplikací."}]},
		{k: "step", p: [{t: "Uklidněte ženu a nechte ji soustředit se na svůj dech: Vdechovat nosem a vydechovat ústy (normální rychlostí)."}]},
		{k: "step", p: [{t: "Rytmus tlačení: Zhluboka nadechnout, zadržet dech a zatlačit. Jakmile se objeví hlavička dítěte podpírejte jí držením oběma rukama."}]},
		{k: "image", i: "aid021"},
		{k: "image", i: "aid022"},
		{k: "step", p: [{t: "Po porodu: Držte dítě na předloktí s hlavou dolů tak, aby se z dýchacích cest uvolnila plodová voda. (Tekutinu můžete vysát dítěti z nosu svými ústy). Dítě musí začít dýchat a plakat."}]},
		{k: "step", p: [{t: "Ve vzdálenosti asi 30 cm od dítěte pevně podvažte pupeční šňůru. Porodní cesty matky udržujte v čistotě."}]},
		{k: "image", i: "aid023"},
		{k: "step", p: [{t: "Osušte dítě a udržujte ho teplé. Poznamenejte čas narození a jeďte do nemocnice."}]}
	],
	aid_bleedinglight: [
		{k: "title", t: "Krvácení - lehké", i: "aid082"},
		{k: "description", t: "Cíle: Zastavit krvácení."},
		{k: "step", p: [{t: "Nedotýkejte se poranění (nebezpečí infekce)."}]},
		{k: "step", p: [{t: "Neošetřujte zranění zásypy, mastmi, nebo spreji."}]},
		{k: "step", p: [{t: "Léčba zranění: Zakryjte ho sterilním materiálem a obvažte."}]},
		{k: "image", i: "aid098"},
		{k: "step", p: [{t: "Na mírné krvácení zpravidla stačí náplast."}]},
		{k: "step", p: [{t: "Rozsáhlé zranění zakryjte sterilním polštářkem a obvažte. Neutahujte obvaz příliš těsně, protože městnání může vést ke zvýšenému krvácení."}]},
		{k: "image", i: "aid084"},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Zranění způsobené kousnutím vzteklého zvířete má být omyto mýdlovou vodou."}]},
		{k: "image", i: "aid049"}
	],
	aid_bleedingsevere: [
		{k: "title", t: "Krvácení - vážné"},
		{k: "description", t: "Stříkající, pulsující krvácení. Nebezpečí: Dušení způsobené ztrátou krve, infekce, smrt. Cíle: Zastavit krvácení."},
		{k: "step", p: [{t: "Svlékněte oděv (v případě nutnosti rozstřihněte) a odhalte poranění."}]},
		{k: "step", p: [{t: "Ovažte obvazem, nebo v případě potřeby kusem šatstva stlačujícím okolí rány."}]},
		{k: "image", i: "aid086"},
		{k: "step", p: [{t: "Tlak na ránu udržujte nejméně 10 minut."}]},
		{k: "step", p: [{t: "Pokud je obvaz nasáklý krví, neodstraňujte jej. Namísto toho jej obalte dalším obvazem, nebo kusem šatstva."}]},
		{k: "step", p: [{t: "Postiženou končetinu (není-li zlomena) umístěte kvůli snížení krevního tlaku nad úroveň srdce. Je-li to možné, postiženého položte."}]},
		{k: "step", p: [{t: "Jestliže krvácení neustane, udržujte tlak na ránu a vyhledejte další tlakový bod pro poranění: Při krvácení na předloktí stlačujte nadloktí (pomocí prstů stiskněte žílu na vnitřní straně paže, uprostřed lokte, nebo v podpažní jamce. Při krvácení na noze stiskněte bod ve slabinách (pomocí koule ze spojených rukou stiskněte žílu na ohbí třísel v místě, kde vede tepna přes pánevní kost."}]},
		{k: "image", i: "aid089"},
		{k: "image", i: "aid092"},
		{k: "step", p: [{t: "Volejte okamžitě záchrannou službu."}]},
		{k: "step", p: [{t: "Po zvládnutí krvácení: co nejdříve zahajte opatření proti šoku."}]},
		{k: "image", i: "aid093"}
	],
	aid_brainconcussion: [
		{k: "title", t: "Otřes mozku"},
		{k: "description", t: "Bolest hlavy, nevolnost, zvracení. Rozostřené vidění, Může nastat bezvědomí."},
		{k: "image", i: "aid035a"},
		{k: "step", p: [{t: "Postiženou osobu položte."}]},
		{k: "step", p: [{t: "Volejte záchrannou službu."}]},
		{k: "description", t: "Při krvácení z hlavy:"},
		{k: "step", p: [{t: "Položte oběť s nazdvihnutou hlavou (na polštáři)."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Ošetřujte poranění (použijte obvaz hlavy)."}]},
		{k: "step", p: [{t: "Volejte záchrannou službu."}]}
	],
	aid_burningslight: [
		{k: "title", t: "Spáleniny (lehké)"},
		{k: "description", t: "Zarudlá kůže. Mírný otok. Bolest."},
		{k: "step", p: [{t: "Postižená místa ochlazujte studenou vodou."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Přiložte volný, mokrý obklad."}]}
	],
	aid_burningsevere: [
		{k: "title", t: "Spáleniny (vážné)"},
		{k: "description", t: "Skvrnité bíločervené oblasti s puchýři. Kůže ztrácí tekutiny. Hluboké poškození tkání. Silná, nebo žádná bolest (protože jsou spáleny nervy)."},
		{k: "image", i: "aid097"},
		{k: "step", p: [{t: "Podle možností odstraňte co nejvíce oblečení."}]},
		{k: "step", p: [{t: "Popálené části těla ochlazujte až 10 minut studenou vodou (okolo 15°C, 59°F), dokud se nezmírní bolest."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Při rozsáhlých popáleninách provádějte ochlazování mokrou látkou."}]},
		{k: "step", p: [{t: "Volejte záchrannou službu."}]},
		{k: "step", p: [{t: "Po ochlazení ošetřete poranění. Nepoužívejte tekutiny (žádné krémy, oleje, masti atd.). Puchýře nepropichujte."}]},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Do příjezdu záchranné služby kontrolujte stav a vědomí postiženého."}]}
	],
	aid_checkbreathing: [
		{k: "title", t: "Kontrola dýchání"},
		{k: "step", p: [{t: "Ověřte zvuky dýchání."}]},
		{k: "step", p: [{t: "Dýchání zjišťujte na horní části břicha (přiložením ruky)."}]},
		{k: "image", i: "aid027"},
		{k: "step", p: [{t: "Snažte se vycítit dech z nosu a z úst oběti."}]}
	],
	aid_chemicalburneyes: [
		{k: "title", t: "Popálení chemikáliemi (oči)"},
		{k: "step", p: [{t: "Volejte záchrannou službu, informujte je o druhu chemikálie."}]},
		{k: "step", p: [{t: "Vyplachujte oko velkým množstvím vody. Při vyplachování druhé oko zakryjte."}]},
		{k: "step", p: [{t: "Proud vody veďte od vnitřního koutku oka k vnějšímu okraji. Vyplachujte ho nejméně 20 minut čistou vodou."}]},
		{k: "image", i: "aid019"},
		{k: "step", p: [{t: "Zavřete obě oči oběti a zavažte je mokrou látkou."}]},
		{k: "image", i: "aid020"},
		{k: "step", p: [{t: "Do příjezdu záchranné služby kontrolujte stav oběti."}]}
	],
	aid_chemicalburn: [
		{k: "title", t: "Popálení chemikáliemi"},
		{k: "description", t: "Poranění tkání."},
		{k: "image", i: "aid095"},
		{k: "step", p: [{t: "Mějte na mysli vlastní ochranu."}]},
		{k: "step", p: [{t: "Jednejte rychle a omyjte popálená místa."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Volejte záchrannou službu."}]},
		{k: "step", p: [{t: "Jedná-li se o popálení zažívacího ústrojí, zvláště úst a hrdla, pijte hodně vody."}]},
		{k: "step", p: [{t: "Nevyvolávejte zvracení."}]}
	],
	aid_dangerzone: [
		{k: "title", t: "Nebezpečná zóna (záchrana)"},
		{k: "step", p: [{t: "Provedení úchopu: Položte jednu ruku zraněného přes jeho hrudník a postavte se za něj."}]},
		{k: "step", p: [{t: "Vsuňte své ruce pod ramena zraněného a uchopte jimi jeho ohnutou paží."}]},
		{k: "step", p: [{t: "Táhněte vzad a odtáhněte zraněného do bezpečí."}]},
		{k: "image", i: "aid001"},
		{k: "image", i: "aid007"}
	],
	aid_diabeticcoma: [
		{k: "title", t: "Diabetické koma"},
		{k: "description", t: "Hladina krevního cukru je příliš vysoká (jinak řečeno nedostatek inzulinu)."},
		{k: "description", t: "Příznaky: Žízeň, časté močení, nevolnost, zvracení. Dech páchne jako ovoce, nebo víno."},
		{k: "step", p: [{t: "Volejte záchrannou službu"}]},
		{k: "step", p: [{t: "Pomožte osobě (je-li ověřena jako diabetik) užít inzulin."}]},
		{k: "image", i: "aid016"},
		{k: "step", p: [{t: "Uložte jí do stabilizované polohy.", h: "#aid_recoveryposition"}, {t: " (Jiná možnost první pomoci není.)"}]},
		{k: "step", p: [{t: "Do příjezdu záchranné služby kontrolujte stav oběti."}]}
	],
	aid_diarrhoea: [
		{k: "title", t: "Průjem"},
		{k: "description", t: "Reakce na zkažené jídlo. Podráždění, nebo infekce střev. Stolice je řídká, slizká, nebo krvavá."},
		{k: "step", p: [{t: "Nebezpečí pro krevní oběh, protože dochází ke ztrátám tekutin a solí."}]},
		{k: "step", p: [{t: "Podávejte tekutiny (čaj, vodu)."}]},
		{k: "step", p: [{t: "Při silných potížích volejte pohotovostního lékaře."}]}
	],
	aid_drowning: [
		{k: "title", t: "Tonutí"},
		{k: "step", p: [{t: "Volejte záchrannou službu. Požádejte lidi v blízkosti o pomoc."}]},
		{k: "image", i: "aid032"},
		{k: "step", p: [{t: "Zachraňte člověka z vody."}]},
		{k: "image", i: "aid033"},
		{k: "image", i: "aid034"},
		{k: "step", p: [{t: "Když oběť dýchá: "}, {t: "Uložte jí do stabilizované polohy", h: "#aid_recoveryposition"}, {t: ". Udržujte jí v teple (zakrytou). Do příjezdu záchranné služby kontrolujte stav oběti.\n    "}]},
		{k: "step", p: [{t: "Když oběť nedýchá: Okamžitě zahajte "}, {t: "resuscitaci", h: "#aid_resuscitation"}, {t: "! (Odsávání vody z plic je bez užitku).\n    "}]}
	],
	aid_electricityaccident: [
		{k: "title", t: "Úraz elektřinou"},
		{k: "step", p: [{t: "Nejdříve odpojte přívod elektřiny."}]},
		{k: "image", i: "aid045plug"},
		{k: "image", i: "aid045"},
		{k: "step", p: [{t: "Nebezpečí: Bezvědomí, zástava dechu."}]},
		{k: "step", p: [{t: "A - Bezvědomí s dýcháním.", h: "#aid_unconsciouswithbreath"}]},
		{k: "step", p: [{t: "B - Bezvědomí se ztrátou dechu", h: "#aid_unconsciouswithoutbreath"}]},
		{k: "image", i: "aid042"},
		{k: "image", i: "aid043"}
	],
	aid_emergencycall: [
		{k: "title", t: "Tísňové volání"},
		{k: "step", p: [{t: "Na nejbližším dostupném telefonu vytočte číslo 112 (v USA: 911). Je vždy dostupné a zdarma. Nezneužívejte ho k volání sanitky! "}]},
		{k: "step", p: [{t: "Do telefonu musíte poskytnout následující informace:"}]},
		{k: "step", p: [{t: "- Co se stalo."}]},
		{k: "step", p: [{t: "- Kde (místo nehody)."}]},
		{k: "step", p: [{t: "- Kolik je postižených."}]},
		{k: "step", p: [{t: "- Jaké mají poranění."}]},
		{k: "step", p: [{t: "Potom čekejte na další pokyny, nebo otázky."}]}
	],
	aid_epilepsy: [
		{k: "title", t: "Epilepsie"},
		{k: "description", t: "Ztuhlé tělo, sevřené pěsti, stisknuté čelisti. Záškuby v končetinách nebo ve tváři. Oči obrácené v sloup. Slinění. Případné bezvědomí."},
		{k: "image", i: "aid058"},
		{k: "step", p: [{t: "Nedržte oběť, nebo neomezujte její pohyby."}]},
		{k: "step", p: [{t: "Položte oběť na měkkou podložku. Odstraňte blízké předměty abyste zabránili sebepoškození oběti."}]},
		{k: "step", p: [{t: "Uklidněte oběť. Uvolněte jí šatstvo aby mohla volně dýchat."}]},
		{k: "step", p: [{t: "Když oběť zvrací, otočte jí hlavu na stranu aby mohly zvratky odtékat."}]},
		{k: "step", p: [{t: "Udržujte volné dýchací cesty. Nebezpečí zapadnutí jazyka."}]},
		{k: "step", p: [{t: "Uložte oběť do stabilizované polohy", h: "#aid_recoveryposition"}, {t: " a volejte záchrannou službu. Pokračujte v kontrole stavu oběti."}]},
		{k: "step", p: [{t: "Přihlížející osoby udržujte v povzdálí."}]}
	],
	aid_eyeinjury: [
		{k: "title", t: "Poranění očí"},
		{k: "step", p: [{t: "Ponechejte cizí těleso v oku oběti. Neodstraňujte jej."}]},
		{k: "step", p: [{t: "Aby se předešlo dalšímu zranění, neměla by oběť hýbat očima. Nedotýkejte se oka."}]},
		{k: "step", p: [{t: "Pokud oko krvácí, zakryjte ho obvazem, nebo sterilní gázou."}]},
		{k: "image", i: "aid020"},
		{k: "step", p: [{t: "Ochlazujte oko chladicím polštářkem zmenší se otok a krvácení ustane rychleji)."}]},
		{k: "step", p: [{t: "Volejte záchrannou službu, nebo dovezte oběť do nemocnice sám."}]}
	],
	aid_fracture: [
		{k: "title", t: "Zlomenina"},
		{k: "description", t: "Příznaky: Neobvyklá poloha, nebo pohyblivost kostí. Bolest při pohybu, citlivost na dotek."},
		{k: "image", i: "aid104"},
		{k: "step", p: [{t: "Vyvarujte se s postiženým hýbat!"}]},
		{k: "step", p: [{t: "Volejte záchrannou službu."}]},
		{k: "step", p: [{t: "Pevně znehybněte zlomenou kost např. vycpávkovým materiálem okolo kosti. Zachovejte polohu kostí."}]},
		{k: "image", i: "aid107"},
		{k: "step", p: [{t: "U otevřené zlomeniny zakryjte ránu sterilním materiálem."}]},
		{k: "image", i: "aid106"}
	],
	aid_frostbitemild: [
		{k: "title", t: "Omrzliny mírné"},
		{k: "description", t: "Bledost, otékání. Nebezpečí pro krevní oběh."},
		{k: "step", p: [{t: "Přesuňte oběť na teplé místo."}]},
		{k: "step", p: [{t: "Dostaňte postiženého z chladna, svlékněte studený oděv, a osušte ho."}]},
		{k: "step", p: [{t: "Zahřívejte oběť vlažnou vodou a tělesným teplem pomáhajícího."}]},
		{k: "step", p: [{t: "Podávejte horké nápoje (čaj). Nepodávejte alkohol."}]},
		{k: "image", i: "aid040"}
	],
	aid_frostbitesevere: [
		{k: "title", t: "Omrzliny vážné"},
		{k: "description", t: "Studená, ztuhlá kůže šedobílé barvy, puchýře, odumírání tkání. Nebezpečí pro krevní oběh."},
		{k: "image", i: "aid096"},
		{k: "step", p: [{t: "Jděte na teplé místo."}]},
		{k: "step", p: [{t: "Ošetřete a zakryjte zranění."}]},
		{k: "step", p: [{t: "Podávejte sladké nápoje."}]},
		{k: "step", p: [{t: "Neprohřívejte oběť třením."}]},
		{k: "step", p: [{t: "Volejte záchrannou službu."}]}
	],
	aid_heartattack: [
		{k: "title", t: "Srdeční infarkt"},
		{k: "description", t: "Silný, déle než 5 minut trvající tlak a bolest na hrudníku, obzvlášť vyzařující do ramena nebo paže. Úzkost, zblednutí, studený pot. Případná nevolnost, zkrácený dech."},
		{k: "image", i: "aid076"},
		{k: "image", i: "aid083"},
		{k: "step", p: [{t: "Volejte záchrannou službu. Sdělte jim podezření na srdeční infarkt."}]},
		{k: "step", p: [{t: "Postiženého posaďte tak, aby měl horní část těla zvednutou. Uvolněte mu těsný oděv. Nepodávejte léky ani nápoje."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Na postiženou osobu mluvte uklidňujícím tónem."}]},
		{k: "step", p: [{t: "Kontrolujte stav vědomí a dýchání."}]},
		{k: "step", p: [{t: "Je-li dostupný, podejte aspirin."}]},
		{k: "step", p: [{t: "Upadne-li postižený do bezvědomí, zahajte "}, {t: "resuscitaci", h: "#aid_resuscitation"}, {t: "."}]}
	],
	aid_hypoglycaemia: [
		{k: "title", t: "Hypoglykémie (nedostatek cukru)"},
		{k: "description", t: "Hladina krevního cukru je pod minimální úrovní (v důsledku předávkování inzulinu, nebo nedostatečného přísunu potravy)."},
		{k: "description", t: "Příznaky: Bledost, nervozita, hlad, třesavka, pocení."},
		{k: "image", i: "aid018"},
		{k: "step", p: [{t: "Ujistěte se že postižený je diabetik (podívejte se po štítku diabetika)."}]},
		{k: "step", p: [{t: "Volejte záchrannou službu."}]},
		{k: "step", p: [{t: "Podávejte sladké nápoje a dextrózu, nebo glukózu (není-li problém s polykáním)."}]},
		{k: "image", i: "aid017"},
		{k: "step", p: [{t: "Když je postižený při vědomí a dýchá: "}, {t: "Uložte ho do stabilizované polohy", h: "#aid_recoveryposition"}, {t: " a kontrolujte jeho dech. Dojde-li k zástavě dechu, zahajte umělé dýchání."}]},
		{k: "step", p: [{t: "Pokud dýchá, můžete mu vložit do úst mezi zuby a tvář kousek cukru a přidržovat ho na místě tlakem zvenčí."}]}
	],
	aid_hyperthermia: [
		{k: "title", t: "Vyčerpání z přehřátí (horké tělo)"},
		{k: "description", t: "Žízeň, slabost, dezorientace, nevolnost, zmatenost, silné pocení, horká pokožka."},
		{k: "image", i: "aid035"},
		{k: "step", p: [{t: "Volejte záchrannou službu."}]},
		{k: "step", p: [{t: "Vyhledejte chladné a stinné místo (přednostně klimatizovanou místnost)."}]},
		{k: "step", p: [{t: "Postiženého položte a nadzdvihněte mu nohy. Uvolněte mu oděv."}]},
		{k: "image", i: "aid078"},
		{k: "step", p: [{t: "Pokožku ochlazujte studenou vodou, nebo na ní položte mokré ručníky."}]},
		{k: "step", p: [{t: "Dávejte pít velké množství vody, nebo ovocných šťáv."}]}
	],
	aid_hypothermia: [
		{k: "title", t: "Podchlazení (studené tělo)"},
		{k: "description", t: "Chvění chladem, ospalost, vyčerpání až ztráta vědomí. Studená, bledá kůže. Pomalý puls, slabý srdeční tep."},
		{k: "image", i: "aid014"},
		{k: "step", p: [{t: "Jděte na teplé místo/ místnost."}]},
		{k: "step", p: [{t: "Volejte záchrannou službu."}]},
		{k: "step", p: [{t: "Zvyšujte tělesnou teplotu postiženého zakrytím a vzájemným tělesným kontaktem oběti a zachránce."}]},
		{k: "step", p: [{t: "Svlékněte postiženému mokrý oděv a oblečte mu zahřáté oblečení. Zakryjte ho pokrývkami nebo jiným materiálem. Zakryjte mu hlavu."}]},
		{k: "step", p: [{t: "Dávejte pít horký čaj, polévku nebo vodu. Nepodávejte alkohol. Udržujte postiženého v bdělém stavu."}]},
		{k: "image", i: "aid039"},
		{k: "image", i: "aid040"},
		{k: "step", p: [{t: "Do příjezdu záchranné služby kontrolujte stav oběti. Pokud ztratí vědomí, zahajte ihned resuscitaci:"}]},
		{k: "step", p: [{t: "A - Bezvědomí s dýcháním.", h: "#aid_unconsciouswithbreath"}]},
		{k: "step", p: [{t: "B - Bezvědomí bez dýchání.", h: "#aid_unconsciouswithoutbreath"}]}
	],
	aid_icerescue: [
		{k: "title", t: "Záchrana z ledu"},
		{k: "description", t: "Věnujte pozornost vlastní bezpečnosti. Nebezpečí: Utonutí, podchlazení."},
		{k: "step", p: [{t: "Požádejte okolní osoby o pomoc. Volejte záchrannou službu."}]},
		{k: "step", p: [{t: "Zachraňujte s pomocí žebříku, prkna, nebo tyče. Váha musí být rozložena rovnoměrně."}]},
		{k: "step", p: [{t: "Plazte se opatrně po břiše společně s podporou (pokud je to možné, přivažte se k pevnému bodu) s tyčí, nebo podobným nástrojem."}]},
		{k: "image", i: "aid041"},
		{k: "step", p: [{t: "Dosáhněte k postiženému tyčí, nebo podobným nástrojem (ne rukou) a povzbuzujte ho ať se jí chytí a táhněte ho ven."}]},
		{k: "step", p: [{t: "Plazte se zpět ke břehu."}]},
		{k: "step", p: [{t: "Poskytujte první pomoc."}]},
		{k: "step", p: [{t: "Případná sebezáchrana: Je-li led pevný, můžete rozložit svojí váhu na led a vytáhnout se ven. Plazte se po břiše ke břehu. Pokud je led křehký, zkuste kousek po kousku lámat led až ke břehu."}]}
	],
	aid_insectstings: [
		{k: "title", t: "Pobodání hmyzem", i: "aid046"},
		{k: "description", t: "Otok, kožní vyrážka, pocit pálení, slabost, obtížné dýchání, snížená úroveň vědomí, zrychleny srdeční puls."},
		{k: "step", p: [{t: "Žihadlo opatrně vytáhněte (pomocí pinzety). Nevymačkávejte ho, protože byste dostali do rány více jedu."}]},
		{k: "step", p: [{t: "Postižené místo ochlazujte (přiložte studený obklad)."}]},
		{k: "step", p: [{t: "Aby se zpomalilo šíření jedu, měla by se postižená oblast udržovat pod úrovní srdce."}]},
		{k: "step", p: [{t: "Při pobodání v oblasti úst, nebo čelistí: Cucejte zmrzlinu a okolo krku ovažte studený obklad."}]},
		{k: "image", i: "aid046ice"},
		{k: "step", p: [{t: "Při vážných problémech, pozorovatelně obtížné dýchání, nebo snížená úroveň vědomí,volejte ihned záchrannou službu."}]}
	],
	aid_nosebleeding: [
		{k: "title", t: "Krvácení z nosu"},
		{k: "description", t: "Prasknutí malé tepny v nose."},
		{k: "step", p: [{t: "Posaďte postiženého a lehce ho nahněte dopředu. Hlavu má držet zpříma."}]},
		{k: "step", p: [{t: "Postiženého nepokládejte, protože při zvýšené poloze hlavy nad úrovní srdce se krvácení zpomaluje."}]},
		{k: "step", p: [{t: "Na krk přiložte chladivý materiál (mokrou látku)."}]},
		{k: "step", p: [{t: "Stiskněte prsty nos a držte ho dokud krvácení neustane (asi 10 min.)."}]},
		{k: "step", p: [{t: "Potom nos nenamáhejte (nesmrkejte)."}]},
		{k: "step", p: [{t: "Pokud je problém vážný a krvácení nelze zastavit, volejte pohotovostního lékaře."}]}
	],
	aid_poisining: [
		{k: "title", t: "Otrava", i: "aid052"},
		{k: "description", t: "Zmatenost, halucinace, rozšířené zornice, horečka, křeče. Bezvědomí."},
		{k: "step", p: [{t: "Protijed podávejte pouze v případě součinnosti s vyškoleným zdravotníkem."}]},
		{k: "image", i: "aid056"},
		{k: "step", p: [{t: "Nepodávejte nápoje. Nevyvolávejte zvracení."}]},
		{k: "step", p: [{t: "Volejte záchranou službu, sdělte jim druh jedu."}]},
		{k: "step", p: [{t: "Uschovejte zbytek jedu a zvratků."}]},
		{k: "image", i: "aid054a"},
		{k: "step", p: [{t: "Je-li oběť při vědomí a dýchá: "}, {t: "uložte jí do stabilizované polohy", h: "#aid_recoveryposition"}, {t: ". Do příjezdu záchranné služby kontrolujte stav oběti."}]},
		{k: "step", p: [{t: "Když oběť nedýchá: "}, {t: "Okamžitě zahajte resuscitaci", h: "#aid_resuscitation"}, {t: ". Předtím ale odstraňte z úst oběti případné zvratky.    "}]}
	],
	aid_recoveryposition: [
		{k: "title", t: "Stabilizovaná poloha"},
		{k: "step", p: [{t: "Položte postiženého na záda a natáhněte mu nohy. Klekněte si vedle něho."}]},
		{k: "step", p: [{t: "Paži která je blíže u vás natáhněte v pravém úhlu k tělu."}]},
		{k: "step", p: [{t: "Vzdálenější paži natáhněte přes hrudník a horní stranu ruky položte na tvář."}]},
		{k: "image", i: "aid008"},
		{k: "step", p: [{t: "Uchopte vzdálenější koleno a přetáhněte ho na svou stranu a položte ho na zem. Nohu ohněte do pravého úhlu. Ruku oběti udržujte pod její tváří."}]},
		{k: "step", p: [{t: "Ujistěte se, že dýchací cesty jsou volné."}]},
		{k: "step", p: [{t: "Mírně otevřete ústa postiženého a otočte hlavu na stranu tak, aby mohly vytékat případné zvratky. Kontrolujte dýchání."}]},
		{k: "image", i: "aid009"},
		{k: "step", p: [{t: "Do příjezdu záchranné služby kontrolujte stav oběti."}]},
		{k: "description", t: "Stabilizovaná poloha pro děti:"},
		{k: "image", i: "aid028"}
	],
	aid_resuscitation: [
		{k: "title", t: "Resuscitace"},
		{k: "subsection", t: "# Srdeční masáž"},
		{k: "step", p: [{t: "Položte postiženého na záda. Klekněte si vedle něj."}]},
		{k: "step", p: [{t: "Obnažte hrudník."}]},
		{k: "step", p: [{t: "Položte dlaň ruky do středu hrudníku (přímo na hrudní kost)."}]},
		{k: "image", i: "aid013"},
		{k: "step", p: [{t: "Na hřbet přiložené ruky položte dlaň své druhé ruky."}]},
		{k: "step", p: [{t: "Natáhněte paže v loktech."}]},
		{k: "image", i: "aid003"},
		{k: "step", p: [{t: "Stlačte hrudník oběti o 5 cm dolů (síla vychází z horní části těla) a uvolněte tlak."}]},
		{k: "step", p: [{t: "Proveďte sérii 30 rychlých a silných stlačení!"}]},
		{k: "subsection", t: "# Umělé dýchání"},
		{k: "step", p: [{t: "Odstraňte jakékoliv cizí předměty z úst a krku. Zakloňte hlavu dozadu."}]},
		{k: "image", i: "aid067"},
		{k: "step", p: [{t: "Stiskněte nos prsty tak, aby byl uzavřen."}]},
		{k: "image", i: "aid010"},
		{k: "step", p: [{t: "Zhluboka se nadechněte a přiložte svá ústa na ústa oběti tak, aby vzduch neunikal."}]},
		{k: "image", i: "aid011"},
		{k: "step", p: [{t: "Proveďte dva vdechy z úst do úst (vdechujte pomalu a zhluboka)."}]},
		{k: "step", p: [{t: "Poté pokračujte v srdeční masáži."}]},
		{k: "description", t: "Do příjezdu záchranné služby opakujte srdeční masáž a dýchání s úst do úst."},
		{k: "image", i: "aid012"},
		{k: "subsection", t: "Resuscitace (děti)"},
		{k: "step", p: [{t: "Použijte pouze dva prsty:"}]},
		{k: "image", i: "aid029"},
		{k: "step", p: [{t: "Nevdechujte příliš silně:"}]},
		{k: "image", i: "aid030"}
	],
	aid_safeguardaccident: [
		{k: "title", t: "Zabezpečení místa nehody"},
		{k: "step", p: [{t: "Zastavte své auto 50 až 100 m za místem nehody (pokud jste na dálnici, nebo rychlostní silnici). Zapněte varovná světla. Oblékněte si výstražnou vestu."}]},
		{k: "step", p: [{t: "Před místo nehody položte výstražný trojúhelník. Pozor: Je-li nehoda v místě zatáčky, dejte trojúhelník před zatáčku!"}]},
		{k: "image", i: "aid111"},
		{k: "step", p: [{t: "Požádejte okolostojící o pomoc."}]},
		{k: "step", p: [{t: "Otevřete dveře auta postiženého nehodou (jsou-li zaklíněny, použijte k jejich vypáčení zvedák automobilu). Vypněte zapalování."}]},
		{k: "step", p: [{t: "Zachraňte oběti nehody: Rozepněte záchranné pasy, posuňte sedačku dozadu. Vysvoboďte oběť z auta pomocí "}, {t: "záchranného úchopu.", h: "#aid_dangerzone"}]},
		{k: "image", i: "aid001"},
		{k: "step", p: [{t: "Volejte záchrannou službu."}]},
		{k: "step", p: [{t: "Pokračujte poskytováním první pomoci."}]}
	],
	aid_shock: [
		{k: "title", t: "Šok"},
		{k: "description", t: "Potíže krevního oběhu v důsledku nedostatečného zásobování těla kyslíkem."},
		{k: "description", t: "Příčina: Ztráta tekutin, snížení objemu krve."},
		{k: "description", t: "Příznaky: Bledost, studená kůže, studený pot, úzkost."},
		{k: "step", p: [{t: "Odstraňte příčiny šoku (např. zastavte ztrátu tekutin, obvažte zranění)!"}]},
		{k: "step", p: [{t: "Položte zraněnou osobu na přikrývku a nadzdvihněte jí nohy. Uklidňujte jí."}]},
		{k: "image", i: "aid078"},
		{k: "step", p: [{t: "Volejte záchrannou službu."}]},
		{k: "step", p: [{t: "Nastanou-li dýchací potíže nebo bezvědomí, zahajte "}, {t: "resuscitaci", h: "#aid_resuscitation"}, {t: "."}]}
	],
	aid_skullfracture: [
		{k: "title", t: "Zlomenina lebky"},
		{k: "description", t: "Mírné krvácení z nosu, úst, nebo uší. Často otevřené poranění lebky."},
		{k: "step", p: [{t: "Udržujte volné dýchací cesty."}]},
		{k: "step", p: [{t: "Je-li při vědomí: Posaďte poraněného s hlavou ohnutou dopředu. Vyvarujte se dalších pohybů s obětí!"}]},
		{k: "step", p: [{t: "Je-li v bezvědomí: "}, {t: "Uložte oběť do stabilizované polohy", h: "#aid_recoveryposition"}, {t: " (netlačte na ránu na hlavě)."}]},
		{k: "step", p: [{t: "Volejte záchrannou službu."}]},
		{k: "step", p: [{t: "Přiložte obvaz hlavy."}]},
		{k: "step", p: [{t: "Nastanou-li dýchací potíže nebo bezvědomí, zahajte "}, {t: "resuscitaci", h: "#aid_resuscitation"}, {t: ".\n    "}]}
	],
	aid_snakebite: [
		{k: "title", t: "Hadí uštknutí", i: "aid051"},
		{k: "description", t: "Bodné poranění o průměru hřebíku, silné bolesti, otok, fialové zbarvení. Poruchy krevního oběhu, nebezpečí šoku."},
		{k: "step", p: [{t: "Stabilizujte poraněnou část těla."}]},
		{k: "step", p: [{t: "Okolo místa uštknutí přiložte chladivý materiál."}]},
		{k: "step", p: [{t: "Podnikněte opatření proti šoku."}]},
		{k: "step", p: [{t: "Volejte záchrannou službu."}]}
	],
	aid_sos: [
		{k: "title", t: "SOS"},
		{k: "step", p: [{t: "Signál: 3x krátce, 3x dlouze, 3x krátce"}]},
		{k: "step", p: [{t: "Opticky (blikač nebo baterka), nebo akusticky (signální píšťala, klepání)."}]}
	],
	aid_sprain: [
		{k: "title", t: "Vymknutí a přetažení vazů"},
		{k: "description", t: "Bolest, otok (modřina), ztráta funkce kloubu, deformace končetiny."},
		{k: "step", p: [{t: "Položte poraněnou část těla do polohy, co nejpohodlnější pro postiženého."}]},
		{k: "step", p: [{t: "Ochlazujte poranění (použijte sáček s ledem)."}]},
		{k: "step", p: [{t: "Pokud je to možně, umístěte poraněnou část do vyvýšené polohy."}]},
		{k: "step", p: [{t: "Jděte do nemocnice, nebo zavolejte pohotovostního lékaře."}]}
	],
	aid_stroke: [
		{k: "title", t: "Mozková mrtvice"},
		{k: "description", t: "Náhlý pocit ochrnutí nebo znecitlivění (tváře, paže, noha), poruchy srozumitelnosti mluvy, potíže s viděním, střídání vědomí s bezvědomím, silná bolest hlavy. Problém s dýcháním a polykáním. Ztráta kontroly nad močovým měchýřem a střevy."},
		{k: "image", i: "aid059"},
		{k: "step", p: [{t: "Volejte záchrannou službu!"}]},
		{k: "step", p: [{t: "Uvolněte těsný oděv, nepodávejte léky, nebo nápoje."}]},
		{k: "step", p: [{t: "Postiženého pohodlně položte. Uklidňujte ho."}]},
		{k: "step", p: [{t: "Kontrolujte stav vědomí a dýchání."}]},
		{k: "step", p: [{t: "Při potížích s dýcháním nebo vědomím zahajte ihned "}, {t: "resuscitaci", h: "#aid_resuscitation"}, {t: "."}]}
	],
	aid_suffocation: [
		{k: "title", t: "Udušení (Dušení)"},
		{k: "description", t: "Nedostatečné zásobování kyslíkem. Uzavřená průdušnice. Nebezpečí: Zástava dechu."},
		{k: "description", t: "Příznaky: Sípavé zvuky dýchání, stimulace kašle, zkrácený dech, změna barvy kůže."},
		{k: "image", i: "aid066"},
		{k: "step", p: [{t: "Okamžitě jednejte! Nechejte postiženého silně kašlat."}]},
		{k: "step", p: [{t: "Udeřte silně dlaní ruky mezi lopatky (dítě položte na předloktí hlavou dolů)."}]},
		{k: "image", i: "aid068"},
		{k: "image", i: "aid031"},
		{k: "step", p: [{t: "Není-li úspěch: Postavte se za osobu, ruce dejte okolo pasu a lehce jí nakloňte dopředu."}]},
		{k: "step", p: [{t: "Sevřete pěst, položte jí do výše břicha oběti a uchopte jí druhou rukou."}]},
		{k: "image", i: "aid069"},
		{k: "step", p: [{t: "Při sevření použijte obě ruce k provedení prudkého stlačení břicha směrem dovnitř a nahoru (jako kdybyste chtěli osobu zvednout)."}]},
		{k: "step", p: [{t: "Opakujte to 5 krát! Dýchací cesty by se měly uvolnit od cizího předmětu."}]},
		{k: "step", p: [{t: "Volejte záchrannou službu."}]},
		{k: "step", p: [{t: "Pokud tato metoda nemá napoprvé úspěch, provádějte jí až do příjezdu záchranné služby."}]}
	],
	aid_sunburn: [
		{k: "title", t: "Spáleniny od slunce"},
		{k: "step", p: [{t: "Dostaňte postiženého z přímého slunečního svitu. Vyvarujte se dalšího pobytu na slunci."}]},
		{k: "step", p: [{t: "Pijte hodně vody aby se zastavila dehydratace."}]},
		{k: "step", p: [{t: "Má-li postižený vážné spáleniny (puchýře, zčervenání pokožky, bolest) vyhledejte lékařskou pomoc."}]},
		{k: "step", p: [{t: "Je-li kůže jen lehce červená, může být ochlazována mokrým obkladem.. Použijte mléko, nebo gel používaný po opalování."}]}
	],
	aid_sunstroke: [
		{k: "title", t: "Tepelný úpal"},
		{k: "description", t: "Horký, červený obličej, studená kůže, nevolnost, bolest hlavy, závratě. Podráždění mozkových plen."},
		{k: "image", i: "aid035"},
		{k: "step", p: [{t: "Jděte na chladné místo (do stínu) a zvedněte horní polovinu těla postiženého nahoru."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Ochlazujte hlavu mokrými pokrývkami."}]},
		{k: "step", p: [{t: "Volejte záchrannou službu. Provádějte kontrolu dýchání."}]},
		{k: "step", p: [{t: "Je-li postižený při vědomi: Pokud to je možné, podávejte studené nápoje."}]},
		{k: "step", p: [{t: "Nastane-li zástava dechu, zahajte umělé dýchání."}]},
		{k: "step", p: [{t: "Provádějte umělé dýchání.", h: "#aid_apnoea"}]},
		{k: "image", i: "aid036"}
	],
	aid_unconsciouswithbreath: [
		{k: "title", t: "Bezvědomí s dýcháním"},
		{k: "description", t: "Není odezva na hlasité oslovení nebo zatřesení s postiženým. Postižený dýchá."},
		{k: "image", i: "aid057"},
		{k: "step", p: [{t: "Jsou-li poblíž lidé požádejte je o pomoc."}]},
		{k: "step", p: [{t: "Uložte postiženého do stabilizované polohy", h: "#aid_recoveryposition"}, {t: ". Otevřete mu ústa a hlavu dejte do takové polohy, aby mohly odtékat zvratky."}]},
		{k: "image", i: "aid008"},
		{k: "image", i: "aid009"},
		{k: "step", p: [{t: "Volejte záchrannou službu."}]}
	],
	aid_unconsciouswithoutbreath: [
		{k: "title", t: "Bezvědomí bez dýchání"},
		{k: "step", p: [{t: "Postižený nereaguje na podněty, nedýchá."}]},
		{k: "image", i: "aid057"},
		{k: "step", p: [{t: "Zahajte resuscitaci.", h: "#aid_resuscitation"}]}
	],
	aid_vomiting: [
		{k: "title", t: "Zvracení"},
		{k: "description", t: "Nastává z nevolnosti. Samovolné vyprazdňování žaludku. Příčiny: infekce, otravy, žaludeční vřed, léky, zkažené jídlo."},
		{k: "image", i: "aid054"},
		{k: "step", p: [{t: "Nebezpečí pro krevní oběh z důvodu dehydratace a ztráty solí."}]},
		{k: "step", p: [{t: "Podávejte tekutiny (čaj, vodu)."}]},
		{k: "step", p: [{t: "Pokud jsou vážné potíže, krvavé nebo neustávající zvracení, volejte záchrannou službu."}]}
	]
};
var langContinents=[
	{i: "Africa", t: "Afrika"},
	{i: "Asia", t: "Asie"},
	{i: "Europe", t: "Evropa"},
	{i: "Southamerica", t: "Jižní Amerika"},
	{i: "Oceania", t: "Oceánie"},
	{i: "Northamerica", t: "Severní a Střední Amerika"}
];
var langCountries=[
	{i: "afghanistan", t: "Afghánistán"},
	{i: "albania", t: "Albánie"},
	{i: "algeria", t: "Alžírsko"},
	{i: "andorra", t: "Andorra"},
	{i: "angola", t: "Angola"},
	{i: "antiguaandbarbuda", t: "Antigua a Barbuda"},
	{i: "argentina", t: "Argentina"},
	{i: "armenia", t: "Arménie"},
	{i: "australia", t: "Austrálie"},
	{i: "azerbaijan", t: "Azerbajdžán"},
	{i: "bahamas", t: "Bahamy"},
	{i: "bahrain", t: "Bahrain"},
	{i: "bangladesh", t: "Bangladéš"},
	{i: "barbados", t: "Barbados"},
	{i: "belgium", t: "Belgie"},
	{i: "belize", t: "Belize"},
	{i: "belarus", t: "Bělorusko"},
	{i: "benin", t: "Benin"},
	{i: "bhutan", t: "Bhútán"},
	{i: "bolivia", t: "Bolívie"},
	{i: "bosniaandherzegovina", t: "Bosna a Hercegovina"},
	{i: "botswana", t: "Botswana"},
	{i: "brazil", t: "Brazílie"},
	{i: "brunei", t: "Brunei"},
	{i: "bulgaria", t: "Bulharsko"},
	{i: "burundi", t: "Burundi"},
	{i: "chad", t: "Čad"},
	{i: "montenegro", t: "Černá Hora"},
	{i: "czechrepublic", t: "Česká Republika"},
	{i: "chile", t: "Chile"},
	{i: "croatia", t: "Chorvatsko"},
	{i: "china", t: "Čína"},
	{i: "denmark", t: "Dánsko"},
	{i: "dominica", t: "Dominika"},
	{i: "dominicanrepublic", t: "Dominikánská republika"},
	{i: "djibouti", t: "Džibuti"},
	{i: "egypt", t: "Egypt"},
	{i: "ecuador", t: "Ekvádor"},
	{i: "eritrea", t: "Eritrea"},
	{i: "estonia", t: "Estonsko"},
	{i: "ethiopia", t: "Etiopie"},
	{i: "fiji", t: "Fidži"},
	{i: "philippines", t: "Filipíny"},
	{i: "finland", t: "Finsko"},
	{i: "france", t: "Francie"},
	{i: "gabon", t: "Gabun"},
	{i: "gambia", t: "Gambie"},
	{i: "ghana", t: "Ghana"},
	{i: "grenada", t: "Grenada"},
	{i: "greenland", t: "Grónsko"},
	{i: "georgia", t: "Gruzie"},
	{i: "guatemala", t: "Guatemala"},
	{i: "guinea", t: "Guinea"},
	{i: "guinea-bissau", t: "Guinea-Bissau"},
	{i: "guyana", t: "Guyana"},
	{i: "haiti", t: "Haiti"},
	{i: "honduras", t: "Honduras"},
	{i: "hongkong", t: "Hong Kong"},
	{i: "burkinafaso", t: "Horní Volta"},
	{i: "india", t: "Indie"},
	{i: "indonesia", t: "Indonésie"},
	{i: "iraq", t: "Irák"},
	{i: "iran", t: "Írán"},
	{i: "ireland", t: "Irsko"},
	{i: "iceland", t: "Island"},
	{i: "italy", t: "Itálie"},
	{i: "israel", t: "Izrael"},
	{i: "jamaica", t: "Jamajka"},
	{i: "japan", t: "Japonsko"},
	{i: "yemen", t: "Jemen"},
	{i: "southafrica", t: "Jižní Afrika"},
	{i: "southkorea", t: "Jižní Korea (Korejská Republika)"},
	{i: "jordan", t: "Jordán"},
	{i: "caymanislands", t: "Kajmanské ostrovy"},
	{i: "cambodia", t: "Kambodža"},
	{i: "cameroon", t: "Kamerun"},
	{i: "canada", t: "Kanada"},
	{i: "qatar", t: "Katar"},
	{i: "kazakhstan", t: "Kazachstán"},
	{i: "kenya", t: "Keni"},
	{i: "kiribati", t: "Kiribati"},
	{i: "colombia", t: "Kolumbie"},
	{i: "comoros", t: "Komory"},
	{i: "congodemocraticrepublic", t: "Kongo (demokratická republika)"},
	{i: "congorepublic", t: "Kongo (republika)"},
	{i: "kosovo", t: "Kosovo"},
	{i: "costarica", t: "Kostarika"},
	{i: "cuba", t: "Kuba"},
	{i: "kurdistan", t: "Kurdistán"},
	{i: "kuwait", t: "Kuvajt"},
	{i: "cyprus", t: "Kypr"},
	{i: "kyrgyzstan", t: "Kyrgistán"},
	{i: "laos", t: "Laos"},
	{i: "lesotho", t: "Lesotho"},
	{i: "lebanon", t: "Libanon"},
	{i: "liberia", t: "Libérie"},
	{i: "libya", t: "Libye"},
	{i: "liechtenstein", t: "Lichtenjstensko"},
	{i: "lithuania", t: "Litva"},
	{i: "latvia", t: "Lotyšsko"},
	{i: "luxembourg", t: "Lucembursko"},
	{i: "macau", t: "Macao"},
	{i: "madagascar", t: "Madagaskar"},
	{i: "hungary", t: "Maďarsko"},
	{i: "macedonia", t: "Makedonie"},
	{i: "malaysia", t: "Malajsie"},
	{i: "malawi", t: "Malawi"},
	{i: "maldives", t: "Maledivy"},
	{i: "mali", t: "Mali"},
	{i: "malta", t: "Malta"},
	{i: "morocco", t: "Maroko"},
	{i: "marshallislands", t: "Marshallovy ostrovy"},
	{i: "mauritania", t: "Mauritánie"},
	{i: "mauritius", t: "Mauritius"},
	{i: "mayotte", t: "Mayotte"},
	{i: "mexico", t: "Mexiko"},
	{i: "micronesia", t: "Mikronésie"},
	{i: "moldova", t: "Moldavsko"},
	{i: "monaco", t: "Monako"},
	{i: "mongolia", t: "Mongolsko"},
	{i: "mozambique", t: "Mosambik"},
	{i: "myanmar", t: "Myanmar"},
	{i: "capeverde", t: "Mys Verde"},
	{i: "namibia", t: "Namibie"},
	{i: "nauru", t: "Nauru"},
	{i: "germany", t: "Německo"},
	{i: "nepal", t: "Nepál"},
	{i: "niger", t: "Niger"},
	{i: "nigeria", t: "Nigérie"},
	{i: "nicaragua", t: "Nikaragua"},
	{i: "netherlands", t: "Nizozemsko"},
	{i: "norway", t: "Norsko"},
	{i: "newzealand", t: "Nový Zéland"},
	{i: "oman", t: "Omán"},
	{i: "pakistan", t: "Pákistán"},
	{i: "palau", t: "Palau"},
	{i: "panama", t: "Panama"},
	{i: "papuanewguinea", t: "Papua a Nová Guinea"},
	{i: "paraguay", t: "Paraguay"},
	{i: "peru", t: "Peru"},
	{i: "ivorycoast", t: "Pobřeží Slonoviny"},
	{i: "poland", t: "Polsko"},
	{i: "portugal", t: "Portugalsko"},
	{i: "austria", t: "Rakousko"},
	{i: "greece", t: "Řecko"},
	{i: "reunion", t: "Reunion"},
	{i: "equatorialguinea", t: "Rovníková Guinea"},
	{i: "romania", t: "Rumunsko"},
	{i: "russia", t: "Rusko"},
	{i: "rwanda", t: "Rwanda"},
	{i: "sahrawiarabdemocraticrepublic", t: "Sahrawi Arab Democratic Republic"},
	{i: "stlucia", t: "Saint Pierre a Miquelon"},
	{i: "solomonislands", t: "Šalomounovy Ostrovy"},
	{i: "elsalvador", t: "Salvador"},
	{i: "samoa", t: "Samoa"},
	{i: "sanmarino", t: "San Marino"},
	{i: "saotomeandprincipe", t: "Sao Tomé a Principe"},
	{i: "saudiarabia", t: "Saudská Arábie"},
	{i: "senegal", t: "Senegal"},
	{i: "northkorea", t: "Severní Korea"},
	{i: "seychelles", t: "Seychely"},
	{i: "sierraleone", t: "Sierra Leone"},
	{i: "singapore", t: "Singapur"},
	{i: "slovakia", t: "Slovensko"},
	{i: "slovenia", t: "Slovinsko"},
	{i: "somalia", t: "Somálsko"},
	{i: "spain", t: "Španělsko"},
	{i: "unitedarabemirates", t: "Spojené Arabské Emiráty"},
	{i: "unitedstatesofamerica", t: "Spojené Státy Americké"},
	{i: "serbia", t: "Srbsko"},
	{i: "srilanka", t: "Srí Lanka"},
	{i: "centralafricanrepublic", t: "Středoafrická republika"},
	{i: "sudan", t: "Súdán"},
	{i: "suriname", t: "Surinam"},
	{i: "stkittsandnevis", t: "Svatá Lucie"},
	{i: "saintpierreandmiquelon", t: "Svatý Kryštof a Nevis"},
	{i: "stvincentandgrenadines", t: "Svatý Vincent a Grenadiny"},
	{i: "swaziland", t: "Svazijsko"},
	{i: "sweden", t: "Švédsko"},
	{i: "switzerland", t: "Švýcarsko"},
	{i: "syria", t: "Sýrie"},
	{i: "tajikistan", t: "Tádžikistán"},
	{i: "taiwan", t: "Taiwan"},
	{i: "tanzania", t: "Tanzánie"},
	{i: "thailand", t: "Thajsko"},
	{i: "togo", t: "Togo"},
	{i: "tonga", t: "Tonga"},
	{i: "trinidadandtobago", t: "Trinidad a Tobago"},
	{i: "tunisia", t: "Tunisko"},
	{i: "turkey", t: "Turecko"},
	{i: "turkmenistan", t: "Turkmenistán"},
	{i: "tuvalu", t: "Tuvalu"},
	{i: "uganda", t: "Uganda"},
	{i: "ukraine", t: "Ukrajina"},
	{i: "uruguay", t: "Uruguay"},
	{i: "uzbekistan", t: "Uzbekistán"},
	{i: "vanuatu", t: "Vanuatu"},
	{i: "vaticancity", t: "Vatikán"},
	{i: "unitedkingdom", t: "Velká Británie"},
	{i: "venezuela", t: "Venezuela"},
	{i: "vietnam", t: "Vietnam"},
	{i: "easttimor", t: "Východní Timor"},
	{i: "zambia", t: "Zambie"},
	{i: "zimbabwe", t: "Zimbabwe"}
];
