//:Primo Soccorso
// Generated file, do not edit
var langTexts={
	title: "Primo Soccorso",
	back: "〈Back〉",
	continent: "〈Continent〉",
	emergency_fire: "〈Fire〉",
	emergency_medical: "〈Medical〉",
	emergency_police: "〈Police〉",
	emergency_cancelcard: "",
	emergency_local: "〈local numbers〉",
	emergency_nosystem: "〈no system〉",
	emergency_radioonly: "〈only radio telephones〉",
	emergency_none: "〈--〉",
	emergency_or: "〈or〉",
	emergency_mobile: "〈mobile〉",
	emergency_tourist: "〈tourists〉"
};
var langMenu=[
	{h: "#aid_disclaimer", t: "# Informazioni legali"},
	{h: "#numbers", t: "# Chiamate di emergenza"},
	{h: "#aid_general", t: "# Condotta generale"},
	{h: "#aid_asthma", t: "Affanno"},
	{h: "#aid_amputation", t: "Amputazione"},
	{h: "#aid_apnoea", t: "Apnea"},
	{h: "#aid_asthma", t: "Asma"},
	{h: "#aid_frostbitemild", t: "Assideramento mite"},
	{h: "#aid_poisining", t: "Avvelenamento"},
	{h: "#aid_bleedinglight", t: "Bleeding luce"},
	{h: "#aid_brainconcussion", t: "Brain commozione cerebrale"},
	{h: "#aid_chemicalburn", t: "Burn chimica"},
	{h: "#aid_burningslight", t: "Burning luce"},
	{h: "#aid_chemicalburneyes", t: "Chemical Burn (Occhi)"},
	{h: "#aid_emergencycall", t: "Chiamata d'emergenza"},
	{h: "#aid_diabeticcoma", t: "Coma diabetico"},
	{h: "#aid_checkbreathing", t: "Controllare respirazione"},
	{h: "#aid_stroke", t: "Corsa"},
	{h: "#aid_diarrhoea", t: "Diarrea"},
	{h: "#aid_recoveryposition", t: "Di recupero posizione"},
	{h: "#aid_apnoea", t: "Di respirazione"},
	{h: "#aid_safeguardaccident", t: "Di salvaguardia degli incidenti"},
	{h: "#aid_sprain", t: "Distorsione di tensione"},
	{h: "#aid_backinjury", t: "Dorso-lombari"},
	{h: "#aid_drowning", t: "Drowning"},
	{h: "#aid_electricityaccident", t: "Energia elettrica di incidenti"},
	{h: "#aid_epilepsy", t: "Epilessia"},
	{h: "#aid_sunburn", t: "Eritema solare"},
	{h: "#aid_fracture", t: "Frattura"},
	{h: "#aid_backinjury", t: "Frattura spinale"},
	{h: "#aid_frostbitesevere", t: "Grave assideramento"},
	{h: "#aid_burningsevere", t: "Grave che brucia"},
	{h: "#aid_heartattack", t: "Heart Attack"},
	{h: "#aid_icerescue", t: "Ice salvataggio"},
	{h: "#aid_safeguardaccident", t: "Incidente stradale"},
	{h: "#aid_unconsciouswithbreath", t: "Incoscienza con la respirazione"},
	{h: "#aid_unconsciouswithoutbreath", t: "Incoscienza senza respiro"},
	{h: "#aid_diabeticcoma", t: "Iperglicemia (zucchero)"},
	{h: "#aid_hyperthermia", t: "Ipertermia (caldo corpo)"},
	{h: "#aid_hypoglycaemia", t: "Ipoglicemia (basso zucchero)"},
	{h: "#aid_hypothermia", t: "Ipotermia (aria fresca corpo)"},
	{h: "#aid_skullfracture", t: "La frattura Cranio'"},
	{h: "#aid_eyeinjury", t: "Lesione"},
	{h: "#aid_insectstings", t: "Morsi di insetto"},
	{h: "#aid_animalbite", t: "Morso degli animali"},
	{h: "#aid_birth", t: "Nascita"},
	{h: "#aid_nosebleeding", t: "Nosebleeding"},
	{h: "#aid_allergic", t: "Reazione allergica"},
	{h: "#aid_resuscitation", t: "Rianimazione"},
	{h: "#aid_bleedingsevere", t: "Sanguinamento grave"},
	{h: "#aid_shock", t: "Shock"},
	{h: "#aid_snakebite", t: "Snakebite"},
	{h: "#aid_suffocation", t: "Soffocamento"},
	{h: "#aid_sos", t: "SOS"},
	{h: "#aid_sunstroke", t: "Sunstroke"},
	{h: "#aid_suffocation", t: "Swallow / Soffocamento"},
	{h: "#aid_resuscitation", t: "Toracico di compressione"},
	{h: "#aid_vomiting", t: "Vomito"},
	{h: "#aid_dangerzone", t: "Zona pericolosa"},
	{h: "tel:112", t: "〈Call Emergency 112〉"}
];
var langSections={
	aid_disclaimer: [
		{k: "title", t: "Informazioni legali"},
		{k: "subsection", t: "Software"},
		{k: "description", t: "Di primo soccorso sul tuo telefonino"},
		{k: "description", t: "Copyright: Kai Kajus Noack"},
		{k: "description", t: "〈Translators: …〉"},
		{k: "description", t: "Licenza: Creative Commons"},
		{k: "image", i: "cc88x31"},
		{k: "description", t: "Questo programma è supposto di dare informazioni sul pronto soccorso. Tuttavia, esso non rappresenta un sostituto a un corso di primo soccorso. E 'invece vi serve il tuo rinfrescante già acquisito conoscenze."},
		{k: "description", t: "〈Illustrations〉 © Med4Teens"},
		{k: "subsection", t: "Disclaimer"},
		{k: "description", t: "Si prega di notare che io non assume alcuna responsabilità per le conseguenze derivanti dall'uso di software."},
		{k: "description", t: "Ogni responsabilità è esclusa!"},
		{k: "description", t: "Utilizzare a proprio rischio e pericolo!"},
		{k: "description", t: "In tutti i casi di emergenza, si prega di cercare un aiuto professionale immediatamente."},
		{k: "subsection", t: "Per salvare una vita è di aver salvato il mondo."}
	],
	aid_general: [
		{k: "title", t: "Condotta generale"},
		{k: "step", p: [{t: "Semper eseguire pronto soccorso. Non è possibile effettuare eventuali errori."}]},
		{k: "step", p: [{t: "Tutto l'attenzione alla propria sicurezza."}]},
		{k: "step", p: [{t: "Esaminare la situazione e garantire l'incidente posto."}]},
		{k: "step", p: [{t: "Chiamata di emergenza, le misure di primo soccorso!"}]},
		{k: "step", p: [{t: "Se ci sono diverse vittime, il trattamento della maggior parte lesa ha la priorità."}]},
		{k: "step", p: [{t: "Semper cercare di calmare la persona in questione. Rimanere calma te!"}]},
		{k: "step", p: [{t: "Se possibile stabilire la sua / lui comodamente. Mai dare alcol, nicotina o uso di sostanze stupefacenti ad una persona."}]}
	],
	aid_allergic: [
		{k: "title", t: "Reazione allergica", i: "aid046"},
		{k: "step", p: [{t: "Telefono per un'ambulanza immediatamente."}]},
		{k: "step", p: [{t: "Provare a calmare il sinistro e lasciarlo stare comodo."}]},
		{k: "step", p: [{t: "Rimuovere questione provocando reazioni allergiche (ad esempio, di un bastone ape) attentamente."}]},
		{k: "step", p: [{t: "Cool colpiti pelle (comprimere bagnato, ghiaccio)."}]},
		{k: "image", i: "aid046ice"},
		{k: "step", p: [{t: "Se il sinistro ha un antidoto, egli dovrebbe utilizzare (aiuto lui)."}]},
		{k: "step", p: [{t: "Monitorare il numero delle vittime fino a condizione ambulanza arriva."}]},
		{k: "step", p: [{t: "Se sinistro perde coscienza o smette di respirare, seguire le istruzioni del caso!"}]},
		{k: "image", i: "aid077"}
	],
	aid_amputation: [
		{k: "title", t: "Amputazione"},
		{k: "description", t: "Amputata parte del corpo può essere RICOSTITUIRLO nuovamente. Obiettivo: Tenere amputata parte raffreddare fino ad arrivare a un ospedale."},
		{k: "step", p: [{t: "Calma la persona, laici lui / lei, e coprire con una coperta."}]},
		{k: "step", p: [{t: "Arrestare il sanguinamento, si veda 'Bleeding (grave)' e 'Shock'."}]},
		{k: "step", p: [{t: "Avvolgere amputata parte in un ambiente pulito e asciutto, e metterla in un sacchetto di plastica impermeabile."}]},
		{k: "step", p: [{t: "Chiudi questa borsa di plastica e metterla in un sacchetto di plastica, che contiene acqua fresca / ghiaccio."}]},
		{k: "step", p: [{t: "Non dare alcool, sigarette o cibo per sinistro (nel caso di un intervento chirurgico con anestesia in ospedale)."}]},
		{k: "step", p: [{t: "Non congelare la amputata parte (solo tenerlo fresco)."}]},
		{k: "step", p: [{t: "Chiamata di emergenza o di unità di pronto soccorso ospedale te."}]}
	],
	aid_animalbite: [
		{k: "title", t: "Morso degli animali", i: "aid047"},
		{k: "description", t: "Attenzione: pericolo di alta di infezione. Risultato potrebbe essere pus, il tetano, la rabbia."},
		{k: "step", p: [{t: "Lavare ferita con acqua calda sapone."}]},
		{k: "image", i: "aid049"},
		{k: "step", p: [{t: "Successivamente l'uso di disinfezione della ferita."}]},
		{k: "step", p: [{t: "Se si ha una forte emorragia, elevare la persona della parte superiore del corpo."}]},
		{k: "step", p: [{t: "Applicare un bendaggio asettico."}]},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Andare a un ospedale o chiamare il medico di emergenza."}]}
	],
	aid_apnoea: [
		{k: "title", t: "Apnea"},
		{k: "description", t: "N. respirazione respiro suoni o movimenti, evidente scolorimento della pelle."},
		{k: "step", p: [{t: "Chiamata di emergenza."}]},
		{k: "step", p: [{t: "Lay sinistro sulla schiena."}]},
		{k: "step", p: [{t: "Tratto in testa al collo. Rimuovere le sostanze di bocca e della gola."}]},
		{k: "image", i: "aid067"},
		{k: "step", p: [{t: "Ala di spingere il naso insieme, in modo che il naso è chiuso."}]},
		{k: "image", i: "aid010"},
		{k: "step", p: [{t: "Fai un respiro profondo e metti la tua bocca sulla bocca del sinistro, che non può perdite d'aria."}]},
		{k: "image", i: "aid011"},
		{k: "step", p: [{t: "Soffio fuori lentamente e completamente."}]},
		{k: "step", p: [{t: "Se senza successo: Non respirare finché arriva ambulanza."}]}
	],
	aid_asthma: [
		{k: "title", t: "Asma"},
		{k: "description", t: "Pesante affanno. Sibilo respiratorio rumore. Ansie."},
		{k: "step", p: [{t: "Calma la persona. Rimanere calma te!"}]},
		{k: "step", p: [{t: "Allentare indumenti."}]},
		{k: "step", p: [{t: "Consentitemi di sinistro e sedersi magra avanti, chiedere a respirare lentamente e profondamente."}]},
		{k: "step", p: [{t: "Se ha un sinistro inhalator, egli dovrebbe utilizzare (aiuto lui). Dopo 5-10 minuti si deve entrare in vigore."}]},
		{k: "image", i: "aid074"},
		{k: "step", p: [{t: "Se non vi è alcun miglioramento: Usa inhalator ogni 5 minuti fino a quando arriva in ambulanza."}]},
		{k: "step", p: [{t: "Chiamata di emergenza."}]},
		{k: "step", p: [{t: "Se appare apnea, inizia con la respirazione."}, {t: "〈+〉", h: "#aid_apnoea"}]}
	],
	aid_backinjury: [
		{k: "title", t: "Dorso-lombari"},
		{k: "description", t: "Dolore alla schiena, intirizzito braccia e gambe."},
		{k: "step", p: [{t: "Non spostare il sinistro!"}]},
		{k: "image", i: "aid064"},
		{k: "step", p: [{t: "Tenere la testa il modo in cui la persona si trova stabile (mantenere il loro capo fermo)"}]},
		{k: "image", i: "aid065"},
		{k: "step", p: [{t: "Stabilizzare il sinistro con rafforza sul lato."}]},
		{k: "step", p: [{t: "Calma la persona."}]},
		{k: "step", p: [{t: "Chiamata di emergenza, segnalare il dorso-lombari."}]}
	],
	aid_birth: [
		{k: "title", t: "Nascita"},
		{k: "description", t: "Deflusso di liquido amniotico. Contrazione dolori verificarsi. Nascita inaspettata."},
		{k: "image", i: "aid025"},
		{k: "step", p: [{t: "Prestare attenzione al rispetto della vita privata e mantenere la calma! - Chiamata di emergenza."}]},
		{k: "step", p: [{t: "Lasciate che la donna incinta nudo la parte inferiore del suo corpo, e sedersi su una sterile underlay con diffusione gambe."}]},
		{k: "step", p: [{t: "Angolo le ginocchia. Tirare verso l'alto il gambe. Posizionare il bacino leggermente verso l'alto. - La nascita è un processo naturale e gestisce la maggior parte senza complicazioni."}]},
		{k: "step", p: [{t: "Calma la donna, sia il suo concentrarsi sulla sua respirazione: Respira attraverso il naso, respirare attraverso la bocca (a velocità normale)."}]},
		{k: "step", p: [{t: "Ritmo delle pressanti: Fai un respiro profondo, essere in possesso di respiro, e premere. Non appena il bambino la testa sembra, il sostegno con il mouse con entrambe le mani."}]},
		{k: "image", i: "aid021"},
		{k: "image", i: "aid022"},
		{k: "step", p: [{t: "Dopo il parto: Tenere il bambino slantly con la testa verso il basso per liberare le vie aeree dal liquido amniotico. (Forse si deve aspirare il liquido fuori dal naso del bambino con la bocca.) Il bambino deve respirare e piangere!"}]},
		{k: "step", p: [{t: "Impegnare il cordone ombelicale 30 cm di distanza dal bambino (può anche essere fatto in ospedale). Coprire la vagina della madre sterile."}]},
		{k: "image", i: "aid023"},
		{k: "step", p: [{t: "Asciutto il bambino e lo tiene caldo. Nota il tempo e guida in ospedale."}]}
	],
	aid_bleedinglight: [
		{k: "title", t: "Bleeding luce", i: "aid082"},
		{k: "description", t: "Obiettivo: Arrestare il sanguinamento."},
		{k: "step", p: [{t: "Non toccare la ferita (pericolo di infezione)."}]},
		{k: "step", p: [{t: "Non trattare con ferita in polvere, salves o spray."}]},
		{k: "step", p: [{t: "Ferita trattamento con materiale sterile e un bendaggio."}]},
		{k: "image", i: "aid098"},
		{k: "step", p: [{t: "Per po 'di sanguinamento un cerotto è spesso sufficiente."}]},
		{k: "step", p: [{t: "Se ferita è larga scala l'uso coprire una ferita e una benda. Non si applicano al bendaggio stretto, come una stasi può portare ad un aumento di sanguinamento."}]},
		{k: "image", i: "aid084"},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Nota: Le ferite della rabbia devono essere lavati con la soluzione di sapone."}]},
		{k: "image", i: "aid049"}
	],
	aid_bleedingsevere: [
		{k: "title", t: "Sanguinamento grave"},
		{k: "description", t: "Spruzzi, e la vivacità di sangue. Pericolo: Starter a causa della perdita di sangue, infezioni, la morte. Obiettivo: Arrestare il sanguinamento."},
		{k: "step", p: [{t: "Rimuovere i vestiti (taglio se necessario) e rivelano ferita."}]},
		{k: "step", p: [{t: "Avvolgere un bendaggio o, se necessario, un indumento con pressione intorno alla ferita."}]},
		{k: "image", i: "aid086"},
		{k: "step", p: [{t: "Esercitare pressioni per almeno 10 min."}]},
		{k: "step", p: [{t: "Se bendaggio è intrisa di sangue, non rimuoverlo. Invece avvolgere un altro bendaggio / indumento intorno ad esso."}]},
		{k: "step", p: [{t: "Conservare la parte colpita (se non rotto) superiore al cuore per ridurre le quantità di pressione sanguigna. Se possibile stabilire sinistro."}]},
		{k: "step", p: [{t: "Se l'emorragia non si ferma, mantenere la pressione sulla ferita, e ha fissato inoltre il punto di pressione sulla ferita: Per un sanguinamento del avambraccio comprimere la parte superiore del braccio (premere vena a lato interno del braccio, a metà del gomito e braccio-buca, utilizzando il dita). Per il dissanguamento della gamba impostare la pressione nel punto inguine (stampa in vena di truffatore inguine, dove conduce su arteria pelvico, utilizzando la tua sfera della mano)."}]},
		{k: "image", i: "aid089"},
		{k: "image", i: "aid092"},
		{k: "step", p: [{t: "Chiamata di emergenza medico immediatamente."}]},
		{k: "step", p: [{t: "Non appena l'emorragia è sotto controllo: Avviare il soffocamento misure."}]},
		{k: "image", i: "aid093"}
	],
	aid_brainconcussion: [
		{k: "title", t: "Brain commozione cerebrale"},
		{k: "description", t: "Mal di testa, nausea, vomito. Visivo. Perdita di coscienza può verificarsi."},
		{k: "image", i: "aid035a"},
		{k: "step", p: [{t: "Stabilire persona interessata."}]},
		{k: "step", p: [{t: "Chiamata di emergenza."}]},
		{k: "description", t: "Se l'emorragia a testa:"},
		{k: "step", p: [{t: "Stabilire sinistro, posizione elevata la testa (sul cuscino)."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Fare ferita-trattamento (uso testa-bendaggio)."}]},
		{k: "step", p: [{t: "Chiamata di emergenza."}]}
	],
	aid_burningslight: [
		{k: "title", t: "Burning luce"},
		{k: "description", t: "Arrossamento della pelle. Lieve gonfiore. Dolore."},
		{k: "step", p: [{t: "Tenere interessato l'area sotto acqua fredda."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Applica bagnato bendaggio liberamente."}]}
	],
	aid_burningsevere: [
		{k: "title", t: "Grave che brucia"},
		{k: "description", t: "Spotted bianco-rosso settori, vesciche. La pelle perde liquido. Deep danni di tessuto. Forte dolore o non dolore (a causa di bruciato nervi)."},
		{k: "image", i: "aid097"},
		{k: "step", p: [{t: "Rimuovere i vestiti, per quanto possibile."}]},
		{k: "step", p: [{t: "Cool bruciato parti del corpo con acqua (circa 15 ° C, 59 ° F) fino a 10 minuti, fino a quando il dolore diminuisce."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Se la combustione è ampia, basta usare panni umidi raffreddare."}]},
		{k: "step", p: [{t: "Chiamata di emergenza."}]},
		{k: "step", p: [{t: "Dopo il raffreddamento fare la ferita trattamento: Utilizzare una medicazione sterile. Non applicare fluidi (senza creme, oli, pomate, ecc.) Non perforare il blister."}]},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Controllo la respirazione e della coscienza della persona fino a quando arriva medico di emergenza."}]}
	],
	aid_checkbreathing: [
		{k: "title", t: "Controllare respirazione"},
		{k: "step", p: [{t: "Controllare la respirazione suoni."}]},
		{k: "step", p: [{t: "Diagnosticare la respirazione in addome superiore (laici tua mano su di esso)."}]},
		{k: "image", i: "aid027"},
		{k: "step", p: [{t: "Senso a respirare il naso e la bocca."}]}
	],
	aid_chemicalburneyes: [
		{k: "title", t: "Chemical Burn (Occhi)"},
		{k: "step", p: [{t: "Chiamata di emergenza, punto di sostanze chimiche."}]},
		{k: "step", p: [{t: "Lavare gli occhi con molta acqua. Copertina occhio sano durante vampate di calore."}]},
		{k: "step", p: [{t: "Portare il getto d'acqua dal punto di vista interiore di vista esterno angolo di occhio. Pulito per almeno 20 minuti sotto acqua."}]},
		{k: "image", i: "aid019"},
		{k: "step", p: [{t: "Chiudere entrambi gli occhi del sinistro e si legano con un panno umido."}]},
		{k: "image", i: "aid020"},
		{k: "step", p: [{t: "Monitor condizione fino a quando arriva ambulanza."}]}
	],
	aid_chemicalburn: [
		{k: "title", t: "Burn chimica"},
		{k: "description", t: "Lesioni dei tessuti."},
		{k: "image", i: "aid095"},
		{k: "step", p: [{t: "Mente auto-protezione!"}]},
		{k: "step", p: [{t: "Agire rapidamente e di lavaggio fino alla località bruciato."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Chiamata di emergenza."}]},
		{k: "step", p: [{t: "Se vi è una sostanza chimica di bruciare la digestione modi bere molta acqua."}]},
		{k: "step", p: [{t: "Non provocare il vomito!"}]}
	],
	aid_dangerzone: [
		{k: "title", t: "Zona pericolosa"},
		{k: "step", p: [{t: "Grip esecuzione: Posizione braccio uno dei feriti di fronte il suo petto, e avere dietro di lui / lei."}]},
		{k: "step", p: [{t: "Metti le mani sotto le spalle dei feriti, prendendola per il braccio angolato."}]},
		{k: "step", p: [{t: "Tirare indietro e portare la persona in sicurezza."}]},
		{k: "image", i: "aid001"},
		{k: "image", i: "aid007"}
	],
	aid_diabeticcoma: [
		{k: "title", t: "Coma diabetico"},
		{k: "description", t: "Livello di zucchero nel sangue è troppo alto (risp. mancanza di insulina)."},
		{k: "description", t: "Sintomi: sete, minzione frequente, nausea, vomito. Respiro odori di frutta / vino."},
		{k: "step", p: [{t: "Chiamata di emergenza."}]},
		{k: "step", p: [{t: "Supporto sinistro (se assicurato diabetica) del trattamento insulinico."}]},
		{k: "image", i: "aid016"},
		{k: "step", p: [{t: "Recupero posizione. (N. ulteriori possibilità per la prima aiutare.)"}, {t: "〈+〉", h: "#aid_recoveryposition"}]},
		{k: "step", p: [{t: "Monitorare la condizione del sinistro fino a quando arriva medico di emergenza."}]}
	],
	aid_diarrhoea: [
		{k: "title", t: "Diarrea"},
		{k: "description", t: "Sickliness di cibo, di infezione o malattia intestinale. Sgabello è diluito, viscido o sanguinoso."},
		{k: "step", p: [{t: "Pericolo per la circolazione a causa della disidratazione e perdita di sale!"}]},
		{k: "step", p: [{t: "Dare liquidi (tè, acqua)."}]},
		{k: "step", p: [{t: "Se vi sono forti disturbi di emergenza chiamare il medico."}]}
	],
	aid_drowning: [
		{k: "title", t: "Drowning"},
		{k: "step", p: [{t: "Chiamata di emergenza. Chiedere alle persone accanto a voi per aiutarvi."}]},
		{k: "image", i: "aid032"},
		{k: "step", p: [{t: "Soccorso persona di acqua!"}]},
		{k: "image", i: "aid033"},
		{k: "image", i: "aid034"},
		{k: "step", p: [{t: "Se il sinistro è di respirazione: Recupero posizione. Tenere lui / lei caldo (copertina). Monitor condizione di emergenza fino a quando arriva medico."}, {t: "〈+〉", h: "#aid_recoveryposition"}]},
		{k: "step", p: [{t: "Se il sinistro non è la respirazione: iniziare immediatamente con la rianimazione! (Emit di acqua dal polmone è inutile.)"}, {t: "〈+〉", h: "#aid_resuscitation"}]}
	],
	aid_electricityaccident: [
		{k: "title", t: "Energia elettrica di incidenti"},
		{k: "step", p: [{t: "In primo luogo interrompere la fornitura di energia elettrica!"}]},
		{k: "image", i: "aid045plug"},
		{k: "image", i: "aid045"},
		{k: "step", p: [{t: "Pericolo: L'incoscienza, apnea."}]},
		{k: "step", p: [{t: "A - L'incoscienza con la respirazione", h: "#aid_unconsciouswithbreath"}]},
		{k: "step", p: [{t: "B - L'incoscienza senza respiro", h: "#aid_unconsciouswithoutbreath"}]},
		{k: "image", i: "aid042"},
		{k: "image", i: "aid043"}
	],
	aid_emergencycall: [
		{k: "title", t: "Chiamata d'emergenza"},
		{k: "step", p: [{t: "112 con il prossimo disponibili telefono (Stati Uniti d'America: 911). Semper possibile e gratuitamente! Non esitate a chiamare un'ambulanza!"}]},
		{k: "step", p: [{t: "Il telefono è necessario fornire le seguenti informazioni:"}]},
		{k: "step", p: [{t: "- Che cosa è accaduto"}]},
		{k: "step", p: [{t: "- Dove (luogo incidente)"}]},
		{k: "step", p: [{t: "- Come molte vittime"}]},
		{k: "step", p: [{t: "- Che tipo di lesioni."}]},
		{k: "step", p: [{t: "Successivamente attendere per ulteriori indagini."}]}
	],
	aid_epilepsy: [
		{k: "title", t: "Epilessia"},
		{k: "description", t: "Del corpo rigido, stretto pugni, pressati mandibola, spasmi nelle arti o del viso. Rolling occhi. Salivazione. Possibile perdita di coscienza."},
		{k: "image", i: "aid058"},
		{k: "step", p: [{t: "Non tenere il sinistro o danno al loro movimento."}]},
		{k: "step", p: [{t: "Lay è verificato il sinistro su un morbido base (cuscino), rimuovere gli oggetti vicino a prevenire auto-lesioni."}]},
		{k: "step", p: [{t: "Calmati è verificato il sinistro. Allentare abbigliamento, la libertà di fornire respiro."}]},
		{k: "step", p: [{t: "Se vomits sinistro, girare la testa al lato vomito che possono esaurire."}]},
		{k: "step", p: [{t: "Tenere Airways chiaro. Pericolo di inghiottire la lingua."}]},
		{k: "step", p: [{t: "Posizione di ripristino di chiamata di emergenza. Continuare a monitorare la condizione del sinistro."}, {t: "〈+〉", h: "#aid_recoveryposition"}]},
		{k: "step", p: [{t: "Tenere altre persone a distanza."}]}
	],
	aid_eyeinjury: [
		{k: "title", t: "Lesione"},
		{k: "step", p: [{t: "Lascia oggetto negli occhi di sinistro, non rimuoverlo."}]},
		{k: "step", p: [{t: "Tenere gli occhi immobile al fine di evitare ulteriori danni. Non toccare l'occhio."}]},
		{k: "step", p: [{t: "Se occhio è il sanguinamento, coprire con un comprimere o una garza sterile."}]},
		{k: "image", i: "aid020"},
		{k: "step", p: [{t: "Raffreddare l'occhio con un tampone imbevuto di freddo (riduce il gonfiore, sanguinamento si arresta più veloce)."}]},
		{k: "step", p: [{t: "Chiamata di emergenza o di guidare in ospedale da lei."}]}
	],
	aid_fracture: [
		{k: "title", t: "Frattura"},
		{k: "description", t: "Sintomi: Innaturale movability posizione e di ossa. Deformazione. Doloroso movimento, sensibile al tocco."},
		{k: "image", i: "aid104"},
		{k: "step", p: [{t: "Evitare movimenti!"}]},
		{k: "step", p: [{t: "Chiamata di emergenza."}]},
		{k: "step", p: [{t: "Immobilizzare l'osso fratturato, vale a dire rafforzare il materiale osseo intorno ermeticamente. Tenere la posizione del tessuto osseo."}]},
		{k: "image", i: "aid107"},
		{k: "step", p: [{t: "Se la frattura è aperta, coprire la ferita sterili."}]},
		{k: "image", i: "aid106"}
	],
	aid_frostbitemild: [
		{k: "title", t: "Assideramento mite"},
		{k: "description", t: "Pallore, gonfiore. Pericolo per la fornitura di sangue."},
		{k: "step", p: [{t: "Portare sinistro in una zona calda."}]},
		{k: "step", p: [{t: "Uscire dal freddo, togliere i vestiti a freddo, secco persona."}]},
		{k: "step", p: [{t: "Warm up con acqua tiepida e con il calore del corpo del soccorritore."}]},
		{k: "step", p: [{t: "Lascia la bevanda calda (tè). Niente alcool!"}]},
		{k: "image", i: "aid040"}
	],
	aid_frostbitesevere: [
		{k: "title", t: "Grave assideramento"},
		{k: "description", t: "Freddo rigido della pelle, grigio-bianco, vesciche, tessuto muore fuori. Pericolo per la fornitura di sangue!"},
		{k: "image", i: "aid096"},
		{k: "step", p: [{t: "Vai alla zona calda."}]},
		{k: "step", p: [{t: "Ferita trattamento / copertura."}]},
		{k: "step", p: [{t: "Dare una bevanda zuccherata."}]},
		{k: "step", p: [{t: "Non strofinare caldo è verificato il sinistro!"}]},
		{k: "step", p: [{t: "Chiamata di emergenza."}]}
	],
	aid_heartattack: [
		{k: "title", t: "Heart Attack"},
		{k: "description", t: "Pesante, più di 5 minuti della durata di pressione e il dolore nel petto, in particolare irradia tra le braccia / spalle. Ansia, pallore, sudorazione fredda. Eventualmente, nausea, mancanza di respiro."},
		{k: "image", i: "aid076"},
		{k: "image", i: "aid083"},
		{k: "step", p: [{t: "Chiamata di emergenza! Sottolineare il presunto attacco di cuore."}]},
		{k: "step", p: [{t: "Posizionare la parte superiore del corpo elevata. Allentare indumenti stretti. Non somministrare farmaci o bevande."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Talk calmingly alla persona interessata."}]},
		{k: "step", p: [{t: "Controllo della coscienza e la respirazione."}]},
		{k: "step", p: [{t: "Dare l'aspirina, se disponibile."}]},
		{k: "step", p: [{t: "Se il soggetto si inconscio iniziare con la rianimazione."}, {t: "〈+〉", h: "#aid_resuscitation"}]}
	],
	aid_hypoglycaemia: [
		{k: "title", t: "Ipoglicemia (basso zucchero)"},
		{k: "description", t: "Livello di zucchero nel sangue è inferiore al valore minimo (a causa di un sovradosaggio di insulina o non sufficiente assunzione di cibo)."},
		{k: "description", t: "Sintomi: pallore, nervosismo, la fame, brividi, sudore."},
		{k: "image", i: "aid018"},
		{k: "step", p: [{t: "Assicurarsi che la persona è un diabetico (guardare per un diabetico badge)."}]},
		{k: "step", p: [{t: "Chiamata di emergenza."}]},
		{k: "step", p: [{t: "Dare una bevanda zuccherata e destrosio / glucosio (se non ci sono problemi nella deglutizione)."}]},
		{k: "image", i: "aid017"},
		{k: "step", p: [{t: "Se il soggetto è cosciente e la respirazione: Recupero posizione. Monitorare la respirazione della persona. Se appare apnea, con inizio dando respiro."}, {t: "〈+〉", h: "#aid_recoveryposition"}]},
		{k: "step", p: [{t: "Se non vi è respirazione, è possibile mettere un grumo di zucchero in un sacchetto la guancia, spingere al di fuori contro di essa."}]}
	],
	aid_hyperthermia: [
		{k: "title", t: "Ipertermia (caldo corpo)"},
		{k: "description", t: "Sete, debolezza, disorientamento, nausea, confusione, forte sudorazione, pelle calda."},
		{k: "image", i: "aid035"},
		{k: "step", p: [{t: "Chiamata di emergenza."}]},
		{k: "step", p: [{t: "Trova un luogo fresco ombreggiato (camera con aria condizionata preferibile)."}]},
		{k: "step", p: [{t: "Stabilire persona, elevare il livello delle gambe. Allentare indumenti."}]},
		{k: "image", i: "aid078"},
		{k: "step", p: [{t: "Raffreddare la pelle con molta acqua o laici a freddo asciugamani."}]},
		{k: "step", p: [{t: "Dare molta acqua o succhi di frutta da bere."}]}
	],
	aid_hypothermia: [
		{k: "title", t: "Ipotermia (aria fresca corpo)"},
		{k: "description", t: "Brivido freddo, sonnolenza, stanchezza, fino alla perdita di coscienza. Cole pallido pelle. Polso lento, debole battito cardiaco."},
		{k: "image", i: "aid014"},
		{k: "step", p: [{t: "Vai a uno spazio caldo / stanza."}]},
		{k: "step", p: [{t: "Chiamata di emergenza."}]},
		{k: "step", p: [{t: "Stop impatto del freddo. Aumento della temperatura corporea (copertina e del corpo a corpo a contatto)."}]},
		{k: "step", p: [{t: "Rimuovere i vestiti bagnati e messo in vestiti caldi. Metti nel copre. Coprire la testa."}]},
		{k: "step", p: [{t: "Dare il tè caldo, minestra o acqua calda da bere. Niente alcool! Tenere persona sveglio."}]},
		{k: "image", i: "aid039"},
		{k: "image", i: "aid040"},
		{k: "step", p: [{t: "Monitorare il numero delle vittime condizione di emergenza fino a quando arriva medico. Se il soggetto si incoscienza, avviare la rianimazione:"}]},
		{k: "step", p: [{t: "A - L'incoscienza con la respirazione", h: "#aid_unconsciouswithbreath"}]},
		{k: "step", p: [{t: "B - L'incoscienza senza respiro", h: "#aid_unconsciouswithoutbreath"}]}
	],
	aid_icerescue: [
		{k: "title", t: "Ice salvataggio"},
		{k: "description", t: "Prestare attenzione alla propria sicurezza. Pericolo: Drowning, ipotermia."},
		{k: "step", p: [{t: "Salvataggio tramite scala a pioli, bordo o bar. Peso deve essere distribuito diffusa."}]},
		{k: "step", p: [{t: "Chiedere ad altri per aiutare le persone. Consentitemi di chiamare un ambulanza d'emergenza."}]},
		{k: "step", p: [{t: "Scansione attentamente sul tuo ventre (se possibile cordata up) con lo strumento per la violazione."}]},
		{k: "image", i: "aid041"},
		{k: "step", p: [{t: "Mano è verificato il sinistro a distanza lo strumento (non la tua mano!) E tirare fuori lui."}]},
		{k: "step", p: [{t: "Scansione indietro Torna alla Brink."}]},
		{k: "step", p: [{t: "Misure di pronto soccorso."}]},
		{k: "step", p: [{t: "Auto-salvataggio possibile: se il ghiaccio è solido si può distribuire il suo peso sul ghiaccio e tirare fuori te. Scansione piatto sul tuo ventre al baratro. Se il ghiaccio è fragile, provare a rompere il ghiaccio pezzo per pezzo fino al baratro."}]}
	],
	aid_insectstings: [
		{k: "title", t: "Morsi di insetto", i: "aid046"},
		{k: "description", t: "Gonfiore, rash cutaneo, sensazione di bruciore, debolezza, difficoltà respiratoria, riduzione della coscienza, tachicardia."},
		{k: "step", p: [{t: "Rimuovere attentamente Stringer (con un tweezer). Non strizzare la stinger in quanto ciò potrebbe iniettare più veleno."}]},
		{k: "step", p: [{t: "Cool posto in questione (si applica a freddo comprimere)."}]},
		{k: "step", p: [{t: "Zona in questione dovrebbero essere tenuti inferiore al cuore di rallentare la circolazione del veleno."}]},
		{k: "step", p: [{t: "Se cucire in bocca-mascella-zona: Suck gelati, e applicare un freddo comprimere nei pressi di gola."}]},
		{k: "image", i: "aid046ice"},
		{k: "step", p: [{t: "Se si verificano gravi problemi chiamare un'ambulanza."}]}
	],
	aid_nosebleeding: [
		{k: "title", t: "Nosebleeding"},
		{k: "description", t: "Bursted piccola arteria di punta del naso."},
		{k: "step", p: [{t: "Siediti sanguinamento persona, magra leggermente in avanti. Tenere testa diritta."}]},
		{k: "step", p: [{t: "Non posizionare la persona piatta, in qualità di capo oltre l'altezza del cuore rallenta il sanguinamento."}]},
		{k: "step", p: [{t: "Fredda collo busta."}]},
		{k: "step", p: [{t: "Pizzico narici insieme fino a quando si arresta il sanguinamento (per 10 min)."}]},
		{k: "step", p: [{t: "Successivamente non ceppo il naso (non snorting)."}]},
		{k: "step", p: [{t: "Se si verificano gravi problemi di sanguinamento o non può essere arrestato, chiamata di emergenza medico."}]}
	],
	aid_poisining: [
		{k: "title", t: "Avvelenamento", i: "aid052"},
		{k: "description", t: "Confusione, allucinazioni, grandi allievi, febbre, crampi. Incoscienza."},
		{k: "step", p: [{t: "Antidoti solo se sono accompagnati da un medico addestrato."}]},
		{k: "image", i: "aid056"},
		{k: "step", p: [{t: "Non somministrare bevande. Non provocare il vomito."}]},
		{k: "step", p: [{t: "Chiamata di emergenza sottolineare l'avvelenamento!"}]},
		{k: "step", p: [{t: "Salvaguardia resti di veleno e il vomito!"}]},
		{k: "image", i: "aid054a"},
		{k: "step", p: [{t: "Se il sinistro è cosciente e la respirazione: Recupero posizione. Monitor condizione di emergenza fino a quando arriva medico."}, {t: "〈+〉", h: "#aid_recoveryposition"}]},
		{k: "step", p: [{t: "Se il sinistro non è la respirazione: iniziare immediatamente con la rianimazione! Libera bocca da vomitare prima."}, {t: "〈+〉", h: "#aid_resuscitation"}]}
	],
	aid_recoveryposition: [
		{k: "title", t: "Di recupero posizione"},
		{k: "step", p: [{t: "Lay sinistro per il suo / la sua schiena, raddrizzare le gambe. Ginocchio in giù accanto."}]},
		{k: "step", p: [{t: "Luogo braccio più vicino a voi in un angolo destro al corpo."}]},
		{k: "step", p: [{t: "Tirare il braccio più lontano da te in tutto il torace e il luogo del dorso della mano contro la guancia."}]},
		{k: "image", i: "aid008"},
		{k: "step", p: [{t: "Aggiudicati la misura ginocchio, tirare al vostro fianco, e laici che sul terreno. Posizione la gamba destra in un angolo. Tenere sinistro la mano sulla guancia della persona."}]},
		{k: "step", p: [{t: "Assicurarsi che le vie aeree sono libere."}]},
		{k: "step", p: [{t: "Aprire leggermente la bocca, e la posizione della testa in questo modo che può esaurire vomito. Controllare la respirazione."}]},
		{k: "image", i: "aid009"},
		{k: "step", p: [{t: "Controllo sinistro della condizione di emergenza fino a quando il medico arriva."}]},
		{k: "description", t: "〈Recovery position for babies:〉"},
		{k: "image", i: "aid028"}
	],
	aid_resuscitation: [
		{k: "title", t: "Rianimazione"},
		{k: "subsection", t: "# Cuore Massaggi"},
		{k: "step", p: [{t: "Lay sinistro sulla schiena. Inginocchiarsi accanto a persona."}]},
		{k: "step", p: [{t: "Nudo il petto."}]},
		{k: "step", p: [{t: "Luogo balla una mano al centro del torace (poco più di sterno)."}]},
		{k: "image", i: "aid013"},
		{k: "step", p: [{t: "Luogo altro canto balla sul dorso della mano che è già in posizione."}]},
		{k: "step", p: [{t: "Estrusione le braccia e gomiti."}]},
		{k: "image", i: "aid003"},
		{k: "step", p: [{t: "Premere 5 cm di profondità nella persona del torace (potenza proviene da parte superiore del corpo) e liberazione."}]},
		{k: "step", p: [{t: "Push-30 volte in una riga breve e fortemente!"}]},
		{k: "subsection", t: "# Di respirazione"},
		{k: "step", p: [{t: "Tratto in testa al collo. Rimuovere le sostanze di bocca e della gola."}]},
		{k: "image", i: "aid067"},
		{k: "step", p: [{t: "Spingere le ali del naso insieme, in modo che il naso è chiuso."}]},
		{k: "image", i: "aid010"},
		{k: "step", p: [{t: "Fai un respiro profondo e metti la tua bocca sulla bocca del sinistro, che non può perdite d'aria."}]},
		{k: "image", i: "aid011"},
		{k: "step", p: [{t: "Non bocca-a-bocca-respirazione due volte (soffio fuori lentamente e completamente)."}]},
		{k: "step", p: [{t: "Successivamente, fare di nuovo centro massaggi."}]},
		{k: "description", t: "Ripetere il cuore massaggio respirazione bocca-emergenza fino a quando il medico arriva."},
		{k: "image", i: "aid012"},
		{k: "subsection", t: "〈Resuscitation (Baby)〉"},
		{k: "step", p: [{t: "〈Only use two fingers:〉"}]},
		{k: "image", i: "aid029"},
		{k: "step", p: [{t: "〈Do not breath too strong:〉"}]},
		{k: "image", i: "aid030"}
	],
	aid_safeguardaccident: [
		{k: "title", t: "Di salvaguardia degli incidenti"},
		{k: "step", p: [{t: "Stop tua auto 50-100 m dietro l'incidente sito (se siete su una strada o di un paese su strada). Accendere le luci di avvertimento. Immessi sul giubbotto ad alta visibilità."}]},
		{k: "step", p: [{t: "Posizionare il triangolo di avvertimento prima che l'incidente sito. Attenzione: Se incidente si trova in una posizione curva triangolo di avvertimento prima della curva!"}]},
		{k: "image", i: "aid111"},
		{k: "step", p: [{t: "Chiedete altre persone per il loro aiuto."}]},
		{k: "step", p: [{t: "Apri la porta di incidente auto (se uptight, prize aperta utilizzando una macchina jack). Spegnere accensione."}]},
		{k: "step", p: [{t: "Soccorso alle vittime di un sinistro: Unstrap cintura di sicurezza, spostare indietro sedile. Libera il sinistro fuori dalla macchina da presa di salvataggio."}, {t: "〈+〉", h: "#aid_dangerzone"}]},
		{k: "image", i: "aid001"},
		{k: "step", p: [{t: "Chiamata di emergenza."}]},
		{k: "step", p: [{t: "Procedere con misure di pronto soccorso."}]}
	],
	aid_shock: [
		{k: "title", t: "Shock"},
		{k: "description", t: "Disturbi circolatori da poveri di ossigeno nel corpo."},
		{k: "description", t: "Causa: perdita di liquido, ridotto volume di sangue."},
		{k: "description", t: "Sintomi: pallore, pelle fredda, sudorazione fredda, ansia."},
		{k: "step", p: [{t: "Eliminare la causa di shock (ad esempio, interrompere la perdita di liquidi, impegnare la ferita)!"}]},
		{k: "step", p: [{t: "Lay i feriti su una coperta, la posizione delle gambe fino. Calma la persona."}]},
		{k: "image", i: "aid078"},
		{k: "step", p: [{t: "Chiamata di emergenza."}]},
		{k: "step", p: [{t: "Se difficoltà nella respirazione o coscienza, avviare la rianimazione."}, {t: "〈+〉", h: "#aid_resuscitation"}]}
	],
	aid_skullfracture: [
		{k: "title", t: "La frattura Cranio'"},
		{k: "description", t: "Luce di sanguinamenti del naso, della bocca o orecchio. Spesso ferite aperte al cranio."},
		{k: "step", p: [{t: "Mantenere le vie aeree libera."}]},
		{k: "step", p: [{t: "Se cosciente: Lasciate che i feriti sedersi con testa piegato in avanti. Evitare ulteriori movimenti!"}]},
		{k: "step", p: [{t: "Se inconscio: Recupero posizione (nessuna pressione sulla ferita di testa)."}, {t: "〈+〉", h: "#aid_recoveryposition"}]},
		{k: "step", p: [{t: "Chiamata di emergenza."}]},
		{k: "step", p: [{t: "Applica testa bendaggio."}]},
		{k: "step", p: [{t: "Se difficoltà nella respirazione o coscienza, avviare la rianimazione."}, {t: "〈+〉", h: "#aid_resuscitation"}]}
	],
	aid_snakebite: [
		{k: "title", t: "Snakebite", i: "aid051"},
		{k: "description", t: "Punctuate ferita nella dimensione di un pin, gravi dolori, gonfiore, colore viola. Disturbo circolatorio, il pericolo di scossa."},
		{k: "step", p: [{t: "Costante i feriti parte del corpo."}]},
		{k: "step", p: [{t: "Applica freddo buste circa morso ferita."}]},
		{k: "step", p: [{t: "Misure contro la folgorazione."}]},
		{k: "step", p: [{t: "Chiamata di emergenza."}]}
	],
	aid_sos: [
		{k: "title", t: "SOS"},
		{k: "step", p: [{t: "Signal: 3x breve, 3x lungo, 3x breve."}]},
		{k: "step", p: [{t: "Otticamente (luce strobo, torcia elettrica), o acusticamente (segnale di fischietto, bussare)."}]}
	],
	aid_sprain: [
		{k: "title", t: "Distorsione di tensione"},
		{k: "description", t: "Dolore, gonfiore (lividi), perdita di funzione, la deformazione della parte."},
		{k: "step", p: [{t: "Costante la parte lesa del corpo solo nella posizione più comoda per il sinistro."}]},
		{k: "step", p: [{t: "Cool (con ghiaccio)."}]},
		{k: "step", p: [{t: "Se possibile, la posizione di parte lesa elevata."}]},
		{k: "step", p: [{t: "Andare in ospedale o chiamare il medico di emergenza."}]}
	],
	aid_stroke: [
		{k: "title", t: "Corsa"},
		{k: "description", t: "Improvvisa sensazione di intorpidimento o paralisi (viso, braccia, gambe), disordini in lingua comprensione, la visione dei problemi, turbato la coscienza, forte mal di testa. Problemi di respirazione e la deglutizione, perdita di controllo su di vescica e intestino."},
		{k: "image", i: "aid059"},
		{k: "step", p: [{t: "Chiamata di emergenza!"}]},
		{k: "step", p: [{t: "Allentare indumenti stretti, non danno farmaci o bevande."}]},
		{k: "step", p: [{t: "Sit o fissare comodamente persona interessata. Calma lui / lei!"}]},
		{k: "step", p: [{t: "Controllo della coscienza e la respirazione."}]},
		{k: "step", p: [{t: "Se difficoltà nella respirazione o coscienza, avviare la rianimazione."}, {t: "〈+〉", h: "#aid_resuscitation"}]}
	],
	aid_suffocation: [
		{k: "title", t: "Soffocamento"},
		{k: "description", t: "Insufficiente di ossigeno. Trachea chiusa. Pericolo: apnea."},
		{k: "description", t: "Sintomi: sibilo respiratorio rumore, stimolo della tosse, mancanza di respiro, macchie sulla pelle."},
		{k: "image", i: "aid066"},
		{k: "step", p: [{t: "Un'azione immediata! Lasciate che la persona interessata tosse molto forte."}]},
		{k: "step", p: [{t: "Strike fortemente con un piatto a mano sul retro tra le scapole (laici neonati sul tuo avambraccio, con testa in giù)."}]},
		{k: "image", i: "aid068"},
		{k: "image", i: "aid031"},
		{k: "step", p: [{t: "Se senza successo: Stand dietro persona, di armi nei pressi di vita, inchinarsi leggermente in avanti."}]},
		{k: "step", p: [{t: "Stringere il tuo pugno, in posizione di altezza della persona stomaco, e portarlo con l'altra mano."}]},
		{k: "image", i: "aid069"},
		{k: "step", p: [{t: "In abbraccio utilizzare entrambe le mani per dare un duro colpo allo stomaco direzione verso l'alto (come si tenta di sollevare la persona)."}]},
		{k: "step", p: [{t: "Ripetere questa operazione fino a 5 volte! Airways dovrebbe ottenere gratuitamente da oggetto."}]},
		{k: "step", p: [{t: "Chiamata di emergenza."}]},
		{k: "step", p: [{t: "Se la prima misura di aiuto non riesce a mantenere farlo fino a quando arriva medico di emergenza."}]}
	],
	aid_sunburn: [
		{k: "title", t: "Eritema solare"},
		{k: "step", p: [{t: "Rimuovere la persona interessata dalla luce diretta del sole. Evitare ulteriori sole."}]},
		{k: "step", p: [{t: "Bere molta acqua per impedire la disidratazione."}]},
		{k: "step", p: [{t: "Se vi è un grave bruciare domenica (blister, arrossamento, dolore), consultare un medico."}]},
		{k: "step", p: [{t: "Se la pelle è solo leggermente rosso, può essere raffreddato con buste umido. Utilizzare dopo domenica lozione o gel."}]}
	],
	aid_sunstroke: [
		{k: "title", t: "Sunstroke"},
		{k: "description", t: "Rosso testa calda, raffreddare la pelle, la malattia, mal di testa, vertigini. Causa: irritazione della membrana cerebrale."},
		{k: "image", i: "aid035"},
		{k: "step", p: [{t: "Vai a un luogo fresco (ombra) e la posizione della parte superiore del corpo della persona."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Cool con la testa bagnata coperte."}]},
		{k: "step", p: [{t: "Chiamata di emergenza, a mantenere il controllo della respirazione."}]},
		{k: "step", p: [{t: "Se cosciente: bere Lascia raffreddare, se applicabili."}]},
		{k: "step", p: [{t: "Se appare apnea, inizia con la respirazione:"}]},
		{k: "step", p: [{t: "Vai con Breath Dare!", h: "#aid_apnoea"}]},
		{k: "image", i: "aid036"}
	],
	aid_unconsciouswithbreath: [
		{k: "title", t: "Incoscienza con la respirazione"},
		{k: "description", t: "Nessuna reazione a chiedere a gran voce, nessuna risposta a scuotimento. Respirazione non esiste."},
		{k: "image", i: "aid057"},
		{k: "step", p: [{t: "Se ci sono persone accanto a voi per chiedere aiuto."}]},
		{k: "step", p: [{t: "Recupero posizione. Apri la bocca e la posizione di testa in questo modo che può esaurire vomito."}, {t: "〈+〉", h: "#aid_recoveryposition"}]},
		{k: "image", i: "aid008"},
		{k: "image", i: "aid009"},
		{k: "step", p: [{t: "Chiamata di emergenza."}]}
	],
	aid_unconsciouswithoutbreath: [
		{k: "title", t: "Incoscienza senza respiro"},
		{k: "step", p: [{t: "Nessuna reazione di sinistro, non respira."}]},
		{k: "image", i: "aid057"},
		{k: "step", p: [{t: "Avviare la rianimazione."}, {t: "〈+〉", h: "#aid_resuscitation"}]}
	],
	aid_vomiting: [
		{k: "title", t: "Vomito"},
		{k: "description", t: "Nasce dalla nausea. Stomaco si svuota. Cause: infezione, avvelenamento, ulcera, la droga, la cattiva alimentazione, la gravidanza."},
		{k: "image", i: "aid054"},
		{k: "step", p: [{t: "Pericolo per la circolazione a causa della disidratazione e perdita di sale!"}]},
		{k: "step", p: [{t: "Dare liquidi (tè, acqua)."}]},
		{k: "step", p: [{t: "Se vi sono forti disturbi, sanguinosa continuo vomito o chiamare il medico di emergenza."}]}
	]
};
var langContinents=[
	{i: "Africa", t: "〈Africa〉"},
	{i: "Asia", t: "〈Asia〉"},
	{i: "Europe", t: "〈Europe〉"},
	{i: "Northamerica", t: "〈North-/Central-America〉"},
	{i: "Oceania", t: "〈Oceania〉"},
	{i: "Southamerica", t: "〈South-America〉"}
];
var langCountries=[
	{i: "afghanistan", t: "〈Afghanistan〉"},
	{i: "albania", t: "〈Albania〉"},
	{i: "algeria", t: "〈Algeria〉"},
	{i: "andorra", t: "〈Andorra〉"},
	{i: "angola", t: "〈Angola〉"},
	{i: "antiguaandbarbuda", t: "〈Antigua and Barbuda〉"},
	{i: "argentina", t: "〈Argentina〉"},
	{i: "armenia", t: "〈Armenia〉"},
	{i: "australia", t: "〈Australia〉"},
	{i: "austria", t: "〈Austria〉"},
	{i: "azerbaijan", t: "〈Azerbaijan〉"},
	{i: "bahamas", t: "〈Bahamas〉"},
	{i: "bahrain", t: "〈Bahrain〉"},
	{i: "bangladesh", t: "〈Bangladesh〉"},
	{i: "barbados", t: "〈Barbados〉"},
	{i: "belarus", t: "〈Belarus〉"},
	{i: "belgium", t: "〈Belgium〉"},
	{i: "belize", t: "〈Belize〉"},
	{i: "benin", t: "〈Benin〉"},
	{i: "bhutan", t: "〈Bhutan〉"},
	{i: "bolivia", t: "〈Bolivia〉"},
	{i: "bosniaandherzegovina", t: "〈Bosnia and Herzegovina〉"},
	{i: "botswana", t: "〈Botswana〉"},
	{i: "brazil", t: "〈Brazil〉"},
	{i: "brunei", t: "〈Brunei〉"},
	{i: "bulgaria", t: "〈Bulgaria〉"},
	{i: "burkinafaso", t: "〈Burkina Faso〉"},
	{i: "burundi", t: "〈Burundi〉"},
	{i: "cambodia", t: "〈Cambodia〉"},
	{i: "cameroon", t: "〈Cameroon〉"},
	{i: "canada", t: "〈Canada〉"},
	{i: "capeverde", t: "〈Cape Verde〉"},
	{i: "caymanislands", t: "〈Cayman Islands〉"},
	{i: "centralafricanrepublic", t: "〈Central African Republic〉"},
	{i: "chad", t: "〈Chad〉"},
	{i: "chile", t: "〈Chile〉"},
	{i: "china", t: "〈China〉"},
	{i: "colombia", t: "〈Colombia〉"},
	{i: "comoros", t: "〈Comoros〉"},
	{i: "congodemocraticrepublic", t: "〈Congo (Democratic Republic)〉"},
	{i: "congorepublic", t: "〈Congo (Republic)〉"},
	{i: "costarica", t: "〈Costa Rica〉"},
	{i: "croatia", t: "〈Croatia〉"},
	{i: "cuba", t: "〈Cuba〉"},
	{i: "cyprus", t: "〈Cyprus〉"},
	{i: "czechrepublic", t: "〈Czech Republic〉"},
	{i: "denmark", t: "〈Denmark〉"},
	{i: "djibouti", t: "〈Djibouti〉"},
	{i: "dominicanrepublic", t: "〈Dominican Republic〉"},
	{i: "dominica", t: "〈Dominica〉"},
	{i: "easttimor", t: "〈East Timor〉"},
	{i: "ecuador", t: "〈Ecuador〉"},
	{i: "egypt", t: "〈Egypt〉"},
	{i: "elsalvador", t: "〈El Salvador〉"},
	{i: "equatorialguinea", t: "〈Equatorial Guinea〉"},
	{i: "eritrea", t: "〈Eritrea〉"},
	{i: "estonia", t: "〈Estonia〉"},
	{i: "ethiopia", t: "〈Ethiopia〉"},
	{i: "fiji", t: "〈Fiji〉"},
	{i: "finland", t: "〈Finland〉"},
	{i: "france", t: "〈France〉"},
	{i: "gabon", t: "〈Gabon〉"},
	{i: "gambia", t: "〈Gambia〉"},
	{i: "georgia", t: "〈Georgia〉"},
	{i: "germany", t: "〈Germany〉"},
	{i: "ghana", t: "〈Ghana〉"},
	{i: "greece", t: "〈Greece〉"},
	{i: "greenland", t: "〈Greenland〉"},
	{i: "grenada", t: "〈Grenada〉"},
	{i: "guatemala", t: "〈Guatemala〉"},
	{i: "guinea-bissau", t: "〈Guinea-Bissau〉"},
	{i: "guinea", t: "〈Guinea〉"},
	{i: "guyana", t: "〈Guyana〉"},
	{i: "haiti", t: "〈Haiti〉"},
	{i: "honduras", t: "〈Honduras〉"},
	{i: "hongkong", t: "〈Hong Kong〉"},
	{i: "hungary", t: "〈Hungary〉"},
	{i: "iceland", t: "〈Iceland〉"},
	{i: "india", t: "〈India〉"},
	{i: "indonesia", t: "〈Indonesia〉"},
	{i: "iran", t: "〈Iran〉"},
	{i: "iraq", t: "〈Iraq〉"},
	{i: "ireland", t: "〈Ireland〉"},
	{i: "israel", t: "〈Israel〉"},
	{i: "italy", t: "〈Italy〉"},
	{i: "ivorycoast", t: "〈Ivory Coast〉"},
	{i: "jamaica", t: "〈Jamaica〉"},
	{i: "japan", t: "〈Japan〉"},
	{i: "jordan", t: "〈Jordan〉"},
	{i: "kazakhstan", t: "〈Kazakhstan〉"},
	{i: "kenya", t: "〈Kenya〉"},
	{i: "kiribati", t: "〈Kiribati〉"},
	{i: "kosovo", t: "〈Kosovo〉"},
	{i: "kurdistan", t: "〈Kurdistan〉"},
	{i: "kuwait", t: "〈Kuwait〉"},
	{i: "kyrgyzstan", t: "〈Kyrgyzstan〉"},
	{i: "laos", t: "〈Laos〉"},
	{i: "latvia", t: "〈Latvia〉"},
	{i: "lebanon", t: "〈Lebanon〉"},
	{i: "lesotho", t: "〈Lesotho〉"},
	{i: "liberia", t: "〈Liberia〉"},
	{i: "libya", t: "〈Libya〉"},
	{i: "liechtenstein", t: "〈Liechtenstein〉"},
	{i: "lithuania", t: "〈Lithuania〉"},
	{i: "luxembourg", t: "〈Luxembourg〉"},
	{i: "macau", t: "〈Macau〉"},
	{i: "macedonia", t: "〈Macedonia〉"},
	{i: "madagascar", t: "〈Madagascar〉"},
	{i: "malawi", t: "〈Malawi〉"},
	{i: "malaysia", t: "〈Malaysia〉"},
	{i: "maldives", t: "〈Maldives〉"},
	{i: "mali", t: "〈Mali〉"},
	{i: "malta", t: "〈Malta〉"},
	{i: "marshallislands", t: "〈Marshall Islands〉"},
	{i: "mauritania", t: "〈Mauritania〉"},
	{i: "mauritius", t: "〈Mauritius〉"},
	{i: "mayotte", t: "〈Mayotte〉"},
	{i: "mexico", t: "〈Mexico〉"},
	{i: "micronesia", t: "〈Micronesia〉"},
	{i: "moldova", t: "〈Moldova〉"},
	{i: "monaco", t: "〈Monaco〉"},
	{i: "mongolia", t: "〈Mongolia〉"},
	{i: "montenegro", t: "〈Montenegro〉"},
	{i: "morocco", t: "〈Morocco〉"},
	{i: "mozambique", t: "〈Mozambique〉"},
	{i: "myanmar", t: "〈Myanmar〉"},
	{i: "namibia", t: "〈Namibia〉"},
	{i: "nauru", t: "〈Nauru〉"},
	{i: "nepal", t: "〈Nepal〉"},
	{i: "netherlands", t: "〈Netherlands〉"},
	{i: "newzealand", t: "〈New Zealand〉"},
	{i: "nicaragua", t: "〈Nicaragua〉"},
	{i: "nigeria", t: "〈Nigeria〉"},
	{i: "niger", t: "〈Niger〉"},
	{i: "northkorea", t: "〈North Korea〉"},
	{i: "norway", t: "〈Norway〉"},
	{i: "oman", t: "〈Oman〉"},
	{i: "pakistan", t: "〈Pakistan〉"},
	{i: "palau", t: "〈Palau〉"},
	{i: "panama", t: "〈Panama〉"},
	{i: "papuanewguinea", t: "〈Papua New Guinea〉"},
	{i: "paraguay", t: "〈Paraguay〉"},
	{i: "peru", t: "〈Peru〉"},
	{i: "philippines", t: "〈Philippines〉"},
	{i: "poland", t: "〈Poland〉"},
	{i: "portugal", t: "〈Portugal〉"},
	{i: "qatar", t: "〈Qatar〉"},
	{i: "reunion", t: "〈Réunion〉"},
	{i: "romania", t: "〈Romania〉"},
	{i: "russia", t: "〈Russia〉"},
	{i: "rwanda", t: "〈Rwanda〉"},
	{i: "sahrawiarabdemocraticrepublic", t: "〈Sahrawi Arab Democratic Republic〉"},
	{i: "stkittsandnevis", t: "〈Saint Kitts and Nevis〉"},
	{i: "stlucia", t: "〈Saint Lucia〉"},
	{i: "saintpierreandmiquelon", t: "〈Saint Pierre and Miquelon〉"},
	{i: "stvincentandgrenadines", t: "〈Saint Vincent and Grenadines〉"},
	{i: "samoa", t: "〈Samoa〉"},
	{i: "sanmarino", t: "〈San Marino〉"},
	{i: "saotomeandprincipe", t: "〈Sao Tomé and Principe〉"},
	{i: "saudiarabia", t: "〈Saudi Arabia〉"},
	{i: "senegal", t: "〈Senegal〉"},
	{i: "serbia", t: "〈Serbia〉"},
	{i: "seychelles", t: "〈Seychelles〉"},
	{i: "sierraleone", t: "〈Sierra Leone〉"},
	{i: "singapore", t: "〈Singapore〉"},
	{i: "slovakia", t: "〈Slovakia〉"},
	{i: "slovenia", t: "〈Slovenia〉"},
	{i: "solomonislands", t: "〈Solomon Islands〉"},
	{i: "somalia", t: "〈Somalia〉"},
	{i: "southafrica", t: "〈South Africa〉"},
	{i: "southkorea", t: "〈South Korea (Republic Korea)〉"},
	{i: "spain", t: "〈Spain〉"},
	{i: "srilanka", t: "〈Sri Lanka〉"},
	{i: "sudan", t: "〈Sudan〉"},
	{i: "suriname", t: "〈Suriname〉"},
	{i: "swaziland", t: "〈Swaziland〉"},
	{i: "sweden", t: "〈Sweden〉"},
	{i: "switzerland", t: "〈Switzerland〉"},
	{i: "syria", t: "〈Syria〉"},
	{i: "taiwan", t: "〈Taiwan〉"},
	{i: "tajikistan", t: "〈Tajikistan〉"},
	{i: "tanzania", t: "〈Tanzania〉"},
	{i: "thailand", t: "〈Thailand〉"},
	{i: "togo", t: "〈Togo〉"},
	{i: "tonga", t: "〈Tonga〉"},
	{i: "trinidadandtobago", t: "〈Trinidad and Tobago〉"},
	{i: "tunisia", t: "〈Tunisia〉"},
	{i: "turkey", t: "〈Turkey〉"},
	{i: "turkmenistan", t: "〈Turkmenistan〉"},
	{i: "tuvalu", t: "〈Tuvalu〉"},
	{i: "uganda", t: "〈Uganda〉"},
	{i: "ukraine", t: "〈Ukraine〉"},
	{i: "unitedarabemirates", t: "〈United Arab Emirates〉"},
	{i: "unitedkingdom", t: "〈United Kingdom〉"},
	{i: "unitedstatesofamerica", t: "〈United States of America〉"},
	{i: "uruguay", t: "〈Uruguay〉"},
	{i: "uzbekistan", t: "〈Uzbekistan〉"},
	{i: "vanuatu", t: "〈Vanuatu〉"},
	{i: "vaticancity", t: "〈Vatican City〉"},
	{i: "venezuela", t: "〈Venezuela〉"},
	{i: "vietnam", t: "〈Vietnam〉"},
	{i: "yemen", t: "〈Yemen〉"},
	{i: "zambia", t: "〈Zambia〉"},
	{i: "zimbabwe", t: "〈Zimbabwe〉"}
];
