//:Pierwsza pomoc
// Generated file, do not edit
var langTexts={
	title: "Pierwsza pomoc",
	back: "Z powrotem",
	continent: "Kontynent",
	emergency_fire: "Ogień",
	emergency_medical: "Medycyna",
	emergency_police: "Policja",
	emergency_cancelcard: "",
	emergency_local: "Lokalne numery",
	emergency_nosystem: "Bez systemu",
	emergency_radioonly: "Tylko telefony radiowe",
	emergency_none: "--",
	emergency_or: "Lub",
	emergency_mobile: "komórkowy",
	emergency_tourist: "turystów"
};
var langMenu=[
	{h: "#aid_disclaimer", t: "# Odpowiedzialność i informacje"},
	{h: "#numbers", t: "# Numery alarmowe"},
	{h: "#aid_general", t: "# Ogólne postępowania"},
	{h: "#aid_amputation", t: "Amputacja"},
	{h: "#aid_asthma", t: "Astma"},
	{h: "#aid_stroke", t: "Atak"},
	{h: "#aid_heartattack", t: "Atak serca"},
	{h: "#aid_apnoea", t: "Bezdech"},
	{h: "#aid_diarrhoea", t: "Biegunka"},
	{h: "#aid_suffocation", t: "Duszenie"},
	{h: "#aid_asthma", t: "Duszności"},
	{h: "#aid_dangerzone", t: "Grozny obszar (Ratowanie)"},
	{h: "#aid_diabeticcoma", t: "Hiperglikemia (cukier)"},
	{h: "#aid_hyperthermia", t: "Hipertermia (gorące ciało)"},
	{h: "#aid_hypoglycaemia", t: "Hipoglikemia (niski poziom cukru)"},
	{h: "#aid_hypothermia", t: "Hipotermia (schłodzenia ciała)"},
	{h: "#aid_resuscitation", t: "Kompresja klatki piersiowej"},
	{h: "#aid_bleedingsevere", t: "Krwawienie ciężkie"},
	{h: "#aid_bleedinglight", t: "Krwawienie słabe"},
	{h: "#aid_nosebleeding", t: "Krwawienie z nosa"},
	{h: "#aid_birth", t: "Narodziny"},
	{h: "#aid_unconsciouswithbreath", t: "Nieświadomości z oddychaniem"},
	{h: "#aid_emergencycall", t: "Numer alarmowy"},
	{h: "#aid_apnoea", t: "Oddychanie"},
	{h: "#aid_frostbitesevere", t: "Odmrożenie ciężką"},
	{h: "#aid_frostbitemild", t: "Odmrożenie łagodne"},
	{h: "#aid_epilepsy", t: "Padaczka"},
	{h: "#aid_suffocation", t: "Połknięcie/Zadławienie"},
	{h: "#aid_chemicalburn", t: "Poparzenie chemikaliami"},
	{h: "#aid_burningsevere", t: "Poparzenie ciężkie"},
	{h: "#aid_chemicalburneyes", t: "Poparzenie oczu chemikaliami"},
	{h: "#aid_burningslight", t: "Poparzenie  słabe"},
	{h: "#aid_sunburn", t: "Poparzenie słoneczne"},
	{h: "#aid_sunstroke", t: "Porażenie słoneczne"},
	{h: "#aid_recoveryposition", t: "Pozycja bezpieczna"},
	{h: "#aid_resuscitation", t: "Ratowanie z lodu"},
	{h: "#aid_allergic", t: "Reakcje alergiczne"},
	{h: "#aid_resuscitation", t: "Reanimacja"},
	{h: "#aid_sos", t: "SOS"},
	{h: "#aid_checkbreathing", t: "Sprawdź Oddech"},
	{h: "#aid_shock", t: "Szok"},
	{h: "#aid_diabeticcoma", t: "Śpiączką cukrzycową"},
	{h: "#aid_unconsciouswithoutbreath", t: "Świadomości bez oddychania"},
	{h: "#aid_drowning", t: "Tonięcie"},
	{h: "#aid_insectstings", t: "Ugryzienia owadów"},
	{h: "#aid_animalbite", t: "Ugryzienie zwierzęcia"},
	{h: "#aid_snakebite", t: "Ukąszenie wężą"},
	{h: "#aid_backinjury", t: "Urazy kręgosłupa"},
	{h: "#aid_eyeinjury", t: "Uszkodzenie oka"},
	{h: "#aid_brainconcussion", t: "Wstrząs mózgu"},
	{h: "#aid_vomiting", t: "Wymioty"},
	{h: "#aid_safeguardaccident", t: "Wypadek drogowy"},
	{h: "#aid_electricityaccident", t: "Wypadek elektryczny"},
	{h: "#aid_safeguardaccident", t: "Wypadek samochodowy"},
	{h: "#aid_poisining", t: "Zatrucie"},
	{h: "#aid_backinjury", t: "Złamania kręgu rdzeniowego"},
	{h: "#aid_fracture", t: "Złamanie"},
	{h: "#aid_skullfracture", t: "Złamanie czaszki"},
	{h: "#aid_sprain", t: "Zwichnięcia i nadwyrężenia"},
	{h: "tel:112", t: "Volejte záchrannou službu 112"}
];
var langSections={
	aid_disclaimer: [
		{k: "title", t: "Odpowiedzialność i informacje"},
		{k: "subsection", t: "Oprogramowanie"},
		{k: "description", t: "Pierwsza pomoc w twoim telefonie"},
		{k: "description", t: "Prawa autorskie: Kai Kajus Noack"},
		{k: "description", t: "Translator: Robert Moleda"},
		{k: "description", t: "Licencja: Creative Commons"},
		{k: "image", i: "cc88x31"},
		{k: "description", t: "Ten program ma udzielić informacji na temat pierwszej pomocy. Jednakże, nie stanowi on  substytutu dla kursu pierwszej pomocy. Służy on raczej do odświeżenia już zdobytej wiedzy."},
		{k: "description", t: "Ilustracje © Med4Teens"},
		{k: "subsection", t: "Odpowiedzialność"},
		{k: "description", t: "Należy pamiętać, że nie biorę żadnej odpowiedzialności za konsekwencje wynikające z korzystania z oprogramowania."},
		{k: "description", t: "Jakakolwiek odpowiedzialności jest wyłączona!"},
		{k: "description", t: "Korzstanie na własne ryzyko!"},
		{k: "description", t: "We wszystkich sytuacjach kryzysowych należy natychmiast szukać profesjonalnej pomocy."},
		{k: "subsection", t: "Uratuj człowieka a uratujesz świat."}
	],
	aid_general: [
		{k: "title", t: "Ogólne postępowania"},
		{k: "step", p: [{t: "Zawsze udzielaj pierwszej pomocy. Nie można popełnić żadnych błędów."}]},
		{k: "step", p: [{t: "Zawsze zwracaj uwagę na własne bezpieczeństwo."}]},
		{k: "step", p: [{t: "Zbadaj sytuacje i zabezpiecz miejsce wypadku."}]},
		{k: "step", p: [{t: "Dzwoń po pomoc i udzielaj pierwszej pomocy!"}]},
		{k: "step", p: [{t: "Jeśli istnieje kilku poszkodowanych,  najbardziej poszkodowany ma pierwszeństwo."}]},
		{k: "step", p: [{t: "Staraj się zawsze uciszyć osoby poszkodowane i zachowaj sam spokój !"}]},
		{k: "step", p: [{t: "Jeśli to możliwe ułożyć poszkodowanego wygodnie. Nigdy nie dawać alkoholu, nikotyny lub narkotyków osobie poszkodowanej"}]}
	],
	aid_allergic: [
		{k: "title", t: "Reakcje alergiczne", i: "aid046"},
		{k: "step", p: [{t: "Zadzwoinić natychmiast po pogotowie."}]},
		{k: "step", p: [{t: "Staraj się uspokoić poszkodowanego i niech usiądzie wygodnie."}]},
		{k: "step", p: [{t: "Usuń powody uczulenia (np. żądło pszczoły) starannie."}]},
		{k: "step", p: [{t: "Chłodz dotkniętą skórę (mokre kompresy, lód)."}]},
		{k: "image", i: "aid046ice"},
		{k: "step", p: [{t: "Jeśli poszkodowany ma antidotum, powinien go użyć (pomóż)."}]},
		{k: "step", p: [{t: "Monitoruj stan ofiary aż przyjedzie ambulans."}]},
		{k: "step", p: [{t: "Jeśli poszkodowany utracił przytomności lub przestał oddychać, wykonaj następujące instrukcje!"}]},
		{k: "image", i: "aid077"}
	],
	aid_amputation: [
		{k: "title", t: "Amputacja"},
		{k: "description", t: "Amputowana część ciała może zostać przyszyta ponownie. Celem jest chłodzenie części amputowanej do dostarczenia do szpitala"},
		{k: "step", p: [{t: "Uspokuj osobę, połóż ją i osłoń kocem"}]},
		{k: "step", p: [{t: "Zatamuj krwawienie. Zobacz w programie pod krwawienie i szok"}]},
		{k: "step", p: [{t: "Owiń amputowaną część suchą i czystą tkaniną i włóż część do wodoszczelnego worka plastikowego."}]},
		{k: "step", p: [{t: "Zamknij plastikową torbę i włóż ją do kolejnej plastikowej torby zawierającej zimną wodę lub lód"}]},
		{k: "step", p: [{t: "Nie dawaj alkoholu, papierosów lub jedzenia poszkodowanemu, gdy w szpitalu będzie operacja w narkozie"}]},
		{k: "step", p: [{t: "Nie zamrażaj części tylko ją chłodz"}]},
		{k: "step", p: [{t: "Zadzwoń po karetkę lub zawiez sam do szpitala."}]}
	],
	aid_animalbite: [
		{k: "title", t: "Ugryzienie zwierzęcia", i: "aid047"},
		{k: "description", t: "UWAGA: Wysokie zagrożenie zakażenia. Wynikiem może być ropa, tężec, wścieklizna."},
		{k: "step", p: [{t: "Umyć ranę mydłem z ciepłą wodą."}]},
		{k: "image", i: "aid049"},
		{k: "step", p: [{t: "Następnie dezynfekować ranę."}]},
		{k: "step", p: [{t: "Jeśli nie ma silnego krwawienia, unieść tułów osoby ."}]},
		{k: "step", p: [{t: "Stosować aseptyczny bandaż."}]},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Przyjedź do szpitala lub wezwij lekarza pogotowia."}]}
	],
	aid_apnoea: [
		{k: "title", t: "Bezdech"},
		{k: "description", t: "Brak dźwięków oddechu lub ruchów, zauważalne przebarwienia na skórze."},
		{k: "step", p: [{t: "Dzwonić po pomoc."}]},
		{k: "step", p: [{t: "Połóż osobę na plecy."}]},
		{k: "step", p: [{t: "Usuń rzeczy z jamy ustnej i gardła. Wyciągnij głowę i szyie."}]},
		{k: "image", i: "aid067"},
		{k: "step", p: [{t: "Zaciśnij nos."}]},
		{k: "image", i: "aid010"},
		{k: "step", p: [{t: "Weź głęboki wdech i rób usta usta , tak że nie może uciec powietrze."}]},
		{k: "image", i: "aid011"},
		{k: "step", p: [{t: "Oddychaj powoli i pełnie."}]},
		{k: "step", p: [{t: "Jeśli bez powodzenia: kontynuuj tak długo, aż przyjedzie ambulans."}]}
	],
	aid_asthma: [
		{k: "title", t: "Astma"},
		{k: "description", t: "Ciężkie duszności. Świszczący oddech . Niepokojenie się."},
		{k: "step", p: [{t: "Uspokój osobę. Zachowaj sam spokój!"}]},
		{k: "step", p: [{t: "Poluzuj ubranie."}]},
		{k: "step", p: [{t: "Niech osoba siedzi i pochyla się do przodu, poproś o  powolny i głęboki oddech."}]},
		{k: "step", p: [{t: "Jeśli osoba posiada inhalator, powinna go użyć (pomagać jej). Po 5-10 min staje się on skuteczne."}]},
		{k: "image", i: "aid074"},
		{k: "step", p: [{t: "Jeżeli nie ma poprawy: Użyj inhalator co 5 min, aż przybędzie karetka."}]},
		{k: "step", p: [{t: "Dzwoń po pomoc.."}]},
		{k: "step", p: [{t: "Jeśli pojawi się bezdech, zacznij z instrukcjami dla "}, {t: "bezdechu", h: "#aid_apnoea"}, {t: ".\n    "}]}
	],
	aid_backinjury: [
		{k: "title", t: "Urazy kręgosłupa"},
		{k: "description", t: "Bóle pleców, zdrętwiałe ręce i nogi."},
		{k: "step", p: [{t: "Nie poruszaj poszkodowanego!"}]},
		{k: "image", i: "aid064"},
		{k: "step", p: [{t: "Trzymaj głowę w sposób, aby osoba była stabilna (trzymać głowę miejscowo)"}]},
		{k: "image", i: "aid065"},
		{k: "step", p: [{t: "Stabilizację wypadku z wzmacnia na stronie."}]},
		{k: "step", p: [{t: "Spokojna osoba."}]},
		{k: "step", p: [{t: "Dzwonić po pomoc , zwracać uwagę na urazy kręgosłupa."}]}
	],
	aid_birth: [
		{k: "title", t: "Narodziny"},
		{k: "description", t: "Wypływ płynów .Bóle kontrakcyjne . Nieoczekiwane narodziny."},
		{k: "image", i: "aid025"},
		{k: "step", p: [{t: "Zwróć uwagę, aby zachować prywatność i spokój! - Dzwonienie po pomoc."}]},
		{k: "step", p: [{t: "Niech  kobieta w ciąży odsłoni dolną część swojego ciała usiądzie na sterylnym podkładzie z  rozłożonymi nogami."}]},
		{k: "step", p: [{t: "Zgiąć kolana. Wyciągnąć nogi. Biodra lekko w górę. - Narodziny są naturalnym procesem i działają głównie bez komplikacji."}]},
		{k: "step", p: [{t: "Uspokoić kobietę, pozwolic jej skoncentrować się na oddychaniu: wdychać przez nos, wydychać przez usta (w normalnej prędkości)."}]},
		{k: "step", p: [{t: "Rytm naciskania: Weź głęboki oddech, oddech przytrzymaj i naciśnij. Jak tylko pojawi się głowa dziecka, wspierać chwytając je z obydwoma dłoniami."}]},
		{k: "image", i: "aid021"},
		{k: "image", i: "aid022"},
		{k: "step", p: [{t: "Po urodzeniu dziecka: Trzymaj dziecko skosem z głową w dół, aby wyzwolić z dróg oddechowych płynz. (Być może należy wyssać płynu z nosa dziecka przez usta.) Dziecko musi  krzyczeć i oddychać!"}]},
		{k: "step", p: [{t: "Zawiąż  pępowinę 30 cm od dziecka (może być również zrobione w szpitalu). Dbaj o sterylność pochwy matki."}]},
		{k: "image", i: "aid023"},
		{k: "step", p: [{t: "Wysusz dziecko i dbaj o jego ciepło. Zwróć uwagę na czas i jedz do szpitala."}]}
	],
	aid_bleedinglight: [
		{k: "title", t: "Krwawienie słabe", i: "aid082"},
		{k: "description", t: "Cel: Zatrzymaj krwawienie."},
		{k: "step", p: [{t: "Nie należy dotykać rany (niebezpieczeństwo zakażenia)."}]},
		{k: "step", p: [{t: "Nie należy traktować  rany proszkiem, maścią lub sprejem."}]},
		{k: "step", p: [{t: "Osłoń ranę przy pomocy sterylnych materiałów i bandaży."}]},
		{k: "image", i: "aid098"},
		{k: "step", p: [{t: "Na niewielkie krwawienie plaster jest często wystarczający."}]},
		{k: "step", p: [{t: "Jeśli rana jest duża użyj bandaż. Nie zaciskaj  za mocno, bo może to doprowadzić do zwiększonego krwawienia."}]},
		{k: "image", i: "aid084"},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Uwaga: rany wścieklizny muszą być myte w roztworze mydła."}]},
		{k: "image", i: "aid049"}
	],
	aid_bleedingsevere: [
		{k: "title", t: "Krwawienie ciężkie"},
		{k: "description", t: "Rzylewanie, pulsująca krew. Niebezpieczeństwo: gardzieli z powodu utraty krwi, zakażenia, śmierć. Cel: Zatrzymaj krwawienie."},
		{k: "step", p: [{t: "Usuń ubrania (cięcie, jeśli to konieczne) i odsłoń rany."}]},
		{k: "step", p: [{t: "Przykleić plaster lub w razie konieczności, gazę z ciśnieniem wokół rany."}]},
		{k: "image", i: "aid086"},
		{k: "step", p: [{t: "Wywieraj nacisk przez co najmniej 10 min."}]},
		{k: "step", p: [{t: "Jeśli bandaż jest nasączony  krwią, nie należy go usunąć. Zamiast tego owinąć kolejnym bandażem."}]},
		{k: "step", p: [{t: "Umieścić dotknięte kończyny (jeśli nie są złamane) wyżej niż serce w celu zmniejszenia ciśnienia tętniczego krwi. Jeśli to możliwe położyć poszkodowanego."}]},
		{k: "step", p: [{t: "Jeżeli krwawienie nie ustaje, utrzymać presję na ranę, a dodatkowo uciskać w innych miejscach: W przypadku krwawienia  ramienia uciskać górną część (naciśnij żyły na wewnętrznej stronie ramienia, w środku łokcia i dołu ramienia używając swojego palca). W przypadku krwawienia nogi uciskać pachwinę (naciśnij na żyły w pachwinie, gdzie tętnica prowadzi przez kości miednicy, używając swojego nadgarstka)."}]},
		{k: "image", i: "aid089"},
		{k: "image", i: "aid092"},
		{k: "step", p: [{t: "Zadzwoń po lekarza pogotowia natychmiast."}]},
		{k: "step", p: [{t: "Jeżeli krwawienie jest pod kontrolą uruchom środki przeciw krztuszeniu  się"}]},
		{k: "image", i: "aid093"}
	],
	aid_brainconcussion: [
		{k: "title", t: "Wstrząs mózgu"},
		{k: "description", t: "Bóle głowy, nudności, wymioty. Zaburzenia widzenia. Może wystąpić utrata przytomności ."},
		{k: "image", i: "aid035a"},
		{k: "step", p: [{t: "Położyć poszkodowanego."}]},
		{k: "step", p: [{t: "Zadzwonic po pomoc."}]},
		{k: "description", t: "Jeśli krwawi głowa:"},
		{k: "step", p: [{t: "Połóż poszkodowanego z podwyższoną głową (na poduszce)."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Lecz ranę, użyj bandażu."}]},
		{k: "step", p: [{t: "Dzwoń po pomoc"}]}
	],
	aid_burningslight: [
		{k: "title", t: "Poparzenie  słabe"},
		{k: "description", t: "Zaczerwienienie skóry. Łagodne obrzęki. Ból."},
		{k: "step", p: [{t: "Trzymaj skórę pod zimną wodą."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Stosuj mokre i luźne bandaże."}]}
	],
	aid_burningsevere: [
		{k: "title", t: "Poparzenie ciężkie"},
		{k: "description", t: "Biało-czerwone obszary, powstawanie pęcherzy. Skóra traci płyn. Głębokie uszkodzenia tkanek. Silny ból lub bez bólu (ze względu na spalone nerwy)."},
		{k: "image", i: "aid097"},
		{k: "step", p: [{t: "Usuń jak najwięcej ubrań."}]},
		{k: "step", p: [{t: "Chłodz spalone części ciała wodą (około 15 ° C, 59 ° F) do 10 min, aż bólu się zmniejszy."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Jeżeli spalanie jest rozległe, wystarczy użyć mokrej ścierki do ostygnięcia."}]},
		{k: "step", p: [{t: "Dzwoń po pomoc."}]},
		{k: "step", p: [{t: "Po schłodzeniu nie rany leczenia: Za pomocą sterylnego opatrunku. Nie stosować płynów (nie kremy, oliwki, maści itp.)."}]},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Kontroluj oddech i świadomości osoby, aż przybędzie lekarz pogotowia."}]}
	],
	aid_checkbreathing: [
		{k: "title", t: "Sprawdź Oddech"},
		{k: "step", p: [{t: "Sprawdź dzwięk oddechu."}]},
		{k: "step", p: [{t: "Diagnozuj oddychanie w górnej części brzucha (połóż na nim rękę)."}]},
		{k: "image", i: "aid027"},
		{k: "step", p: [{t: "Poczucie oddech z nosa i ust."}]}
	],
	aid_chemicalburneyes: [
		{k: "title", t: "Poparzenie oczu chemikaliami"},
		{k: "step", p: [{t: "Zadzwonic po pomoc, zwrócić uwagę na chemikalia."}]},
		{k: "step", p: [{t: "Wypłucz oko  dużo ilością wody. Osłoń zdrowe oko podczas płukania."}]},
		{k: "step", p: [{t: "Kieruj strumień wody z wewnętrznego kąta oka do zewnętrznego kąta oka. Trzymaj na co najmniej 20 min pod czystą wodą."}]},
		{k: "image", i: "aid019"},
		{k: "step", p: [{t: "Zamknij oczy poszkodowanemu i owiń mokrą szmatką."}]},
		{k: "image", i: "aid020"},
		{k: "step", p: [{t: "Monitor stan, aż przyjedzie ambulans."}]}
	],
	aid_chemicalburn: [
		{k: "title", t: "Poparzenie chemikaliami"},
		{k: "description", t: "Szkody tkanki."},
		{k: "image", i: "aid095"},
		{k: "step", p: [{t: "Pamiętaj o  ochronie osobistej!"}]},
		{k: "step", p: [{t: "Działaj szybko i myj spalone miejsca."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Dzwoń po pomoc."}]},
		{k: "step", p: [{t: "Jeśli jest spalony układ trawienny prubój pić dużo wody."}]},
		{k: "step", p: [{t: "Nie powoduj  wymiotów!"}]}
	],
	aid_dangerzone: [
		{k: "title", t: "Grozny obszar (Ratowanie)"},
		{k: "step", p: [{t: "Wykonanie uchwytu: połóż jedno z ramion pokrzywdzonego na klatce piersiowej i idz za niego."}]},
		{k: "step", p: [{t: "Połóż dłonie na barkach rannego  biorąc ugięte ramię."}]},
		{k: "step", p: [{t: "Odwróć i przenieś osobę do bezpieczeństwa."}]},
		{k: "image", i: "aid001"},
		{k: "image", i: "aid007"}
	],
	aid_diabeticcoma: [
		{k: "title", t: "Śpiączką cukrzycową"},
		{k: "description", t: "Poziom cukru we krwi jest zbyt wysoki (powód brak insuliny)."},
		{k: "description", t: "Symptomy: pragnienie, częste oddawanie moczu, nudności, wymioty. Oddech zapachów owoców / wina."},
		{k: "step", p: [{t: "Wezwanie pogotowia."}]},
		{k: "step", p: [{t: "Pomóc pokrzywdzonemu (o ile potwierdzona cukrzyca), biorąc insulinę."}]},
		{k: "image", i: "aid016"},
		{k: "step", p: [{t: "Odzyskiwanie stanowiska", h: "#aid_recoveryposition"}, {t: ". (Brak dalszych możliwości dla pomagającego.)\n    "}]},
		{k: "step", p: [{t: "Monitorować stan poszkodowanego aż dotrze lekarz."}]}
	],
	aid_diarrhoea: [
		{k: "title", t: "Biegunka"},
		{k: "description", t: "Ckliwość żywności, infekcja jelita lub zaburzenia. Stolec jest rozcieńczony, grząski lub krwawy."},
		{k: "step", p: [{t: "Niebezpieczeństwo cyrkulacji z powodu odwodnienia i utraty soli!"}]},
		{k: "step", p: [{t: "Podać płyny (herbata, woda)."}]},
		{k: "step", p: [{t: "Jeśli istnieją silne zaburzenia zadzwonić po lekarza pogotowia."}]}
	],
	aid_drowning: [
		{k: "title", t: "Tonięcie"},
		{k: "step", p: [{t: "Wezwanie pogotowia. Zapytaj ludzi obok Ciebie o pomoc."}]},
		{k: "image", i: "aid032"},
		{k: "step", p: [{t: "Ratowanie osoby z wody!"}]},
		{k: "image", i: "aid033"},
		{k: "image", i: "aid034"},
		{k: "step", p: [{t: "Jeśli poszkodowany oddycha: "}, {t: "pozycja ratownicza", h: "#aid_recoveryposition"}, {t: ". Trzymaj go ciepłym. Monitoruj stan, aż przyjedzie lekarz pogotowia.\n    "}]},
		{k: "step", p: [{t: "Jeśli poszkodowany oddycha: Natychmiast rozpocząć z "}, {t: "reanimacją", h: "#aid_resuscitation"}, {t: "! (Wypuszczanie wody z płuc jest bezużyteczne.)\n    "}]}
	],
	aid_electricityaccident: [
		{k: "title", t: "Wypadek elektryczny"},
		{k: "step", p: [{t: "Po pierwsze przerwać dostawę energii elektrycznej!"}]},
		{k: "image", i: "aid045plug"},
		{k: "image", i: "aid045"},
		{k: "step", p: [{t: "Niebezpieczeństwo: utrata przytomności, bezdech."}]},
		{k: "step", p: [{t: "A - Oddychający nieprzytomny", h: "#aid_unconsciouswithbreath"}]},
		{k: "step", p: [{t: "B - Nieoddychający nieprzytomny", h: "#aid_unconsciouswithoutbreath"}]},
		{k: "image", i: "aid042"},
		{k: "image", i: "aid043"}
	],
	aid_emergencycall: [
		{k: "title", t: "Numer alarmowy"},
		{k: "step", p: [{t: "Zadzwoń pod 112 z najbliższego telefonu (USA: 911). Zawsze jest to możliwe i za darmo! Nie wahaj się zadzwonić po pogotowie!"}]},
		{k: "step", p: [{t: "W rozmowie należy podać następujące informacje:"}]},
		{k: "step", p: [{t: "- Co się wydarzyło"}]},
		{k: "step", p: [{t: "- Gdzie (miejsce wypadku)"}]},
		{k: "step", p: [{t: "- Ile ofiar"}]},
		{k: "step", p: [{t: "- Jakiego rodzaju urazy."}]},
		{k: "step", p: [{t: "Potem czekać na dalsze postępowanie."}]}
	],
	aid_epilepsy: [
		{k: "title", t: "Padaczka"},
		{k: "description", t: "Sztywne ciało,zaciśnięte pięści,zaciskane szczęki, drganie kończyn lub twarzy. krążące oczy. Ślinienie. Utrata przytomnośći  możliwa."},
		{k: "image", i: "aid058"},
		{k: "step", p: [{t: "Nie trzymaj ofiary i nie zatrzymuj jej ruchów."}]},
		{k: "step", p: [{t: "Połóż ofiarę na miękkiej podstawie (poduszka), usunąć rzeczy aby zapobiec własnej szkodzie."}]},
		{k: "step", p: [{t: "Ucisz ofiarę. Rozluźnij odzież, zapewnij swobodę oddechu."}]},
		{k: "step", p: [{t: "Jeśli ofiara wymiotuje, przekręć głowę na bok by mogła wymiotować."}]},
		{k: "step", p: [{t: "Trzymaj drogi oddechowe wolne. Niebezpieczeństwo połknięcia języka."}]},
		{k: "step", p: [{t: "Odzyskanie pozycji", h: "#aid_recoveryposition"}, {t: ". Zadzwoń po pomoc. Kontynuuj monitorowanie stanu ofiary.\n    "}]},
		{k: "step", p: [{t: "Trzymaj  innych ludzi na odległość."}]}
	],
	aid_eyeinjury: [
		{k: "title", t: "Uszkodzenie oka"},
		{k: "step", p: [{t: "Zostawić objekt w oku, nie należy go usunąć."}]},
		{k: "step", p: [{t: "Unieruchomić oczy, aby uniknąć dalszych urazów. Nie wolno dotykać oczu."}]},
		{k: "step", p: [{t: "Jeżeli oko krwawi, okładaj kompresem lub sterylnym gazikiem."}]},
		{k: "image", i: "aid020"},
		{k: "step", p: [{t: "Chłodz oko  zimnym okładem (zmniejsza obrzęki, krwawienia przestaje szybciej)."}]},
		{k: "step", p: [{t: "Zadzwonić po pomoc lub zawieść samemu do szpitala."}]}
	],
	aid_fracture: [
		{k: "title", t: "Złamanie"},
		{k: "description", t: "Objawy: nienaturalne pozycje kości i ruchy. Deformacja. Bolesny ruch,ból przy dotyku."},
		{k: "image", i: "aid104"},
		{k: "step", p: [{t: "Unikaj ruchów!"}]},
		{k: "step", p: [{t: "Zadzwoń po pomoc."}]},
		{k: "step", p: [{t: "Unieruchamiaj złamaną kość, n.p. owiń materiał szczelnie wokół kości. Zachować pozycję kości."}]},
		{k: "image", i: "aid107"},
		{k: "step", p: [{t: "Jeśli złamanie jest otwarte, pokryj ranę sterylnie."}]},
		{k: "image", i: "aid106"}
	],
	aid_frostbitemild: [
		{k: "title", t: "Odmrożenie łagodne"},
		{k: "description", t: "Bladość, obrzęki. Zagrożenie dla dostawy krwi."},
		{k: "step", p: [{t: "Położyć ofiarę w ciepłym obszarze."}]},
		{k: "step", p: [{t: "Odejdź od zimna, usuń zimne ubrania, osusz osobę."}]},
		{k: "step", p: [{t: "Ocieplaj za pomocą letniej wody i ciepła z ciała o pomocnika."}]},
		{k: "step", p: [{t: "Daj ciepły napój (herbata). Zakaz spożywania alkoholu!"}]},
		{k: "image", i: "aid040"}
	],
	aid_frostbitesevere: [
		{k: "title", t: "Odmrożenie ciężką"},
		{k: "description", t: "Twarda skóra zimna, szaro-biała, pęcherze, tkanka wymiera . Zagrożenie dla dostawy krwi!"},
		{k: "image", i: "aid096"},
		{k: "step", p: [{t: "Przejdź do ciepłego obszaru."}]},
		{k: "step", p: [{t: "Lecz rany ."}]},
		{k: "step", p: [{t: "Daj słodki napój."}]},
		{k: "step", p: [{t: "Nie trzeć ofiary!"}]},
		{k: "step", p: [{t: "Zadzwonić po pomoc."}]}
	],
	aid_heartattack: [
		{k: "title", t: "Atak serca"},
		{k: "description", t: "Ciężki, więcej niż 5 min trwałe ciśnienie i ból w klatce piersiowej, szczególnie promieniujące w ramionach / barkich. Niepokój, bladość, zimne poty. Ewentualnie nudności, duszność."},
		{k: "image", i: "aid076"},
		{k: "image", i: "aid083"},
		{k: "step", p: [{t: "Zadzwonić po pomoc! Zwrócić uwagę na domniemany atak serca."}]},
		{k: "step", p: [{t: "Podwyższyć górną część ciała . Odzież rozluźnić. Nie dać narkotyków lub napojów."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Uspokój osobę."}]},
		{k: "step", p: [{t: "Kontroluj świadomość i oddychanie."}]},
		{k: "step", p: [{t: "Dać aspirynę, jeśli jest dostępna."}]},
		{k: "step", p: [{t: "Jeżeli osoba staje się nieprzytomna, "}, {t: "ratować", h: "#aid_resuscitation"}, {t: ".\n    "}]}
	],
	aid_hypoglycaemia: [
		{k: "title", t: "Hipoglikemia (niski poziom cukru)"},
		{k: "description", t: "Poziom cukru we krwi jest poniżej wartości minimalnej (z powodu przedawkowania insuliny lub nie wystarczającego spożycia żywności)."},
		{k: "description", t: "Objawy: bladość, nerwowość, głód, dreszcze, poty."},
		{k: "image", i: "aid018"},
		{k: "step", p: [{t: "Upewnij się, że dana osoba ma cukrzycę (spójrz na znaczek cukrzycowy)."}]},
		{k: "step", p: [{t: "Dzwoń po pomoc."}]},
		{k: "step", p: [{t: "Daj słodki napój i dekstrozę / glukozę (jeśli nie ma problemów z połykaniem)."}]},
		{k: "image", i: "aid017"},
		{k: "step", p: [{t: "Jeśli osoba jest przytomna i oddycha: "}, {t: "Odzyskanie pozycji", h: "#aid_recoveryposition"}, {t: ". Monitorować oddech danej osoby. Jeśli pojawi się bezdech,ratować.\n    "}]},
		{k: "step", p: [{t: "Jeśli osoba oddycha, możesz umieścić woreczek cukru w ustach i naciskać  z zewnątrz przeciwko niemu."}]}
	],
	aid_hyperthermia: [
		{k: "title", t: "Hipertermia (gorące ciało)"},
		{k: "description", t: "Pragnienie, osłabienie, dezorientacja, nudności, dezorientacja, silne pocenie się, gorąca skóra."},
		{k: "image", i: "aid035"},
		{k: "step", p: [{t: "Dzwoń po pomoc."}]},
		{k: "step", p: [{t: "Znajdź chłodne i zaciemnione miejsce (pokój z klimatyzacja zalecany)."}]},
		{k: "step", p: [{t: "Połóż osobę, podciągać nogi. Poluzuj ubranie."}]},
		{k: "image", i: "aid078"},
		{k: "step", p: [{t: "Chłodz skórę dużą ilością wody lub zimnymi ręczniki."}]},
		{k: "step", p: [{t: "Daj dużo wody lub soków do picia."}]}
	],
	aid_hypothermia: [
		{k: "title", t: "Hipotermia (schłodzenia ciała)"},
		{k: "description", t: "Zimne dreszcze, senność, wyczerpanie aż do utraty przytomności. Zimna i blada skóra. Powolny puls, słabe tętno."},
		{k: "image", i: "aid014"},
		{k: "step", p: [{t: "Przejdź do ciepłego obszaru / pokoju."}]},
		{k: "step", p: [{t: "Wezwij pogotowie."}]},
		{k: "step", p: [{t: "Zatrzymaj dopływ zimna. Celem jest wzrost temperatury ciała (n.p ciepły okład lub kontakt ciało-ciało)."}]},
		{k: "step", p: [{t: "Zdejmij mokre ubranie i daj ciepłe ubrania. Osłon kołdrą i osłaniaj głowę."}]},
		{k: "step", p: [{t: "Daj gorącej herbaty, zupy lub ciepłej wody do picia. Zakaz spożywania alkoholu! Nie daj zasnąć osobie."}]},
		{k: "image", i: "aid039"},
		{k: "image", i: "aid040"},
		{k: "step", p: [{t: "Monitor stan ofiary, aż przyjedzie lekarz pogotowia. Jeśli osoba traci przytomność, ratować:"}]},
		{k: "step", p: [{t: "A - Oddychający nieświadomy", h: "#aid_unconsciouswithbreath"}]},
		{k: "step", p: [{t: "B - Nieoddychający nieświadomy", h: "#aid_unconsciouswithoutbreath"}]}
	],
	aid_icerescue: [
		{k: "title", t: "Ratowanie z lodu"},
		{k: "description", t: "Zwracać uwagę na własne bezpieczeństwo. Niebezpieczeństwo: Tonięcie, Hipotermia."},
		{k: "step", p: [{t: "Poprosić o pomoc innych ludzi. Niech wezwą karetkę."}]},
		{k: "step", p: [{t: ".Ratowanie przy użyciu drabiny, deski lub listwy. Waga musi być rozłożona szeroko powszchni."}]},
		{k: "step", p: [{t: "Czołgać się do przodu leżąc na brzuchu(jeśli to możliwe być przywiązanym liną do słupa)."}]},
		{k: "image", i: "aid041"},
		{k: "step", p: [{t: "Podać ofierze  na odległość narzędzie (nie rękę!) I wyciągnąć ją."}]},
		{k: "step", p: [{t: "Czołgać się do tyłu ."}]},
		{k: "step", p: [{t: "Środki pierwszej pomocy."}]},
		{k: "step", p: [{t: "Ratowanie samemu możliwe: Jeśli lód jest stały można rozłożyć swoją masę i się wyciągnąć. Jeśli lód jest kruchy, spróbuj przełamać kawałek lodu."}]}
	],
	aid_insectstings: [
		{k: "title", t: "Ugryzienia owadów", i: "aid046"},
		{k: "description", t: "Obrzęk, wysypka, uczucie pieczenia, osłabienie, trudności w oddychaniu, zmniejszenie świadomości, tachykardia."},
		{k: "step", p: [{t: "Usuń żądło starannie (pęsetą). Nie wyciskać z żądła, jak mogłoby to wstrzyknąć więcej jadem."}]},
		{k: "step", p: [{t: "Cool zainteresowanych miejscu (stosowanie zimna kompresji)."}]},
		{k: "step", p: [{t: "Zainteresowanych dziedzinie powinny być przechowywane niższe niż serce powoli do obrotu na jad."}]},
		{k: "step", p: [{t: "Jeśli ściegu w ustach-szczęka strefy: Suck lodów, a także zastosowanie kompresji zimno wokół gardła."}]},
		{k: "image", i: "aid046ice"},
		{k: "step", p: [{t: "Jeśli wystąpić poważne problemy wezwać karetkę."}]}
	],
	aid_nosebleeding: [
		{k: "title", t: "Krwawienie z nosa"},
		{k: "description", t: "Pęknięta żyła."},
		{k: "step", p: [{t: "Usiądz i pochyl się nieco do przodu. Trzymaj głowę prosto."}]},
		{k: "step", p: [{t: "Głowa trzymana nad sercem spowalnia krwawienie."}]},
		{k: "step", p: [{t: "Chłodzić szyję."}]},
		{k: "step", p: [{t: "Zaciśnij nozdrza aż zatrzyma się krwawienie (10 min)."}]},
		{k: "step", p: [{t: "Potem nie ruszaj nosa (nie chrapać)."}]},
		{k: "step", p: [{t: "Jeśli występują problemy lub ciężkie krwawienie które nie można zatrzymać, wezwij lekarza pogotowia."}]}
	],
	aid_poisining: [
		{k: "title", t: "Zatrucie", i: "aid052"},
		{k: "description", t: "Omamy, gorączka, skurcze. Nieprzytomności."},
		{k: "step", p: [{t: "Tylko dać antidotum, jeśli towarzyszy wyszkolony lekarz."}]},
		{k: "image", i: "aid056"},
		{k: "step", p: [{t: "Nie dawać napojów. Nie powodować wymiów."}]},
		{k: "step", p: [{t: "Zdwoniąc po pomoc zwrócić uwagę na zatrucie!"}]},
		{k: "step", p: [{t: "Zachować trucizny i wymioty!"}]},
		{k: "image", i: "aid054a"},
		{k: "step", p: [{t: "Jeśli ofiara jest przytomna i oddycha: "}, {t: "Odzyskanie pozycji", h: "#aid_recoveryposition"}, {t: ". Monitorować stan, aż przyjedzie lekarz pogotowia.\n    "}]},
		{k: "step", p: [{t: "Jeśli ofiara nie oddycha: Natychmiast rozpocząć z "}, {t: "reanimacją", h: "#aid_resuscitation"}, {t: "! Opróżnić usta z wymiocin.\n    "}]}
	],
	aid_recoveryposition: [
		{k: "title", t: "Pozycja bezpieczna"},
		{k: "step", p: [{t: "Położyć ofiarę na plecach, wyprostować nogi. Kolana obok."}]},
		{k: "step", p: [{t: "Położyć ramię  pod kątem prostym do ciała."}]},
		{k: "step", p: [{t: "Wyciągnij ramię najdalej od ciebie i od klatki piersiowej i umieść z powrotem pod policzek."}]},
		{k: "image", i: "aid008"},
		{k: "step", p: [{t: "Wyciągnij kolana i połóż je na ziemi.Nogi pod kątem prostym. Trzymać ręce ofiary  pod policzkiem danej osoby."}]},
		{k: "step", p: [{t: "Upewnij się, że drogi oddechowe są wolne."}]},
		{k: "step", p: [{t: "Otwórz usta lekko i przekręć głowę tak, aby ofiara mogła wymiotować . Sprawdź oddech."}]},
		{k: "image", i: "aid009"},
		{k: "step", p: [{t: "Kontroluj  stan ofiary aż przyjedzie  lekarz pogotowia."}]},
		{k: "description", t: "Pozycja bezpieczna dla niemowląt:"},
		{k: "image", i: "aid028"}
	],
	aid_resuscitation: [
		{k: "title", t: "Reanimacja"},
		{k: "subsection", t: "# Masaż serca"},
		{k: "step", p: [{t: "Położyć ofiarę na plecach. Klęczeć obok osoby."}]},
		{k: "step", p: [{t: "Uwolnij klatkę pierśiową."}]},
		{k: "step", p: [{t: "Połóż dłoń na środku klatki piersiowej (nieco ponad mostkiem)."}]},
		{k: "image", i: "aid013"},
		{k: "step", p: [{t: "Połóż drugą na pierwszą dłoń."}]},
		{k: "step", p: [{t: "Wyciągnąć ramiona i nogi."}]},
		{k: "image", i: "aid003"},
		{k: "step", p: [{t: "Naciśnij 5 cm w głąb klatki piersiowej (moc pochodzi z górnej części ciała) i puść."}]},
		{k: "step", p: [{t: "Naciśnij 30 razy z rzędu krótko i zdecydowanie!"}]},
		{k: "subsection", t: "# Oddychanie"},
		{k: "step", p: [{t: "Usuń substancje z jamy ustnej i gardła. Wyciągnij głowę do szyi."}]},
		{k: "image", i: "aid067"},
		{k: "step", p: [{t: "Zaciśnij nos."}]},
		{k: "image", i: "aid010"},
		{k: "step", p: [{t: "Weź głęboki wdech i połóż usta na ustach ofiary aby nie było szczelin ."}]},
		{k: "image", i: "aid011"},
		{k: "step", p: [{t: "Rób usta-usta dwa razy (oddech powoli iw pełni)."}]},
		{k: "step", p: [{t: "Następnie wykonaj ponownie masaż serca."}]},
		{k: "description", t: "Powtórz masaż serca oddychanie i usta-usta do przyjazdu lekarza pogotowia ."},
		{k: "image", i: "aid012"},
		{k: "subsection", t: "Reanimacja (niemowlę)"},
		{k: "step", p: [{t: "Użyj tylko dwóch palców:"}]},
		{k: "image", i: "aid029"},
		{k: "step", p: [{t: "Nie oddychaj za mocno:"}]},
		{k: "image", i: "aid030"}
	],
	aid_safeguardaccident: [
		{k: "title", t: "Wypadek samochodowy"},
		{k: "step", p: [{t: "Zatrzymaj swój samochód 50-100 m za miejscem wypadku (jeśli jesteś na autostradzie lub drodze krajowej). Włącz światła awaryjne. Włóż kamizelkę odblaskową."}]},
		{k: "step", p: [{t: "Postaw trójkąt ostrzegawczy przed wypadkiem . Uwaga: Jeżeli  wypadek jest na zakręcie to postaw trójkąt przed zakrętem!"}]},
		{k: "image", i: "aid111"},
		{k: "step", p: [{t: "Poproś innych ludzi o pomoc."}]},
		{k: "step", p: [{t: "Otwórz drzwi od samochodu (jeśli zaklinowane to otworzyć za pomocą łomu). Wyłącz zapłon."}]},
		{k: "step", p: [{t: "Ratowanie ofiary wypadku: Odepnij pasy bezpieczeństwa, siedzenia przesunąć do tyłu. Wyciągnij za pomocą "}, {t: "ratowniczego uchwytu", h: "#aid_dangerzone"}, {t: ".\n    "}]},
		{k: "image", i: "aid001"},
		{k: "step", p: [{t: "Dzwoń po pomoc."}]},
		{k: "step", p: [{t: "Postępować z pierwszą pomocy."}]}
	],
	aid_shock: [
		{k: "title", t: "Szok"},
		{k: "description", t: "Zaburzenia krążenia przez słabą dostawę tlenu w organizmie."},
		{k: "description", t: "Przyczyna: Utrata płynów, zmniejszona objętość krwi."},
		{k: "description", t: "Objawy: bladość, zimna skór, zimne poty, niepokój."},
		{k: "step", p: [{t: "Wyeliminować przyczyny tego wstrząsu (np. zatrzymanie utraty płynu, wiązania rany!)"}]},
		{k: "step", p: [{t: "Połóż rannego na kocu, do góry nogami. Uspokój osobę."}]},
		{k: "image", i: "aid078"},
		{k: "step", p: [{t: "Dzwoń po pomoc"}]},
		{k: "step", p: [{t: "Jeżeli są trudności w oddychaniu lub utrata świadomości, inicjować "}, {t: "reanimację", h: "#aid_resuscitation"}, {t: ".\n    "}]}
	],
	aid_skullfracture: [
		{k: "title", t: "Złamanie czaszki"},
		{k: "description", t: "Lekkie krwawienia z nosa, jamy ustnej lub ucha. Często otwarte rany na czaszce."},
		{k: "step", p: [{t: "Trzymaj drogi oddechowe otwarte."}]},
		{k: "step", p: [{t: "Jeśli poszkodowany świadomy: Niech  siedzi z głową do ugiętą do przodu. Uniknąć dalszych ruchów!"}]},
		{k: "step", p: [{t: "Jeśli nieprzytomny: "}, {t: "Odzyskanie pozycji", h: "#aid_recoveryposition"}, {t: " (bez nacisku na rany głowy).\n    "}]},
		{k: "step", p: [{t: "Dzwoń po pomoc"}]},
		{k: "step", p: [{t: "Załóż bandaż na głowę."}]},
		{k: "step", p: [{t: "Jeżeli trudności w oddychaniu lub świadomości, inicjować "}, {t: "reanimacje", h: "#aid_resuscitation"}, {t: ".\n    "}]}
	],
	aid_snakebite: [
		{k: "title", t: "Ukąszenie wężą", i: "aid051"},
		{k: "description", t: "Miejscowa rana o wielkości szpilki, ciężkie bóle, obrzęk, kolor purpurowy. Zaburzenia krążenia, zagrożenie napadu eliptycznego."},
		{k: "step", p: [{t: "Usztywnij ranną część ciała."}]},
		{k: "step", p: [{t: "Zastosuj zimny okład wokół rany ."}]},
		{k: "step", p: [{t: "Podać środki przeciwko wstrząsowi"}]},
		{k: "step", p: [{t: "Dzwoń po pomoc."}]}
	],
	aid_sos: [
		{k: "title", t: "SOS"},
		{k: "step", p: [{t: "Sygnał: 3x krótkie, długie 3x, 3x krótkie."}]},
		{k: "step", p: [{t: "Optycznie (sygnał światła, latarki) lub akustycznie (gwizdnięcie, pukanie)."}]}
	],
	aid_sprain: [
		{k: "title", t: "Zwichnięcia i nadwyrężenia"},
		{k: "description", t: "Ból, obrzęk (siniec), utrata funkcji uginania kończyny."},
		{k: "step", p: [{t: "Ułożyć część ciała w najwygodniejszy sposób dla poszkodowanego."}]},
		{k: "step", p: [{t: "Chodzić (za pomocą lodu)."}]},
		{k: "step", p: [{t: "Jeśli to możliwe, unieść część ranną trochę."}]},
		{k: "step", p: [{t: "Przyjedź do szpitala lub zadzwoń po lekarza pogotowia."}]}
	],
	aid_stroke: [
		{k: "title", t: "Atak"},
		{k: "description", t: "Nagłe uczucie drętwienia lub paraliż (twarzy, ramion, nóg), zaburzenia zrozumienia,  problemy wzroku, zakłócenie świadomości, silne bóle głowy. Problemy  z oddychaniem i połykaniem, utrata kontroli nad pęcherzem moczowym i jelitami."},
		{k: "image", i: "aid059"},
		{k: "step", p: [{t: "Dzwonić po pomoc !"}]},
		{k: "step", p: [{t: "Rozluźnić napiętą Odzież, nie dawać narkotyków lub napojów."}]},
		{k: "step", p: [{t: "Położyć lub posadzić osobę komfortowo. Uspokoić!"}]},
		{k: "step", p: [{t: "Kontroluj świadomość i oddychanie."}]},
		{k: "step", p: [{t: "Jeżeli występują trudności w oddychaniu lub świadomości, inicjować "}, {t: "reanimację", h: "#aid_resuscitation"}, {t: ".\n    "}]}
	],
	aid_suffocation: [
		{k: "title", t: "Duszenie"},
		{k: "description", t: "Niedostateczna dostawa tlenu. Tchawica zamknięta. Niebezpieczeństwo: bezdech."},
		{k: "description", t: "Objawy: świszczący oddech , kaszel bodźca, duszność, przebarwienia skóry."},
		{k: "image", i: "aid066"},
		{k: "step", p: [{t: "Natychmiastowe działania! Niech dana osoba kaszle bardzo mocno."}]},
		{k: "step", p: [{t: "Uderzyć  silnie płaską ręką pomiędzy łopatki (Położyć niemowlę na przedramieniu, z głową do dółu)."}]},
		{k: "image", i: "aid068"},
		{k: "image", i: "aid031"},
		{k: "step", p: [{t: "Jeśli bez powodzenia: Stań za osobą, obejmij wokół pasa, uginaj lekko do przodu."}]},
		{k: "step", p: [{t: "Zamknąć pięść, położyć na wysokość żołądka osoby i wziąć drugą ręką  ."}]},
		{k: "image", i: "aid069"},
		{k: "step", p: [{t: "Mocno nacisnąć na brzuch tak jakby się próbowało podnieść osobę"}]},
		{k: "step", p: [{t: "Powtórz tę czynność aż  5 razy! Drogi oddechowe powinny stać się wolne ."}]},
		{k: "step", p: [{t: "Dzwoń po pomoc ."}]},
		{k: "step", p: [{t: "Jeżeli się nie powiedzie za pierwszym razie to kontynuować  aż przybędzie lekarz pogotowia."}]}
	],
	aid_sunburn: [
		{k: "title", t: "Poparzenie słoneczne"},
		{k: "step", p: [{t: "Odciągnąć osobę od słońca i unikać je w przyszłości.i"}]},
		{k: "step", p: [{t: "Pić dużo wody aby zatrzymać odwodnienie."}]},
		{k: "step", p: [{t: "Jeśli istnieje poważne poparzenie słoneczne (pęcherze, zaczerwienienie, ból), zasięgnąć porady lekarza."}]},
		{k: "step", p: [{t: "Jeśli skóra jest tylko lekko czerwona, może być chłodzona mokrym okładem. Użyj balsam lub żel."}]}
	],
	aid_sunstroke: [
		{k: "title", t: "Porażenie słoneczne"},
		{k: "description", t: "gorąca i czerwona głowa, zimna skóra, zawrót głowy, ból głowy, . Przyczyna: Podrażnienie  membrany mózgowej."},
		{k: "image", i: "aid035"},
		{k: "step", p: [{t: "Przejdź w chłodne miejsce (cień) i unieś górną część ciała."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Schłodzić głowę mokrymi okładami."}]},
		{k: "step", p: [{t: "Dzwoń po pomoc i kontroluj oddychanie."}]},
		{k: "step", p: [{t: "Jeśli świadomy: Daj chłodny napój gdy możliwe ."}]},
		{k: "step", p: [{t: "Jeśli pojawi się bezdech, zacznij z oddychaniem:"}]},
		{k: "step", p: [{t: "Przejdź na Usta-Usta!", h: "#aid_apnoea"}]},
		{k: "image", i: "aid036"}
	],
	aid_unconsciouswithbreath: [
		{k: "title", t: "Nieświadomości z oddychaniem"},
		{k: "description", t: "Bez reakcji na głośne pytania , nie ma odpowiedzi na wstrząsanie. Nie ma oddychania."},
		{k: "image", i: "aid057"},
		{k: "step", p: [{t: "Jeżeli są ludzie obok Ciebie poproś o pomoc."}]},
		{k: "step", p: [{t: "Pozycja bezpieczna", h: "#aid_recoveryposition"}, {t: ". Otwórz usta i ustaw głową w ten sposób, żeby osoba mogła wymiotować."}]},
		{k: "image", i: "aid008"},
		{k: "image", i: "aid009"},
		{k: "step", p: [{t: "Dzwoń po pomoc."}]}
	],
	aid_unconsciouswithoutbreath: [
		{k: "title", t: "Świadomości bez oddychania"},
		{k: "step", p: [{t: "Ofiara nie reaguje, nie  oddycha."}]},
		{k: "image", i: "aid057"},
		{k: "step", p: [{t: "Wszczęcie renimacjii.", h: "#aid_resuscitation"}]}
	],
	aid_vomiting: [
		{k: "title", t: "Wymioty"},
		{k: "description", t: "Wynika z nudności. Żołądek opróżnia się. Przyczyny: Infekcja, zatrucie, owrzodzenia, narkotyki, złe jedzenie, ciąża."},
		{k: "image", i: "aid054"},
		{k: "step", p: [{t: "Niebezpieczeństwo dla krwiobiegu z powodu odwodnienia i utraty soli!"}]},
		{k: "step", p: [{t: "Podać płyny (herbata, woda)."}]},
		{k: "step", p: [{t: "Jeśli istnieją silne zaburzenia, krwawe wymioty lub ciągłe to wezwij  lekarza pogotowia."}]}
	]
};
var langContinents=[
	{i: "Africa", t: "Afryka"},
	{i: "Asia", t: "Azja"},
	{i: "Europe", t: "Europa"},
	{i: "Oceania", t: "Oceania"},
	{i: "Southamerica", t: "Południowa ameryka"},
	{i: "Northamerica", t: "Północna i centralna ameryka"}
];
var langCountries=[
	{i: "afghanistan", t: "Afganistan"},
	{i: "albania", t: "Albania"},
	{i: "algeria", t: "Algieria"},
	{i: "andorra", t: "Andora"},
	{i: "angola", t: "Angola"},
	{i: "antiguaandbarbuda", t: "Antigua i Barbuda"},
	{i: "saudiarabia", t: "Arabia Saudyjska"},
	{i: "argentina", t: "Argentyna"},
	{i: "armenia", t: "Armenia"},
	{i: "australia", t: "Australia"},
	{i: "austria", t: "Austria"},
	{i: "azerbaijan", t: "Azerbejdżan"},
	{i: "bahamas", t: "Bahamy"},
	{i: "bahrain", t: "Bahrajn"},
	{i: "bangladesh", t: "Bangladeszu"},
	{i: "barbados", t: "Barbados"},
	{i: "belgium", t: "Belgia"},
	{i: "belize", t: "Belize"},
	{i: "benin", t: "Benin"},
	{i: "bhutan", t: "Bhutan"},
	{i: "belarus", t: "Białoruś"},
	{i: "bolivia", t: "Boliwia"},
	{i: "bosniaandherzegovina", t: "Bośnia i Hercegowina"},
	{i: "botswana", t: "Botswana"},
	{i: "brazil", t: "Brazylia"},
	{i: "brunei", t: "Brunei"},
	{i: "bulgaria", t: "Bułgaria"},
	{i: "burkinafaso", t: "Burkina Faso"},
	{i: "burundi", t: "Burundi"},
	{i: "chile", t: "Chile"},
	{i: "china", t: "Chiny"},
	{i: "croatia", t: "Chorwacja"},
	{i: "cyprus", t: "Cypr"},
	{i: "chad", t: "Czadzie"},
	{i: "montenegro", t: "Czarnogóra"},
	{i: "denmark", t: "Dania"},
	{i: "dominica", t: "Dominika"},
	{i: "djibouti", t: "Dżibuti"},
	{i: "egypt", t: "Egipt"},
	{i: "ecuador", t: "Ekwador"},
	{i: "eritrea", t: "Erytreę"},
	{i: "estonia", t: "Estonia"},
	{i: "ethiopia", t: "Etiopia"},
	{i: "fiji", t: "Fidżi"},
	{i: "philippines", t: "Filipiny"},
	{i: "finland", t: "Finlandia"},
	{i: "france", t: "Francja"},
	{i: "gabon", t: "Gabon"},
	{i: "gambia", t: "Gambia"},
	{i: "ghana", t: "Ghana"},
	{i: "greece", t: "Grecja"},
	{i: "grenada", t: "Grenady"},
	{i: "greenland", t: "Grenlandia"},
	{i: "georgia", t: "Gruzja"},
	{i: "guyana", t: "Gujana"},
	{i: "guatemala", t: "Gwatemala"},
	{i: "equatorialguinea", t: "Gwinea Równikowa"},
	{i: "guinea", t: "Gwinei"},
	{i: "guinea-bissau", t: "Gwinei Bissau"},
	{i: "haiti", t: "Haiti"},
	{i: "spain", t: "Hiszpania"},
	{i: "netherlands", t: "Holandia"},
	{i: "honduras", t: "Hondurasu"},
	{i: "hongkong", t: "Hong Kong"},
	{i: "india", t: "Indie"},
	{i: "indonesia", t: "Indonezja"},
	{i: "iraq", t: "Iraku"},
	{i: "iran", t: "Iran"},
	{i: "ireland", t: "Irlandia"},
	{i: "iceland", t: "Islandia"},
	{i: "israel", t: "Izrael"},
	{i: "jamaica", t: "Jamajka"},
	{i: "japan", t: "Japonia"},
	{i: "yemen", t: "Jemen"},
	{i: "jordan", t: "Jordan"},
	{i: "caymanislands", t: "Kajmany"},
	{i: "cambodia", t: "Kambodża"},
	{i: "cameroon", t: "Kamerun"},
	{i: "canada", t: "Kanada"},
	{i: "qatar", t: "Katar"},
	{i: "kazakhstan", t: "Kazachstan"},
	{i: "kenya", t: "Kenia"},
	{i: "kyrgyzstan", t: "Kirgistan"},
	{i: "kiribati", t: "Kiribati"},
	{i: "colombia", t: "Kolumbia"},
	{i: "comoros", t: "Komory"},
	{i: "congorepublic", t: "Kongo (Republika)"},
	{i: "congodemocraticrepublic", t: "Kongo (Republika Demokratyczna)"},
	{i: "southkorea", t: "Korea Południowa (Republika Korei)"},
	{i: "northkorea", t: "Korea Północna"},
	{i: "kosovo", t: "Kosowo"},
	{i: "costarica", t: "Kostaryka"},
	{i: "cuba", t: "Kuba"},
	{i: "kurdistan", t: "Kurdystan"},
	{i: "kuwait", t: "Kuwejt"},
	{i: "laos", t: "Laos"},
	{i: "lesotho", t: "Lesoto"},
	{i: "lebanon", t: "Liban"},
	{i: "liberia", t: "Liberii"},
	{i: "libya", t: "Libia"},
	{i: "liechtenstein", t: "Liechtenstein"},
	{i: "lithuania", t: "Litwa"},
	{i: "luxembourg", t: "Luksemburg"},
	{i: "latvia", t: "Łotwa"},
	{i: "macedonia", t: "Macedonii"},
	{i: "madagascar", t: "Madagaskar"},
	{i: "mayotte", t: "Majotta"},
	{i: "macau", t: "Makau"},
	{i: "malawi", t: "Malawi"},
	{i: "maldives", t: "Malediwy"},
	{i: "malaysia", t: "Malezja"},
	{i: "mali", t: "Mali"},
	{i: "malta", t: "Malta"},
	{i: "morocco", t: "Maroko"},
	{i: "mauritania", t: "Mauretania *"},
	{i: "mauritius", t: "Mauritius *"},
	{i: "mexico", t: "Meksyk"},
	{i: "micronesia", t: "Mikronezji"},
	{i: "moldova", t: "Mołdowa"},
	{i: "monaco", t: "Monako"},
	{i: "mongolia", t: "Mongolii"},
	{i: "mozambique", t: "Mozambik"},
	{i: "myanmar", t: "Myanmar"},
	{i: "namibia", t: "Namibii"},
	{i: "nauru", t: "Nauru"},
	{i: "nepal", t: "Nepalu"},
	{i: "germany", t: "Niemcy"},
	{i: "nigeria", t: "Nigerii"},
	{i: "niger", t: "Nigru"},
	{i: "nicaragua", t: "Nikaragua"},
	{i: "norway", t: "Norwegia"},
	{i: "newzealand", t: "Nowa Zelandia"},
	{i: "oman", t: "Oman"},
	{i: "pakistan", t: "Pakistan"},
	{i: "palau", t: "Palau"},
	{i: "panama", t: "Panama"},
	{i: "papuanewguinea", t: "Papua-Nowa Gwinea"},
	{i: "paraguay", t: "Paragwaj"},
	{i: "peru", t: "Peru"},
	{i: "poland", t: "Polska"},
	{i: "portugal", t: "Portugalia"},
	{i: "czechrepublic", t: "Republika Czeska"},
	{i: "dominicanrepublic", t: "Republika Dominikany"},
	{i: "southafrica", t: "Republika Południowej Afryki"},
	{i: "centralafricanrepublic", t: "Republika Środkowoafrykańska"},
	{i: "reunion", t: "Reunion"},
	{i: "russia", t: "Rosja"},
	{i: "rwanda", t: "Ruanda"},
	{i: "romania", t: "Rumunia"},
	{i: "sahrawiarabdemocraticrepublic", t: "Saharyjskich Arabskiej Republiki Demokratycznej"},
	{i: "saintpierreandmiquelon", t: "Saint Kitts i Nevis"},
	{i: "stkittsandnevis", t: "Saint Lucia"},
	{i: "stlucia", t: "Saint-Pierre i Miquelon"},
	{i: "stvincentandgrenadines", t: "Saint Vincent i Grenadyny"},
	{i: "elsalvador", t: "Salwador"},
	{i: "samoa", t: "Samoa"},
	{i: "sanmarino", t: "San Marino"},
	{i: "senegal", t: "Senegalu"},
	{i: "serbia", t: "Serbia"},
	{i: "seychelles", t: "Seszele"},
	{i: "sierraleone", t: "Sierra Leone"},
	{i: "singapore", t: "Singapur"},
	{i: "slovakia", t: "Słowacja"},
	{i: "slovenia", t: "Słowenia"},
	{i: "somalia", t: "Somalii"},
	{i: "srilanka", t: "Sri Lanka"},
	{i: "unitedstatesofamerica", t: "Stany Zjednoczone Ameryki"},
	{i: "swaziland", t: "Suazi"},
	{i: "sudan", t: "Sudanie"},
	{i: "suriname", t: "Surinam"},
	{i: "syria", t: "Syrii"},
	{i: "switzerland", t: "Szwajcaria"},
	{i: "sweden", t: "Szwecja"},
	{i: "tajikistan", t: "Tadżykistan"},
	{i: "thailand", t: "Tajlandia"},
	{i: "taiwan", t: "Tajwan"},
	{i: "tanzania", t: "Tanzanii"},
	{i: "easttimor", t: "Timoru Wschodniego"},
	{i: "togo", t: "Togo"},
	{i: "tonga", t: "Tonga"},
	{i: "trinidadandtobago", t: "Trynidad i Tobago"},
	{i: "tunisia", t: "Tunezja"},
	{i: "turkey", t: "Turcja"},
	{i: "turkmenistan", t: "Turkmenistan"},
	{i: "tuvalu", t: "Tuvalu"},
	{i: "uganda", t: "Uganda"},
	{i: "ukraine", t: "Ukraina"},
	{i: "uruguay", t: "Urugwaj"},
	{i: "uzbekistan", t: "Uzbekistan"},
	{i: "vanuatu", t: "Vanuatu"},
	{i: "vaticancity", t: "Watykan"},
	{i: "venezuela", t: "Wenezuela"},
	{i: "hungary", t: "Węgry"},
	{i: "unitedkingdom", t: "Wielka Brytania"},
	{i: "vietnam", t: "Wietnam"},
	{i: "italy", t: "Włochy"},
	{i: "ivorycoast", t: "Wybrzeże Kości Słoniowej"},
	{i: "saotomeandprincipe", t: "Wysp Świętego Tomasza i Książęcej"},
	{i: "marshallislands", t: "Wyspy Marshalla"},
	{i: "solomonislands", t: "Wyspy Salomona"},
	{i: "capeverde", t: "Wyspy Zielonego Przylądka"},
	{i: "zambia", t: "Zambii"},
	{i: "zimbabwe", t: "Zimbabwe"},
	{i: "unitedarabemirates", t: "Zjednoczone Emiraty Arabskie"}
];
