//:Pirmoji Medicinos Pagalba
// Generated file, do not edit
var langTexts={
	title: "Pirmoji Medicinos Pagalba",
	back: "Atgal",
	continent: "Žemynas",
	emergency_fire: "Gaisrine",
	emergency_medical: "Gydytojas",
	emergency_police: "Policija",
	emergency_cancelcard: "",
	emergency_local: "vietinio telefono ryšio numeriais",
	emergency_nosystem: "nera ryšio",
	emergency_radioonly: "tik radijo ryšio telefonais",
	emergency_none: "--",
	emergency_or: "arba",
	emergency_mobile: "mobilusis",
	emergency_tourist: "turistams"
};
var langMenu=[
	{h: "#aid_disclaimer", t: "# Atsakomybė + Nuorodos"},
	{h: "#numbers", t: "# Pagalbos telefonai"},
	{h: "#aid_general", t: "# Bendros nuorodos"},
	{h: "#aid_chemicalburneyes", t: "Akių nudegimas chemikalais"},
	{h: "#aid_eyeinjury", t: "Akių sužeidimai"},
	{h: "#aid_allergic", t: "Alerginės reakcijos"},
	{h: "#aid_amputation", t: "Amputavimas"},
	{h: "#aid_poisining", t: "Apsinuodijimas"},
	{h: "#aid_asthma", t: "Astma / Kvėpavimo sutrikimai"},
	{h: "#aid_diabeticcoma", t: "Diabetinė koma"},
	{h: "#aid_apnoea", t: "Dirbtinis kvėpavimas"},
	{h: "#aid_asthma", t: "Dusulys"},
	{h: "#aid_safeguardaccident", t: "Eismo nelaimė"},
	{h: "#aid_epilepsy", t: "Epilepsija"},
	{h: "#aid_resuscitation", t: "Gaivinimas (Reanimacija)"},
	{h: "#aid_dangerzone", t: "Gelbėjimas"},
	{h: "#aid_birth", t: "Gimdymo priėmimas"},
	{h: "#aid_snakebite", t: "Gyvatės įkandimas"},
	{h: "#aid_animalbite", t: "Gyvūnų įkandimai"},
	{h: "#aid_emergencycall", t: "Greitosios pagalbos kvietimas"},
	{h: "#aid_diabeticcoma", t: "Hiperglikemija (cukraus kiekio padidėjimas kraujyje)"},
	{h: "#aid_hypoglycaemia", t: "Hipoglikemija (cukraus kiekio sumažėjimas kraujyje)"},
	{h: "#aid_stroke", t: "Insultas"},
	{h: "#aid_skullfracture", t: "Kaukolės lūžis"},
	{h: "#aid_fracture", t: "Kaulo lūžis, atviras"},
	{h: "#aid_bleedinglight", t: "Kraujavimas, lengvas"},
	{h: "#aid_bleedingsevere", t: "Kraujavimas, stiprus"},
	{h: "#aid_nosebleeding", t: "Kraujavimas iš nosies"},
	{h: "#aid_resuscitation", t: "Krūtinės ląstos masažas"},
	{h: "#aid_apnoea", t: "Kvėpavimas sustojęs"},
	{h: "#aid_checkbreathing", t: "Kvėpavimo kontroliavimas"},
	{h: "#aid_safeguardaccident", t: "Nelaimės vieta, pažymėkite"},
	{h: "#aid_icerescue", t: "Nelaimingas atsitikimas ant ledo"},
	{h: "#aid_burningslight", t: "Nudegimas, lengvas"},
	{h: "#aid_burningsevere", t: "Nudegimas, stiprus"},
	{h: "#aid_chemicalburn", t: "Nudegimas chemikalais"},
	{h: "#aid_sunburn", t: "Nudegimas saulėje"},
	{h: "#aid_backinjury", t: "Nugaros sužalojimai"},
	{h: "#aid_frostbitemild", t: "Nušalimas, lengvas"},
	{h: "#aid_frostbitesevere", t: "Nušalimas, sunkus"},
	{h: "#aid_electricityaccident", t: "Nutrenkimas elektros srove"},
	{h: "#aid_hyperthermia", t: "Perkaitimas"},
	{h: "#aid_resuscitation", t: "Reanimacija"},
	{h: "#aid_unconsciouswithbreath", t: "Sąmonės netekimas/ nualpimas (nukentėjęs kvėpuoja)"},
	{h: "#aid_unconsciouswithoutbreath", t: "Sąmonės netekimas (nukentėjęs nekvėpuoja)"},
	{h: "#aid_sunstroke", t: "Saulės smūgis"},
	{h: "#aid_sprain", t: "Sausgyslės patempimas, sąnario išsukimas"},
	{h: "#aid_drowning", t: "Skendimas"},
	{h: "#aid_brainconcussion", t: "Smegenų sukrėtimas"},
	{h: "#aid_sos", t: "SOS - Nelaimės Signalas"},
	{h: "#aid_recoveryposition", t: "Stabili pozicija ant šono."},
	{h: "#aid_backinjury", t: "Stuburo lūžis"},
	{h: "#aid_hypothermia", t: "Sušalimas (Hipotermija)"},
	{h: "#aid_heartattack", t: "Širdies infarktas"},
	{h: "#aid_shock", t: "Šokas"},
	{h: "#aid_suffocation", t: "Uždusimas / Užspringimas"},
	{h: "#aid_insectstings", t: "Vabzdžių įkandimai"},
	{h: "#aid_vomiting", t: "Vėmimas"},
	{h: "#aid_diarrhoea", t: "Viduriavimas"},
	{h: "tel:112", t: "Skambinti 112"}
];
var langSections={
	aid_disclaimer: [
		{k: "title", t: "Atsakomybė + Nuorodos"},
		{k: "subsection", t: "Programinė įranga"},
		{k: "description", t: "Pirmoji Medicinos Pagalba Mobiliajam Telefonui"},
		{k: "description", t: "Visos teisės saugomos: Kai Kajus Noack"},
		{k: "description", t: "Vertėja: Alma Petruškevičiūtė"},
		{k: "description", t: "Licencija: Creative Commons by-nc-nd"},
		{k: "image", i: "cc88x31"},
		{k: "description", t: "Ši programa teikia informaciją apie pirmąją medicinos pagalbą. Ji neatstoja pirmosios pagalbos kurso, bet padeda atnaujinti jau įgytas žinias."},
		{k: "description", t: "Iliustracijos © Med4Teens"},
		{k: "subsection", t: "Atsakomybės nebuvimas"},
		{k: "description", t: "Prašau atsižvelgti į tai, jog už galimas vartojimo pasekmes neatsakau."},
		{k: "description", t: "NEPRISIIMU JOKIOS ATSAKOMYBĖS!"},
		{k: "description", t: "VISĄ RIZIKĄ PRISIIMA VARTOTOJAS!"},
		{k: "description", t: "Visais nelaimės atvejais nedelsiant kreipkitės profesionalios pagalbos."},
		{k: "subsection", t: "Išgelbėk vieną žmogų ir Tu išgelbėsi žmoniją."}
	],
	aid_general: [
		{k: "title", t: "Bendros nuorodos"},
		{k: "step", p: [{t: "Visuomet suteikite pirmąją medicinos pagalbą. Nedarykite klaidų."}]},
		{k: "step", p: [{t: "Saugokitės patys."}]},
		{k: "step", p: [{t: "Susidarykite aiškų vaizdą apie situaciją + pažymėkite nelaimės vietą."}]},
		{k: "step", p: [{t: "Iškvieskite greitąją pagalbą + Suteikite nukentėjusiajam pirmąją medicinos pagalbą."}]},
		{k: "step", p: [{t: "Esant keliems nukentėjusiesiems pirmenybę suteikite sunkiausiai sužalotam."}]},
		{k: "step", p: [{t: "Nuraminkite nukentėjusįjį. Stenkitės išlikti ramus!"}]},
		{k: "step", p: [{t: "Paguldykite susižalojusį kaip galima patogiau. Jokiu būdu neduokite jam alkoholio, nikotino arba vaistų."}]}
	],
	aid_allergic: [
		{k: "title", t: "Alerginės reakcijos", i: "aid046"},
		{k: "step", p: [{t: "Iškviesti greitąją pagalbą."}]},
		{k: "step", p: [{t: "Nuraminkite alergijos ištiktą žmogų ir pasodinkite jį patogiai."}]},
		{k: "step", p: [{t: "Pašalinkite alergijos sukėlėją (pvz. vabzdžio geluonį)."}]},
		{k: "step", p: [{t: "Šaldykie alerginės reakcijos ištikta vietą (drėgnais kompresais, ledu)."}]},
		{k: "image", i: "aid046ice"},
		{k: "step", p: [{t: "Jei žmogus, ištiktas alergines reakcijos, turi priešalerginių vaistų, duokite juos išgerti."}]},
		{k: "step", p: [{t: "Kontroliuokite alergijos ištiktojo būklę, kol atvyks gydytojas."}]},
		{k: "step", p: [{t: "Sąmonės netekimo ar kvėpavimo sutrikimo atvejais imkitės atitinkamų priemonių!"}]},
		{k: "image", i: "aid077"}
	],
	aid_amputation: [
		{k: "title", t: "Amputavimas"},
		{k: "description", t: "Amputuotos kūno dalys gali būti prisiūtos. Amputuotą kūno dalį šaldyti, kol atvyks gydytojas."},
		{k: "step", p: [{t: "Nukentėjusįjį nuraminkite, paguldykite ir užklokite."}]},
		{k: "step", p: [{t: "Sustabdykite kraujavimą, žiūrėti 'Kraujavimas (stiprus\") ir \"Šokas\"."}]},
		{k: "step", p: [{t: "Amputuotą kūno dalį suvyniokite į švarų sausą rankšluostį ir įdėkite į neperšlampantį plastikinį maišelį."}]},
		{k: "step", p: [{t: "Plastikinį maišelį užriškite ir įdėkite į kitą plastikinį maišelį pripildytą šalto vandens arba ledo."}]},
		{k: "step", p: [{t: "Neduokite alkoholio, rūkyti ar valgyti (ligoninėje gali prireikti operuoti su narkoze)."}]},
		{k: "step", p: [{t: "Amputuotos kūno dalies nedėkite į šaldikliį (tik šaldykite)."}]},
		{k: "step", p: [{t: "Kvieskite greitąją pagalbą arba važiuokite į ligoninę."}]}
	],
	aid_animalbite: [
		{k: "title", t: "Gyvūnų įkandimai", i: "aid047"},
		{k: "description", t: "Dėmesio: Galite užsikrėsti stablige, pasiutlige."},
		{k: "step", p: [{t: "Nuplaukite žaizdą karštu vandeniu su muilu."}]},
		{k: "image", i: "aid049"},
		{k: "step", p: [{t: "Dezinfekuokite žaizdą."}]},
		{k: "step", p: [{t: "Sunkaus kraujavimo atveju, paguldykite nekentėjusį taip, kad viršutinė kūno dalis būtų pakelta."}]},
		{k: "step", p: [{t: "Sutvarstykite steriliu tvarsčiu."}]},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Kreipkitės pas gydytoją arba kvieskite greitąją pagalbą."}]}
	],
	aid_apnoea: [
		{k: "title", t: "Kvėpavimas sustojęs"},
		{k: "description", t: "Negirdėti kvėpavimo, nėra kvėpavimui būdingų judesių, pasikeitusi odos spalva."},
		{k: "step", p: [{t: "Kvieskite greitąją pagalbą."}]},
		{k: "step", p: [{t: "Paguldykite kvėpavimo sutrikimų ištiktąjį ant nugaros."}]},
		{k: "step", p: [{t: "Iš nukentėjusiojo burnos ir gerklės pašalinkite svetimkūnius. Atloškite nukentejusiojo galvą."}]},
		{k: "image", i: "aid067"},
		{k: "step", p: [{t: "Suspauskite nosies sparnelius taip, kad nosis būtų užkimšta."}]},
		{k: "image", i: "aid010"},
		{k: "step", p: [{t: "Giliai įkvėpkite, priglauskite savo burną prie nukentėjusiojo burnos taip, kad visas Jūsų iškvėpiamas oras patektų į nukentėjusiojo plaučius."}]},
		{k: "image", i: "aid011"},
		{k: "step", p: [{t: "Giliai ir lėtai iškvėpkite."}]},
		{k: "step", p: [{t: "Jei nukentėjusysis neatsigauna, tęskite dirbtinį kvėpavimą iš burnos į burną, kol atvyks gydytojas."}]}
	],
	aid_asthma: [
		{k: "title", t: "Astma / Kvėpavimo sutrikimai"},
		{k: "description", t: "Ūmūs kvėpavimo sutrikimai. Švokščiantis kvėpavimas. Baimės jausmas."},
		{k: "step", p: [{t: "Nuraminkite ištiktą astmos priepuolio žmogų. Stenkitės išlikti ramus!"}]},
		{k: "step", p: [{t: "Atlaisvinkite jo drabužius."}]},
		{k: "step", p: [{t: "Ištiktąjį astmos priepolio pasodinkite patogiai, šiek tiek palenkite į priekį, liepkite jam lėtai ir giliai kvėpuoti."}]},
		{k: "step", p: [{t: "Jei astmos priepuolio ištiktasis turi inhaliatorių, padėkite jam juo pasinaudoti. Po 5-10 min. turėtų pagerėti."}]},
		{k: "image", i: "aid074"},
		{k: "step", p: [{t: "Jei nepagerėtų, toliau naudokite inhaliatorių kas 5 minutes, kol atvyks gydytojas."}]},
		{k: "step", p: [{t: "Kvieskite greitąją pagalbą."}]},
		{k: "step", p: [{t: "Jei astmos priepuolio ištiktasis nustotų kvėpuoti, pradėkite dirbtinį "}, {t: "kvėpavimą", h: "#aid_apnoea"}, {t: "."}]}
	],
	aid_backinjury: [
		{k: "title", t: "Nugaros sužalojimai"},
		{k: "description", t: "Skausmas nugaroje, nutirpę rankos ir kojos."},
		{k: "step", p: [{t: "Jokiu būdu nejudinkite sužalotojo!"}]},
		{k: "image", i: "aid064"},
		{k: "step", p: [{t: "Laikykite nukentėjusiojo galvą taip, kad būsena būtų stabili."}]},
		{k: "image", i: "aid065"},
		{k: "step", p: [{t: "Stabilizuoti nukentėjusiojo būseną paremiant iš šonų."}]},
		{k: "step", p: [{t: "Nusiraminkite nukentėjusįjį."}]},
		{k: "step", p: [{t: "Kvieskite greitąją pagalbą, informuokite apie nugaros sužeidimą."}]}
	],
	aid_birth: [
		{k: "title", t: "Gimdymo priėmimas"},
		{k: "description", t: "Ištekėjo vaisiaus vandenys. Prasideda gimdymo skausmai. Netikėtas gimdymas."},
		{k: "image", i: "aid025"},
		{k: "step", p: [{t: "Išlikite ramūs! - Kvieskite greitąją pagalbą."}]},
		{k: "step", p: [{t: "Pasodinkite nėščiąją praskėstomis apnuogintomis kojomis ant sterilaus pagrindo."}]},
		{k: "step", p: [{t: "Sulenkite kelius. Šiek tiek pakelkite jos dubenį. - Gimdymas yra natūralus procesas ir dažniausiai praeina be komplikacijų."}]},
		{k: "step", p: [{t: "Nuraminkite moterį, leiskite jai sutelkti dėmesį į kvėpavimą: Įkvėpti per nosį, iškvėpti per burną (normaliu greičiu)."}]},
		{k: "step", p: [{t: "Stūmimo ritmas: Giliai įkvėpti, sulaikyti kvėpavimą, stumti. Kai pasirodys kūdikio galvutė, prilaikykite ją abiem rankomis."}]},
		{k: "image", i: "aid021"},
		{k: "image", i: "aid022"},
		{k: "step", p: [{t: "Po gimdymo: pakelkite kūdikį nuožulniai galva žemyn lengvai palenkta galvele, kad iš kūdikio kvėpavimo takų pasišalintų skystis. (Gali prireikti iš jo burnos ir nosytės burnos pagalba issiurbti likusį skystį). Kūdikis turi kvėpuoti ir verkti!"}]},
		{k: "step", p: [{t: "Suriškite bambagyslę 30 cm atstumu nuo kudikio (tai gali būti atlikta ligoninėje). Steriliai apdenkite gimdyvės makštį."}]},
		{k: "image", i: "aid023"},
		{k: "step", p: [{t: "Nusausinkite kūdikį ir laikykite jį šiltai. Įsidėmėkite laiką ir važiuokite i ligoninę."}]}
	],
	aid_bleedinglight: [
		{k: "title", t: "Kraujavimas, lengvas", i: "aid082"},
		{k: "description", t: "Tikslas: Kraujavimo sustabdymas."},
		{k: "step", p: [{t: "Žaizdos nelieskite (dėl infekcijos pavojaus)."}]},
		{k: "step", p: [{t: "Žaizdos niekuo netepkite, nepurkškite ir nepudruokite."}]},
		{k: "step", p: [{t: "Ant žaizdos uždėkite sterilų tvarstį ir jį užklijuokite pleistru ar bintu apriškite sužeistą vietą."}]},
		{k: "image", i: "aid098"},
		{k: "step", p: [{t: "Esant silpnam kraujavimui užtenka tik paprasto pleistro."}]},
		{k: "step", p: [{t: "Didesnei žaizdai naudokite sterilų tvarstį. Ji uždėkite ant žaizdos ir apriškite bintu (veržkite ne per stipriai, nes tai gali sukelti dar didesnį kraujavimą)."}]},
		{k: "image", i: "aid084"},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Įkandus pasiutusiam gyvūnui žaizdą nuplaukite vandeniu ir muilu."}]},
		{k: "image", i: "aid049"}
	],
	aid_bleedingsevere: [
		{k: "title", t: "Kraujavimas, stiprus"},
		{k: "description", t: "Kraujas liejasi iš žaizdos pulsuodamas, purkšdamas. Pavojus, kad ištiks šokas dėl kraujo netekimo, infekcija, žmogus gali mirti. Tikslas: kraujavimo sustabdymas."},
		{k: "step", p: [{t: "Pašalinkite drabužius (esant būtinybei juos prakirpkite), apnuoginkite sužalotą vietą."}]},
		{k: "step", p: [{t: "Bintu arba drabužio skiaute apvyniokite žaizdą ją užspaudžiant."}]},
		{k: "image", i: "aid086"},
		{k: "step", p: [{t: "Užveržtą žaizdą laikykite mažiausiai 10 minučių."}]},
		{k: "step", p: [{t: "Jei naudojamas varžtas persisunkė krauju, jo nepašalinkite! Ant viršaus dėkite kitą bintą ar drabužio skiautę."}]},
		{k: "step", p: [{t: "Sužeistą galūnę, jei ji nelūžus, pakelkite aukščiau širdies lygmens, kad kraujavimas susilpnėtų. Jei yra galimybė, sužeistąjį paguldykite."}]},
		{k: "step", p: [{t: "Jei kraujavimo nepavyksta sustabdyti, žaizdą laikykite užspaudę toliau, tuo pačiu veržkite virš sužeistos vietos: kraujuojant dilbiui- žastą (pirštais spauskite per viduįi iš vidinės rankos pusės tarp alkūnės ir pažasties); kraujuojant kojai - užspauskite ranka kirkšnį (spauskite kraujagysles kirkšnyje, kur arterija eina per dubens kaulus)."}]},
		{k: "image", i: "aid089"},
		{k: "image", i: "aid092"},
		{k: "step", p: [{t: "Nedelsiant kvieskite greitąją pagalbą."}]},
		{k: "step", p: [{t: "Jeigu kraujavimas sustojo, imkitės pirmosios pagalbos priemonių šokui pašalinti."}]},
		{k: "image", i: "aid093"}
	],
	aid_brainconcussion: [
		{k: "title", t: "Smegenų sukrėtimas"},
		{k: "description", t: "Galvos skausmas, pykinimas, vėmimas. Pablogėjęs regėjimas. Galimas sąmonįs netekimas."},
		{k: "image", i: "aid035a"},
		{k: "step", p: [{t: "Nukentėjusįjį paguldykite."}]},
		{k: "step", p: [{t: "Kvieskite greitąją pagalbą."}]},
		{k: "description", t: "Jeigu galva kraujuoja:"},
		{k: "step", p: [{t: "Paguldykite nukentėjusįjį, pakelkite galvą (ant pagalvės)."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Apriškite žaizdą (naudokite tvarstį)."}]},
		{k: "step", p: [{t: "Kvieskite greitąją pagalbą."}]}
	],
	aid_burningslight: [
		{k: "title", t: "Nudegimas, lengvas"},
		{k: "description", t: "Odos paraudimas. Lengvas patinimas. Skausmas."},
		{k: "step", p: [{t: "Šaldykite sužeistą vietą po šaltu tekančiu vandeniu."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Neveržiant aptvarstykite drėgnu tvarsčiu."}]}
	],
	aid_burningsevere: [
		{k: "title", t: "Nudegimas, stiprus"},
		{k: "description", t: "Pūslėti baltai raudoni odos plotai. Šlapiuojanti oda. Giluminis audinių pažeidimas. Stiprus skausmas arba skausmo nėra (dėl sudegusių nervų)."},
		{k: "image", i: "aid097"},
		{k: "step", p: [{t: "Pašalikite kiek įmanoma drabužius."}]},
		{k: "step", p: [{t: "Šaldykite nudegusias kūno dalis šaltu vandeniu (maždaug 15 ° C) iki 10 min, kol skausmas atslūgs."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Jei nudeginimas platus, šaldykite drėgnais rankšluoščiais."}]},
		{k: "step", p: [{t: "Kvieskite greitąją pagalbą."}]},
		{k: "step", p: [{t: "Po to kai atšaldėte žaizdą, ją sutvarstykite. Naudokite sterilų sausą tvarstį. Nenaudokite jokių skysčių (kremų, aliejų, tepaųi ir kt.) Nepradurkite susidariusių pūslių."}]},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Kontroliuokite nukentėjusiojo kvėpavimą ir sąmonę kol atvyks gydytojas."}]}
	],
	aid_checkbreathing: [
		{k: "title", t: "Kvėpavimo kontroliavimas"},
		{k: "step", p: [{t: "Patikrinkite kvėpavimo garsą."}]},
		{k: "step", p: [{t: "Krūtinės ląstos judėjimas (tikrinti ant pilvo uždedant ranką)."}]},
		{k: "image", i: "aid027"},
		{k: "step", p: [{t: "Patikrinti ar jaučiamas kvėpavimą per nosį ar burną."}]}
	],
	aid_chemicalburneyes: [
		{k: "title", t: "Akių nudegimas chemikalais"},
		{k: "step", p: [{t: "Kvieskite greitąją pagalbą, informuokite apie cheminę medžiagą, nudeginusią akį."}]},
		{k: "step", p: [{t: "Plaukite akį vandeniu. Plaunant uždenkite sveiką akį."}]},
		{k: "step", p: [{t: "Sužeistą akį plaukite šalto vandens srove apie 20 min. nuo vidinio akies krašto link išorinio."}]},
		{k: "image", i: "aid019"},
		{k: "step", p: [{t: "Užmerkite abi akis ir užriškite drėgnu tvarsčiu."}]},
		{k: "image", i: "aid020"},
		{k: "step", p: [{t: "Stebėkite nukentėjusiojo būseną kol atvyks greitoji medicinos pagalba."}]}
	],
	aid_chemicalburn: [
		{k: "title", t: "Nudegimas chemikalais"},
		{k: "description", t: "Audinių sužalojimas."},
		{k: "image", i: "aid095"},
		{k: "step", p: [{t: "Saugokitės patys!"}]},
		{k: "step", p: [{t: "Nedelsiant nuplaukite nudegintą vietą (nudegusią akį plauti šaltu vandeniu maž. 20 min., vandens srovę kreipti nuo vidinio link išorinio akies krašto)."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Kvieskite greitąją pagalbą."}]},
		{k: "step", p: [{t: "Cheminis virškinamojo trakto nudegimas. Gerti daug vandens."}]},
		{k: "step", p: [{t: "Neprovokuoti vėmimo!"}]}
	],
	aid_dangerzone: [
		{k: "title", t: "Gelbėjimas"},
		{k: "step", p: [{t: "Būdas: atsistokite už nukentėjusiojo, nukentėjusiojo ranka ant jo krūtinės."}]},
		{k: "step", p: [{t: "Apkabinkite nukentėjusįjį pro pažastis ir paimkite už sulenktos nukentėjusiojo rankos."}]},
		{k: "step", p: [{t: "Gabenkite nukentėjusįjį į saugią vietą."}]},
		{k: "image", i: "aid001"},
		{k: "image", i: "aid007"}
	],
	aid_diabeticcoma: [
		{k: "title", t: "Diabetinė koma"},
		{k: "description", t: "Cukraus koncentracija kraujyje per didelė (atitinkamai trūksta insulino)."},
		{k: "description", t: "Požymiai: troškulys, dažnas šlapinimasis, pykinimas, vėmimasi. Kvėpavimas atsiduoda vaisiais."},
		{k: "step", p: [{t: "Kvieskite greitąją pagalbą."}]},
		{k: "step", p: [{t: "Jeigu aišku, kad žmogus diabetikas, padėkite susileisti insulino."}]},
		{k: "image", i: "aid016"},
		{k: "step", p: [{t: "Paguldykite nukentėjusįjį "}, {t: "stabiliai ant šono", h: "#aid_recoveryposition"}, {t: ". Daugiau pirmos pagalbos teikėjas negali tokiu atveju padaryti."}]},
		{k: "step", p: [{t: "Stebėti buklę, kol atvyks gydytojas."}]}
	],
	aid_diarrhoea: [
		{k: "title", t: "Viduriavimas"},
		{k: "description", t: "Apsinuodijimas maistu, infekcijos arba žarnyno liga. Viduriavimas skystas, gleivėtas arba su krauju."},
		{k: "step", p: [{t: "Pavojus dėl dehidratacijos ir mineralų trūkumo!"}]},
		{k: "step", p: [{t: "Duoti gerti skysčių (arbatos, vandens)."}]},
		{k: "step", p: [{t: "Sunkiais atvejais vykti pas gydytoją arba kvieti greitąją pagalbą."}]}
	],
	aid_drowning: [
		{k: "title", t: "Skendimas"},
		{k: "step", p: [{t: "Kvieskite greitąją pagalbą. Prašykite aplinkinių žmonių pagalbos."}]},
		{k: "image", i: "aid032"},
		{k: "step", p: [{t: "Gelbekite skęstantįjį!"}]},
		{k: "image", i: "aid033"},
		{k: "image", i: "aid034"},
		{k: "step", p: [{t: "Jeigu nukentėjusįsis kvėpuoja: Paguldykite į "}, {t: "stabilią poziciją ant šono", h: "#aid_recoveryposition"}, {t: ". Apklokite (antklode). Stebėkite būkle, kol atvyks greitoji pagalba."}]},
		{k: "step", p: [{t: "Jeigu nukentėjusįsis nekvėpuoja: Nedelsiant pradėkite "}, {t: "gaivinimą!", h: "#aid_resuscitation"}, {t: " (Nesistenkinte pašalinti vandens iš plaučiu.)"}]}
	],
	aid_electricityaccident: [
		{k: "title", t: "Nutrenkimas elektros srove"},
		{k: "step", p: [{t: "Visu pirma nutraukite elektros energijos tiekimą!"}]},
		{k: "image", i: "aid045plug"},
		{k: "image", i: "aid045"},
		{k: "step", p: [{t: "Galimas sąmonės netekimas kvėpavimo sustojimas."}]},
		{k: "step", p: [{t: "A - Sąmonės netekimas,kvėpavimas nesutrikęs", h: "#aid_unconsciouswithbreath"}]},
		{k: "step", p: [{t: "B - Sąmonės netekimas, kvėpavimo nėra", h: "#aid_unconsciouswithoutbreath"}]},
		{k: "image", i: "aid042"},
		{k: "image", i: "aid043"}
	],
	aid_emergencycall: [
		{k: "title", t: "Greitosios pagalbos kvietimas"},
		{k: "step", p: [{t: "Paskambinkite pirmu pasitaikiusiu telefonu 112 (JAV: 911). Visada galima ir nemokamai! Nedvejokite ir kvieskite greitaja pagalba!"}]},
		{k: "step", p: [{t: "Telefonu privalote suteikti šia informacija:"}]},
		{k: "step", p: [{t: "- Kas nutiko"}]},
		{k: "step", p: [{t: "- Kur (nelaimingo atsitikimo vieta) "}]},
		{k: "step", p: [{t: "- Kiek nukentejusiuju "}]},
		{k: "step", p: [{t: "- Kokios traumos."}]},
		{k: "step", p: [{t: "Laukite tolimesniu nurodymu."}]}
	],
	aid_epilepsy: [
		{k: "title", t: "Epilepsija"},
		{k: "description", t: "Sustingęs kūnas, sugniaužti kumščiai, sukąstas žandikaulis, trūkčiojančios galūnės arba veidas. Besivartančios akys. Seilėjimasis. Galimas sąmonės netekimas."},
		{k: "image", i: "aid058"},
		{k: "step", p: [{t: "Nelaikykite nukentėjusiojo, neribokite jo judesių."}]},
		{k: "step", p: [{t: "Paguldykite nukentėjusįjį ant minkšto pagrindo (pagalvės), pašalinkite arti esancius daiktus siekiant užkirsti kelią susižalojimams."}]},
		{k: "step", p: [{t: "Raminkite nukentėjusįjį žodžiais. Atlaisvinkite drabužius, kad jis galėtų laisvai kvėpuoti."}]},
		{k: "step", p: [{t: "Jeigu nukentėjęs vemia, pakreipkite jo galvą taip, kad neužspringtų."}]},
		{k: "step", p: [{t: "Stebėkite, kad kvėpavimo takai būtų laisvi. Nukentėjęs gali nuryti liežuvį."}]},
		{k: "step", p: [{t: "Paguldykite "}, {t: "stabiliai ant šono", h: "#aid_recoveryposition"}, {t: " + kvieskite greitąją pagalbą. Stebėkite nukentėjusiojo būklę."}]},
		{k: "step", p: [{t: "Neleiskite prisiartinti kitiems žmonėms."}]}
	],
	aid_eyeinjury: [
		{k: "title", t: "Akių sužeidimai"},
		{k: "step", p: [{t: "Svetimkūnį palikite akyje, nesistenkite jo pašalinti."}]},
		{k: "step", p: [{t: "Akies nejudinkite ir nelieskite, tam kad jos dar daugiau nesužeistumėte."}]},
		{k: "step", p: [{t: "Jeigu akis kraujuoja, uždėkite ant jos kompresą arba sterilų tvarstį."}]},
		{k: "image", i: "aid020"},
		{k: "step", p: [{t: "Akį šaldykite šaltu kompresu, tai mažina tinimą, stabdo kraujavimą."}]},
		{k: "step", p: [{t: "Kvieskite greitąją pagalbą arba važiuokite į ligoninę."}]}
	],
	aid_fracture: [
		{k: "title", t: "Kaulo lūžis, atviras"},
		{k: "description", t: "Simptomai: nenatūrali pozicija, nenatūralus kaulų judėjimas. Deformacija. Skausmingas judėjimas, skausmas prisilietus."},
		{k: "image", i: "aid104"},
		{k: "step", p: [{t: "Vengti judesių!"}]},
		{k: "step", p: [{t: "Kvieskite greitąją pagalbą."}]},
		{k: "step", p: [{t: "Uždėkite įtvarą sulaužytam kaului, paremkite nekeičiant kaulo pozicijos."}]},
		{k: "image", i: "aid107"},
		{k: "step", p: [{t: "Jei lūžis atviras, steriliai pridenkite žaizdą."}]},
		{k: "image", i: "aid106"}
	],
	aid_frostbitemild: [
		{k: "title", t: "Nušalimas, lengvas"},
		{k: "description", t: "Blyškumas, patinimas. Gali sutrikti aprūpinimas krauju."},
		{k: "step", p: [{t: "Nuveskite nukentėjusįjį į šilumą."}]},
		{k: "step", p: [{t: "Pasistenkite nukentėjusįjį sušildyti, pašalinkite šlapius drabužius."}]},
		{k: "step", p: [{t: "Sušildykite drungnu vandeniu ir savo kūno šiluma."}]},
		{k: "step", p: [{t: "Duokite šilto gėrimo (arbatos). Jokio alkoholio!"}]},
		{k: "image", i: "aid040"}
	],
	aid_frostbitesevere: [
		{k: "title", t: "Nušalimas, sunkus"},
		{k: "description", t: "Šalta ir kieta kūno oda, pilkai balta spalva, darosi pūslės, audiniai apmiršta. Gali sutrikti aprūpinimas krauju!"},
		{k: "image", i: "aid096"},
		{k: "step", p: [{t: "Eikite į šiltą vietą."}]},
		{k: "step", p: [{t: "Žaizdas sutvarstykite/apdenkite."}]},
		{k: "step", p: [{t: "Duokite cukrumi saldinto gėrimo."}]},
		{k: "step", p: [{t: "Nesistenkite sušildyti trynimu!"}]},
		{k: "step", p: [{t: "Kvieskite greitąją pagalbą."}]}
	],
	aid_heartattack: [
		{k: "title", t: "Širdies infarktas"},
		{k: "description", t: "Sunkus, daugiau kaip 5 min. trunkantis spaudimas ir skausmas krūtinėje, ypatingai besiskleidižantis rankos bei paties srityje. Nerimas, blyškumas, šaltas prakaitas. Galimas pykinimas, dusulys."},
		{k: "image", i: "aid076"},
		{k: "image", i: "aid083"},
		{k: "step", p: [{t: "Kvieskite greitąją pagalbą! Praneškite apie galimą širdies infarktą."}]},
		{k: "step", p: [{t: "Viršutinę kūno dalį pakelkite. Atpalaiduokite drabužius. Neduokite vaistų ar gėrimų."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Raminkite nukentėjusįjį žodžiais."}]},
		{k: "step", p: [{t: "Kontroliuokite sąmonę ir kvėpavimą."}]},
		{k: "step", p: [{t: "Jeigu turite, duokite aspirino."}]},
		{k: "step", p: [{t: "Jei asmuo praranda sąmonę, pradėkite "}, {t: "gaivinimą", h: "#aid_resuscitation"}, {t: "."}]}
	],
	aid_hypoglycaemia: [
		{k: "title", t: "Hipoglikemija (cukraus kiekio sumažėjimas kraujyje)"},
		{k: "description", t: "Cukraus koncentracija kraujyje yra mažesne nei mažiausia vertė (perdozavus insulino arba dėl nepakankamo maitinimosi)."},
		{k: "description", t: "Simptomai: blyškumas, nervingumas, alkis, drebulys, prakaitas."},
		{k: "image", i: "aid018"},
		{k: "step", p: [{t: "Įsitikinkite, kad asmuo yra diabetikas (diabetiko ženklelis)."}]},
		{k: "step", p: [{t: "Kvieskite greitąją pagalbą."}]},
		{k: "step", p: [{t: "Duokite cukrumi saldinto gėrimo arba dekstrozės / gliukozės (jei nėra rijimo problemų)."}]},
		{k: "image", i: "aid017"},
		{k: "step", p: [{t: "Jei asmuo be sąmonės, bet kvėpuoja: paguldykite "}, {t: "stabiliai ant šono", h: "#aid_recoveryposition"}, {t: " ir stebėkite kvėpavimą. Jei kvėpavimas sustojo, darykite dirbtinį kvėpavimą."}]},
		{k: "step", p: [{t: "Jei nukentėjusįsis kvėpuoja, bet be sąmonės, įdėkite gabaliuką cukraus už žando ir paspauskite iš išorės."}]}
	],
	aid_hyperthermia: [
		{k: "title", t: "Perkaitimas"},
		{k: "description", t: "Troškulys, silpnumas, orientacijos sutrikimas, pykinimas, sumišimas, stiprus prakaitavimas, karščiuojanti oda."},
		{k: "image", i: "aid035"},
		{k: "step", p: [{t: "Kvieskite greitąją pagalbą."}]},
		{k: "step", p: [{t: "Vėsinti, ieškoti pavėsio (patalpa su oro kondicionieriumi pageidautina)."}]},
		{k: "step", p: [{t: "Asmenį paguldyti, pakelti kojas. Atlaisvinti drabužius."}]},
		{k: "image", i: "aid078"},
		{k: "step", p: [{t: "Odą vėsinti vandeniu arba uždėti šaltą rankšluostį."}]},
		{k: "step", p: [{t: "Gerti daug vandens ar sulciui."}]}
	],
	aid_hypothermia: [
		{k: "title", t: "Sušalimas (Hipotermija)"},
		{k: "description", t: "Šaltas drebulys, mieguistumas, išsekimas net iki sąmonės netekimo. Šalta, blyški oda. Žemas pulsas, silpnas širdies plakimas."},
		{k: "image", i: "aid014"},
		{k: "step", p: [{t: "Eiti į šiltą patalpą."}]},
		{k: "step", p: [{t: "Kviesti greitąją pagalbą."}]},
		{k: "step", p: [{t: "Pašalinti šalčio šaltinį.. Didinti kūno temperatūrą (dekio arba savo kūno kontaktu)."}]},
		{k: "step", p: [{t: "Nurenkite šlapius drabužius ir aprengite šiltais drabužiais. Apsupkite dekiu. Uždenkite galvą."}]},
		{k: "step", p: [{t: "Duokite atsigerti karštos arbatos, sriubos arba karšto vandens. Jokio alkoholio! Neleiskite asmeniui užmigti."}]},
		{k: "image", i: "aid039"},
		{k: "image", i: "aid040"},
		{k: "step", p: [{t: "Stebėkite sušalusiojo būklę, kol atvyks greitoji pagalba. Jei asmuo netenka sąmonės, pradėkite gaivinimą:"}]},
		{k: "step", p: [{t: "A - Nukentėjęs be sąmonės, bet kvėpuoja", h: "#aid_unconsciouswithbreath"}]},
		{k: "step", p: [{t: "B - Be sąmonės, nekvėpuoja", h: "#aid_unconsciouswithoutbreath"}]}
	],
	aid_icerescue: [
		{k: "title", t: "Nelaimingas atsitikimas ant ledo"},
		{k: "description", t: "Saugokitės patys. Pavojus nuskęsti, nušalimas."},
		{k: "step", p: [{t: "Gelbėkite kopėčių, lentos ar lazdos pagalba. Svoris ant ledo turi būti tolygiai paskirstytas."}]},
		{k: "step", p: [{t: "Paprašykite kitų žmonių pagalbos. Prašykite iškviesti greitąją pagalbą."}]},
		{k: "step", p: [{t: "Su įrankiu rankoje, atsargiai šliaužkite ant pilvo (jei įmanoma, prisirišus virve) link įskilusio ledo."}]},
		{k: "image", i: "aid041"},
		{k: "step", p: [{t: "Paduokite nukentėjusiam įrankį (ne savo ranką!) ir traukite."}]},
		{k: "step", p: [{t: "Šliaužkite atgal link kranto."}]},
		{k: "step", p: [{t: "Suteikite Pirmąją medicinos pagalbą."}]},
		{k: "step", p: [{t: "Savarankiškas gelbėjimasis: Jei ledas kietos, paskirstykite svorį tolygiai ir stenkitės išlipti.Ant pilvo šliaužkite link kranto. Jei ledas trapus, pabandykite sulaužyti ledą iki krašto."}]}
	],
	aid_insectstings: [
		{k: "title", t: "Vabzdžių įkandimai", i: "aid046"},
		{k: "description", t: "Patinimas, odos bėrimas, deginimas, silpnumas, pasunkejęs kvėpavimas, svaigimas, tachikardija."},
		{k: "step", p: [{t: "Atsargiai pašalinkite geluonį (su pincetu). Nespauskite geluonies, nes taip galite įšvirkšti daugiau nuodų."}]},
		{k: "step", p: [{t: "Atšaldykite sužeistą vietą (uždėkite šaltą kompresą)."}]},
		{k: "step", p: [{t: "Įgeltą vietą laikykite žemiau nei širdis, taip cirkuliuos nuodai lėčiau."}]},
		{k: "step", p: [{t: "Jeigu geluonis yra burnos ertmėje: čiulpti ledus ir uždėkite šaltą kompresą aplink gerklę."}]},
		{k: "image", i: "aid046ice"},
		{k: "step", p: [{t: "Pasireiškus sunkioms problemoms iškviesti greitąją pagalbą."}]}
	],
	aid_nosebleeding: [
		{k: "title", t: "Kraujavimas iš nosies"},
		{k: "description", t: "Įtrūkusi kraujagyslė nosies ertmėje."},
		{k: "step", p: [{t: "Pasodinkite kraujuojantį asmenį ir truputį palenkite į prieki. Laikykite galvą tiesiai."}]},
		{k: "step", p: [{t: "Neguldykite asmens, galvos padėtis virš širdies lėtina kraujavimą."}]},
		{k: "step", p: [{t: "Uždėkite šaltą kompresą ant sprando."}]},
		{k: "step", p: [{t: "Užspauskite nosį kol kraujavimas sustos (apie 10 min.)"}]},
		{k: "step", p: [{t: "Vėliau nevarginkite nosies (ne šnypškite)."}]},
		{k: "step", p: [{t: "Jeigu problema rimta arba kraujavimas ilgai nenustoja, kvieskite gydytoją."}]}
	],
	aid_poisining: [
		{k: "title", t: "Apsinuodijimas", i: "aid052"},
		{k: "description", t: "Sumišimas, haliucinacijos, issiplėtę vyzdžiai, karščiavimas, mešlungis, sąmonės netekimas."},
		{k: "step", p: [{t: "Duokite priešnuodžių tik tada jeigu šalia kvalifikuotas medikas."}]},
		{k: "image", i: "aid056"},
		{k: "step", p: [{t: "Neduokite gerti. Neprovokuokite vėmimo."}]},
		{k: "step", p: [{t: "Iškvieskite greitąją pagalbą, būtinai nurodykite, kad asmuo apsinuodijęs!"}]},
		{k: "step", p: [{t: "Išsaugokite nuodų ir vėmimo likučius!"}]},
		{k: "image", i: "aid054a"},
		{k: "step", p: [{t: "Jeigu nukentėjęs be sąmonės, bet kvėpuoja: paguldykite "}, {t: "stabiliai ant šono", h: "#aid_recoveryposition"}, {t: ". Stebėkite sąmonę ir kvėpavimą kol atvyks gydytojas."}]},
		{k: "step", p: [{t: "Jeigu nukentejusysis nekvėpuoja: Nedelsiant pradėkite "}, {t: "gaivinimą!", h: "#aid_resuscitation"}, {t: " Prieš pradedant dirbtinį kvėpavimą, patikrinkite, ar neužsikimšę kvėpavimo takai, pavyzdžiui dėl vėmimo."}]}
	],
	aid_recoveryposition: [
		{k: "title", t: "Stabili pozicija ant šono."},
		{k: "step", p: [{t: "Paguldykite nukentėjusįjį ant nugaros, ištieskite kojas. Atsiklaupkite šalia."}]},
		{k: "step", p: [{t: "Arčiausiai jūsų esančią nekentėjusiojo ranką padėkite stačiu kampu prie kūno."}]},
		{k: "step", p: [{t: "Tolimesniąją ranką uždėkite ant krūtinės, o delno išorinę pusę ant skruosto."}]},
		{k: "image", i: "aid008"},
		{k: "step", p: [{t: "4.Paimkite tolimesnį kelį, patraukite link savęs ir padėkite ant žemės. Koja turi gulėti stačiu kampu. Ranka nukentėjusiojo ant skruoto."}]},
		{k: "step", p: [{t: "Įsitikinkite, kad kvėpavimo takai nėra blokuojami."}]},
		{k: "step", p: [{t: "Atloškite galvą, kilstelėkite smakrą. Lengvai pražiodinkite burną. Stebėkite kvėpavimą."}]},
		{k: "image", i: "aid009"},
		{k: "step", p: [{t: "Stebėkite nukentėjusiojo būklę kol atvyks greitoji pagalba."}]},
		{k: "description", t: "Kūdikio stabili pozicija ant šono"},
		{k: "image", i: "aid028"}
	],
	aid_resuscitation: [
		{k: "title", t: "Gaivinimas (Reanimacija)"},
		{k: "subsection", t: "# Išorinis širdies masažas"},
		{k: "step", p: [{t: "Nukentėjusįjį paguldykite ir atsiklaupkite šalia jo."}]},
		{k: "step", p: [{t: "Atsekite krūtinės dalies drabužius."}]},
		{k: "step", p: [{t: "Uždėkite savo vieną delną ant apatinės krūtinkaulio dalies."}]},
		{k: "image", i: "aid013"},
		{k: "step", p: [{t: "Kitą delną uždėkite ant jo."}]},
		{k: "step", p: [{t: "Ištieskite rankas ir alkūnes."}]},
		{k: "image", i: "aid003"},
		{k: "step", p: [{t: "Statmenai iš viršaus nelenkdami alkūnių stipriai paspauskite krūtinkaulį apie 5 cm ir atleiskite."}]},
		{k: "step", p: [{t: "Trumpai ir stipriai kartokite šį judesį iš eilės 30 kartų!"}]},
		{k: "subsection", t: "# Dirbtinis kvėpavimas"},
		{k: "step", p: [{t: "Pašalinkite visus svetimkūnius, esancius nukentėjusiojo burnoje (protezus, vėmalų likučius ir kt.). Atloškite nukentėjusiojo galvą prilaikydami kaklą."}]},
		{k: "image", i: "aid067"},
		{k: "step", p: [{t: "Laisva ranka užspauskite nosį."}]},
		{k: "image", i: "aid010"},
		{k: "step", p: [{t: "Giliai įkvėpkite ir įpūskite orą nukentėjusiam į burną taip, kad oras negalėtų išeiti."}]},
		{k: "image", i: "aid011"},
		{k: "step", p: [{t: "Įpūtimą iš burnos į burną kartokite du kartus (lėtai, pilnai iškvepiant)."}]},
		{k: "step", p: [{t: "Vėl darykite išorinį širdies masažą."}]},
		{k: "description", t: "Išorinis širdies masažas kartu su dirbtiniu kvėpavimu atliekamas tol kol atvažiuos greitoji pagalba."},
		{k: "image", i: "aid012"},
		{k: "subsection", t: "# Kūdikio Gaivinimas"},
		{k: "step", p: [{t: "Naudoti tik du pirštus:"}]},
		{k: "image", i: "aid029"},
		{k: "step", p: [{t: "Įpūskite ne per stipriai:"}]},
		{k: "image", i: "aid030"}
	],
	aid_safeguardaccident: [
		{k: "title", t: "Nelaimės vieta, pažymėkite"},
		{k: "step", p: [{t: "Savo automobilį pastatykite 50-100 m už eismo ivykio vietos (jeigu įvykis greitkelyje arba plente). Įjunkite avarinį signalą. Apsirenkite matomumo liemenę."}]},
		{k: "step", p: [{t: "Įvykio vietoje pastatykite avarinį ženklą. Dėmesio: Jei avarija posūkyje, pastatykite avarinį ženklą prieš posūkį!"}]},
		{k: "image", i: "aid111"},
		{k: "step", p: [{t: "Pašaukite aplinkinius žmones į pagalbą."}]},
		{k: "step", p: [{t: "Atidarykite automobilio duris (jei užstrigę, naudokite automobilio keltuvą). Išjunkite degimą."}]},
		{k: "step", p: [{t: "Gelbėkite avarijos auką : atsekite saugos diržą, atstumkite sėdynę. Iškelkite sužeistąjį "}, {t: "apkabinę per pažastis", h: "#aid_dangerzone"}, {t: "."}]},
		{k: "image", i: "aid001"},
		{k: "step", p: [{t: "Kvieskite greitąją pagalbą."}]},
		{k: "step", p: [{t: "Suteikite pirmąją medicinos pagalbą."}]}
	],
	aid_shock: [
		{k: "title", t: "Šokas"},
		{k: "description", t: "Kraujotakos sutrikimas dėl nepakankamo deguonies tiekimo į kūną."},
		{k: "description", t: "Priežastis: Skysčių praradimas, sumažėjęs kraujo tūris."},
		{k: "description", t: "Simptomai: blyškumas, šalta oda, šaltas prakaitas, nerimas."},
		{k: "step", p: [{t: "Pašalinkite šoko priežastį (pvz.sustabdykite skysčių praradimą, sutvarstykite žaizdą)!"}]},
		{k: "step", p: [{t: "Paguldykite sužeistąjį ant paklodės, pakelkite kojas aukštyn. Nuraminkit nukentėjusįjį."}]},
		{k: "image", i: "aid078"},
		{k: "step", p: [{t: "Kvieskite greitąją pagalbą."}]},
		{k: "step", p: [{t: "Jei sunku kvėpuoti ar sutrikusi kraujotaka, pradėkite "}, {t: "gaivinimą", h: "#aid_resuscitation"}, {t: "."}]}
	],
	aid_skullfracture: [
		{k: "title", t: "Kaukolės lūžis"},
		{k: "description", t: "Lengvas kraujavimai iš nosies, burnos arba ausų. Dažnai atviros žaizdos kaukolėje."},
		{k: "step", p: [{t: "Stebėkite kvėpavimo takus, kad neužsikimštų."}]},
		{k: "step", p: [{t: "Jeigu nukentėjęs sąmoningas: Pasodinkite ir lengvai palenkite į priekį. Stenkitės daugiau nejudinti.!"}]},
		{k: "step", p: [{t: "Jei be sąmonės: "}, {t: "Stabili pozicija ant šono", h: "#aid_recoveryposition"}, {t: " (nespauskite žaizdos galvoje)."}]},
		{k: "step", p: [{t: "Kvieskite greitąją pagalbą."}]},
		{k: "step", p: [{t: "Sutvarstykite galvą tvarsčiu."}]},
		{k: "step", p: [{t: "Jei sunku kvėpuoti, sutrikusi kraujotaka, "}, {t: "pradėkite gaivinimą", h: "#aid_resuscitation"}, {t: "."}]}
	],
	aid_snakebite: [
		{k: "title", t: "Gyvatės įkandimas", i: "aid051"},
		{k: "description", t: "Smeigtuko dydžio durtinė žaizda, stiprus skausmas, patinimas, purpurinė spalva. Kraujotakos sutrikimas, galimas šokas."},
		{k: "step", p: [{t: "Įkąstą kūno dalį paguldyti."}]},
		{k: "step", p: [{t: "Dėkite šaltus kompresus ant įkandimo vietos."}]},
		{k: "step", p: [{t: "Imkitės veiksmų prieš šoką."}]},
		{k: "step", p: [{t: "Kvieskite greitąją pagalbą."}]}
	],
	aid_sos: [
		{k: "title", t: "SOS - Nelaimės Signalas"},
		{k: "step", p: [{t: "Signalas: 3x trumpai, 3x ilgai, 3x trumpai."}]},
		{k: "step", p: [{t: "Optiškai (lempute, prožektoriumi) oder akustiškai (signaliniškai švilpuku, beldimu)."}]}
	],
	aid_sprain: [
		{k: "title", t: "Sausgyslės patempimas, sąnario išsukimas"},
		{k: "description", t: "Skausmas, tinimas (mėlynė), funcijos nebuvimas, galūnių deformacijos."},
		{k: "step", p: [{t: "Paguldykite nukentėjusiojo galūnę patogiai."}]},
		{k: "step", p: [{t: "Šaldyti (naudokite ledo paketus)."}]},
		{k: "step", p: [{t: "Jei įmanoma paguldykite galūnę aukščiau."}]},
		{k: "step", p: [{t: "Vykite į ligoninę ar kvieskite greitosios pagalbos gydytoją."}]}
	],
	aid_stroke: [
		{k: "title", t: "Insultas"},
		{k: "description", t: "Staigus paralyžius arba nutirpimas (veido, rankos, kojos), kalbos, regos sutrikimai, sutrikusi sąmonė, stiprūs galvos skausmai. Kvėpavimo, rijimo problemos, šlapimo pūslės ir žarnyno nevaldymas."},
		{k: "image", i: "aid059"},
		{k: "step", p: [{t: "Kvieskite greitąją pagalbą!"}]},
		{k: "step", p: [{t: "Atpalaiduokite veržiančius drabužius, neduokite medikamentų, neduokite gerti."}]},
		{k: "step", p: [{t: "Nukentėjusįjį pasodinkite arba paguldykite patogiai. Nusiraminkite!"}]},
		{k: "step", p: [{t: "Stebėkite sąmonę ir kvėpavimą."}]},
		{k: "step", p: [{t: "Jeigu problemos su kvėpavimu arba sąmonės sutrikimai, "}, {t: "pradėkite gaivinimą", h: "#aid_resuscitation"}, {t: "."}]}
	],
	aid_suffocation: [
		{k: "title", t: "Uždusimas / Užspringimas"},
		{k: "description", t: "Nepakankamas aprūpinimas deguonimi. Trachėja uždaryta. Gali sustoti kvėpavimas (apnėja)"},
		{k: "description", t: "Simptomai: švokščiantis kvėpavimas, kosulys, dusulys, odos spalvos pakitimas."},
		{k: "image", i: "aid066"},
		{k: "step", p: [{t: "Veikite skubiai! Leiskite nukentėjusiajam stipriai atsikosėti."}]},
		{k: "step", p: [{t: "Stipriai suduokite plokščia ranka keletą kartų per nugarą tarp menčių (kūdikį pasiguldykite sau ant rankos, galvą laikykite žemyn)."}]},
		{k: "image", i: "aid068"},
		{k: "image", i: "aid031"},
		{k: "step", p: [{t: "Jei tai neduoda rezultatų: atsistokite asmeniui iš nugaros, uždėkite rankas ant juosmens, palenkite nukentėjusįjį lengvai į priekį."}]},
		{k: "step", p: [{t: "Sugniaužkite kumštį nukentėjusiojo skrandžio lygmenyje ir apkabinkite kita ranka."}]},
		{k: "image", i: "aid069"},
		{k: "step", p: [{t: "Abi apkabinusias rankas traukite staigiu judesiu aukštyn/link savęs, lyg norėtumėte nukentėjusįjį kilstelėti."}]},
		{k: "step", p: [{t: "Kartokite tai iki 5-ių kartų! Kvėpavimo takai turėtų atsilaisvinti, jeigu buvo užkimšti daiktu."}]},
		{k: "step", p: [{t: "Kvieskite greitąją pagalbą."}]},
		{k: "step", p: [{t: "Jei ši pirmosios pagalbos priemonė nėra sėkminga, vistiek tęskite ją kol atvyks gydytojas"}]}
	],
	aid_sunburn: [
		{k: "title", t: "Nudegimas saulėje"},
		{k: "step", p: [{t: "Nuveskite nukentėjusįjį į pavėsį. Venkite saulė spindulių."}]},
		{k: "step", p: [{t: "Duokite gerti daug vandens (dėl dehidratacijos)."}]},
		{k: "step", p: [{t: "Esant sunkiam nudegimui (darosi pūslės, paraudimas, skausmas), nedelsiant kreipkitės pas gydytoją."}]},
		{k: "step", p: [{t: "Jeigu oda tik truputį raudona, šaldykite ją drėgnais kompresais. Naudokite kremą arba gelį skirtą tepti po deginimosi saulėje."}]}
	],
	aid_sunstroke: [
		{k: "title", t: "Saulės smūgis"},
		{k: "description", t: "Galva karšta ir raudona, oda šalta, šleikštulys, galvos skausmas, galvos svaigimas. Priežastis: Sudirginta smegenų membrana."},
		{k: "image", i: "aid035"},
		{k: "step", p: [{t: "Ieškokite vėsios vietos, pavėsio. Viršutinė kūno dalis turi būti pakelta aukščiau."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Šaldykite galvą drėgnais kompresais."}]},
		{k: "step", p: [{t: "Skambinkite greitajai pagalbai, stebėkite kvėpavimą."}]},
		{k: "step", p: [{t: "Jei nekentėjusįsis sąmoningas: Duokite gerti šalto gėrimo."}]},
		{k: "step", p: [{t: "Jeigu sustojo kvėpavimas, pradėkite dirbtinį kvėpavimą."}]},
		{k: "step", p: [{t: "Tęskite dirbtinį kvėpavimą!", h: "#aid_apnoea"}]},
		{k: "image", i: "aid036"}
	],
	aid_unconsciouswithbreath: [
		{k: "title", t: "Sąmonės netekimas/ nualpimas (nukentėjęs kvėpuoja)"},
		{k: "description", t: "Nukentėjęs nereaguoja į kalbinimą ar judinimą. Nukentėjęs kvėpuoja."},
		{k: "image", i: "aid057"},
		{k: "step", p: [{t: "Jei netoliese yra žmonių, kreipkitės į juos pagalbos."}]},
		{k: "step", p: [{t: "Paguldykite nukentėjusįjį "}, {t: "stabiliai ant šono", h: "#aid_recoveryposition"}, {t: ". Galvą palenkite žemyn, pražiodinkite burną, kad vemiant neužspringtų."}]},
		{k: "image", i: "aid008"},
		{k: "image", i: "aid009"},
		{k: "step", p: [{t: "Kvieskite greitąją pagalbą."}]}
	],
	aid_unconsciouswithoutbreath: [
		{k: "title", t: "Sąmonės netekimas (nukentėjęs nekvėpuoja)"},
		{k: "step", p: [{t: "Nukentėjęs nerodo jokios reakcijos, nekvėpuoja."}]},
		{k: "image", i: "aid057"},
		{k: "step", p: [{t: "Pradėkite gaivinti", h: "#aid_resuscitation"}, {t: " (dirbtinis kvėpavimas + širdies masažas)."}]}
	],
	aid_vomiting: [
		{k: "title", t: "Vėmimas"},
		{k: "description", t: "Pykinimo rezultatas. Pasituština skrandis. Priežastys: infekcijos, apsinuodijimai, opos, medikamentai, nekokybiškas maistas, neštumas."},
		{k: "image", i: "aid054"},
		{k: "step", p: [{t: "Pavojus dėl dehidratacijos ir mineralų trūkumo!"}]},
		{k: "step", p: [{t: "Duokite gerti skysčių (arbatos, vandens)."}]},
		{k: "step", p: [{t: "Sunkiais atvejais, vemiant krauju arba jeigu vėmimas nenustoja, skambinkite gydytojui."}]}
	]
};
var langContinents=[
	{i: "Africa", t: "Afrika"},
	{i: "Asia", t: "Azija"},
	{i: "Europe", t: "Europa"},
	{i: "Oceania", t: "Okeanija"},
	{i: "Southamerica", t: "Pietų Amerika"},
	{i: "Northamerica", t: "Šiaurės / Centrinė-Amerika"}
];
var langCountries=[
	{i: "afghanistan", t: "Afganistanas"},
	{i: "ireland", t: "Airija"},
	{i: "albania", t: "Albanija"},
	{i: "algeria", t: "Alžyras"},
	{i: "andorra", t: "Andora"},
	{i: "angola", t: "Angola"},
	{i: "antiguaandbarbuda", t: "Antigva ir Barbuda"},
	{i: "argentina", t: "Argentina"},
	{i: "armenia", t: "Armėnija"},
	{i: "australia", t: "Australija"},
	{i: "austria", t: "Austrija"},
	{i: "azerbaijan", t: "Azerbaidžanas"},
	{i: "bahamas", t: "Bahamai"},
	{i: "bahrain", t: "Bahreinas"},
	{i: "belarus", t: "Baltarusija"},
	{i: "bangladesh", t: "Bangladešas"},
	{i: "barbados", t: "Barbadosas"},
	{i: "belgium", t: "Belgija"},
	{i: "belize", t: "Belizas"},
	{i: "benin", t: "Beninas"},
	{i: "bolivia", t: "Bolivija"},
	{i: "bosniaandherzegovina", t: "Bosnija ir Hercegovina"},
	{i: "botswana", t: "Botsvana"},
	{i: "brazil", t: "Brazilija"},
	{i: "brunei", t: "Brunėjus"},
	{i: "bulgaria", t: "Bulgarija"},
	{i: "burkinafaso", t: "Burkina Fasas"},
	{i: "burundi", t: "Burundis"},
	{i: "bhutan", t: "Butanas"},
	{i: "chad", t: "Cadas"},
	{i: "centralafricanrepublic", t: "Centrinė Afrikos Respublika"},
	{i: "czechrepublic", t: "Čekijos Respublika"},
	{i: "chile", t: "Čilė"},
	{i: "denmark", t: "Danija"},
	{i: "dominica", t: "Dominika"},
	{i: "dominicanrepublic", t: "Dominikos Respublika"},
	{i: "ivorycoast", t: "Dramblio Kaulo Krantas"},
	{i: "djibouti", t: "Džibutis"},
	{i: "egypt", t: "Egiptas"},
	{i: "ecuador", t: "Ekvadoras"},
	{i: "elsalvador", t: "El Salvadoras"},
	{i: "eritrea", t: "Eritrėja"},
	{i: "estonia", t: "Estija"},
	{i: "ethiopia", t: "Etiopija"},
	{i: "fiji", t: "Fidžis"},
	{i: "philippines", t: "Filipinai"},
	{i: "gabon", t: "Gabonas"},
	{i: "guyana", t: "Gajana"},
	{i: "gambia", t: "Gambija"},
	{i: "ghana", t: "Gana"},
	{i: "greece", t: "Graikija"},
	{i: "grenada", t: "Grenada"},
	{i: "greenland", t: "Grenlandija"},
	{i: "georgia", t: "Gruzija"},
	{i: "guatemala", t: "Gvatemala"},
	{i: "guinea", t: "Gvinėja"},
	{i: "guinea-bissau", t: "Gvinėja-Bisau"},
	{i: "haiti", t: "Haitis"},
	{i: "honduras", t: "Honduras"},
	{i: "hongkong", t: "Honkongas"},
	{i: "india", t: "Indija"},
	{i: "indonesia", t: "Indonezija"},
	{i: "iraq", t: "Irakas"},
	{i: "iran", t: "Iranas"},
	{i: "iceland", t: "Islandija"},
	{i: "spain", t: "Ispanija"},
	{i: "italy", t: "Italija"},
	{i: "israel", t: "Izraelis"},
	{i: "jamaica", t: "Jamaika"},
	{i: "japan", t: "Japonija"},
	{i: "yemen", t: "Jemenas"},
	{i: "jordan", t: "Jordanija"},
	{i: "unitedkingdom", t: "Jungtinė Karalystė"},
	{i: "unitedstatesofamerica", t: "Jungtinės Amerikos Valstijos"},
	{i: "unitedarabemirates", t: "Jungtiniai Arabu Emyratai"},
	{i: "montenegro", t: "Juodkalnija"},
	{i: "caymanislands", t: "Kaimanu salos"},
	{i: "cambodia", t: "Kambodža"},
	{i: "cameroon", t: "Kamerunas"},
	{i: "canada", t: "Kanada"},
	{i: "qatar", t: "Kataras"},
	{i: "kazakhstan", t: "Kazachstanas"},
	{i: "kenya", t: "Kenija"},
	{i: "china", t: "Kinija"},
	{i: "cyprus", t: "Kipras"},
	{i: "kyrgyzstan", t: "Kirgizija"},
	{i: "kiribati", t: "Kiribatis"},
	{i: "colombia", t: "Kolumbija"},
	{i: "comoros", t: "Komorai"},
	{i: "congodemocraticrepublic", t: "Kongas (Kongo Demokratinė Respublika)"},
	{i: "congorepublic", t: "Kongas (Kongo Respublika)"},
	{i: "kosovo", t: "Kosovas"},
	{i: "costarica", t: "Kosta Rika"},
	{i: "croatia", t: "Kroatija"},
	{i: "cuba", t: "Kuba"},
	{i: "kurdistan", t: "Kurdistanas"},
	{i: "kuwait", t: "Kuveitas"},
	{i: "laos", t: "Laosas"},
	{i: "latvia", t: "Latvija"},
	{i: "poland", t: "Lenkija"},
	{i: "lesotho", t: "Lesotas"},
	{i: "lebanon", t: "Libanas"},
	{i: "liberia", t: "Liberija"},
	{i: "libya", t: "Libija"},
	{i: "liechtenstein", t: "Lichtenšteinas"},
	{i: "lithuania", t: "Lietuva"},
	{i: "luxembourg", t: "Liuksemburgas"},
	{i: "madagascar", t: "Madagaskaras"},
	{i: "mayotte", t: "Majota"},
	{i: "macau", t: "Makao"},
	{i: "macedonia", t: "Makedonija"},
	{i: "malaysia", t: "Malaizija"},
	{i: "malawi", t: "Malavis"},
	{i: "maldives", t: "Maldyvai"},
	{i: "mali", t: "Malis"},
	{i: "malta", t: "Malta"},
	{i: "morocco", t: "Marokas"},
	{i: "marshallislands", t: "Maršalo salos"},
	{i: "mauritius", t: "Mauricijus"},
	{i: "mauritania", t: "Mauritanija"},
	{i: "mexico", t: "Meksika"},
	{i: "myanmar", t: "Mianmaras"},
	{i: "micronesia", t: "Mikronezija"},
	{i: "moldova", t: "Moldavija"},
	{i: "monaco", t: "Monakas"},
	{i: "mongolia", t: "Mongolija"},
	{i: "mozambique", t: "Mozambikas"},
	{i: "namibia", t: "Namibija"},
	{i: "newzealand", t: "Naujoji Zelandija"},
	{i: "nauru", t: "Nauru"},
	{i: "nepal", t: "Nepalas"},
	{i: "netherlands", t: "Nyderlandai"},
	{i: "nigeria", t: "Nigerija"},
	{i: "niger", t: "Nigeris"},
	{i: "nicaragua", t: "Nikaragva"},
	{i: "norway", t: "Norvegija"},
	{i: "oman", t: "Omanas"},
	{i: "pakistan", t: "Pakistanas"},
	{i: "palau", t: "Palau"},
	{i: "panama", t: "Panama"},
	{i: "papuanewguinea", t: "Papua ir Naujoji Gvineja"},
	{i: "paraguay", t: "Paragvajus"},
	{i: "peru", t: "Peru"},
	{i: "southafrica", t: "Pietų Afrika"},
	{i: "southkorea", t: "Pietų Korėja (Korėjos Respublika)"},
	{i: "portugal", t: "Portugalija"},
	{i: "france", t: "Prancūzija"},
	{i: "equatorialguinea", t: "Pusiaujo Gvinėja"},
	{i: "reunion", t: "Reunionas"},
	{i: "easttimor", t: "Rytų Timoras"},
	{i: "rwanda", t: "Ruanda"},
	{i: "romania", t: "Rumunija"},
	{i: "russia", t: "Rusija"},
	{i: "sahrawiarabdemocraticrepublic", t: "Sacharos Arabų Demokratinė Respublika"},
	{i: "solomonislands", t: "Saliamono Salos"},
	{i: "samoa", t: "Samoa"},
	{i: "sanmarino", t: "San Marinas"},
	{i: "saotomeandprincipe", t: "San Tome ir Prinsipe"},
	{i: "saudiarabia", t: "Saudo Arabija"},
	{i: "seychelles", t: "Seišeliai"},
	{i: "senegal", t: "Senegalas"},
	{i: "stkittsandnevis", t: "Sent Kitsas ir Nevis"},
	{i: "stlucia", t: "Sent Lusija"},
	{i: "saintpierreandmiquelon", t: "Sent Pjeras ir Mikelonas"},
	{i: "stvincentandgrenadines", t: "Sent Vinsentas ir Grenadinai"},
	{i: "serbia", t: "Serbija"},
	{i: "sierraleone", t: "Siera Leone"},
	{i: "singapore", t: "Singapuras"},
	{i: "syria", t: "Sirija"},
	{i: "slovakia", t: "Slovakija"},
	{i: "slovenia", t: "Slovėnija"},
	{i: "somalia", t: "Somalis"},
	{i: "sudan", t: "Sudanas"},
	{i: "finland", t: "Suomija"},
	{i: "suriname", t: "Surinamas"},
	{i: "swaziland", t: "Svazilandas"},
	{i: "northkorea", t: "Šiaurės Korėja"},
	{i: "srilanka", t: "Šri Lanka"},
	{i: "sweden", t: "Švedija"},
	{i: "switzerland", t: "Šveicarija"},
	{i: "tajikistan", t: "Tadžikistanas"},
	{i: "thailand", t: "Tailandas"},
	{i: "taiwan", t: "Taivanas"},
	{i: "tanzania", t: "Tanzanija"},
	{i: "togo", t: "Togas"},
	{i: "tonga", t: "Tonga"},
	{i: "trinidadandtobago", t: "Trinidadas ir Tobagas"},
	{i: "tunisia", t: "Tunisas"},
	{i: "turkey", t: "Turkija"},
	{i: "turkmenistan", t: "Turkmėnistanas"},
	{i: "tuvalu", t: "Tuvalu"},
	{i: "uganda", t: "Uganda"},
	{i: "ukraine", t: "Ukraina"},
	{i: "uruguay", t: "Urugvajus"},
	{i: "uzbekistan", t: "Uzbekija"},
	{i: "vanuatu", t: "Vanuatu"},
	{i: "vaticancity", t: "Vatikanas"},
	{i: "venezuela", t: "Venesuela"},
	{i: "hungary", t: "Vengrija"},
	{i: "vietnam", t: "Vietnamas"},
	{i: "germany", t: "Vokietija"},
	{i: "zambia", t: "Zambija"},
	{i: "zimbabwe", t: "Zimbabvė"},
	{i: "capeverde", t: "Žaliojo Kyšulio salos"}
];
