//:cấp cứu
// Generated file, do not edit
var langTexts={
	title: "cấp cứu",
	back: "lùi lại",
	continent: "Lục địa",
	emergency_fire: "Lửa",
	emergency_medical: "Y tế",
	emergency_police: "Cảnh sát",
	emergency_cancelcard: "",
	emergency_local: "Số địa phương",
	emergency_nosystem: "Không có hệ thống",
	emergency_radioonly: "Chỉ có hình máy điện thoại",
	emergency_none: "--",
	emergency_or: "or",
	emergency_mobile: "điện thoại di động",
	emergency_tourist: "Chỉ có hình máy điện thoại"
};
var langMenu=[
	{h: "#aid_disclaimer", t: "# Phủ nhận + Thông tin"},
	{h: "#numbers", t: "# Cuộc Gọi Khẩn Cấp"},
	{h: "#aid_general", t: "# Bước Tiến Hành Chung"},
	{h: "#aid_safeguardaccident", t: "An Toàn Tai Nạn"},
	{h: "#aid_epilepsy", t: "Bịnh Kinh Phong"},
	{h: "#aid_eyeinjury", t: "Bị Thương Mắt"},
	{h: "#aid_nosebleeding", t: "Chảy Máu Cam"},
	{h: "#aid_brainconcussion", t: "Chấn Động Não"},
	{h: "#aid_backinjury", t: "Chấn Thương Lưng"},
	{h: "#aid_drowning", t: "Chết Đuối"},
	{h: "#aid_diabeticcoma", t: "Chứng Hôn Mê Của Tiểu Đường"},
	{h: "#aid_insectstings", t: "Côn Trùng Chích"},
	{h: "#aid_allergic", t: "Dị ứng"},
	{h: "#aid_heartattack", t: "Đau Tim"},
	{h: "#aid_fracture", t: "Gãy Xương"},
	{h: "#aid_backinjury", t: "Gãy Xương Cột Sống"},
	{h: "#aid_icerescue", t: "Giải Cứu Trên Băng Đá"},
	{h: "#aid_emergencycall", t: "Gọi Khẩn Cấp "},
	{h: "#aid_hypothermia", t: "Hạ Thân Nhiệt (mát cơ thể)"},
	{h: "#aid_asthma", t: "Hết Hơi"},
	{h: "#aid_resuscitation", t: "Hồi Sinh"},
	{h: "#aid_apnoea", t: "Hơi Thở"},
	{h: "#aid_diabeticcoma", t: "Hyperglycaemia (đường)"},
	{h: "#aid_hyperthermia", t: "Hyperthermia (thân nhiệt)"},
	{h: "#aid_hypoglycaemia", t: "Hypoglycaemia (thấp đường)"},
	{h: "#aid_dangerzone", t: "Khu Vực Nguy Hiểm (Giải Cứu)"},
	{h: "#aid_checkbreathing", t: "Kiểm Tra Hơi Thở"},
	{h: "#aid_apnoea", t: "Ngừng Thở"},
	{h: "#aid_suffocation", t: "Nuốt/Nghẹn"},
	{h: "#aid_skullfracture", t: "Nứt Xương Sọ"},
	{h: "#aid_vomiting", t: "ói Mửa"},
	{h: "#aid_chemicalburn", t: "Phỏng Hóa Chất"},
	{h: "#aid_chemicalburneyes", t: "Phỏng Hóa Chất (Mắt)"},
	{h: "#aid_sunburn", t: "Phỏng Nắng"},
	{h: "#aid_burningslight", t: "Phỏng Nhẹ"},
	{h: "#aid_burningsevere", t: "Phỏng Trầm Trọng"},
	{h: "#aid_snakebite", t: "Rắn Cắn"},
	{h: "#aid_resuscitation", t: "Reanimation"},
	{h: "#aid_birth", t: "Sinh Đẻ"},
	{h: "#aid_sos", t: "SOS Tín Hiệu Cầu Cứu (Save Our Soul)"},
	{h: "#aid_sunstroke", t: "Sốc Nắng"},
	{h: "#aid_asthma", t: "Suyễn"},
	{h: "#aid_shock", t: "Sự Kích Ngất"},
	{h: "#aid_suffocation", t: "Sự Ngộp Thở"},
	{h: "#aid_bleedingsevere", t: "Sự Ra Máu Nặng"},
	{h: "#aid_bleedinglight", t: "Sự Ra Máu Nhẹ"},
	{h: "#aid_frostbitesevere", t: "Sự Tê Cóng Nặng"},
	{h: "#aid_frostbitemild", t: "Sự Tê Cóng Nhẹ"},
	{h: "#aid_stroke", t: "Tai Biến Mạch Máu Não"},
	{h: "#aid_safeguardaccident", t: "Tai Nạn Giao Thông"},
	{h: "#aid_electricityaccident", t: "Tai Nạn Về Điện"},
	{h: "#aid_animalbite", t: "Thú Cắn"},
	{h: "#aid_amputation", t: "Thủ Thuật Cắt Cụt"},
	{h: "#aid_diarrhoea", t: "Tiêu Chảy"},
	{h: "#aid_unconsciouswithoutbreath", t: "Tình trạng bất tỉnh không hơi thở"},
	{h: "#aid_unconsciouswithbreath", t: "Tình trạng bất tỉnh với hơi thở"},
	{h: "#aid_sprain", t: "Trẹo + Trặc Gân"},
	{h: "#aid_poisining", t: "Trúng Độc"},
	{h: "#aid_resuscitation", t: "Tức Ngực"},
	{h: "#aid_recoveryposition", t: "Tư Thế Phục Hồi"},
	{h: "tel:112", t: "Call Emergency 112"}
];
var langSections={
	aid_disclaimer: [
		{k: "title", t: "Phủ nhận + Thông tin"},
		{k: "subsection", t: "Phần Mềm"},
		{k: "description", t: "Hướng dẫn cấp cứu trên điện thoại di động"},
		{k: "description", t: "Bản quyền: Kai Kajus Noack"},
		{k: "description", t: "Thông dịch: Thanh Dang + Vu Nguyen"},
		{k: "description", t: "Giấy phép: Creative Commons"},
		{k: "image", i: "cc88x31"},
		{k: "description", t: "Chương trình này được thiết kế để cung cấp thông tin về sơ cứu. Tuy nhiên, nó không có chức năng thay thế cho 1 khóa học cấp cứu. Thay vào đó, nó giúp bạn ôn lại những kiến thức về cấp cứu đã học được."},
		{k: "description", t: "tranh minh hoạ © Med4Teens"},
		{k: "subsection", t: "Phủ Nhận "},
		{k: "description", t: "Xin lưu ý rằng tôi không chịu trách nhiệm về những hậu quả xảy ra từ việc sử dụng các phần mềm."},
		{k: "description", t: "Bất kỳ trách nhiệm hữu là loại trừ!"},
		{k: "description", t: "Xử dụng tại rủi ro riêng của bạn!"},
		{k: "description", t: "Trong tất cả các trường hợp khẩn cấp, hãy tìm kiếm sự giúp đỡ chuyên môn ngay lập tức."},
		{k: "subsection", t: "Cứu một cuộc sống củng giống như bạn cứu cả trên thế giới."}
	],
	aid_general: [
		{k: "title", t: "Bước Tiến Hành Chung"},
		{k: "step", p: [{t: "Luôn luôn tiến hành sơ cứu, bạn không được phạm lỗi nào"}]},
		{k: "step", p: [{t: "Luôn luôn chú ý đến an toàn của riêng bạn."}]},
		{k: "step", p: [{t: "Kiểm tra tình hình an toàn và các nơi xảy ra tai nạn."}]},
		{k: "step", p: [{t: "Gọi cấp cứu và các pương pháp sơ cứu!"}]},
		{k: "step", p: [{t: "Nếu có nhiều người bị thương, bạn phải sơ cứu cho người bị nặng nhất"}]},
		{k: "step", p: [{t: "Giữ bình tĩnh cho những người có liên quan và cho chính bạn!"}]},
		{k: "step", p: [{t: "Nếu có thể, đặt nạn nhân nằm xuống 1 cách thoải mái. Tuyệt đối không cho nạn nhân của tai nạn uống rượu, nicotin hay các loại thuốc."}]}
	],
	aid_allergic: [
		{k: "title", t: "Dị ứng", i: "aid046"},
		{k: "step", p: [{t: "Điện thoại cho xe cứu thương ngay lập tức."}]},
		{k: "step", p: [{t: "Cố gắng giữ nạn nhân bình tĩnh và để nạn nhân ngồi một cách thoải mái"}]},
		{k: "step", p: [{t: "Lấy vật làm dị ứng ra (Vd: nọc ong)"}]},
		{k: "step", p: [{t: "Làm mát vùng da bị thương. (Băng ướt, nước đá')."}]},
		{k: "image", i: "aid046ice"},
		{k: "step", p: [{t: "Nếu nạn nhân có thuốc giải độc, giúp ông ta uống."}]},
		{k: "step", p: [{t: "Theo dõi tình hình nạn nhân cho đến khi xe cấp cứu tới."}]},
		{k: "step", p: [{t: "Nếu nạn nhân bất tỉnh hoặc ngừng thở, làm theo hướng dẫn thích hợp"}]},
		{k: "image", i: "aid077"}
	],
	aid_amputation: [
		{k: "title", t: "Thủ Thuật Cắt Cụt"},
		{k: "description", t: "Phần bị tách rời của cơ thể khi tai nạn có thể hàng gắn lại. Mục đích: Hãy giữ lạnh phần ấy cho đến khi bạn tới bệnh viện."},
		{k: "step", p: [{t: "Trấn tỉnh người đó. Đặt người đó nằm xuống và bao bọc lại với những cái mền."}]},
		{k: "step", p: [{t: "Chặn đứng sự ra máu, xem \"Sự Ra máu nặng\" và \"Sự Kích ngât\""}]},
		{k: "step", p: [{t: "Hãy gói phần bị tách rời ấy trong vải khô, sạch sẽ và để phần ấy vào trong bao bọc nhựa không thấm nước."}]},
		{k: "step", p: [{t: "Hãy cột bao nhựa ấy lại và để vào trong một bao nhựa khác có nước lạnh/nước đá."}]},
		{k: "step", p: [{t: "Không cho nạn nhân dùng rượu, thúc hút hay thức ăn ( khi cứu nạn nhân lúc mê man trong bệnh viện.)"}]},
		{k: "step", p: [{t: "Đừng để phần tách rời ấy bị đông cứng (chỉ giữ lạnh phần ấy thôi!)."}]},
		{k: "step", p: [{t: "Gọi cấp cứu hay mình tự đưa nạn nhân vào bệnh viện."}]}
	],
	aid_animalbite: [
		{k: "title", t: "Thú Cắn", i: "aid047"},
		{k: "description", t: "Chú ý: Khả năng nhiễm trùng cao, hậu quả có thể là nhiểm trùng, uốn ván, dại."},
		{k: "step", p: [{t: "Rửa vết thương với nước xà phòng nóng."}]},
		{k: "image", i: "aid049"},
		{k: "step", p: [{t: "Sau đó khử trùng vết thương."}]},
		{k: "step", p: [{t: "Nếu có chảy máu nặng, nâng cao phần thân trên của nạn nhân."}]},
		{k: "step", p: [{t: "Dán băng khử trùng."}]},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Đưa đến một bệnh viện hoặc gọi bác sĩ khẩn cấp."}]}
	],
	aid_apnoea: [
		{k: "title", t: "Ngừng Thở"},
		{k: "description", t: "Không có tiếng thở hoặc cơn thở, làng da bị biến màu rõ ràng."},
		{k: "step", p: [{t: "Gọi Khẩn Cấp."}]},
		{k: "step", p: [{t: "Đặt nạn nhân nằm trên lưng của ông/bà ta."}]},
		{k: "step", p: [{t: "Loại bỏ chất nhờn ra khỏi miệng và họng. Ngửa đầu ra phiá sau."}]},
		{k: "image", i: "aid067"},
		{k: "step", p: [{t: "Bóp cửa mũi lại với nhau để lổ mũi đóng lại."}]},
		{k: "image", i: "aid010"},
		{k: "step", p: [{t: "Hít một hơi thở thật sâu và áp miệng của bạn lên miệng của nạn nhân, không để hơi thóat ra ngoài."}]},
		{k: "image", i: "aid011"},
		{k: "step", p: [{t: "Thở hết hơi ra một cách chậm rãi và đầy ."}]},
		{k: "step", p: [{t: "Nếu không thành công: Thực hiện tiếp tục tiếp hơi trong khi chờ đợi xe cứu thương tới."}]}
	],
	aid_asthma: [
		{k: "title", t: "Suyễn"},
		{k: "description", t: "Thở nặng. Tiếng thở khò khè. Hồi hộp."},
		{k: "step", p: [{t: "Trấn an nạn nhân. Giữ bình tĩnh cho mình!"}]},
		{k: "step", p: [{t: "Nới lỏng quần áo."}]},
		{k: "step", p: [{t: "Hãy để nạn nhân ngồi dựa về phía trước, khuyẽn khích người đó thở chậm và sâu."}]},
		{k: "step", p: [{t: "Nạn nhân nên xài ống hút suyễn nếu có (giúp anh ta). Sau 5-10 phút, thuốc suyễn sẽ có hiệu lực."}]},
		{k: "image", i: "aid074"},
		{k: "step", p: [{t: "Nếu không có cải tiến: Sử dụng ống hút suyễn mỗi 5 phút cho đến khi xe cứu thương đến."}]},
		{k: "step", p: [{t: "Gọi khẩn cấp."}]},
		{k: "step", p: [{t: "Nếu ngừng thở, theo lời chỉ dẫn khi nạn nhân bị "}, {t: "ngừng thở", h: "#aid_apnoea"}, {t: "."}]}
	],
	aid_backinjury: [
		{k: "title", t: "Chấn Thương Lưng"},
		{k: "description", t: "Đau ở sau lưng, tê cánh tay và chân."},
		{k: "step", p: [{t: "Không di chuyển nạn nhân!!"}]},
		{k: "image", i: "aid064"},
		{k: "step", p: [{t: "Giữ cái đầu để nạn nhân nằm yên (giữ cái đầu một chỗ)"}]},
		{k: "image", i: "aid065"},
		{k: "step", p: [{t: "Ổn định nạn nhân với bolsters bên cạnh."}]},
		{k: "step", p: [{t: "Trấn an nạn nhân."}]},
		{k: "step", p: [{t: "Gọi khẩn cấp, chỉ ra thương tích sau lưng."}]}
	],
	aid_birth: [
		{k: "title", t: "Sinh Đẻ"},
		{k: "description", t: "Sự tiết ra của chất lỏng trong màng bọc thai nhi. Những cơn đau co lút xảy ra. Sinh nở ngoài ý muốn."},
		{k: "image", i: "aid025"},
		{k: "step", p: [{t: "Chú ý đến sự riêng tư và giữ bình tĩnh! - Gọi cấp cứu."}]},
		{k: "step", p: [{t: "Để người phụ nữ mang thai ở truồng phần dưới của cơ thể, và ngồi xuống trên một khoảng đất vô trùng với hai chân dang ra."}]},
		{k: "step", p: [{t: "Gấp đầu gối lại. Kéo hai chân dứơi lên trên. Lót ngửa cái chậu lớn nhẹ nhàng và o vị Trí'. - Sinh sản là một quá trình tự nhiên và diễn tiến hầu hết là không có biến chứng."}]},
		{k: "step", p: [{t: "Trấn tỉnh người phụ nữ, để bà ấy tập trung vào hơi thở: Thở vào qua mũi, thở ra thông qua miệng (ở tốc độ bình thường)."}]},
		{k: "step", p: [{t: "Nhịp nhấn: Lấy một hơi thở sâu, giữ hơi thở, và rặn. Chẳng bao lâu đầu em bé sẽ hiện ra, trợ giúp bằng cách giử lấy nó với cả hai tay của bạn."}]},
		{k: "image", i: "aid021"},
		{k: "image", i: "aid022"},
		{k: "step", p: [{t: "Sau khi sinh: Giữ em bé theo chiều nghiêng với đầu dốc xuống để xả hơi đường thông khí từ màng bọc thai nhi. (Có lẽ bạn cần phải hút ra chất lỏng từ mũi của em bé bằng miệng.) Em bé phải thở và khóc!"}]},
		{k: "step", p: [{t: "Buộc cuống rốn 30 cm từ đứa trẻ (cũng có thể được thực hiện trong bệnh viện). Giử âm đạo của người mẹ khô ráo."}]},
		{k: "image", i: "aid023"},
		{k: "step", p: [{t: "Lau khô Em bé' và giữ ấm nó. Lưu ý thời gian và lái xe đến bệnh viện."}]}
	],
	aid_bleedinglight: [
		{k: "title", t: "Sự Ra Máu Nhẹ", i: "aid082"},
		{k: "description", t: "Mục tiêu: Chặn đứng sự ra máu."},
		{k: "step", p: [{t: "Đừng đụng chạm tới vết thương (nguy cơ nhiễm trùng)."}]},
		{k: "step", p: [{t: "Đừng chữa trị vết thương với bột, thoa thuốc hoặc phun."}]},
		{k: "step", p: [{t: "Điều trị vết thương: che đậy với những vật liệu khô ráo và một băng dán."}]},
		{k: "image", i: "aid098"},
		{k: "step", p: [{t: "Nếu chảy máu nhẹ, đắp thuốc dán thường là đủ."}]},
		{k: "step", p: [{t: "Nếu vết thương lớn rộng, dùng một băng bọc thương tích và một băng dán. Đừng dán băng dán quá chặt, một sự dồn ứ có thể dẩn tới sự ra máu nhiều hơn."}]},
		{k: "image", i: "aid084"},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Lưu ý: Những vết thương bởi bị thú dại cắn phải được rửa với dung dịch xà bông."}]},
		{k: "image", i: "aid049"}
	],
	aid_bleedingsevere: [
		{k: "title", t: "Sự Ra Máu Nặng"},
		{k: "description", t: "Mạch máu văng bắn lên. Nguy hiểm: Ngộp thở vì mất máu, nhiễm trùng, chết. Mục tiêu: Chặn đứng sự ra máu."},
		{k: "step", p: [{t: "Cởi bỏ quần áo (cắt, nếu cần) và làm lộ vết thương."}]},
		{k: "step", p: [{t: "Quấn một băng vải hoặc nếu cần thiết một mảnh áo quần. Xiết chặt xung quanh vết thương."}]},
		{k: "image", i: "aid086"},
		{k: "step", p: [{t: "Cố gắng quấn chặt ít nhất 10 phút."}]},
		{k: "step", p: [{t: "Nếu băng vải đã thấm đầy máu, đừng tháo ra. Thay vào đó quấn một băng khác hay áo quần xung quanh nó."}]},
		{k: "step", p: [{t: "Đặt chân, tay bị ảnh hưởng (nếu không gãy) cao hơn tim để làm giãm lượng áp lực của máu. Nếu có thể, đặt bệnh nhân nằm dài xuống."}]},
		{k: "step", p: [{t: "Nếu máu chảy không ngừng, giữ áp lực trên vết thương, và đặt thêm điểm áp lực trên vết thương: Đối với chảy máu của cánh tay, đè ép phần phía trên cánh tay (nhấn mạch máu ở phía bên trong của cánh tay, ở giữa cùi chỏ và nách, xử dụng các ngón tay của bạn). Đối với chảy máu ở chân, đặt điểm áp lực ở háng (nhấn mạch máu ở nơi gập lại của háng, nơi mà động mạch nằm phía trên xương chậu, xử dụng lòng bàn tay của tay bạn)."}]},
		{k: "image", i: "aid089"},
		{k: "image", i: "aid092"},
		{k: "step", p: [{t: "Khẩn cấp gọi bác sĩ ngay lập tức."}]},
		{k: "step", p: [{t: "Chẳng bao lâu khi chảy máu được kiềm chế: bắt đầu các biện pháp cầm và đo máu."}]},
		{k: "image", i: "aid093"}
	],
	aid_brainconcussion: [
		{k: "title", t: "Chấn Động Não"},
		{k: "description", t: "Nhức đầu, buồn nôn, nôn mửa. Khiếm thị tầm nhìn. Tình trạng bất tỉnh có thể xảy ra."},
		{k: "image", i: "aid035a"},
		{k: "step", p: [{t: "Đặt nằm người có liên quan."}]},
		{k: "step", p: [{t: "Gọi khẩn cấp."}]},
		{k: "description", t: "Nếu chảy máu ở đầu:"},
		{k: "step", p: [{t: "Đặt người bị thương nằm xuống với vị trí đầu cao (trên gối)."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Thực hiện điều trị vết thương (xử dụng băng dán đầu)."}]},
		{k: "step", p: [{t: "Gọi cấp cứu."}]}
	],
	aid_burningslight: [
		{k: "title", t: "Phỏng Nhẹ"},
		{k: "description", t: "Da ửng đỏ. Phồng lên nhẹ. Đau."},
		{k: "step", p: [{t: "Giử vùng bị thương dưới nước lạnh."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Đặt băng uớt lên vết thương một cách lỏng lẻo."}]}
	],
	aid_burningsevere: [
		{k: "title", t: "Phỏng Trầm Trọng"},
		{k: "description", t: "Nhiều vùng nổi đốm trắng đỏ, da phồng lên. Da mất chất lỏng. Mô, tế bào tổn thương nặng. Đau dữ dội hoặc không đau (vì thần kinh bị đốt)."},
		{k: "image", i: "aid097"},
		{k: "step", p: [{t: "Cởi bỏ quần áo càng nhiều càng tốt."}]},
		{k: "step", p: [{t: "Làm mát những nơi bị phỏng với nước (khoảng 15 ° C, 59 ° F) lên đến 10 phút, cho đến khi giảm đau."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Nếu vết phỏng rộng, hãy dùng quần áo ướt để làm mát."}]},
		{k: "step", p: [{t: "Gọi cấp cứu."}]},
		{k: "step", p: [{t: "Sau khi làm mát, thực hiện điều trị vết thương: Xử dụng một băng khử trùng băng bó. Không áp dụng những chất lỏng (không dùng kem, dầu, dung dịch dầu v.v). Đừng đâm thấu qua những chổ bị phồng."}]},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Kiểm soát hơi thở và ý thức tỉnh của người bị thương cho đến khi bác sĩ cấp cứu đến."}]}
	],
	aid_checkbreathing: [
		{k: "title", t: "Kiểm Tra Hơi Thở"},
		{k: "step", p: [{t: "Kiểm tra tiếng thở."}]},
		{k: "step", p: [{t: "Chẩn đoán hơi thở ở phía trên bụng (đặt tay của bạn trên đó)."}]},
		{k: "image", i: "aid027"},
		{k: "step", p: [{t: "Cảm thấy hơi thở từ mũi và miệng."}]}
	],
	aid_chemicalburneyes: [
		{k: "title", t: "Phỏng Hóa Chất (Mắt)"},
		{k: "step", p: [{t: "Gọi cấp cứu, chỉ ra những loại hóa chất nào."}]},
		{k: "step", p: [{t: "Phun vô mắt với nhiều nước. Che con mắt lành mạnh trong lúc phun nước."}]},
		{k: "step", p: [{t: "Dẫn lực nước từ bên trong góc mắt đển bên ngoài góc mắt. Chùi rửa ít nhất 20 phút dưới nước sạch."}]},
		{k: "image", i: "aid019"},
		{k: "step", p: [{t: "Khép hai mắt của người bị thương và buộc lại với miếng vải ướt."}]},
		{k: "image", i: "aid020"},
		{k: "step", p: [{t: "Theo dỏi tình trạng cho đến khi xe cứu thương đến."}]}
	],
	aid_chemicalburn: [
		{k: "title", t: "Phỏng Hóa Chất"},
		{k: "description", t: "Thương tích của tế bào."},
		{k: "image", i: "aid095"},
		{k: "step", p: [{t: "Chú ý bảo vệ bản thân!"}]},
		{k: "step", p: [{t: "Hành động một cách nhanh chóng và rửa những nơi bị phỏng."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Gọi cấp cứu."}]},
		{k: "step", p: [{t: "Nếu có phỏng hóa chất thuộc vùng tiêu hoá, đặc biệt là ở miệng và cổ họng, uống thật nhiều nước."}]},
		{k: "step", p: [{t: "Đừng làm nôn mửa!"}]}
	],
	aid_dangerzone: [
		{k: "title", t: "Khu Vực Nguy Hiểm (Giải Cứu)"},
		{k: "step", p: [{t: "Tình huống thực hiện: Đặt một cánh tay của người bị thương trước ngực của anh/chị ấy, và đứng phía sau người đó."}]},
		{k: "step", p: [{t: "Đặt tay của bạn dưới vai của những người bị thương, nắm lấy khủy tay."}]},
		{k: "step", p: [{t: "Kéo trở lại và đem người ấy đến nơi an toàn."}]},
		{k: "image", i: "aid001"},
		{k: "image", i: "aid007"}
	],
	aid_diabeticcoma: [
		{k: "title", t: "Chứng Hôn Mê Của Tiểu Đường"},
		{k: "description", t: "Lượng đường trong máu ở mức quá cao (resp. thiếu insulin)."},
		{k: "description", t: "Những triệu chứng: khát, thường xuyên đi tiểu, buồn nôn, mửa. Hơi thở có mùi của các loại trái cây/rượu."},
		{k: "step", p: [{t: "Gọi cấp cứu."}]},
		{k: "step", p: [{t: "Giúp đở người bệnh (nếu xác nhận là bệnh tiểu đường) dùng insulin."}]},
		{k: "image", i: "aid016"},
		{k: "step", p: [{t: "Phục hồi tư thế.", h: "#aid_recoveryposition"}, {t: " (Người làm cấp cứu không thể làm gì hơn nữa.)"}]},
		{k: "step", p: [{t: "Giám sát tình trạng của người bệnh cho đến khi bác sĩ cấp cứu tới."}]}
	],
	aid_diarrhoea: [
		{k: "title", t: "Tiêu Chảy"},
		{k: "description", t: "Sự phản ứng của thức ăn nhiễm độc, nhiễm trùng của ruột hay rối loạn. Phân thì loãng, có bọt hoặc máu."},
		{k: "step", p: [{t: "Nguy hiểm cho sự lưu thông vì mất nước và thiếu muối !"}]},
		{k: "step", p: [{t: "Cho uống chất lỏng (trà, nước)."}]},
		{k: "step", p: [{t: "Nếu có rối loạn trầm trọng gọi khẩn cấp bác sĩ cấp cứu."}]}
	],
	aid_drowning: [
		{k: "title", t: "Chết Đuối"},
		{k: "step", p: [{t: "Gọi cấp cứu. Hỏi người xung quanh bạn để được giúp đỡ."}]},
		{k: "image", i: "aid032"},
		{k: "step", p: [{t: "Cứu người ra khỏi nước!"}]},
		{k: "image", i: "aid033"},
		{k: "image", i: "aid034"},
		{k: "step", p: [{t: "Nếu người bị nạn vẫn đang thở: "}, {t: "Phục hồi lại tư thế.", h: "#aid_recoveryposition"}, {t: " Giữ người đó ấm (bao bọc). Giám sát tình trạng cho tới khi bác sĩ cấp cứu đến."}]},
		{k: "step", p: [{t: "Nếu người bị nạn đã ngưng thở: Ngay lập tức bắt đầu làm cho sống lại. "}, {t: "(hồi sinh)", h: "#aid_resuscitation"}, {t: "! (Trục nước ra từ phổi thì vô ích.)"}]}
	],
	aid_electricityaccident: [
		{k: "title", t: "Tai Nạn Về Điện"},
		{k: "step", p: [{t: "Trước hết là cắt đứt các vật cung cấp điện!"}]},
		{k: "image", i: "aid045plug"},
		{k: "image", i: "aid045"},
		{k: "step", p: [{t: "Nguy hiểm: Bất tỉnh, ngừng thở cấp tính."}]},
		{k: "step", p: [{t: "A - Bất tỉnh nhưng vẫn còn thở", h: "#aid_unconsciouswithbreath"}]},
		{k: "step", p: [{t: "B - Bất tỉnh mà không thở", h: "#aid_unconsciouswithoutbreath"}]},
		{k: "image", i: "aid042"},
		{k: "image", i: "aid043"}
	],
	aid_emergencycall: [
		{k: "title", t: "Gọi Khẩn Cấp "},
		{k: "step", p: [{t: "Quay số 112 với những điện thoại sẳn sàng bên cạnh (Mỹ: 911). Luôn luôn có thể gọi và miễn phí!"}]},
		{k: "step", p: [{t: "Không ngần ngại gọi một xe cứu thương! Trên điện thoại, bạn phải cung cấp các thông tin sau:"}]},
		{k: "step", p: [{t: "- Điều gì đã xảy ra "}]},
		{k: "step", p: [{t: "- ở đâu (nơi xảy ra tai nạn) "}]},
		{k: "step", p: [{t: "- bao nhiêu người bị nạn "}]},
		{k: "step", p: [{t: "- những loại thương tích nào."}]},
		{k: "step", p: [{t: "Sau đó chờ những chỉ dẫn thêm hoặc những câu hỏi."}]}
	],
	aid_epilepsy: [
		{k: "title", t: "Bịnh Kinh Phong"},
		{k: "description", t: "Cứng ngắc cơ thể, bàn tay nắm chặt, ép hàm, chân tay hay mặt co rút. Mắt xoay tròn. Xùi bọt mép. Có thể bất tỉnh."},
		{k: "image", i: "aid058"},
		{k: "step", p: [{t: "Đừng giữ nạn nhân hoặc kềm chế cử động của họ."}]},
		{k: "step", p: [{t: "Đặt người bị nạn nằm trên một nền mềm (lót gối), di chuyển tới gần đối tượng để ngăn ngừa tự gây thương tích."}]},
		{k: "step", p: [{t: "Trấn tỉnh nạn nhân. Nới lỏng quần áo, cung cấp sự tự do để thở."}]},
		{k: "step", p: [{t: "Nếu nạn nhân nôn mửa, xoay đầu của họ sang bên cạnh để mửa có thể trào ra."}]},
		{k: "step", p: [{t: "Giữ cho đường hô hấp được thông suốt. Nguy hiểm về sự nuốt lưỡi."}]},
		{k: "step", p: [{t: "Phục hồi", h: "#aid_recoveryposition"}, {t: " tư thế + gọi cấp cứu. Tiếp tục giám sát tình trạng của nạn nhân."}]},
		{k: "step", p: [{t: "Giữ cho những người khác ở khoảng cách."}]}
	],
	aid_eyeinjury: [
		{k: "title", t: "Bị Thương Mắt"},
		{k: "step", p: [{t: "Để yên vật trong mắt của nạn nhân, đừng di chuyển nó."}]},
		{k: "step", p: [{t: "Giữ mắt đứng yên để tránh bị tổn thương thêm. Đừng chạm vào mắt."}]},
		{k: "step", p: [{t: "Nếu mắt bị chảy máu, che phủ nó với một băng vải hoặc một băng vải lưới đã sát trùng."}]},
		{k: "image", i: "aid020"},
		{k: "step", p: [{t: "Làm mát mắt với một miếng lót lạnh (làm giảm sưng, chảy máu ngưng nhanh hơn)."}]},
		{k: "step", p: [{t: "Gọi điện thoại cấp cứu hoặc bạn lái xe đưa nạn nhân đến bệnh viện ."}]}
	],
	aid_fracture: [
		{k: "title", t: "Gãy Xương"},
		{k: "description", t: "Triệu chứng: Vị trí không tự nhiên và di độ của xương. Làm biến hình. Đau đớn di chuyển, đụng chạm nhạy cảm."},
		{k: "image", i: "aid104"},
		{k: "step", p: [{t: "Tránh những sự di chuyển!"}]},
		{k: "step", p: [{t: "Gọi cấp cứu."}]},
		{k: "step", p: [{t: "Để yên chổ xương bị gãy ,i.e dùng vật liệu để chống hoăc kẹp chặt xung quanh xương. Giữ vị trí của xương."}]},
		{k: "image", i: "aid107"},
		{k: "step", p: [{t: "Nếu vết nứt bị hở, bao bọc vết thương với vật liệu khô ráo."}]},
		{k: "image", i: "aid106"}
	],
	aid_frostbitemild: [
		{k: "title", t: "Sự Tê Cóng Nhẹ"},
		{k: "description", t: "Tái xanh, sưng lên. Nguy hiểm cho cung cấp máu."},
		{k: "step", p: [{t: "Mang nạn nhân tới một nơi ấm áp."}]},
		{k: "step", p: [{t: "Tránh xa chổ lạnh, cởi bỏ quần áo lạnh, làm khô nạn nhân."}]},
		{k: "step", p: [{t: "Làm nóng người với nước ấm và với thân nhiệt của người giúp đỡ."}]},
		{k: "step", p: [{t: "Cho uống nước ấm (trà). Đừng cho uống rượu!"}]},
		{k: "image", i: "aid040"}
	],
	aid_frostbitesevere: [
		{k: "title", t: "Sự Tê Cóng Nặng"},
		{k: "description", t: "Da lạnh cứng, màu xám-trắng, phồng lên, tế bào chết đi. Nguy hiểm cho cung cấp máu!"},
		{k: "image", i: "aid096"},
		{k: "step", p: [{t: "Di chuyển tới khu vực ấm."}]},
		{k: "step", p: [{t: "Điều trị thương tích/bọc lại."}]},
		{k: "step", p: [{t: "Cho một thức uống có đường."}]},
		{k: "step", p: [{t: "Đừng chà xát nạn nhân để làm ấm họ!"}]},
		{k: "step", p: [{t: "Gọi cấp cứu."}]}
	],
	aid_heartattack: [
		{k: "title", t: "Đau Tim"},
		{k: "description", t: "Nặng, hơn 5 phút kéo dài áp lực và đau trong ngực, đặc biệt bức xạ trong cánh tay/vai. Lo lắng, tái mét, toát mồ hôi lạnh. Có thể là buồn nôn, thở dốc."},
		{k: "image", i: "aid076"},
		{k: "image", i: "aid083"},
		{k: "step", p: [{t: "Gọi cấp cứu! Chỉ ra chứng đau tim."}]},
		{k: "step", p: [{t: "Tư thế với cơ thể nâng cao. Nới lỏng quần áo chật. Không cho các lọai thuốc hoặc thức uống."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Nói chuyện một cách bình tĩnh với người bịnh."}]},
		{k: "step", p: [{t: "Kiểm soát sự mất ý thức và hơi thở."}]},
		{k: "step", p: [{t: "Cho aspirin nếu có."}]},
		{k: "step", p: [{t: "Nếu người đó trở nên bất tỉnh, bắt đầu làm "}, {t: "hồi sinh", h: "#aid_resuscitation"}, {t: "."}]}
	],
	aid_hypoglycaemia: [
		{k: "title", t: "Hypoglycaemia (thấp đường)"},
		{k: "description", t: "Lượng đường trong máu dưới mức tối thiểu (vì quá liều insulin hoặc không có đủ phần ăn của thực phẩm)."},
		{k: "description", t: "Triệu chứng: Tái xanh, hồi hộp, đói, rùng mình, toát mồ hôi."},
		{k: "image", i: "aid018"},
		{k: "step", p: [{t: "Xác định rằng người đó thì mắc bệnh tiểu đường (tìm kiếm dấu hiệu của bệnh tiểu đường)."}]},
		{k: "step", p: [{t: "Gọi cấp cứu."}]},
		{k: "step", p: [{t: "Cho một thức uống có đường và Dextrose/đường thực vật (nếu không bị khó khăn khi nuốt)."}]},
		{k: "image", i: "aid017"},
		{k: "step", p: [{t: "Nếu người đó tỉnh lại và thở: "}, {t: "Phục hồi tư thế", h: "#aid_recoveryposition"}, {t: ". Theo dõi hơi thở của họ. Nếu bị ngừng thở, bắt đầu với tiếp hơi."}]},
		{k: "step", p: [{t: "Nếu đang thở, bạn có thể đặt một cục đường vào bên trong má miệng, đẩy nó từ bên ngoài."}]}
	],
	aid_hyperthermia: [
		{k: "title", t: "Hyperthermia (thân nhiệt)"},
		{k: "description", t: "Khát, yếu đuối, rối loạn, buồn nôn, lầm lẩn, ra nhiều đổ mồ hôi, da nóng."},
		{k: "image", i: "aid035"},
		{k: "step", p: [{t: "Gọi cấp cứu."}]},
		{k: "step", p: [{t: "Tìm một nơi bóng râm mát mẻ (phòng với không khí lạnh càng tốt)."}]},
		{k: "step", p: [{t: "Đặt người đó nằm xuống, nâng cao chân. Nới lỏng quần áo."}]},
		{k: "image", i: "aid078"},
		{k: "step", p: [{t: "Làm mát da với nước lạnh hoặc nằm trên khăn lạnh."}]},
		{k: "step", p: [{t: "Cung cấp cho nhiều nước hay nước trái cây để uống."}]}
	],
	aid_hypothermia: [
		{k: "title", t: "Hạ Thân Nhiệt (mát cơ thể)"},
		{k: "description", t: "Ớn lạnh, mơ màng, kiệt sức đến bất tỉnh. Da tái lạnh. Mạch chậm, tim đập yếu."},
		{k: "image", i: "aid014"},
		{k: "step", p: [{t: "Đến một khu vực/phòng ấm áp."}]},
		{k: "step", p: [{t: "Gọi cấp cứu."}]},
		{k: "step", p: [{t: "Tăng nhiệt độ cơ thể lên (bao lại và cơ thể-tiếp xưc với cơ thể)."}]},
		{k: "step", p: [{t: "Cởi bỏ quần áo ướt và mặc vào quần áo ấm. Bao bọc lại với những cái mền hoặc những vật bao bọc khác. Bọc lấy đầu."}]},
		{k: "step", p: [{t: "Cho trà nóng , súp hoặc nước nóng để uống. Đừng cho uống rượu! Giữ người tỉnh thức."}]},
		{k: "image", i: "aid039"},
		{k: "image", i: "aid040"},
		{k: "step", p: [{t: "Quan sát tình trạng của nạn nhân cho đến khi bác sĩ cấp cứu tới. Nếu người đó bất tỉnh, bắt đầu làm hồi sinh:"}]},
		{k: "step", p: [{t: "A - Tình trạng bất tỉnh với thở", h: "#aid_unconsciouswithbreath"}]},
		{k: "step", p: [{t: "B - Tình trạng bất tỉnh mà không thở", h: "#aid_unconsciouswithoutbreath"}]}
	],
	aid_icerescue: [
		{k: "title", t: "Giải Cứu Trên Băng Đá"},
		{k: "description", t: "Chú ý đến sự an toàn của bạn. Nguy hiểm: sự chết đuối, hạ thân nhiệt."},
		{k: "step", p: [{t: "Hỏi những người khác giúp đở. Gọi cho một xe cứu thương cấp cứu."}]},
		{k: "step", p: [{t: "Giải cứu bằng cách dùng thang, tấm ván hoặc song cửa. Sức nặng phải dược phân bố một cách cân bằng"}]},
		{k: "step", p: [{t: "Bò cẩn thận trên bụng của bạn (nếu có thể cột lại tới một điểm cố định) với một cây sào hoặc dụng cụ tương tự."}]},
		{k: "image", i: "aid041"},
		{k: "step", p: [{t: "Với tới người đó với cây sào hoặc dụng cụ khác (không phải tay của bạn), khuyến khích ông/bà ấy nắm lấy nó và kéo ông/bà ấy ra."}]},
		{k: "step", p: [{t: "Bò ngược trở lại."}]},
		{k: "step", p: [{t: "Các biên pháp cứu thương."}]},
		{k: "step", p: [{t: "Tự cứu lấy bản thân: Nếu băng mà rắn , bạn có thể phân bố sức nặng của bạn trên băng và kéo mình ra . Trườn sấp trên bụng cho tới bờ. Nếu băng mà mỏng, cố gắng làm vở từng mảng từng mảng cho tới bờ."}]}
	],
	aid_insectstings: [
		{k: "title", t: "Côn Trùng Chích", i: "aid046"},
		{k: "description", t: "Sưng, da đay, cảm giác bị đốt, yếu đuối, khó thở, giảm ý thức, tim đập nhanh."},
		{k: "step", p: [{t: "Lấy kim độc ra một cách cẩn thận (với một cây nhíp). Đừng bóp kim độc như thế có thể chích thêm nọc độc."}]},
		{k: "step", p: [{t: "Làm mát chổ bị độc (áp lên một băng vải lạnh)."}]},
		{k: "step", p: [{t: "Khu vực có liên quan phải được giử thấp hơn tim để làm chậm lưu thông của chất độc."}]},
		{k: "step", p: [{t: "Nếu chất độc trong miệng/vùng hàm: mút kem, và dùng một băng vải lạnh quần xung quanh họng."}]},
		{k: "image", i: "aid046ice"},
		{k: "step", p: [{t: "Nếu vấn đề nghiêm trọng, sự khó khăn đáng kể trong hô hấp hoặc làm giảm sự nhận thức xảy ra gọi một xe cứu thương ngay lập tức."}]}
	],
	aid_nosebleeding: [
		{k: "title", t: "Chảy Máu Cam"},
		{k: "description", t: "Động mạch nhỏ vở ra trong mũi."},
		{k: "step", p: [{t: "Đặt người đó ngồi xuống, nghiêng nhẹ về phía trứơc. Giữ đầu thẳng."}]},
		{k: "step", p: [{t: "Đừng để tư thế nằm ngang, như đầu cao trên tim làm chậm chảy máu."}]},
		{k: "step", p: [{t: "Đặt những vật liệu lạnh xung quanh cổ (y phục ướt)."}]},
		{k: "step", p: [{t: "Bóp lổ mủi lại với nhau cho đến khi ngưng chảy máu (10 phút)."}]},
		{k: "step", p: [{t: "Sau đó đừng căng mũi (không khịt mủi)."}]},
		{k: "step", p: [{t: "Nếu vấn đề nghiêm trọng xảy ra hay chảy máu không thể ngừng lại, gọi bác sĩ cấp cứu."}]}
	],
	aid_poisining: [
		{k: "title", t: "Trúng Độc", i: "aid052"},
		{k: "description", t: "Rối lọan, ảo giác, con ngươi mắt lớn ra, sốt, gân rút. Bất tỉnh."},
		{k: "step", p: [{t: "Chỉ cho thuốc giải độc nếu bạn có theo một khóa huấn luyện cứu thương."}]},
		{k: "image", i: "aid056"},
		{k: "step", p: [{t: "Không cho thức uống. Đừng gây nôn mửa."}]},
		{k: "step", p: [{t: "Gọi cấp cứu + chỉ ra chất độc!"}]},
		{k: "step", p: [{t: "Bảo vệ an toàn tất cả chất độc và chất mửa!"}]},
		{k: "image", i: "aid054a"},
		{k: "step", p: [{t: "Nếu nạn nhân sáng suốt và thở: "}, {t: "Phục hồi tư thế", h: "#aid_recoveryposition"}, {t: ". Quan sát tình trạng cho đến khi bác sĩ cấp cứu đến."}]},
		{k: "step", p: [{t: "Nếu nạn nhân không thở: Ngay lập tức bắt đầu làm "}, {t: "hồi sinh!", h: "#aid_resuscitation"}, {t: " Nhớ lấy chất mửa ra khỏi miệng trước."}]}
	],
	aid_recoveryposition: [
		{k: "title", t: "Tư Thế Phục Hồi"},
		{k: "step", p: [{t: "Đặt nạn nhân nằm trên lưng bà/ông ấy, duỗi thẳng hai chân. Quỳ xuống bên cạnh ông/bà ấy'."}]},
		{k: "step", p: [{t: "Để cánh tay gần bạn nhất ở một góc phải với cơ thể."}]},
		{k: "step", p: [{t: "Kéo cánh tay xa hơn từ bạn chéo qua ngực và đặt lưng bàn tay trên má."}]},
		{k: "image", i: "aid008"},
		{k: "step", p: [{t: "Nắm lấy đầu gối phía xa, kéo nó về phía bạn, và đặt nằm trên mặt đất. Vị trí của chân ở góc bên phải. Giữ tay của nạn nhân dưới má của người đó."}]},
		{k: "step", p: [{t: "Hãy chắc chắn rằng đường hô hấp được thông suốt."}]},
		{k: "step", p: [{t: "Mở hé miệng, và lấy tư thế đầu qua bên cạnh để chất mữa trào ra. Theo dỏi hơi thở."}]},
		{k: "image", i: "aid009"},
		{k: "step", p: [{t: "Kiểm soát tình trạng của nạn nhân cho tới khi bác sĩ cấp cứu đến."}]},
		{k: "description", t: "Phục hồi tư thế cho em bé:"},
		{k: "image", i: "aid028"}
	],
	aid_resuscitation: [
		{k: "title", t: "Hồi Sinh"},
		{k: "subsection", t: "# Xoa Bóp Tim"},
		{k: "step", p: [{t: "Đặt nạn nhân nằm trên lưng ông ấy/bà ấy. Quỳ xuống bên cạnh họ."}]},
		{k: "step", p: [{t: "Ngực để trần."}]},
		{k: "step", p: [{t: "Đặt cườm tay ở giữa ngực (chỉ hơn xương ức)."}]},
		{k: "image", i: "aid013"},
		{k: "step", p: [{t: "Đặt tay kia trên phía sau bàn tay mà đã ở trong vị trí."}]},
		{k: "step", p: [{t: "Duỗi thẳng cánh tay và cùi chỏ."}]},
		{k: "image", i: "aid003"},
		{k: "step", p: [{t: "Nhấn sâu 5 cm vào ngực của người đó (sức lực đến từ phần trên của cơ thể) rồi thả lỏng cánh tay."}]},
		{k: "step", p: [{t: "Nhấn 30 lần một cách ngắn và mạnh!"}]},
		{k: "subsection", t: "# Sự Thở"},
		{k: "step", p: [{t: "Loại bỏ những chất trong miệng ra khỏi miệng và họng. Ngửa đầu ra phía sau."}]},
		{k: "image", i: "aid067"},
		{k: "step", p: [{t: "Bóp cửa mũi lại với nhau để lổ mũi đóng lại."}]},
		{k: "image", i: "aid010"},
		{k: "step", p: [{t: "Hít một hơi thở thật sâu và đặt miệng bạn lên miệng của nạn nhân, đừng để không khí xì ra."}]},
		{k: "image", i: "aid011"},
		{k: "step", p: [{t: "Thực hành cách thở miệng-áp-miệng hai lần (hơi thở ra chậm và đầy)."}]},
		{k: "step", p: [{t: "Sau đó thực hành xoa bóp tim lần nửa."}]},
		{k: "description", t: "Xoa tim lại + làm hô hấp bằng miệng cho đến khi bác sĩ cấp cứu đến."},
		{k: "image", i: "aid012"},
		{k: "subsection", t: "Làm hồi sinh (Em Bé)"},
		{k: "step", p: [{t: "chỉ dùng 2 ngón tay"}]},
		{k: "image", i: "aid029"},
		{k: "step", p: [{t: "Đừng thở manh quá:"}]},
		{k: "image", i: "aid030"}
	],
	aid_safeguardaccident: [
		{k: "title", t: "An Toàn Tai Nạn"},
		{k: "step", p: [{t: "Dừng xe hơi của bạn 50-100 m phía sau nơi tai nạn xảy ra (nếu bạn đang trên một đường cao tốc hoặc đường quê). Chuyển sang đèn cảnh báo. Mặc áo mà có thể được thấy từ xa."}]},
		{k: "step", p: [{t: "Đặc cái tam giác cảnh cáo trước nơi xãy ra tai nạn. Lưu ý: Nếu tai nạn xãy ra trên đường cong, đặc cái tam giác cảnh cáo trước đường cong!"}]},
		{k: "image", i: "aid111"},
		{k: "step", p: [{t: "Yêu cầu những người khác giúp đỡ."}]},
		{k: "step", p: [{t: "Mở cửa xe bị nạn (nếu bị kẹt, bẩy nó ra bằng cách xử dụng một con đội). Tắt máy."}]},
		{k: "step", p: [{t: "Cứu nạn nhân bị tai nạn: Cởi tháo dây seat-belt, đẩy ghế ngồi ra phía sau. Cứu nạn nhân ra khỏi xe bằng phương pháp giải "}, {t: "cứu ôm chặt", h: "#aid_dangerzone"}, {t: "."}]},
		{k: "image", i: "aid001"},
		{k: "step", p: [{t: "Gọi cấp cứu."}]},
		{k: "step", p: [{t: "Tiến hành các biện pháp cứu thương."}]}
	],
	aid_shock: [
		{k: "title", t: "Sự Kích Ngất"},
		{k: "description", t: "Rối loạn tuần hoàn do cung cấp dưỡng khí xấu trong cơ thể."},
		{k: "description", t: "Nguyên nhân: mất chất lỏng, lượng máu giảm."},
		{k: "description", t: "Triệu chứng: Da tái, da lạnh, mồ hôi lạnh, lo lắng."},
		{k: "step", p: [{t: "Loại bỏ những nguyên nhân của shock (ví dụ như chặn đứng sự mất mát các chất lỏng, băng bó vết thương)!"}]},
		{k: "step", p: [{t: "Đặt người bị thương trên một cái chăn, vị trí của chân lên cao. Trấn tỉnh người đó."}]},
		{k: "image", i: "aid078"},
		{k: "step", p: [{t: "Gọi cấp cứu."}]},
		{k: "step", p: [{t: "Nếu bị khó khăn trong lúc thở hay mất ý thức, bắt đầu phương pháp "}, {t: "hồi sinh", h: "#aid_resuscitation"}, {t: "."}]}
	],
	aid_skullfracture: [
		{k: "title", t: "Nứt Xương Sọ"},
		{k: "description", t: "Chảy máu ở nhẹ mũi, miệng hoặc tai. Thường là các vết thương mở miệng trên sọ."},
		{k: "step", p: [{t: "Giử đường hô hấp thông suốt."}]},
		{k: "step", p: [{t: "Nếu tỉnh táo: Hãy để người bị thương ngồi với đầu cúi ra phía trứơc. Tránh di chuyển xa hơn!"}]},
		{k: "step", p: [{t: "Nếu bất tỉnh: "}, {t: "Phục hồi", h: "#aid_recoveryposition"}, {t: " tư thế (đừng đặt áp lực lên vết thương trên đầu)."}]},
		{k: "step", p: [{t: "Gọi cấp cứu."}]},
		{k: "step", p: [{t: "Băng bó đầu lại."}]},
		{k: "step", p: [{t: "Nếu bị khó khăn trong sự hô hấp hay bất tỉnh, bắt đầu phương pháp "}, {t: "hồi sinh", h: "#aid_resuscitation"}, {t: "."}]}
	],
	aid_snakebite: [
		{k: "title", t: "Rắn Cắn", i: "aid051"},
		{k: "description", t: "Vết thương bị đâm nhỏ, đau nặng, sưng lên, màu tím. Tuần hoàn rối loạn, nguy cơ bị sốc."},
		{k: "step", p: [{t: "Giữ yên phần bị thương của cơ thể."}]},
		{k: "step", p: [{t: "Xử dụng vật liệu lạnh bao xung quanh vết thương bị cắn."}]},
		{k: "step", p: [{t: "Các biện pháp chống bị sốc."}]},
		{k: "step", p: [{t: "Gọi cấp cứu."}]}
	],
	aid_sos: [
		{k: "title", t: "SOS Tín Hiệu Cầu Cứu (Save Our Soul)"},
		{k: "step", p: [{t: "Tín hiệu: 3x ngắn, dài 3x, 3x ngắn."}]},
		{k: "step", p: [{t: "Thị giác (đèn bão, đèn \"pin\"), hoặc thính giác (tín hiệu còi, gỏ)."}]}
	],
	aid_sprain: [
		{k: "title", t: "Trẹo + Trặc Gân"},
		{k: "description", t: "Đau, sưng (bầm), sự mất chức năng, sự biến hình của chân tay."},
		{k: "step", p: [{t: "Đặt phần bị thương của cơ thể ở vị trí thoải mái nhất cho nạn nhân."}]},
		{k: "step", p: [{t: "Làm mát (bằng cách xử dụng những bịch nước đá )."}]},
		{k: "step", p: [{t: "Nếu có thể, nâng cao vị trí phần bị thương."}]},
		{k: "step", p: [{t: "Đưa đến bệnh viện hoặc gọi bác sĩ cấp cứu."}]}
	],
	aid_stroke: [
		{k: "title", t: "Tai Biến Mạch Máu Não"},
		{k: "description", t: "Bất thình lình bị cảm giác như tê liệt hoặc tê cóng (mặt, cánh tay, chân), bối rối trong sự hiểu biết ngôn ngữ, thị giác bị khó khăn, rối loạn ý thức, nhức đầu trầm trọng. Những vấn đề trong sự hô hấp và nuốt, mất kiểm soát của bọng đái và ruột."},
		{k: "image", i: "aid059"},
		{k: "step", p: [{t: "Gọi cấp cứu!"}]},
		{k: "step", p: [{t: "Nới lỏng quần áo chật. Đừng cho các loại thuốc hoặc thức uống."}]},
		{k: "step", p: [{t: "Cho người đó ngồi hay nằm xuống một cách thoải mái. Trấn an anh/chị ấy!"}]},
		{k: "step", p: [{t: "Kiểm soát sự thức tỉnh và sự thở."}]},
		{k: "step", p: [{t: "Nếu gặp những khó khăn trong sự thở hay giảm ý thức, bắt đầu phương pháp "}, {t: "hồi sinh", h: "#aid_resuscitation"}, {t: "."}]}
	],
	aid_suffocation: [
		{k: "title", t: "Sự Ngộp Thở"},
		{k: "description", t: "Cung cấp không đủ dưỡng khí. Khí quản bị đóng. Nguy hiểm: chứng ngừng thở."},
		{k: "description", t: "Triệu chứng: Tiếng hô hấp phát ra khò khè, kích thích ho, thở dốc, da mất màu."},
		{k: "image", i: "aid066"},
		{k: "step", p: [{t: "Hành động ngay lập tức! Để cho người bị nạn ho thật mạnh."}]},
		{k: "step", p: [{t: "Đánh mạnh với bàn tay phẳng lên lưng ở giửa bả vai (đặt em bé nằm trên cánh tay trước của bạn, với đầu chúi xuống)."}]},
		{k: "image", i: "aid068"},
		{k: "image", i: "aid031"},
		{k: "step", p: [{t: "Nếu không thành công: đứng đằng sau người đó, choàng tay xung quanh thắt lưng, cúi về phía trước một chút."}]},
		{k: "step", p: [{t: "Nắm chặt tay lại, đặt ở vị trí cao của dạ dày người đó, và nắm lấy bàn tay kia."}]},
		{k: "image", i: "aid069"},
		{k: "step", p: [{t: "Trong lúc ôm, xử dụng cả hai tay để cho một thổ mạnh lên trên phía bao tử (như bạn cố gắng để nâng người đó)."}]},
		{k: "step", p: [{t: "Làm lại như vậy 5 lần! Đường hô hấp sẽ được thông suốt."}]},
		{k: "step", p: [{t: "Gọi cấp cứu."}]},
		{k: "step", p: [{t: "Nếu phương pháp cứu chửa không thành công ở bước đầu, tiếp tục làm cho đến khi bác sĩ cấp cứu đến."}]}
	],
	aid_sunburn: [
		{k: "title", t: "Phỏng Nắng"},
		{k: "step", p: [{t: "Di chuyển người bị ảnh hưởng ra khỏi ánh sáng mặt trời. Tránh xa ánh nắng."}]},
		{k: "step", p: [{t: "Uống nhiều nước để ngừng mất nước."}]},
		{k: "step", p: [{t: "Nếu đó là phỏng nắng nghiêm trọng (phồng lên, đỏ, đau), tìm kiếm lời khuyên y tế."}]},
		{k: "step", p: [{t: "Nếu da chỉ màu đỏ nhạt, nó có thể được làm mát với băng vải ướt. Xử dụng sau đó lotion hoặc gel."}]}
	],
	aid_sunstroke: [
		{k: "title", t: "Sốc Nắng"},
		{k: "description", t: "Đầu nóng đỏ, da mát, bệnh tật, nhức đầu, chóng mặt. Nguyên nhân: sự đau nhức của các màng não mỏng."},
		{k: "image", i: "aid035"},
		{k: "step", p: [{t: "Đến một nơi thoáng mát (bóng râm) và đặt phần trên cơ thể của người bịnh lên cao."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Làm mát đầu với chăn ướt."}]},
		{k: "step", p: [{t: "Gọi cấp cứu, tiếp tục kiểm soát hơi thở."}]},
		{k: "step", p: [{t: "Nếu tỉnh táo: Cho uống nước lạnh nếu được."}]},
		{k: "step", p: [{t: "Nếu chứng ngưng thở xuất hiện, bắt đầu với hơi thở:"}]},
		{k: "step", p: [{t: "Tiếp tục với phương pháp tiếp hơi thở!", h: "#aid_apnoea"}]},
		{k: "image", i: "aid036"}
	],
	aid_unconsciouswithbreath: [
		{k: "title", t: "Tình trạng bất tỉnh với hơi thở"},
		{k: "description", t: "Không phản ứng trên sự hỏi lớn tiếng, không trả lời khi bị lắc. Có hơi thở."},
		{k: "image", i: "aid057"},
		{k: "step", p: [{t: "Nếu có người bên cạnh bạn yêu cầu được giúp đỡ."}]},
		{k: "step", p: [{t: "Phục hồi tư thế.", h: "#aid_recoveryposition"}, {t: " Mở miệng và giữ cái đầu để chất mửa có thể chảy ra."}]},
		{k: "image", i: "aid008"},
		{k: "image", i: "aid009"},
		{k: "step", p: [{t: "Gọi cấp cứu."}]}
	],
	aid_unconsciouswithoutbreath: [
		{k: "title", t: "Tình trạng bất tỉnh không hơi thở"},
		{k: "step", p: [{t: "Không có phản ứng của nạn nhân, không có hơi thở."}]},
		{k: "image", i: "aid057"},
		{k: "step", p: [{t: "Bắt đầu làm "}, {t: "hồi sinh", h: "#aid_resuscitation"}, {t: "."}]}
	],
	aid_vomiting: [
		{k: "title", t: "ói Mửa"},
		{k: "description", t: "Phát sinh từ buồn nôn. Dạ dày tự trống rỏng. Nguyên nhân: Viêm nhiễm, ngộ độc, ung nhọt, các loại thuốc, thức ăn xấu, mang thai."},
		{k: "image", i: "aid054"},
		{k: "step", p: [{t: "Nguy hiểm cho lưu thông vì mất nước và thiếu muối!"}]},
		{k: "step", p: [{t: "Cho các loại nước (trà, nước lọc)."}]},
		{k: "step", p: [{t: "Nếu có những rối loạn mạnh, ra máu hoặc tiếp tục nôn mửa gọi cho bác sĩ cấp cứu."}]}
	]
};
var langContinents=[
	{i: "Northamerica", t: "Bắc Mỹ"},
	{i: "Asia", t: "Châu á"},
	{i: "Europe", t: "Châu âu"},
	{i: "Oceania", t: "Châu Đại Dương"},
	{i: "Africa", t: "Châu Phi"},
	{i: "Southamerica", t: "Nam-Mỹ"}
];
var langCountries=[
	{i: "afghanistan", t: "Afghanistan"},
	{i: "egypt", t: "Ai Cập"},
	{i: "ireland", t: "Ai Len"},
	{i: "albania", t: "Albania"},
	{i: "algeria", t: "Algérie"},
	{i: "andorra", t: "Andorra"},
	{i: "angola", t: "Angola"},
	{i: "antiguaandbarbuda", t: "Antigua và Barbuda"},
	{i: "austria", t: "áo"},
	{i: "saudiarabia", t: "Ả Rập Saudi"},
	{i: "argentina", t: "Argentina"},
	{i: "armenia", t: "Armenia"},
	{i: "azerbaijan", t: "Azerbaijan"},
	{i: "india", t: "Ấn Độ"},
	{i: "bahamas", t: "Bahamas"},
	{i: "bahrain", t: "Bahrain"},
	{i: "poland", t: "Ba Lan"},
	{i: "barbados", t: "Barbados"},
	{i: "northkorea", t: "Bắc Triều Tiên"},
	{i: "bangladesh", t: "Băng-la-đét"},
	{i: "belarus", t: "Belarus"},
	{i: "belize", t: "Belize"},
	{i: "benin", t: "Bê-nanh"},
	{i: "bhutan", t: "Bhutan"},
	{i: "belgium", t: "Bỉ"},
	{i: "bolivia", t: "Bolivia"},
	{i: "bosniaandherzegovina", t: "Bosnia và Herzegovina"},
	{i: "botswana", t: "Botswana"},
	{i: "portugal", t: "Bồ Đào Nha"},
	{i: "ivorycoast", t: "Bờ biển Ngà"},
	{i: "brazil", t: "Brazil"},
	{i: "brunei", t: "Brunei"},
	{i: "bulgaria", t: "Bungari"},
	{i: "burkinafaso", t: "Burkina Faso"},
	{i: "burundi", t: "Bu-run-đi"},
	{i: "cameroon", t: "Cameroon"},
	{i: "cambodia", t: "Cam-pu-chia"},
	{i: "canada", t: "Canada"},
	{i: "capeverde", t: "Cape Verde"},
	{i: "chad", t: "Chad"},
	{i: "chile", t: "Chile"},
	{i: "colombia", t: "Colombia"},
	{i: "comoros", t: "Comoros"},
	{i: "congorepublic", t: "Congo (Cộng hoà)"},
	{i: "congodemocraticrepublic", t: "Congo (Cộng hòa Dân chủ)"},
	{i: "costarica", t: "Costa Rica"},
	{i: "sahrawiarabdemocraticrepublic", t: "Cộng hòa Dân chủ Ả Rập Sahrawi"},
	{i: "dominicanrepublic", t: "Cộng hoà Dominica"},
	{i: "czechrepublic", t: "Cộng hòa Séc"},
	{i: "centralafricanrepublic", t: "Cộng hòa Trung Phi"},
	{i: "croatia", t: "Croatia"},
	{i: "cuba", t: "Cuba"},
	{i: "dominica", t: "Dominica"},
	{i: "taiwan", t: "Đài Loan"},
	{i: "denmark", t: "Đan Mạch"},
	{i: "easttimor", t: "Đông Timor"},
	{i: "germany", t: "Đức"},
	{i: "ecuador", t: "Ecuador"},
	{i: "elsalvador", t: "El Salvador"},
	{i: "equatorialguinea", t: "Equatorial Guinea"},
	{i: "eritrea", t: "Eritrea"},
	{i: "estonia", t: "Estonia"},
	{i: "ethiopia", t: "Etiopia"},
	{i: "gabon", t: "Ga-bông"},
	{i: "gambia", t: "Gambia"},
	{i: "georgia", t: "Georgia"},
	{i: "guinea", t: "Ghi-nê"},
	{i: "djibouti", t: "Gi-bu-ti"},
	{i: "greenland", t: "Greenland"},
	{i: "grenada", t: "Grê-na-đa"},
	{i: "guatemala", t: "Guatemala"},
	{i: "guinea-bissau", t: "Guinea-Bissau"},
	{i: "guyana", t: "Guy-a-na"},
	{i: "haiti", t: "Haiti"},
	{i: "netherlands", t: "Hà Lan"},
	{i: "southkorea", t: "Hàn Quốc (Cộng hòa Hàn Quốc)"},
	{i: "honduras", t: "Honduras"},
	{i: "hongkong", t: "Hồng Kông"},
	{i: "hungary", t: "Hungary"},
	{i: "greece", t: "Hy Lạp"},
	{i: "iceland", t: "Iceland"},
	{i: "indonesia", t: "Indonesia"},
	{i: "iran", t: "Iran"},
	{i: "iraq", t: "Iraq"},
	{i: "jamaica", t: "Jamaica"},
	{i: "jordan", t: "Jordan"},
	{i: "kazakhstan", t: "Kazakhstan"},
	{i: "kenya", t: "Kenya"},
	{i: "kiribati", t: "Kiribati"},
	{i: "kosovo", t: "Kosovo"},
	{i: "kurdistan", t: "Kurdistan"},
	{i: "kuwait", t: "Kuwait"},
	{i: "kyrgyzstan", t: "Kyrgyzstan"},
	{i: "laos", t: "Lào"},
	{i: "latvia", t: "Latvia"},
	{i: "lesotho", t: "Lesotho"},
	{i: "lebanon", t: "Li-băng"},
	{i: "liberia", t: "Liberia"},
	{i: "libya", t: "Libya"},
	{i: "liechtenstein", t: "Liechtenstein"},
	{i: "lithuania", t: "Lithuania"},
	{i: "luxembourg", t: "Luxembourg"},
	{i: "macau", t: "Macau"},
	{i: "macedonia", t: "Macedonia"},
	{i: "madagascar", t: "Madagascar"},
	{i: "malawi", t: "Ma-la-uy"},
	{i: "malaysia", t: "Malaysia"},
	{i: "maldives", t: "Maldives"},
	{i: "mali", t: "Ma-li"},
	{i: "malta", t: "Malta"},
	{i: "morocco", t: "Ma rốc"},
	{i: "mauritania", t: "Mauritanie"},
	{i: "mauritius", t: "Mauritius"},
	{i: "mayotte", t: "Mayotte"},
	{i: "mexico", t: "Mexico"},
	{i: "micronesia", t: "Micronesia"},
	{i: "moldova", t: "Moldova"},
	{i: "montenegro", t: "Montenegro"},
	{i: "mozambique", t: "Mô-dăm-bích"},
	{i: "monaco", t: "Mô-na-cô"},
	{i: "mongolia", t: "Mông Cổ"},
	{i: "myanmar", t: "Myanmar"},
	{i: "namibia", t: "Namibia"},
	{i: "southafrica", t: "Nam Phi"},
	{i: "nauru", t: "Nauru"},
	{i: "norway", t: "Na Uy"},
	{i: "nepal", t: "Nepal"},
	{i: "newzealand", t: "New Zealand"},
	{i: "russia", t: "Nga"},
	{i: "japan", t: "Nhật Bản"},
	{i: "nicaragua", t: "Nicaragua"},
	{i: "nigeria", t: "Nigeria"},
	{i: "niger", t: "Ni-giê"},
	{i: "oman", t: "ô-man"},
	{i: "pakistan", t: "Pakistan"},
	{i: "palau", t: "Palau"},
	{i: "panama", t: "Panama"},
	{i: "papuanewguinea", t: "Papua New Guinea"},
	{i: "paraguay", t: "Paraguay"},
	{i: "peru", t: "Peru"},
	{i: "france", t: "Pháp"},
	{i: "finland", t: "Phần Lan"},
	{i: "fiji", t: "Phi-gi"},
	{i: "philippines", t: "Philippines"},
	{i: "qatar", t: "Qatar"},
	{i: "caymanislands", t: "Quần đảo Cayman"},
	{i: "marshallislands", t: "Quần đảo Marshall"},
	{i: "solomonislands", t: "Quần đảo Solomon"},
	{i: "reunion", t: "Réunion"},
	{i: "romania", t: "Romania"},
	{i: "rwanda", t: "Ru-an-đa"},
	{i: "stkittsandnevis", t: "Saint Kitts và Nevis"},
	{i: "stlucia", t: "Saint Lucia"},
	{i: "saintpierreandmiquelon", t: "Saint-Pierre và Miquelon"},
	{i: "stvincentandgrenadines", t: "Saint Vincent và Grenadines"},
	{i: "samoa", t: "Samoa"},
	{i: "sanmarino", t: "San Marino"},
	{i: "saotomeandprincipe", t: "Sao Tomé và Principe"},
	{i: "senegal", t: "Senegal"},
	{i: "serbia", t: "Serbia"},
	{i: "sierraleone", t: "Sierra Leone"},
	{i: "singapore", t: "Singapore"},
	{i: "cyprus", t: "Síp"},
	{i: "slovakia", t: "Slovakia"},
	{i: "slovenia", t: "Slovenia"},
	{i: "srilanka", t: "Sri Lanka"},
	{i: "swaziland", t: "Swaziland"},
	{i: "syria", t: "Syria"},
	{i: "tajikistan", t: "Tajikistan"},
	{i: "tanzania", t: "Tanzania"},
	{i: "spain", t: "Tây Ban Nha"},
	{i: "thailand", t: "Thái Lan"},
	{i: "vaticancity", t: "Thành phố Vatican"},
	{i: "turkey", t: "Thổ Nhĩ Kỳ"},
	{i: "sweden", t: "Thụy Điển"},
	{i: "switzerland", t: "Thụy Sĩ"},
	{i: "togo", t: "Tô-gô"},
	{i: "tonga", t: "Tông-ga"},
	{i: "trinidadandtobago", t: "Trinidad và Tobago"},
	{i: "china", t: "Trung Quốc"},
	{i: "tunisia", t: "Tunisia"},
	{i: "turkmenistan", t: "Turkmenistan"},
	{i: "tuvalu", t: "Tu-va-lu"},
	{i: "australia", t: "úc"},
	{i: "uganda", t: "Uganda"},
	{i: "ukraine", t: "Ukraina"},
	{i: "unitedarabemirates", t: "United Arab Emirates"},
	{i: "unitedstatesofamerica", t: "United States of America"},
	{i: "uruguay", t: "Uruguay"},
	{i: "uzbekistan", t: "Uzbekistan"},
	{i: "vanuatu", t: "Vanuatu"},
	{i: "venezuela", t: "Venezuela"},
	{i: "ghana", t: "Viet-Nam"},
	{i: "vietnam", t: "Việt Nam"},
	{i: "unitedkingdom", t: "Vương quốc Anh"},
	{i: "seychelles", t: "Xây-sen"},
	{i: "somalia", t: "Xô-ma-li"},
	{i: "sudan", t: "Xu-đăng"},
	{i: "suriname", t: "Xu-ri-nam"},
	{i: "italy", t: "ý"},
	{i: "yemen", t: "Y-ê-men"},
	{i: "israel", t: "Y-sơ"},
	{i: "zambia", t: "Zambia"},
	{i: "zimbabwe", t: "Zimbabwe"}
];
