//:Premiers Secours
// Generated file, do not edit
var langTexts={
	title: "Premiers Secours",
	back: "Retour",
	continent: "Continent",
	emergency_fire: "Incendie",
	emergency_medical: "Ambulance",
	emergency_police: "Police",
	emergency_cancelcard: "",
	emergency_local: "Numéro Local",
	emergency_nosystem: "Pas de système",
	emergency_radioonly: "Radio téléphone seulement",
	emergency_none: "--",
	emergency_or: "ou",
	emergency_mobile: "portable",
	emergency_tourist: "touristes"
};
var langMenu=[
	{h: "#aid_disclaimer", t: "# Responsabilité + Info"},
	{h: "#numbers", t: "# Appels d'urgence"},
	{h: "#aid_general", t: "# Conduite générale"},
	{h: "#aid_safeguardaccident", t: "Accident de voiture"},
	{h: "#aid_birth", t: "Accouchement"},
	{h: "#aid_allergic", t: "Allergie"},
	{h: "#aid_amputation", t: "Amputation"},
	{h: "#aid_emergencycall", t: "Appelez les services d'urgence"},
	{h: "#aid_apnoea", t: "Arrêt respiratoire"},
	{h: "#aid_asthma", t: "Asthme"},
	{h: "#aid_chemicalburn", t: "Brûlure chimique"},
	{h: "#aid_chemicalburneyes", t: "Brûlure chimique (yeux)"},
	{h: "#aid_burningsevere", t: "Brûlure grave"},
	{h: "#aid_burningslight", t: "Brûlure légère"},
	{h: "#aid_frostbitesevere", t: "Brûlure par le froid - grave"},
	{h: "#aid_frostbitemild", t: "Brûlure par le froid - léger"},
	{h: "#aid_shock", t: "Choc (Hémorragies)"},
	{h: "#aid_diabeticcoma", t: "Coma diabétique"},
	{h: "#aid_brainconcussion", t: "Commotion cérébrale"},
	{h: "#aid_resuscitation", t: "Compression du thorax"},
	{h: "#aid_sunburn", t: "Coup de soleil"},
	{h: "#aid_heartattack", t: "Crise Cardiaque"},
	{h: "#aid_dangerzone", t: "Dégagement d'urgence"},
	{h: "#aid_diarrhoea", t: "Diarrhées"},
	{h: "#aid_backinjury", t: "Dos - Blessure"},
	{h: "#aid_electricityaccident", t: "Électrocution"},
	{h: "#aid_sprain", t: "Entorse"},
	{h: "#aid_epilepsy", t: "Épilepsie"},
	{h: "#aid_asthma", t: "Essoufflement"},
	{h: "#aid_suffocation", t: "Etouffement / Étranglement"},
	{h: "#aid_fracture", t: "Fracture"},
	{h: "#aid_skullfracture", t: "Fracture du crâne"},
	{h: "#aid_backinjury", t: "Fracture du dos"},
	{h: "#aid_diabeticcoma", t: "Hyperglycémie (forte teneur en sucre)"},
	{h: "#aid_hyperthermia", t: "Hyperthermie (corps trop chaud)"},
	{h: "#aid_hypoglycaemia", t: "Hypoglycémie (faible teneur en sucre)"},
	{h: "#aid_hypothermia", t: "Hypothermie (corps trop froid)"},
	{h: "#aid_unconsciouswithbreath", t: "Inconscient avec respiration"},
	{h: "#aid_unconsciouswithoutbreath", t: "Inconscient sans respiration"},
	{h: "#aid_sunstroke", t: "Insolation"},
	{h: "#aid_poisining", t: "Intoxication"},
	{h: "#aid_animalbite", t: "Morsures d'animaux"},
	{h: "#aid_nosebleeding", t: "Nez - saignement"},
	{h: "#aid_drowning", t: "Noyade"},
	{h: "#aid_eyeinjury", t: "Oeil - blessures"},
	{h: "#aid_insectstings", t: "Piqûres d'insectes"},
	{h: "#aid_recoveryposition", t: "Position latérale de sécurité"},
	{h: "#aid_resuscitation", t: "Réanimation"},
	{h: "#aid_apnoea", t: "Respiration"},
	{h: "#aid_bleedingsevere", t: "Saignement grave"},
	{h: "#aid_bleedinglight", t: "Saignement léger"},
	{h: "#aid_icerescue", t: "Sauvetage sur glace"},
	{h: "#aid_snakebite", t: "Serpent - Morsures"},
	{h: "#aid_sos", t: "SOS"},
	{h: "#aid_checkbreathing", t: "Vérifiez la respiration"},
	{h: "#aid_stroke", t: "Vertige"},
	{h: "#aid_vomiting", t: "Vomissements"},
	{h: "tel:112", t: "Appelez 112"}
];
var langSections={
	aid_disclaimer: [
		{k: "title", t: "Responsabilité + Info"},
		{k: "subsection", t: "Logiciel"},
		{k: "description", t: "Premiers Secours sur Portable"},
		{k: "description", t: "Droit d'auteur: Kai Kajus Noack"},
		{k: "description", t: "Traduction: Sami Ben-Hassine"},
		{k: "description", t: "Licence: Creative Commons"},
		{k: "image", i: "cc88x31"},
		{k: "description", t: "Ce logiciel est censé donner des informations sur les gestes de premiers secours. Toutefois, il ne se substitut pas à une formation aux premiers secours. Il sert plutôt au rafraîchissant des connaissances déjà acquises."},
		{k: "description", t: "Illustrations © Med4Teens"},
		{k: "subsection", t: "Responsabilité"},
		{k: "description", t: "S'il vous plaît, notez que je ne prends aucune responsabilité pour les conséquences résultant de l'usage du logiciel."},
		{k: "description", t: "Toute responsabilité est exclue!"},
		{k: "description", t: "À utiliser à vos propres risques!"},
		{k: "description", t: "Dans tous les cas d'urgence, s'il vous plaît, chercher immédiatement une aide médicale professionnelle."},
		{k: "subsection", t: "Sauver une vie c'est sauver le monde."}
	],
	aid_general: [
		{k: "title", t: "Conduite générale"},
		{k: "step", p: [{t: "Toujours effectuer les gestes de premiers secours. Vous ne pouvez pas faire d'erreur."}]},
		{k: "step", p: [{t: "Toujours prêter attention à votre propre sécurité."}]},
		{k: "step", p: [{t: "Examinez la situation et sécurisez le lieu de l'accident."}]},
		{k: "step", p: [{t: "Appelez les services d'urgences + les gestes de premiers secours!"}]},
		{k: "step", p: [{t: "S'il y a plusieurs victimes, traiter en priorité celle qui est la plus gravement blessée."}]},
		{k: "step", p: [{t: "Toujours essayer de rassurez la personne concernée. Restez calme vous même!"}]},
		{k: "step", p: [{t: "Si possible, asseyez ou allongez la victime confortablement. Ne jamais donner d'alcool, de nicotine ou de la drogue à la victime."}]}
	],
	aid_allergic: [
		{k: "title", t: "Allergie", i: "aid046"},
		{k: "step", p: [{t: "Appelez immédiatement une ambulance."}]},
		{k: "step", p: [{t: "Essayez de calmer la victime et de lui laisser s'asseoir confortable."}]},
		{k: "step", p: [{t: "Retirez avec soin l'origine de l'allergie (par exemple le dard de l'abeille)."}]},
		{k: "step", p: [{t: "Refroidir la peau (compresse humide, glace sans contact direct avec la peau)."}]},
		{k: "image", i: "aid046ice"},
		{k: "step", p: [{t: "Si la victime a un antidote, il doit l'utiliser (l'aider)."}]},
		{k: "step", p: [{t: "Veillez sur la victime jusqu'à l'arrivée de l'ambulance."}]},
		{k: "step", p: [{t: "Si la victime perd conscience ou s'arrête de respirer, voir les instructions appropriées!"}]},
		{k: "image", i: "aid077"}
	],
	aid_amputation: [
		{k: "title", t: "Amputation"},
		{k: "description", t: "Une partie du corps, amputée, peut être rattachée. Objectif: Conserver la partie amputée dans le froid jusqu'à l’arrivée à l'hôpital."},
		{k: "step", p: [{t: "Rassurez la victime, allongez la et la couvrir d’une couverture."}]},
		{k: "step", p: [{t: "Arrêtez l'hémorragie, voir 'Saignement grave' et 'Choc'. "}]},
		{k: "step", p: [{t: "Emballez la partie amputée dans un vêtement propre et sec et la mettre dans un sac en plastique étanche."}]},
		{k: "step", p: [{t: "Fermez le sac en plastique et mettez-le dans un autre sac en plastique, qui contient de l'eau fraîche / glace."}]},
		{k: "step", p: [{t: "Ne donnez pas d'alcool, de cigarettes ou de la nourriture à la victime (dans le cas d'une intervention chirurgicale avec anesthésie à l'hôpital)."}]},
		{k: "step", p: [{t: "Ne pas congeler la partie amputée (juste la tenir au frais)."}]},
		{k: "step", p: [{t: "Appelez les Urgences ou allez en voiture à l'hôpital."}]}
	],
	aid_animalbite: [
		{k: "title", t: "Morsures d'animaux", i: "aid047"},
		{k: "description", t: "Attention: Danger élevé d'infection. Conséquences possibles: infection, tétanos, rage."},
		{k: "step", p: [{t: "Lavez la plaie à l'eau chaude savonneuse."}]},
		{k: "image", i: "aid049"},
		{k: "step", p: [{t: "Ensuite, désinfectez la plaie."}]},
		{k: "step", p: [{t: "S'il y a hémorragie sévère, élever le haut du corps de la personne."}]},
		{k: "step", p: [{t: "Mettre un pansement stérile."}]},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Allez à l'hôpital ou appeler un médecin d'urgence."}]}
	],
	aid_apnoea: [
		{k: "title", t: "Arrêt respiratoire"},
		{k: "description", t: "Pas de son respiratoire, ou de mouvements respiratoire, notable changement de la coloration de la peau."},
		{k: "step", p: [{t: "Appelez les services d'urgence."}]},
		{k: "step", p: [{t: "Allongez la victime sur son dos."}]},
		{k: "step", p: [{t: "Retirer les substances se trouvant dans la bouche et la gorge. Basculez la tête vers l'arrière."}]},
		{k: "image", i: "aid067"},
		{k: "step", p: [{t: "Pincez le nez de sorte que le nez soit fermé."}]},
		{k: "image", i: "aid010"},
		{k: "step", p: [{t: "Prenez une grande inspiration et mettre votre bouche sur la bouche de la victime de sorte que l'air s'échappe pas."}]},
		{k: "image", i: "aid011"},
		{k: "step", p: [{t: "Expirez lentement et complètement."}]},
		{k: "step", p: [{t: "Si la victime ne se remet pas à respirer : continuez l'opération jusqu'à l'arrivée de l'ambulance."}]}
	],
	aid_asthma: [
		{k: "title", t: "Asthme"},
		{k: "description", t: "Fort essoufflement. Sifflements respiratoires. Anxiété."},
		{k: "step", p: [{t: "Rassurez la personne. Restez calme vous même!"}]},
		{k: "step", p: [{t: "Desserrez les vêtements."}]},
		{k: "step", p: [{t: "Asseyez la victime et la pencher vers l'avant. Encouragez la victime à respirer lentement et profondément."}]},
		{k: "step", p: [{t: "Si la victime a un inhalateur, il devrait l'utiliser (l'aider). Après 5 à 10 min, cela devrait prendre effet."}]},
		{k: "image", i: "aid074"},
		{k: "step", p: [{t: "S'il n'y a pas d'amélioration: Utiliser l'inhalateur toutes les 5 min jusqu'à l'arrivée de l'ambulance."}]},
		{k: "step", p: [{t: "Appelez les services d'urgence."}]},
		{k: "step", p: [{t: "Si la victime arrête de respirer, voir les instructions "}, {t: "\"Arrêt respiratoire\".", h: "#aid_apnoea"}]}
	],
	aid_backinjury: [
		{k: "title", t: "Dos - Blessure"},
		{k: "description", t: "Douleur dans le dos, bras et jambes engourdis."},
		{k: "step", p: [{t: "Ne pas déplacer la victime!!"}]},
		{k: "image", i: "aid064"},
		{k: "step", p: [{t: "Maintenez la tête de la victime de façon à ce qu'elle ne bouge plus (garder la tête stationnaire)"}]},
		{k: "image", i: "aid065"},
		{k: "step", p: [{t: "Stabilisez la victime avec des vêtements ou autres sur les côtés."}]},
		{k: "step", p: [{t: "Rassurez la personne."}]},
		{k: "step", p: [{t: "Appelez les services d'urgence, leur indiquer l'emplacement de la blessure."}]}
	],
	aid_birth: [
		{k: "title", t: "Accouchement"},
		{k: "description", t: "Perte des eaux. Contractions douloureuses. Accouchement inattendu."},
		{k: "image", i: "aid025"},
		{k: "step", p: [{t: "Ne pas exposer l'intimité de la femme enceinte et gardez son calme! - Appelez les services d'urgence."}]},
		{k: "step", p: [{t: "Laissez les jambes à nu jusqu'à mi-cuisse et asseyez la femme enceinte sur une surface stérile jambes écartées."}]},
		{k: "step", p: [{t: "Lui plier les genoux. Ecartez les jambes. Placez le bassin légèrement vers le haut. - La naissance est un processus naturel et fonctionne le plus souvent sans complications."}]},
		{k: "step", p: [{t: "Rassurez la femme enceinte, la laisser se concentrer sur sa respiration: Respirez par le nez, expirer par la bouche (à vitesse normale)."}]},
		{k: "step", p: [{t: "Rythme à adopter: Prendre une grande inspiration, tenir le souffle, et pousser. Dès que la tête du bébé apparaît, la soutenir avec vos deux mains."}]},
		{k: "image", i: "aid021"},
		{k: "image", i: "aid022"},
		{k: "step", p: [{t: "Après l'accouchement: Tenez le bébé en oblique la tête vers la bas pour libérer les voies respiratoires du liquide amniotique. (Il est possible que vous ayez à aspirer le fluide par le nez du bébé avec votre bouche). Le bébé doit respirer et pleurer!"}]},
		{k: "step", p: [{t: "Lier le cordon ombilical à 30 cm du bébé (peut aussi être fait à l'hôpital). Veillez à la stérilité du vagin de la mère."}]},
		{k: "image", i: "aid023"},
		{k: "step", p: [{t: "Séchez le bébé et le garder au chaud. Noter l'heure et les conduire à l'hôpital."}]}
	],
	aid_bleedinglight: [
		{k: "title", t: "Saignement léger", i: "aid082"},
		{k: "description", t: "Objectif: arrêter le saignement."},
		{k: "step", p: [{t: "Ne pas toucher la plaie (risque d'infection)."}]},
		{k: "step", p: [{t: "Ne pas traiter la plaie avec de la poudre, du baume ou de la crème ou encore avec un vaporisateur."}]},
		{k: "step", p: [{t: "Traitement des plaies: couvrir avec du matériel stérile (compresse) et un bandage."}]},
		{k: "image", i: "aid098"},
		{k: "step", p: [{t: "Pour les petits saignements un pansement est souvent suffisant."}]},
		{k: "step", p: [{t: "Si la plaie est grande, utiliser une compresse et un bandage. Ne pas trop serrer le bandage, car un ralentissement de la circulation sanguine peut augmenter le saignement."}]},
		{k: "image", i: "aid084"},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Remarque: Les plaies dues à la morsure d'un animal enragé doivent être lavés avec une solution savonneuse."}]},
		{k: "image", i: "aid049"}
	],
	aid_bleedingsevere: [
		{k: "title", t: "Saignement grave"},
		{k: "description", t: "Jet de sang, perte considérable de sang. Danger: perte de connaissance due à la perte de sang, infections, mort. Objectif: arrêter l'hémorragie."},
		{k: "step", p: [{t: "Retirez les vêtements de la victime (les couper si nécessaire) pour faire apparaître la plaie."}]},
		{k: "step", p: [{t: "Bandez la plaie avec un bandage ou, si nécessaire, un vêtement, et serrez fortement."}]},
		{k: "image", i: "aid086"},
		{k: "step", p: [{t: "Exercez une pression d'au moins 10 min."}]},
		{k: "step", p: [{t: "Si le bandage est imbibé de sang, ne pas le retirer. Mettre un bandage/vêtement supplémentaire."}]},
		{k: "step", p: [{t: "Positionnez le membre blessé (s'il n'est pas cassé) à une hauteur plus élevée que le cœur afin de ralentir la circulation sanguine vers le membre blessé. Si possible, allongez la victime."}]},
		{k: "step", p: [{t: "Si le saignement ne s'arrête pas, maintenir la pression sur la plaie et ajoutez des points de pression: Pour un saignement de l'avant-bras, compressez la partie supérieure du bras (compressez la veine situer sur la face interne du bras qui fait face au thorax). Pour un saignement de la jambe, compressez la partie supérieure de la jambe dans l'aine (compressez la veine situer entre les jambes sur la face interne de la jambe concernée)."}]},
		{k: "image", i: "aid089"},
		{k: "image", i: "aid092"},
		{k: "step", p: [{t: "Appelez les services d'urgence immédiatement."}]},
		{k: "step", p: [{t: "Dès que le saignement est sous contrôle: Engager la mesure Anti-choc (Voir Choc)."}]},
		{k: "image", i: "aid093"}
	],
	aid_brainconcussion: [
		{k: "title", t: "Commotion cérébrale"},
		{k: "description", t: "Maux de tête, des nausées, des vomissements. Affaiblissement de la vision. Possible perte de connaissance."},
		{k: "image", i: "aid035a"},
		{k: "step", p: [{t: "Allongez la victime."}]},
		{k: "step", p: [{t: "Appelez les services d'urgence."}]},
		{k: "description", t: "Si saignement à la tête:"},
		{k: "step", p: [{t: "Allongez la victime et surélevée la tête (vêtement/oreiller)."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Traitez la plaie (utiliser un bandage/vêtement)."}]},
		{k: "step", p: [{t: "Appelez les services d'urgence."}]}
	],
	aid_burningslight: [
		{k: "title", t: "Brûlure légère"},
		{k: "description", t: "Rougeur de la peau. Léger gonflements. Douleur."},
		{k: "step", p: [{t: "Passez la zone concernée sous l'eau froide."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Mettre un bandage humide pas trop serré."}]}
	],
	aid_burningsevere: [
		{k: "title", t: "Brûlure grave"},
		{k: "description", t: "Peau blanche-rouge, boursouflures, écoulement de liquide. Dommages tissulaires profond. Forte douleur ou aucune douleur (à cause des nerfs brûlés)."},
		{k: "image", i: "aid097"},
		{k: "step", p: [{t: "Retirez les vêtements autant que possible."}]},
		{k: "step", p: [{t: "Refroidir les zones brûlées avec de l'eau (environ 15 ° C, 59 ° F) pendant 10 min, jusqu'à ce que la douleur diminue."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Si la brûlure est très étendue, utilisez des linges humides pour refroidir."}]},
		{k: "step", p: [{t: "Appelez les services d'urgence."}]},
		{k: "step", p: [{t: "Après refroidissement, traitez de la plaie: Utiliser un pansement/bandage stérile. Ne pas appliquer des fluides (pas de crèmes, huiles, etc.) Ne pas percer les cloques."}]},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Surveillez la respiration et l'état de conscience de la victime jusqu'à l'arrivée du médecin d'urgence."}]}
	],
	aid_checkbreathing: [
		{k: "title", t: "Vérifiez la respiration"},
		{k: "step", p: [{t: "Vérifiez la respiration avec l'oreille sur le torse."}]},
		{k: "step", p: [{t: "Vérifiez la respiration sur le haut du torse (poser votre main sur le torse)."}]},
		{k: "image", i: "aid027"},
		{k: "step", p: [{t: "Sentir la respiration par le nez et/ou la bouche de la victime avec votre joue."}]}
	],
	aid_chemicalburneyes: [
		{k: "title", t: "Brûlure chimique (yeux)"},
		{k: "step", p: [{t: "Appelez les services d'urgence, leur indiquer les produits chimiques en question."}]},
		{k: "step", p: [{t: "Rincez les yeux avec beaucoup d'eau. Couvrir l'oeil en bonne santé durant le rinçage."}]},
		{k: "step", p: [{t: "Conduire le jet d'eau à partir de l'angle interne de l'œil vers l'extérieur de l'œil. Rincez pendant au moins 20 minutes sous l'eau claire."}]},
		{k: "image", i: "aid019"},
		{k: "step", p: [{t: "Fermez les deux yeux de la victime et lui bandez les yeux avec un linge humide."}]},
		{k: "image", i: "aid020"},
		{k: "step", p: [{t: "Veillez sur la victime jusqu'à l'arrivée de l'ambulance."}]}
	],
	aid_chemicalburn: [
		{k: "title", t: "Brûlure chimique"},
		{k: "description", t: "Blessures des tissus."},
		{k: "image", i: "aid095"},
		{k: "step", p: [{t: "L'esprit d'autoprotection!"}]},
		{k: "step", p: [{t: "Agir rapidement et lavez-les endroits brûlés."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Appelez les services d'urgence."}]},
		{k: "step", p: [{t: "S'il y a brûlure chimique dans les voies digestives, boire beaucoup d'eau."}]},
		{k: "step", p: [{t: "Ne pas provoquer de vomissements!"}]}
	],
	aid_dangerzone: [
		{k: "title", t: "Dégagement d'urgence"},
		{k: "step", p: [{t: "Exécution du dégagement: Positionnez un bras de la victime en face de sa poitrine, et mettez vous derrière la victime."}]},
		{k: "step", p: [{t: "Mettez vos mains sous les épaules de la victime, l'une sur la poitrine de la victime, avec l'autre prenez le coude du bras de la victime que vous avez mis sur sa poitrine."}]},
		{k: "step", p: [{t: "Retirez et transporter la personne en sécurité."}]},
		{k: "image", i: "aid001"},
		{k: "image", i: "aid007"}
	],
	aid_diabeticcoma: [
		{k: "title", t: "Coma diabétique"},
		{k: "description", t: "Sucre dans le sang trop élevé (manque d'insuline)."},
		{k: "description", t: "Symptômes: soif, perte contrôle vessie, nausées, vomissements. Halène à l'odeur de fruits/vin."},
		{k: "step", p: [{t: "Appelez les services d'urgence."}]},
		{k: "step", p: [{t: "Aidez la victime (si certitude diabète) a prendre l'insuline."}]},
		{k: "image", i: "aid016"},
		{k: "step", p: [{t: "Position latérale de sécurité.", h: "#aid_recoveryposition"}, {t: " (Pas d'autres possibilités pour aider la première.)"}]},
		{k: "step", p: [{t: "Surveiller l'état de la victime jusqu'à l'arrivée de l'ambulance."}]}
	],
	aid_diarrhoea: [
		{k: "title", t: "Diarrhées"},
		{k: "description", t: "Réaction à intoxication alimentaire, l'infection de l'intestin ou de troubles. Excrément liquide, visqueux ou sanglant."},
		{k: "step", p: [{t: "Danger pour la circulation sanguine en raison de la déshydratation et la perte de sel!"}]},
		{k: "step", p: [{t: "Faites boire (thé, eau)."}]},
		{k: "step", p: [{t: "Si il y a de fortes troubles appeler le médecin d'urgence."}]}
	],
	aid_drowning: [
		{k: "title", t: "Noyade"},
		{k: "step", p: [{t: "Appelez les services d'urgence. Demandez à côté de vous pour obtenir de l'aide."}]},
		{k: "image", i: "aid032"},
		{k: "step", p: [{t: "Sortez la victime de l'eau!"}]},
		{k: "image", i: "aid033"},
		{k: "image", i: "aid034"},
		{k: "step", p: [{t: "Si la victime respire: "}, {t: "Position latérale de sécurité.", h: "#aid_recoveryposition"}, {t: " Garder la victime au chaud (couverture). Surveiller la victime jusqu'à l'arrivée de l'ambulance."}]},
		{k: "step", p: [{t: "Si victime ne respire pas: Commencez immédiatement à la réanimation "}, {t: "(Voir Réanimation)", h: "#aid_resuscitation"}, {t: "! (Émission de l'eau des poumons est inutile.)"}]}
	],
	aid_electricityaccident: [
		{k: "title", t: "Électrocution"},
		{k: "step", p: [{t: "Tout d'abord coupez l'électricité!"}]},
		{k: "image", i: "aid045plug"},
		{k: "image", i: "aid045"},
		{k: "step", p: [{t: "Danger: perte de conscience, arrêt respiratoire."}]},
		{k: "step", p: [{t: "A - Victime inconsciente / respire (Appelez les urgences)", h: "#aid_unconsciouswithbreath"}]},
		{k: "step", p: [{t: "B - Victime inconsciente / ne respire pas (Voir Arrêt respiratoire + Urgence)", h: "#aid_unconsciouswithoutbreath"}]},
		{k: "image", i: "aid042"},
		{k: "image", i: "aid043"}
	],
	aid_emergencycall: [
		{k: "title", t: "Appelez les services d'urgence"},
		{k: "step", p: [{t: "Appelez le 15 (112 à l'international). N'hésitez pas à appeler une ambulance!"}]},
		{k: "step", p: [{t: "Sur le téléphone, vous devez fournir les informations suivantes:"}]},
		{k: "step", p: [{t: "- Que s'est-il passé "}]},
		{k: "step", p: [{t: "- Où (lieu d'accident) "}]},
		{k: "step", p: [{t: "- Combien de victimes "}]},
		{k: "step", p: [{t: "- Quel type de blessures. "}]},
		{k: "step", p: [{t: "Ensuite, attendre de plus amples renseignements."}]}
	],
	aid_epilepsy: [
		{k: "title", t: "Épilepsie"},
		{k: "description", t: "Corps rigide, poings serrés, mâchoire serrée, contraction musculaires dans les membres ou le visage. Yeux retournés. Bave. Perte de connaissance possible."},
		{k: "image", i: "aid058"},
		{k: "step", p: [{t: "Ne pas tenir la victime ou de restreindre ses mouvements."}]},
		{k: "step", p: [{t: "Allongez la victime sur une base souple (coussin), déplacez les objets proches pour éviter les blessures."}]},
		{k: "step", p: [{t: "Rassurez la victime. Desserrer les vêtements, assurez-vous qu'elle puisse respirer convenablement."}]},
		{k: "step", p: [{t: "Si la victime vomit, tournez la tête sur le côté pour que vomit se déverse."}]},
		{k: "step", p: [{t: "Gardez les voies respiratoires libres. Risque d'avaler sa langue."}]},
		{k: "step", p: [{t: "Position latérale de sécurité", h: "#aid_recoveryposition"}, {t: " + d'appel des urgences. Continuez de surveiller l'état de la victime."}]},
		{k: "step", p: [{t: "Tenir les autres personnes à distance."}]}
	],
	aid_eyeinjury: [
		{k: "title", t: "Oeil - blessures"},
		{k: "step", p: [{t: "Laissez l'objet dans l'œil de victime, ne pas le retirer."}]},
		{k: "step", p: [{t: "Gardez les yeux immobiles pour éviter de nouvelles blessures. Ne touchez pas les yeux."}]},
		{k: "step", p: [{t: "Si l'œil saigne, recouvrir d'une compresse ou d'une gaze stérile."}]},
		{k: "image", i: "aid020"},
		{k: "step", p: [{t: "Refroidir les yeux avec un tampon froid (réduit le gonflement, le saignement s'arrête plus rapidement)."}]},
		{k: "step", p: [{t: "Appelez les urgences ou allez en voiture à l'hôpital."}]}
	],
	aid_fracture: [
		{k: "title", t: "Fracture"},
		{k: "description", t: "Symptômes: Forme et mouvement non naturel de l'os. Déformation. Mouvement douloureux, sensible au toucher."},
		{k: "image", i: "aid104"},
		{k: "step", p: [{t: "Évitez les mouvements!"}]},
		{k: "step", p: [{t: "Appelez les services d'urgence."}]},
		{k: "step", p: [{t: "Immobilisez l'os fracturé, c'est-à-dire soutenir l'os un objet en l'attachant solidement. Gardez la position de l'os."}]},
		{k: "image", i: "aid107"},
		{k: "step", p: [{t: "Si la fracture est ouverte, couvrir la plaie avec du matériel stérile."}]},
		{k: "image", i: "aid106"}
	],
	aid_frostbitemild: [
		{k: "title", t: "Brûlure par le froid - léger"},
		{k: "description", t: "Pâleur, gonflements. Danger pour l'approvisionnement en sang."},
		{k: "step", p: [{t: "Emmenez la victime dans un endroit chaud."}]},
		{k: "step", p: [{t: "Eloignez vous du froid, retirer les vêtements froid, séchez la victime."}]},
		{k: "step", p: [{t: "Réchauffez avec de l'eau tiède et avec la chaleur du corps du sauveteur."}]},
		{k: "step", p: [{t: "Donnez une boisson chaude (thé). Pas d'alcool!"}]},
		{k: "image", i: "aid040"}
	],
	aid_frostbitesevere: [
		{k: "title", t: "Brûlure par le froid - grave"},
		{k: "description", t: "Peau froide, gris-blanc, cloque, tissu de la peau meurt. Danger pour l'approvisionnement en sang!"},
		{k: "image", i: "aid096"},
		{k: "step", p: [{t: "Allez dans un endroit chaud."}]},
		{k: "step", p: [{t: "Traitement des plaies / les couvrir."}]},
		{k: "step", p: [{t: "Donnez une boisson sucrée."}]},
		{k: "step", p: [{t: "Ne frottez pas la victime pour la réchauffer!"}]},
		{k: "step", p: [{t: "Appelez les services d'urgence."}]}
	],
	aid_heartattack: [
		{k: "title", t: "Crise Cardiaque"},
		{k: "description", t: "Lourd, plus de 5 min de pression et de douleur dans la poitrine rayonnant dans les bras / épaules. Anxiété, pâleur, sueurs froides. Peut-être des nausées, essoufflement."},
		{k: "image", i: "aid076"},
		{k: "image", i: "aid083"},
		{k: "step", p: [{t: "Appelez les urgences! Les informez d'une possible crise cardiaque."}]},
		{k: "step", p: [{t: "Surélevez le haut du corps de la victime. Desserrez les vêtements. Ne donnez pas de médicaments ou de boissons."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Parlez calmement à la victime."}]},
		{k: "step", p: [{t: "Vérifiez l'état de conscience et la respiration de la victime."}]},
		{k: "step", p: [{t: "Donnez de l'aspirine, si disponible."}]},
		{k: "step", p: [{t: "Si la personne est inconsciente, commencez la réanimation "}, {t: "(voir Réanimation).", h: "#aid_resuscitation"}]}
	],
	aid_hypoglycaemia: [
		{k: "title", t: "Hypoglycémie (faible teneur en sucre)"},
		{k: "description", t: "Niveau de sucre dans le sang inférieur à la valeur minimum (à cause d'un surdosage d'insuline ou pas suffisamment d'apport en nourriture)."},
		{k: "description", t: "Symptômes: pâleur, nervosité, faim, tremblements, sueur."},
		{k: "image", i: "aid018"},
		{k: "step", p: [{t: "Assurez-vous que la personne est une personne diabétique (chercher un badge/carte diabétique)."}]},
		{k: "step", p: [{t: "Appelez les services d'urgences."}]},
		{k: "step", p: [{t: "Donner une boisson sucrée et du dextrose ou glucose (si il n'y a pas de problèmes de déglutition)."}]},
		{k: "image", i: "aid017"},
		{k: "step", p: [{t: "Si la personne est consciente et respire: "}, {t: "position latérale de sécurité.", h: "#aid_recoveryposition"}, {t: " Surveiller la respiration de la personne. Si arrêt respiratoire: voir Arrêt respiratoire."}]},
		{k: "step", p: [{t: "Si la victime respire, vous pouvez mettre un morceau de sucre à l'intérieur la joue, fermez la bouche et poussez le sucre de l'extérieur."}]}
	],
	aid_hyperthermia: [
		{k: "title", t: "Hyperthermie (corps trop chaud)"},
		{k: "description", t: "Soif, faiblesse, désorientation, nausées, confusion, forte transpiration, la peau est chaude."},
		{k: "image", i: "aid035"},
		{k: "step", p: [{t: "Appelez les services d'urgence."}]},
		{k: "step", p: [{t: "Trouver un lieu ombragé et frais (chambre avec air conditionné préférable)."}]},
		{k: "step", p: [{t: "Allongez la victime, élever les jambes. Desserrez les vêtements."}]},
		{k: "image", i: "aid078"},
		{k: "step", p: [{t: "Refroidir la peau avec beaucoup d'eau ou couvrir avec des serviettes froides."}]},
		{k: "step", p: [{t: "Donnez beaucoup d'eau ou des jus de fruits à boire."}]}
	],
	aid_hypothermia: [
		{k: "title", t: "Hypothermie (corps trop froid)"},
		{k: "description", t: "Tremble de froid, somnolence, épuisement jusqu'à l'inconscience. Peau froide et pâle. Faible pouls, rythme cardiaque faible."},
		{k: "image", i: "aid014"},
		{k: "step", p: [{t: "Emmenez la victime dans un endroit chaud."}]},
		{k: "step", p: [{t: "Appelez les services d'urgence."}]},
		{k: "step", p: [{t: "Augmenter la température du corps (couverture et corps à corps)."}]},
		{k: "step", p: [{t: "Enlevez les vêtements mouillés et mettre des vêtements chauds. Couvrir. Couvrir la tête."}]},
		{k: "step", p: [{t: "Donnez du thé chaud, soupe ou de l'eau chaude à boire. Pas d'alcool! Gardez la victime éveillée."}]},
		{k: "image", i: "aid039"},
		{k: "image", i: "aid040"},
		{k: "step", p: [{t: "Surveillez la victime jusqu'a l'arrivée des services d'urgence. Si la victime perd conscience, procéder à la réanimation (voir réanimation)."}]},
		{k: "step", p: [{t: "A - Victime inconsciente / respire (Appelez les Urgences)", h: "#aid_unconsciouswithbreath"}]},
		{k: "step", p: [{t: "B - Victime inconsciente / ne respire pas (Voir Arrêt respiratoire + les Urgences)", h: "#aid_unconsciouswithoutbreath"}]}
	],
	aid_icerescue: [
		{k: "title", t: "Sauvetage sur glace"},
		{k: "description", t: "Faites attention à votre propre sécurité. Danger: noyade, hypothermie."},
		{k: "step", p: [{t: "Demandez à d'autres personnes de vous aider. Appelez les services d'urgence."}]},
		{k: "step", p: [{t: "Effectuez le sauvetage grâce à une échelle, une planche ou une barre. Poids doit être réparti de façon égale."}]},
		{k: "step", p: [{t: "Ramper lentement vers la victime sur le support (si possible s'attacher avec une corde à un point stable) avec une barre ou autre."}]},
		{k: "image", i: "aid041"},
		{k: "step", p: [{t: "Atteindre la victime avec la barre ou autre (ne pas utiliser vos mains!) encouragez la à prendre l'objet et tirez la vers vous."}]},
		{k: "step", p: [{t: "Rampez lentement en arrière."}]},
		{k: "step", p: [{t: "Premiers secours."}]},
		{k: "step", p: [{t: "Auto-évacuation possible: Si la glace est solide, vous pouvez distribuer votre poids sur la glace et ramper à plat ventre, pour vous sortir de l'eau et vous diriger vers la terre ferme. Si la glace est fragile, essayer de la briser petit à petit jusqu'à la terre ferme."}]}
	],
	aid_insectstings: [
		{k: "title", t: "Piqûres d'insectes", i: "aid046"},
		{k: "description", t: "Gonflement, éruption cutanée, sensation de brûlure, faiblesse, respiration difficile, diminution de l'état de conscience, tachycardie."},
		{k: "step", p: [{t: "Retirez soigneusement le dard (avec une pince à épiler). Ne pas presser le dard car cela pourrait injecter plus de venin."}]},
		{k: "step", p: [{t: "Refroidir la zone concernée (utilisez une compresse froide)."}]},
		{k: "step", p: [{t: "La zone concernée devrait être située à une hauteur inférieure au cœur pour ralentir la circulation du venin."}]},
		{k: "step", p: [{t: "Si piqûre dans la bouche/mâchoire : Manger une glace et utilisez une compresse froide pour refroidir la gorge."}]},
		{k: "image", i: "aid046ice"},
		{k: "step", p: [{t: "Si de graves problèmes apparaissent, problème de respiration ou perte de conscience, appelez une ambulance."}]}
	],
	aid_nosebleeding: [
		{k: "title", t: "Nez - saignement"},
		{k: "description", t: "Rupture d'une petite artère dans le bout du nez."},
		{k: "step", p: [{t: "Asseyez la victime, penchée légèrement vers l'avant. Gardez la tête droite."}]},
		{k: "step", p: [{t: "Ne pas allonger la victime, car avoir la tête à une hauteur plus élevée que le coeur ralenti le saignement."}]},
		{k: "step", p: [{t: "Enveloppez le cou avec un linge froid (vêtement mouillé)."}]},
		{k: "step", p: [{t: "Pincement des narines jusqu'à ce que le saignement s'arrête (au moins 10 min)."}]},
		{k: "step", p: [{t: "Ensuite, ne pas forcer sur le nez (ne pas renifler ou souffler fortement)."}]},
		{k: "step", p: [{t: "Si de graves problèmes apparaissent ou le saignement ne peut pas être arrêté, appelez les Urgences."}]}
	],
	aid_poisining: [
		{k: "title", t: "Intoxication", i: "aid052"},
		{k: "description", t: "Confusion, hallucinations, pupille dilatée, fièvre, crampes. Perte de conscience."},
		{k: "step", p: [{t: "Donnez un antidote, Uniquement si vous êtes accompagné par Médecin."}]},
		{k: "image", i: "aid056"},
		{k: "step", p: [{t: "Ne pas donner de boissons. Ne pas faire vomir."}]},
		{k: "step", p: [{t: "Appelez les Urgences + les informés de la nature de l'empoisonnement!"}]},
		{k: "step", p: [{t: "Protégez la victime du reste de poison et des vomissements!"}]},
		{k: "image", i: "aid054a"},
		{k: "step", p: [{t: "Si la victime est consciente et respire: "}, {t: "position latérale de sécurité.", h: "#aid_recoveryposition"}, {t: " Surveiller l'état de la victime jusqu'à l'arrivée de l'ambulance."}]},
		{k: "step", p: [{t: "Si victime ne respire pas: commencer immédiatement la "}, {t: "Réanimation!", h: "#aid_resuscitation"}, {t: " Vider la bouche de la victime avant de procéder (vomit)."}]}
	],
	aid_recoveryposition: [
		{k: "title", t: "Position latérale de sécurité"},
		{k: "step", p: [{t: "Allongez la victime sur le dos, jambes bien droite. Genoux collés."}]},
		{k: "step", p: [{t: "Placez le bras le plus proche de vous en travers de la poitrine de la victime (angle droit)."}]},
		{k: "step", p: [{t: "Tirez le bras le plus éloigné de vous en travers de la poitrine et place le dos de la main contre la joue opposée."}]},
		{k: "image", i: "aid008"},
		{k: "step", p: [{t: "Prenez le genou le plus éloigné, tirez-le vers vous, et posez le sur le sol. Mettre cette jambe en angle droit. Gardez la main de la victime sur sa joue, la paume doit toucher le sol et la tête doit être posé sur le dos de cette main."}]},
		{k: "step", p: [{t: "Assurez-vous que les voies respiratoires sont libres."}]},
		{k: "step", p: [{t: "Ouvrez légèrement la bouche et mettre la tête légèrement en arrière pour drainer la vomit. Vérifiez la respiration."}]},
		{k: "image", i: "aid009"},
		{k: "step", p: [{t: "Surveillez la victime jusqu'à l'arrivée des Urgences."}]},
		{k: "description", t: "Position latérale de sécurité (pour bébé):"},
		{k: "image", i: "aid028"}
	],
	aid_resuscitation: [
		{k: "title", t: "Réanimation"},
		{k: "subsection", t: "# Massage Cardiaque"},
		{k: "step", p: [{t: "Allongez la victime sur le dos. S'agenouiller à coté d'elle."}]},
		{k: "step", p: [{t: "Découvrir la poitrine."}]},
		{k: "step", p: [{t: "Placez la paume d'une main au milieu de la poitrine (au dessus du sternum)."}]},
		{k: "image", i: "aid013"},
		{k: "step", p: [{t: "Placez la deuxième main sur la première."}]},
		{k: "step", p: [{t: "Tendres les bras."}]},
		{k: "image", i: "aid003"},
		{k: "step", p: [{t: "Appuyez sur 5 cm de profondeur dans la poitrine de la victime (la puissance doit venir de la partie haute de votre corps) puis relâcher."}]},
		{k: "step", p: [{t: "Pressez 30 fois de suite en peu de temps et fermement!"}]},
		{k: "subsection", t: "# Bouche à bouche"},
		{k: "step", p: [{t: "Enlevez les substances contenues dans la bouche et la gorge. Pivotez la tête en arrière."}]},
		{k: "image", i: "aid067"},
		{k: "step", p: [{t: "Pincez le du nez de sorte à le fermer hermétiquement."}]},
		{k: "image", i: "aid010"},
		{k: "step", p: [{t: "Prenez une grande inspiration et mettre votre bouche sur la bouche de la victime de sorte que l'air ne peut s'échapper."}]},
		{k: "image", i: "aid011"},
		{k: "step", p: [{t: "Faire le bouche-à-bouche deux fois de suite (expirer lentement et entièrement)."}]},
		{k: "step", p: [{t: "Ensuite, faire le massage cardiaque à nouveau."}]},
		{k: "description", t: "Répétez le massage cardiaque et le bouche-à-bouche jusqu'à l'arrivée de l'ambulance."},
		{k: "image", i: "aid012"},
		{k: "subsection", t: "# Réanimation (Bébé)"},
		{k: "step", p: [{t: "Utiliser seulement deux doigts:"}]},
		{k: "image", i: "aid029"},
		{k: "step", p: [{t: "Ne pas expirer trop fort:"}]},
		{k: "image", i: "aid030"}
	],
	aid_safeguardaccident: [
		{k: "title", t: "Accident de voiture"},
		{k: "step", p: [{t: "Arrêtez votre propre voiture 50-100 m derrière le site de l'accident (si vous êtes sur une autoroute ou route de campagne). Allumer les feux de détresse. Mettez votre gilet de haute visibilité."}]},
		{k: "step", p: [{t: "Placez triangle de présignalisation avant l'accident. Attention: Si l'accident se trouve dans une courbe positionnez le triangle avant la courbe!"}]},
		{k: "image", i: "aid111"},
		{k: "step", p: [{t: "Demandez de l'aide aux personnes autour de vous."}]},
		{k: "step", p: [{t: "Ouvrez la porte de la voiture accidentée de voiture (si bloquée, ouvrir à l'aide d'un cric de voiture). Éteignez le moteur de la voiture."}]},
		{k: "step", p: [{t: "Secours aux victimes de l'accident: détachez la ceinture de sécurité, déplacez le siège vers l'arrière. Sortir la victime de la voiture grâce "}, {t: "à la technique de dégagement d'urgence", h: "#aid_dangerzone"}, {t: "."}]},
		{k: "image", i: "aid001"},
		{k: "step", p: [{t: "Appelez les services d'urgence."}]},
		{k: "step", p: [{t: "Commencez les gestes de premiers secours."}]}
	],
	aid_shock: [
		{k: "title", t: "Choc (Hémorragies)"},
		{k: "description", t: "Troubles de la circulation sanguine dus à un manque d'oxygène dans le corps."},
		{k: "description", t: "Cause: forte perte de sang, réduction du volume sanguin."},
		{k: "description", t: "Symptômes: pâleur, peau froide, sueur froide, anxiété."},
		{k: "step", p: [{t: "Éliminer la cause du choc (par exemple, arrêter la perte de sang, traitez la plaie)!"}]},
		{k: "step", p: [{t: "Déposez la victime sur une couverture, élevez les jambes. Calmez la personne."}]},
		{k: "image", i: "aid078"},
		{k: "step", p: [{t: "Appelez les services d'urgence."}]},
		{k: "step", p: [{t: "Si difficultés à respirer ou perte de conscience, commencez la "}, {t: "réanimation.", h: "#aid_resuscitation"}]}
	],
	aid_skullfracture: [
		{k: "title", t: "Fracture du crâne"},
		{k: "description", t: "Léger saignement du nez, de la bouche ou des oreilles. Souvent, plaies ouvertes au crâne."},
		{k: "step", p: [{t: "Gardez les voies respiratoires libres."}]},
		{k: "step", p: [{t: "Si conscient: laissez la victime s'asseoir avec la tête incliné vers l'avant. Évitez de nouveaux mouvements!"}]},
		{k: "step", p: [{t: "Si inconscient: "}, {t: "position latérale de sécurité", h: "#aid_recoveryposition"}, {t: " (pas de pression sur la blessure de la tête)."}]},
		{k: "step", p: [{t: "Appelez les services d'urgence."}]},
		{k: "step", p: [{t: "Mettre un bandage sur la tête."}]},
		{k: "step", p: [{t: "Si difficultés à respirer ou perte de conscience, commencez la "}, {t: "réanimation.", h: "#aid_resuscitation"}]}
	],
	aid_snakebite: [
		{k: "title", t: "Serpent - Morsures", i: "aid051"},
		{k: "description", t: "Plaie de la taille d'une épingle, de fortes douleurs, gonflement, couleur pourpre. Troubles de la circulation sanguine, danger de mise en état de choc."},
		{k: "step", p: [{t: "Traitez les parties blessées."}]},
		{k: "step", p: [{t: "Refroidir la zone autour de la morsure."}]},
		{k: "step", p: [{t: "Commencez les gestes Anti-chocs (Choc)."}]},
		{k: "step", p: [{t: "Appelez les services d'urgence."}]}
	],
	aid_sos: [
		{k: "title", t: "SOS"},
		{k: "step", p: [{t: "Signal: 3x court, 3xlong, 3x court."}]},
		{k: "step", p: [{t: "Visuel (laser de poche, lampe de poche), ou sonore (sifflet, frapper contre une surface)."}]}
	],
	aid_sprain: [
		{k: "title", t: "Entorse"},
		{k: "description", t: "Douleur, gonflements (bleu), perte de mobilité, déformation."},
		{k: "step", p: [{t: "Placez la partie blessée du corps dans la position la plus confortable pour la victime."}]},
		{k: "step", p: [{t: "Refroidir (à l'aide de packs de glace)."}]},
		{k: "step", p: [{t: "Si possible, élevez la partie blessée."}]},
		{k: "step", p: [{t: "Allez à l'hôpital ou appelez les Urgences."}]}
	],
	aid_stroke: [
		{k: "title", t: "Vertige"},
		{k: "description", t: "Sentiment de paralysie ou engourdissement subit (visage, bras, jambe), problèmes de compréhension, troubles de la vision, perte de conscience, forts maux de tête. Problèmes de respiration et de déglutition, perte de contrôle de la vessie et des intestins."},
		{k: "image", i: "aid059"},
		{k: "step", p: [{t: "Appelez les services d'urgence!"}]},
		{k: "step", p: [{t: "Desserrez les vêtements. Ne donner pas de médicaments ou de boissons."}]},
		{k: "step", p: [{t: "Asseyez ou allongez confortablement la victime. Rassurez la!"}]},
		{k: "step", p: [{t: "Surveillez l'état de conscience et la respiration de la victime."}]},
		{k: "step", p: [{t: "Si difficultés à respirer ou perte de conscience, commencez la "}, {t: "réanimation.", h: "#aid_resuscitation"}]}
	],
	aid_suffocation: [
		{k: "title", t: "Etouffement / Étranglement"},
		{k: "description", t: "Manque d'oxygène. Trachée fermée. Danger: arrêt respiratoire."},
		{k: "description", t: "Symptômes: bruit respiratoire (sifflement), toux, essoufflement, décoloration de la peau."},
		{k: "image", i: "aid066"},
		{k: "step", p: [{t: "Agir immédiatement! Laissez la victime tousser très fortement."}]},
		{k: "step", p: [{t: "Tapez fortement avec la paume de la main sur le dos entre les omoplates (allongez le bébé sur votre avant-bras, la tête en bas)."}]},
		{k: "image", i: "aid068"},
		{k: "image", i: "aid031"},
		{k: "step", p: [{t: "Si, sans succès: Tenez-vous derrière la victime, les bras autour de la taille, penchez-vous légèrement vers l'avant."}]},
		{k: "step", p: [{t: "Serrez votre poing à hauteur de l'estomac de la victime et prendre votre poing avec l'autre main."}]},
		{k: "image", i: "aid069"},
		{k: "step", p: [{t: "Utilisez les deux mains pour donner un coup sec dans l'estomac en ramenant vers le haut (comme vous le feriez pour essayer de lever la personne)."}]},
		{k: "step", p: [{t: "Répétez cette manoeuvre jusqu'à 5 fois! Les voies respiratoires devraient être libérées de l'objet."}]},
		{k: "step", p: [{t: "Appelez les services d'urgence."}]},
		{k: "step", p: [{t: "Si la première tentative échoue, répétez la manoeuvre jusqu'à l'arrivée de l'ambulance."}]}
	],
	aid_sunburn: [
		{k: "title", t: "Coup de soleil"},
		{k: "step", p: [{t: "Déplacez la victime de la lumière directe du soleil. Éviter de nouvelles expositions au soleil."}]},
		{k: "step", p: [{t: "Faire boire beaucoup d'eau pour arrêter la déshydratation."}]},
		{k: "step", p: [{t: "Si brûlure grave (cloques, rougeur, douleur), demandez un avis médical."}]},
		{k: "step", p: [{t: "Si la peau est légèrement rouge, elle peut être refroidi à l'aide de compresse humide. Utilisez une lotion ou gel de protection solaire."}]}
	],
	aid_sunstroke: [
		{k: "title", t: "Insolation"},
		{k: "description", t: "Tête chaude, visage rouge, maux de tête, vertiges. Cause: Irritation de la membrane cérébrale."},
		{k: "image", i: "aid035"},
		{k: "step", p: [{t: "Déplacez la victime dans un endroit frais (à l'ombre) et la partie supérieure du corps de la victime doit rester élevée."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Refroidir la tête avec des couvertures humides."}]},
		{k: "step", p: [{t: "Appelez les Urgences, Surveillez la respiration."}]},
		{k: "step", p: [{t: "Si conscient: Donnez une boisson fraîche le cas échéant."}]},
		{k: "step", p: [{t: "Si arrêt respiratoire, démarrez avec la respiration:"}]},
		{k: "step", p: [{t: "Commencez le bouche-à-bouche!", h: "#aid_apnoea"}]},
		{k: "image", i: "aid036"}
	],
	aid_unconsciouswithbreath: [
		{k: "title", t: "Inconscient avec respiration"},
		{k: "description", t: "Victime ne réagit pas lorsqu'on lui parle, pas de réaction lorsqu'on la secoue. Respiration existe."},
		{k: "image", i: "aid057"},
		{k: "step", p: [{t: "Si il y a des gens à côté de vous, demandez de l'aide."}]},
		{k: "step", p: [{t: "Position latérale de sécurité.", h: "#aid_recoveryposition"}, {t: " Ouvrir la bouche et positionnez la tête de cette façon à laissez sortir le vomit."}]},
		{k: "image", i: "aid008"},
		{k: "image", i: "aid009"},
		{k: "step", p: [{t: "Appelez les services d'urgence."}]}
	],
	aid_unconsciouswithoutbreath: [
		{k: "title", t: "Inconscient sans respiration"},
		{k: "step", p: [{t: "Pas de réaction de la victime, pas de respiration."}]},
		{k: "image", i: "aid057"},
		{k: "step", p: [{t: "Lancer la réanimation.", h: "#aid_resuscitation"}]}
	],
	aid_vomiting: [
		{k: "title", t: "Vomissements"},
		{k: "description", t: "Provoqué par des nausées. L'estomac se vide. Causes: infections, intoxications, ulcère, drogues/médicaments, mauvaise alimentation, grossesse."},
		{k: "image", i: "aid054"},
		{k: "step", p: [{t: "Danger pour la circulation sanguine en raison de la déshydratation et la perte de sel!"}]},
		{k: "step", p: [{t: "Faire boire (thé, eau)."}]},
		{k: "step", p: [{t: "Si il y a de forts troubles, du sang ou des vomissements continus appelez les Urgences. "}]}
	]
};
var langContinents=[
	{i: "Africa", t: "Afrique"},
	{i: "Northamerica", t: "Amérique du Nord / Centrale"},
	{i: "Southamerica", t: "Amérique du Sud"},
	{i: "Asia", t: "Asie"},
	{i: "Europe", t: "Europe"},
	{i: "Oceania", t: "Océanie"}
];
var langCountries=[
	{i: "afghanistan", t: "Afghanistan"},
	{i: "southafrica", t: "Afrique du Sud"},
	{i: "albania", t: "Albanie"},
	{i: "algeria", t: "Algérie"},
	{i: "germany", t: "Allemagne"},
	{i: "andorra", t: "Andorre"},
	{i: "angola", t: "Angola"},
	{i: "antiguaandbarbuda", t: "Antigua-et-Barbuda"},
	{i: "saudiarabia", t: "Arabie saoudite"},
	{i: "argentina", t: "Argentine"},
	{i: "armenia", t: "Arménie"},
	{i: "australia", t: "Australie"},
	{i: "austria", t: "Autriche"},
	{i: "azerbaijan", t: "Azerbaïdjan"},
	{i: "bahamas", t: "Bahamas"},
	{i: "bahrain", t: "Bahreïn"},
	{i: "bangladesh", t: "Bangladesh"},
	{i: "barbados", t: "Barbade"},
	{i: "belgium", t: "Belgique"},
	{i: "belize", t: "Belize"},
	{i: "benin", t: "Bénin"},
	{i: "bhutan", t: "Bhoutan"},
	{i: "belarus", t: "Biélorussie"},
	{i: "bolivia", t: "Bolivie"},
	{i: "bosniaandherzegovina", t: "Bosnie-Herzégovine"},
	{i: "botswana", t: "Botswana"},
	{i: "brazil", t: "Brésil"},
	{i: "brunei", t: "Brunei"},
	{i: "bulgaria", t: "Bulgarie"},
	{i: "burkinafaso", t: "Burkina Faso"},
	{i: "burundi", t: "Burundi"},
	{i: "cambodia", t: "Cambodge"},
	{i: "cameroon", t: "Cameroun"},
	{i: "canada", t: "Canada"},
	{i: "capeverde", t: "Cap-Vert"},
	{i: "chile", t: "Chili"},
	{i: "china", t: "Chine"},
	{i: "cyprus", t: "Chypre"},
	{i: "vaticancity", t: "Cité du Vatican"},
	{i: "colombia", t: "Colombie"},
	{i: "comoros", t: "Comores"},
	{i: "congorepublic", t: "Congo (République)"},
	{i: "congodemocraticrepublic", t: "Congo (République démocratique)"},
	{i: "northkorea", t: "Corée du Nord"},
	{i: "southkorea", t: "Corée du Sud (République de Corée)"},
	{i: "costarica", t: "Costa Rica"},
	{i: "ivorycoast", t: "Côte d'Ivoire"},
	{i: "croatia", t: "Croatie"},
	{i: "cuba", t: "Cuba"},
	{i: "denmark", t: "Danemark"},
	{i: "djibouti", t: "Djibouti"},
	{i: "dominica", t: "Dominique"},
	{i: "egypt", t: "Egypte"},
	{i: "elsalvador", t: "El Salvador"},
	{i: "unitedarabemirates", t: "Émirats arabes unis"},
	{i: "ecuador", t: "Equateur"},
	{i: "eritrea", t: "Erythrée"},
	{i: "spain", t: "Espagne"},
	{i: "estonia", t: "Estonie"},
	{i: "unitedstatesofamerica", t: "États-Unis d'Amérique"},
	{i: "ethiopia", t: "Ethiopie"},
	{i: "fiji", t: "Fidji"},
	{i: "finland", t: "Finlande"},
	{i: "france", t: "France"},
	{i: "gabon", t: "Gabon"},
	{i: "gambia", t: "Gambie"},
	{i: "georgia", t: "Géorgie"},
	{i: "ghana", t: "Ghana"},
	{i: "greece", t: "Grèce"},
	{i: "grenada", t: "Grenade"},
	{i: "greenland", t: "Groenland"},
	{i: "guatemala", t: "Guatemala"},
	{i: "guinea", t: "Guinée"},
	{i: "guinea-bissau", t: "Guinée-Bissau"},
	{i: "equatorialguinea", t: "Guinée équatoriale"},
	{i: "guyana", t: "Guyana"},
	{i: "haiti", t: "Haïti"},
	{i: "honduras", t: "Honduras"},
	{i: "hongkong", t: "Hong Kong"},
	{i: "hungary", t: "Hongrie"},
	{i: "caymanislands", t: "Îles Caïmans"},
	{i: "marshallislands", t: "Iles Marshall"},
	{i: "solomonislands", t: "Îles Salomon"},
	{i: "india", t: "Inde"},
	{i: "indonesia", t: "Indonésie"},
	{i: "iran", t: "Iran"},
	{i: "iraq", t: "Iraq"},
	{i: "ireland", t: "Irlande"},
	{i: "iceland", t: "Islande"},
	{i: "israel", t: "Israël"},
	{i: "italy", t: "Italie"},
	{i: "jamaica", t: "Jamaïque"},
	{i: "japan", t: "Japon"},
	{i: "jordan", t: "Jordanie"},
	{i: "kazakhstan", t: "Kazakhstan"},
	{i: "kenya", t: "Kenya"},
	{i: "kyrgyzstan", t: "Kirghizistan"},
	{i: "kiribati", t: "Kiribati"},
	{i: "kosovo", t: "Kosovo"},
	{i: "kuwait", t: "Koweït"},
	{i: "kurdistan", t: "Kurdistan"},
	{i: "laos", t: "Laos"},
	{i: "lesotho", t: "Lesotho"},
	{i: "latvia", t: "Lettonie"},
	{i: "lebanon", t: "Liban"},
	{i: "liberia", t: "Libéria"},
	{i: "libya", t: "Libye"},
	{i: "liechtenstein", t: "Liechtenstein"},
	{i: "lithuania", t: "Lituanie"},
	{i: "luxembourg", t: "Luxembourg"},
	{i: "macau", t: "Macao"},
	{i: "macedonia", t: "Macédoine"},
	{i: "madagascar", t: "Madagascar"},
	{i: "malaysia", t: "Malaisie"},
	{i: "malawi", t: "Malawi"},
	{i: "maldives", t: "Maldives"},
	{i: "mali", t: "Mali"},
	{i: "malta", t: "Malte"},
	{i: "morocco", t: "Maroc"},
	{i: "mauritius", t: "Maurice"},
	{i: "mauritania", t: "Mauritanie"},
	{i: "mayotte", t: "Mayotte"},
	{i: "mexico", t: "Mexique"},
	{i: "micronesia", t: "Micronésie"},
	{i: "moldova", t: "Moldova"},
	{i: "monaco", t: "Monaco"},
	{i: "mongolia", t: "Mongolie"},
	{i: "montenegro", t: "Monténégro"},
	{i: "mozambique", t: "Mozambique"},
	{i: "myanmar", t: "Myanmar"},
	{i: "namibia", t: "Namibie"},
	{i: "nauru", t: "Nauru"},
	{i: "nepal", t: "Népal"},
	{i: "nicaragua", t: "Nicaragua"},
	{i: "niger", t: "Niger"},
	{i: "nigeria", t: "Nigéria"},
	{i: "norway", t: "Norvège"},
	{i: "newzealand", t: "Nouvelle-Zélande"},
	{i: "oman", t: "Oman"},
	{i: "uganda", t: "Ouganda"},
	{i: "uzbekistan", t: "Ouzbékistan"},
	{i: "pakistan", t: "Pakistan"},
	{i: "palau", t: "Palau"},
	{i: "panama", t: "Panama"},
	{i: "papuanewguinea", t: "Papouasie-Nouvelle-Guinée"},
	{i: "paraguay", t: "Paraguay"},
	{i: "netherlands", t: "Pays-Bas"},
	{i: "peru", t: "Pérou"},
	{i: "philippines", t: "Philippines"},
	{i: "poland", t: "Pologne"},
	{i: "portugal", t: "Portugal"},
	{i: "qatar", t: "Qatar"},
	{i: "sahrawiarabdemocraticrepublic", t: "République arabe sahraouie démocratique"},
	{i: "centralafricanrepublic", t: "République centrafricaine"},
	{i: "dominicanrepublic", t: "République dominicaine"},
	{i: "czechrepublic", t: "République tchèque"},
	{i: "reunion", t: "Réunion"},
	{i: "romania", t: "Roumanie"},
	{i: "unitedkingdom", t: "Royaume-Uni"},
	{i: "russia", t: "Russie"},
	{i: "rwanda", t: "Rwanda"},
	{i: "stlucia", t: "Sainte-Lucie"},
	{i: "stkittsandnevis", t: "Saint-Kitts-et-Nevis"},
	{i: "sanmarino", t: "Saint-Marin"},
	{i: "saintpierreandmiquelon", t: "Saint-Pierre-et-Miquelon"},
	{i: "stvincentandgrenadines", t: "Saint-Vincent-et-les Grenadines"},
	{i: "samoa", t: "Samoa"},
	{i: "saotomeandprincipe", t: "Sao Tomé et Principe"},
	{i: "senegal", t: "Sénégal"},
	{i: "serbia", t: "Serbie"},
	{i: "seychelles", t: "Seychelles"},
	{i: "sierraleone", t: "Sierra Leone"},
	{i: "singapore", t: "Singapour"},
	{i: "slovakia", t: "Slovaquie"},
	{i: "slovenia", t: "Slovénie"},
	{i: "somalia", t: "Somalie"},
	{i: "sudan", t: "Soudan"},
	{i: "srilanka", t: "Sri Lanka"},
	{i: "sweden", t: "Suède"},
	{i: "switzerland", t: "Suisse"},
	{i: "suriname", t: "Suriname"},
	{i: "swaziland", t: "Swaziland"},
	{i: "syria", t: "Syrie"},
	{i: "tajikistan", t: "Tadjikistan"},
	{i: "taiwan", t: "Taiwan"},
	{i: "tanzania", t: "Tanzanie"},
	{i: "chad", t: "Tchad"},
	{i: "thailand", t: "Thaïlande"},
	{i: "easttimor", t: "Timor oriental"},
	{i: "togo", t: "Togo"},
	{i: "tonga", t: "Tonga"},
	{i: "trinidadandtobago", t: "Trinité-et-Tobago"},
	{i: "tunisia", t: "Tunisie"},
	{i: "turkmenistan", t: "Turkménistan"},
	{i: "turkey", t: "Turquie"},
	{i: "tuvalu", t: "Tuvalu"},
	{i: "ukraine", t: "Ukraine"},
	{i: "uruguay", t: "Uruguay"},
	{i: "vanuatu", t: "Vanuatu"},
	{i: "venezuela", t: "Venezuela"},
	{i: "vietnam", t: "Vietnam"},
	{i: "yemen", t: "Yémen"},
	{i: "zambia", t: "Zambie"},
	{i: "zimbabwe", t: "Zimbabwe"}
];
