//:Erste Hilfe
// Generated file, do not edit
var langTexts={
	title: "Erste Hilfe",
	back: "Zurück",
	continent: "Kontinent",
	emergency_fire: "Feuerwehr",
	emergency_medical: "Notarzt",
	emergency_police: "Polizei",
	emergency_cancelcard: "Geldkarten sperren",
	emergency_local: "lokale Nummern",
	emergency_nosystem: "kein System",
	emergency_radioonly: "nur Radiotelefon",
	emergency_none: "--",
	emergency_or: "oder",
	emergency_mobile: "mobil",
	emergency_tourist: "Touristen"
};
var langMenu=[
	{h: "#aid_disclaimer", t: "# Haftung + Hinweise!"},
	{h: "#numbers", t: "# Notrufe weltweit"},
	{h: "#aid_general", t: "# Allgemeines"},
	{h: "#aid_allergic", t: "Allergische Reaktion"},
	{h: "#aid_amputation", t: "Amputation"},
	{h: "#aid_asthma", t: "Asthma / Atemnot"},
	{h: "#aid_apnoea", t: "Atemstillstand"},
	{h: "#aid_checkbreathing", t: "Atmung prüfen"},
	{h: "#aid_eyeinjury", t: "Augenverletzung"},
	{h: "#aid_apnoea", t: "Beatmung"},
	{h: "#aid_unconsciouswithbreath", t: "Bewusstlosigkeit mit Atmung"},
	{h: "#aid_unconsciouswithoutbreath", t: "Bewusstlosigkeit ohne Atmung"},
	{h: "#aid_bleedinglight", t: "Blutung (leicht)"},
	{h: "#aid_bleedingsevere", t: "Blutung (schwer)"},
	{h: "#aid_diabeticcoma", t: "Diabetisches Koma"},
	{h: "#aid_diarrhoea", t: "Durchfall"},
	{h: "#aid_icerescue", t: "Eisunfall"},
	{h: "#aid_electricityaccident", t: "Elektrounfall"},
	{h: "#aid_epilepsy", t: "Epileptischer Anfall"},
	{h: "#aid_vomiting", t: "Erbrechen"},
	{h: "#aid_frostbitemild", t: "Erfrierung (leicht)"},
	{h: "#aid_frostbitesevere", t: "Erfrierung (stark)"},
	{h: "#aid_suffocation", t: "Ersticken"},
	{h: "#aid_drowning", t: "Ertrinken"},
	{h: "#aid_birth", t: "Geburt"},
	{h: "#aid_dangerzone", t: "Gefahrenzone (Retten)"},
	{h: "#aid_brainconcussion", t: "Gehirnerschütterung"},
	{h: "#aid_resuscitation", t: "Herzdruckmassage"},
	{h: "#aid_heartattack", t: "Herzinfarkt"},
	{h: "#aid_hyperthermia", t: "Hitzschlag"},
	{h: "#aid_insectstings", t: "Insektenstich"},
	{h: "#aid_fracture", t: "Knochenbruch"},
	{h: "#aid_nosebleeding", t: "Nasenbluten"},
	{h: "#aid_emergencycall", t: "Notruf"},
	{h: "#aid_resuscitation", t: "Reanimation"},
	{h: "#aid_backinjury", t: "Rückenverletzung"},
	{h: "#aid_skullfracture", t: "Schädelbasisbruch"},
	{h: "#aid_stroke", t: "Schlaganfall"},
	{h: "#aid_snakebite", t: "Schlangenbiss"},
	{h: "#aid_shock", t: "Schock"},
	{h: "#aid_sunburn", t: "Sonnenbrand"},
	{h: "#aid_sunstroke", t: "Sonnenstich"},
	{h: "#aid_sos", t: "SOS"},
	{h: "#aid_recoveryposition", t: "Stabile Seitenlage"},
	{h: "#aid_animalbite", t: "Tierbiss"},
	{h: "#aid_hyperthermia", t: "Überhitzung"},
	{h: "#aid_diabeticcoma", t: "Überzuckerung"},
	{h: "#aid_safeguardaccident", t: "Unfallstelle sichern"},
	{h: "#aid_hypothermia", t: "Unterkühlung"},
	{h: "#aid_hypoglycaemia", t: "Unterzuckerung"},
	{h: "#aid_chemicalburn", t: "Verätzung"},
	{h: "#aid_chemicalburneyes", t: "Verätzung (Augen)"},
	{h: "#aid_burningslight", t: "Verbrennung (leicht)"},
	{h: "#aid_burningsevere", t: "Verbrennung (schwer)"},
	{h: "#aid_poisining", t: "Vergiftung"},
	{h: "#aid_safeguardaccident", t: "Verkehrsunfall"},
	{h: "#aid_suffocation", t: "Verschlucken"},
	{h: "#aid_sprain", t: "Verstauchung + Verrenkung"},
	{h: "#aid_resuscitation", t: "Wiederbelebung"},
	{h: "#aid_backinjury", t: "Wirbelsäule"},
	{h: "tel:112", t: "Notruf 112 wählen"}
];
var langSections={
	aid_disclaimer: [
		{k: "title", t: "Haftung + Hinweise"},
		{k: "subsection", t: "Software"},
		{k: "description", t: "Erste Hilfe auf dem Handy"},
		{k: "description", t: "Copyright: Kai Kajus Noack"},
		{k: "description", t: "Lizenz: Creative Commons"},
		{k: "image", i: "cc88x31"},
		{k: "description", t: "Dieses Programm soll Informationen zur Ersten Hilfe geben. Es stellt jedoch in keiner Weise einen Ersatz für einen Erste-Hilfe-Kurs dar, sondern dient der Auffrischung des bereits erworbenen Wissens. "},
		{k: "description", t: "Illustrationen © Med4Teens"},
		{k: "subsection", t: "Haftungsausschluss"},
		{k: "description", t: "Bitte beachten Sie, dass ich keine Verantwortung für Konsequenzen, die aus der Nutzung entstehen, übernehme."},
		{k: "description", t: "JEGLICHE HAFTUNG IST AUSGESCHLOSSEN!"},
		{k: "description", t: "VERWENDUNG AUF EIGENE GEFAHR!"},
		{k: "description", t: "In allen Notfällen suchen Sie bitte sofort professionelle Hilfe."},
		{k: "subsection", t: "Rette einen Menschen und du rettest die ganze Welt."}
	],
	aid_general: [
		{k: "title", t: "Allgemeines"},
		{k: "step", p: [{t: "Leisten Sie immer Erste Hilfe. Sie können keine Fehler machen."}]},
		{k: "step", p: [{t: "Achten Sie immer auf Ihre eigene Sicherheit."}]},
		{k: "step", p: [{t: "Machen Sie sich ein Bild von der Situation + Sichern Sie die Unfallstelle."}]},
		{k: "step", p: [{t: "Notruf + Sofortmaßnahmen!"}]},
		{k: "step", p: [{t: "Bei mehreren Verletzten hat der am stärksten bedrohte Vorrang."}]},
		{k: "step", p: [{t: "Beruhigen Sie den Betroffenen. Und bleiben Sie selbst ruhig!"}]},
		{k: "step", p: [{t: "Lagern Sie den Betroffenen falls möglich bequem. Grundsätzlich nie Alkohol, Nikotin oder Medikamente verabreichen."}]}
	],
	aid_allergic: [
		{k: "title", t: "Allergische Reaktion", i: "aid046"},
		{k: "step", p: [{t: "Notruf absetzen."}]},
		{k: "step", p: [{t: "Beruhigen des Betroffenen und bequem hinsetzen."}]},
		{k: "step", p: [{t: "Allergie-auslösenden Stoff (z. B. Insektenstachel) vorsichtig entfernen."}]},
		{k: "step", p: [{t: "Betroffene Hautstelle kühlen (feuchter Umschlag, Eis)."}]},
		{k: "image", i: "aid046ice"},
		{k: "step", p: [{t: "Falls Betroffener ein Gegenmittel hat, sollte er dieses nutzen."}]},
		{k: "step", p: [{t: "Kontrolle des Zustands bis Notarzt eintrifft."}]},
		{k: "step", p: [{t: "Bei eintretender Bewusstlosigkeit oder Atemnot entsprechende Maßnahmen ergreifen!"}]},
		{k: "image", i: "aid077"}
	],
	aid_amputation: [
		{k: "title", t: "Amputation"},
		{k: "description", t: "Abgetrennter Körperteil kann wieder angenäht werden. Ziel: Amputat bis zum Eintreffen im Krankenhaus kühlen. "},
		{k: "step", p: [{t: "Betroffenen beruhigen, hinlegen und zudecken."}]},
		{k: "step", p: [{t: "Blutung stoppen, siehe 'Blutung (schwer)' und 'Schock'."}]},
		{k: "step", p: [{t: "Abgetrennten Körperteil in ein sauberes trockenes Tuch wickeln und in eine wasserdichte Plastiktüte legen. "}]},
		{k: "step", p: [{t: "Diese Plastiktüte verschließen und in eine zweite Plastiktüte legen, die kühles Wasser/Eis enthält. "}]},
		{k: "step", p: [{t: "Keinen Alkohol, Zigaretten oder Essen geben (falls im Krankenhaus mit Narkose operiert wird). "}]},
		{k: "step", p: [{t: "Das Amputat nicht einfrieren (nur kühlen). "}]},
		{k: "step", p: [{t: "Notarzt rufen oder selbst zum Krankenhaus fahren. "}]}
	],
	aid_animalbite: [
		{k: "title", t: "Tierbiss", i: "aid047"},
		{k: "description", t: "Achtung, hohe Infektionsgefahr. Folgen wie Eiter, Tetanus, Tollwut."},
		{k: "step", p: [{t: "Wunde sofort mit heißem Seifenwasser auswaschen."}]},
		{k: "image", i: "aid049"},
		{k: "step", p: [{t: "Anschließend Wunddesinfektion auftragen."}]},
		{k: "step", p: [{t: "Bei starker Blutung den Oberkörper erhöht lagern."}]},
		{k: "step", p: [{t: "Keimfreien Verband anlegen."}]},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Krankenhaus aufsuchen oder Notruf absetzen."}]}
	],
	aid_apnoea: [
		{k: "title", t: "Atemstillstand"},
		{k: "description", t: "Keine Geräusche oder Atembewegungen, auffallende Hautverfärbung."},
		{k: "step", p: [{t: "Notruf absetzen."}]},
		{k: "step", p: [{t: "Betroffenen auf Rücken legen."}]},
		{k: "step", p: [{t: "Entfernen von Fremdkörpern aus Mund und Rachen. Überstrecken des Kopfes in den Nacken."}]},
		{k: "image", i: "aid067"},
		{k: "step", p: [{t: "Nasenflügel zusammendrücken, damit Nase geschlossen ist."}]},
		{k: "image", i: "aid010"},
		{k: "step", p: [{t: "Tief einatmen und Mund auf Mund des Betroffenen aufsetzen, sodass keine Luft entweichen kann."}]},
		{k: "image", i: "aid011"},
		{k: "step", p: [{t: "Langsam und vollständig ausatmen."}]},
		{k: "step", p: [{t: "Falls ohne Erfolg: Atemspende fortsetzen bis Notarzt eintrifft."}]}
	],
	aid_asthma: [
		{k: "title", t: "Asthma / Atemnot"},
		{k: "description", t: "Starke Atemnot. Pfeifendes Atemgeräusch. Angstgefühle."},
		{k: "step", p: [{t: "Beruhigen des Betroffenen. (Bleiben Sie selbst ruhig!)"}]},
		{k: "step", p: [{t: "Kleidung lockern."}]},
		{k: "step", p: [{t: "Betroffenen bequem leicht nach vorne gebeugt hinsetzen und auffordern, langsam und tief ein- und auszuatmen."}]},
		{k: "step", p: [{t: "Falls der Betroffene einen Inhalator besitzt, sollte dieser benutzt werden (helfen Sie dabei). Nach 5-10 min sollte sich Wirkung zeigen."}]},
		{k: "image", i: "aid074"},
		{k: "step", p: [{t: "Sofern keine Besserung eintritt: Inhalator jede 5 min anwenden, solange bis Notarzt eintrifft."}]},
		{k: "step", p: [{t: "Notruf absetzen."}]},
		{k: "step", p: [{t: "Falls es zum Atemstillstand kommt, mit der "}, {t: "Beatmung", h: "#aid_apnoea"}, {t: " beginnen."}]}
	],
	aid_backinjury: [
		{k: "title", t: "Rückenverletzung"},
		{k: "description", t: "Schmerzen im Rücken, gefühllose Arme und Beine."},
		{k: "step", p: [{t: "Verletzten auf keinen Fall bewegen!"}]},
		{k: "image", i: "aid064"},
		{k: "step", p: [{t: "Kopf so halten, dass Betroffener stabil liegt."}]},
		{k: "image", i: "aid065"},
		{k: "step", p: [{t: "Verletzten nur mittels seitlicher Polsterung stabilisieren."}]},
		{k: "step", p: [{t: "Betroffenen beruhigen."}]},
		{k: "step", p: [{t: "Notruf absetzen, Hinweis auf Rückenverletzung."}]}
	],
	aid_birth: [
		{k: "title", t: "Geburt"},
		{k: "description", t: "Abgang von Fruchtwasser. Presswehen treten ein. Unerwartete Geburt."},
		{k: "image", i: "aid025"},
		{k: "step", p: [{t: "Intimsphäre wahren und Ruhe bewahren! - Notruf absetzen."}]},
		{k: "step", p: [{t: "Die Schwangere breitbeinig, mit freigemachtem Unterkörper auf sterile Unterlage hinsetzen."}]},
		{k: "step", p: [{t: "Kniee anwinkeln. Beine etwas heranziehen. Becken leicht erhöht lagern. - Die Geburt ist ein natürlicher Prozess und läuft häufig ohne Komplikationen ab."}]},
		{k: "step", p: [{t: "Schwangere beruhigen und auf Atmung konzentrieren lassen: Durch Nase einatmen und Mund ausatmen (normales Atemtempo)."}]},
		{k: "step", p: [{t: "Pressrhythmus: Tief Luft holen, anhalten und pressen. Sobald Kopf des Babys erscheint, mit beiden Händen unterstützend zugreifen."}]},
		{k: "image", i: "aid021"},
		{k: "image", i: "aid022"},
		{k: "step", p: [{t: "Nach der Geburt: Neugeborenes schräg nach unten hängen, um Fruchtwasser aus Atemwegen zu befreien. (Evtl. mit dem Mund das Fruchtwasser aus der Nase des Babys absaugen.) Kind muss atmen und schreien!"}]},
		{k: "step", p: [{t: "Nabelschnur 30 cm vom Kind entfernt abbinden (kann auch im Krankenhaus erfolgen). Scheide der Mutter steril abdecken."}]},
		{k: "image", i: "aid023"},
		{k: "step", p: [{t: "Das Baby abtrocknen und warm halten. Uhrzeit notieren und zum Krankenhaus fahren."}]}
	],
	aid_bleedinglight: [
		{k: "title", t: "Blutung (leicht)", i: "aid082"},
		{k: "description", t: "Ziel: Stoppen der Blutung."},
		{k: "step", p: [{t: "Wunde nicht berühren (Infektionsgefahr)."}]},
		{k: "step", p: [{t: "Wunde nicht mit Puder, Salben, Sprays behandeln."}]},
		{k: "step", p: [{t: "Wundversorgung mittels keimfreier Wundauflage und Befestigungsmaterial (Pflaster, Binde)."}]},
		{k: "image", i: "aid098"},
		{k: "step", p: [{t: "Bei kleiner Blutung reicht meist ein Pflasterstreifen."}]},
		{k: "step", p: [{t: "Bei großflächiger Verletzung Wundauflage und Verbandtuch benutzen. Verband nicht zu fest binden, da Stauung zu vermehrter Blutung führt."}]},
		{k: "image", i: "aid084"},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Hinweis: Tollwut-Wunden mit Seifenlösung auswaschen."}]},
		{k: "image", i: "aid049"}
	],
	aid_bleedingsevere: [
		{k: "title", t: "Blutung (schwer)"},
		{k: "description", t: "Spritzendes, in Stößen austretendes Blut. Gefahr: Schock durch Blutverlust, Infektionen, Tod. Ziel: Stoppen der Blutung."},
		{k: "step", p: [{t: "Kleidung entfernen (notfalls aufschneiden), Wunde freilegen."}]},
		{k: "step", p: [{t: "Binde oder notfalls Kleidungsstück mit Druck um Wunde wickeln."}]},
		{k: "image", i: "aid086"},
		{k: "step", p: [{t: "Für mind. 10 min Druck auf Wunde ausüben."}]},
		{k: "step", p: [{t: "Falls Binde mit Blut durchnässt, nicht die alte Binde entfernen! Eine andere Binde/Kleidungsstück darüber binden."}]},
		{k: "step", p: [{t: "Verletztes Glied (sofern nicht gebrochen) über Höhe des Herzens lagern, damit sich Blutung verlangsamt. Wenn möglich Betroffenen hinlegen."}]},
		{k: "step", p: [{t: "Falls Blutung nicht stoppt, Druck auf Wunde beibehalten und zusätzlich Druckpunkte über der Wunde setzen: Bei Blutung am Unterarm den Oberarm abdrücken (Ader auf Arm-Innenseite mittig zwischen Ellbogen und Achselhöhle, mit Fingern abdrücken). Bei Blutung des Beins, Druckpunkt in Leiste setzen (Ader in Leistenbeuge, wo Arterie über Beckenknochen verläuft, mit Handballen abdrücken)."}]},
		{k: "image", i: "aid089"},
		{k: "image", i: "aid092"},
		{k: "step", p: [{t: "Sofort Notarzt anfordern."}]},
		{k: "step", p: [{t: "Sobald Blutung unter Kontrolle: Schockbekämpfung einleiten."}]},
		{k: "image", i: "aid093"}
	],
	aid_brainconcussion: [
		{k: "title", t: "Gehirnerschütterung"},
		{k: "description", t: "Kopfschmerz, Übelkeit, Erbrechen. Sehstörung. Bewusstlosigkeit kann eintreten."},
		{k: "image", i: "aid035a"},
		{k: "step", p: [{t: "Betroffenen hinlegen."}]},
		{k: "step", p: [{t: "Notruf absetzen."}]},
		{k: "description", t: "Bei Blutung am Kopf:"},
		{k: "step", p: [{t: "Betroffenen hinlegen, Kopf erhöht lagern (Kissen)."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Wundversorgung durchführen (Kopf-Verband anlegen)."}]},
		{k: "step", p: [{t: "Notruf absetzen."}]}
	],
	aid_burningslight: [
		{k: "title", t: "Verbrennung (leicht)"},
		{k: "description", t: "Rötung der Haut. Leichte Schwellung. Schmerzen."},
		{k: "step", p: [{t: "Betroffene Stelle unter laufendem kalten Wasser kühlen."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Feuchten Verband locker anlegen."}]}
	],
	aid_burningsevere: [
		{k: "title", t: "Verbrennung (schwer)"},
		{k: "description", t: "Gefleckte weiße rote Stellen, Blasenbildung. Flüssigkeitsaustritt aus Haut. Tiefe Gewebeschädigung. Starke Schmerzen oder keine Schmerzen (aufgrund verbrannter Nerven)."},
		{k: "image", i: "aid097"},
		{k: "step", p: [{t: "Kleidung soweit wie möglich entfernen."}]},
		{k: "step", p: [{t: "Mit kaltem Wasser (ca. 15°C) bis zu 10 min kühlen, bis Schmerzlinderung eintritt."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Falls Verbrennung großflächig, nur mit feuchten Tüchern kühlen."}]},
		{k: "step", p: [{t: "Notruf absetzen."}]},
		{k: "step", p: [{t: "Nach Kühlung die Wundversorgung durchführen. Sterile, trockene Wundauflage benutzen. Keine Flüssigkeiten aufbringen (keine Cremes, Öle, Salben etc.). Blasen nicht aufstechen."}]},
		{k: "image", i: "aid085"},
		{k: "step", p: [{t: "Atmung und Bewusstsein des Betroffenen kontrollieren, bis Notarzt eintrifft."}]}
	],
	aid_checkbreathing: [
		{k: "title", t: "Atmung prüfen"},
		{k: "step", p: [{t: "Atemgeräusche prüfen."}]},
		{k: "step", p: [{t: "Atmung am Oberbauch feststellen (Hand auflegen)."}]},
		{k: "image", i: "aid027"},
		{k: "step", p: [{t: "Atmung an Nase/Mund fühlbar."}]}
	],
	aid_chemicalburneyes: [
		{k: "title", t: "Verätzung (Augen)"},
		{k: "step", p: [{t: "Notarzt rufen, auf Ätz-Substanz hinweisen."}]},
		{k: "step", p: [{t: "Auge sofort mit viel Wasser spülen. Gesundes Auge während Spülung abdecken."}]},
		{k: "step", p: [{t: "Wasserstrahl vom inneren Augenwinkel zum äußeren Augenwinkel. Ca. 20 min reinigen."}]},
		{k: "image", i: "aid019"},
		{k: "step", p: [{t: "Beide Augen des Betroffenen schließen und mit angefeuchtetem Tuch verbinden."}]},
		{k: "image", i: "aid020"},
		{k: "step", p: [{t: "Zustand kontrollieren, bis Notarzt eintrifft."}]}
	],
	aid_chemicalburn: [
		{k: "title", t: "Verätzung"},
		{k: "description", t: "Zerstörung von Gewebe."},
		{k: "image", i: "aid095"},
		{k: "step", p: [{t: "Eigenschutz beachten!"}]},
		{k: "step", p: [{t: "Zügig handeln und verätzte Stellen abspülen (bei Verätzung der Augen mind. 20 min mit klarem Wasser spülen). Wasserstrahl vom inneren Augenwinkel zum äußeren Augenwinkel."}]},
		{k: "image", i: "aid100"},
		{k: "step", p: [{t: "Notruf absetzen."}]},
		{k: "step", p: [{t: "Bei Verätzung des Verdauungsweges: Vermehrt Flüssigkeit trinken."}]},
		{k: "step", p: [{t: "Kein Erbrechen auslösen!"}]}
	],
	aid_dangerzone: [
		{k: "title", t: "Gefahrenzone (Retten)"},
		{k: "step", p: [{t: "Grifftechnik: Arm des Verletzten vor dessen Brust, hinter den Verletzten stellen."}]},
		{k: "step", p: [{t: "Mit beiden Händen den angewinkelten Arm des Verletzten durch dessen Achseln greifen."}]},
		{k: "step", p: [{t: "Person in Sicherheit bringen."}]},
		{k: "image", i: "aid001"},
		{k: "image", i: "aid007"}
	],
	aid_diabeticcoma: [
		{k: "title", t: "Diabetisches Koma"},
		{k: "description", t: "Blutzuckerspiegel zu hoch bzw. Insulinmangel."},
		{k: "description", t: "Symptome: Durst, häufiges Wasserlassen, Übelkeit, Erbrechen. Atem riecht nach Obst."},
		{k: "step", p: [{t: "Notruf absetzen."}]},
		{k: "step", p: [{t: "Unterstützung bei der Insulingabe, sofern sichergestellt, dass Diabetiker."}]},
		{k: "image", i: "aid016"},
		{k: "step", p: [{t: "Stabile Seitenlage", h: "#aid_recoveryposition"}, {t: ". (Keine weiteren Möglichkeiten für den Ersthelfer.)"}]},
		{k: "step", p: [{t: "Zustand des Betroffenen kontrollieren bis Notarzt eintrifft."}]}
	],
	aid_diarrhoea: [
		{k: "title", t: "Durchfall"},
		{k: "description", t: "Nahrungsmittel-Unverträglichkeit, Darm-Entzündung oder Erkrankung. Stuhlgang wässrig, schleimig oder blutig."},
		{k: "step", p: [{t: "Gefahr für Kreislauf aufgrund Flüssigkeits- und Salz-Verlustes!"}]},
		{k: "step", p: [{t: "Flüssigkeit zuführen (Tee, Wasser)."}]},
		{k: "step", p: [{t: "Bei starken Beschwerden Arzt aufsuchen oder Notruf absetzen."}]}
	],
	aid_drowning: [
		{k: "title", t: "Ertrinken"},
		{k: "step", p: [{t: "Notruf absetzen. Personen in der Nähe um Hilfe bitten."}]},
		{k: "image", i: "aid032"},
		{k: "step", p: [{t: "Aus Wasser retten!"}]},
		{k: "image", i: "aid033"},
		{k: "image", i: "aid034"},
		{k: "step", p: [{t: "Wenn Atmung vorhanden: "}, {t: "Stabile Seitenlage", h: "#aid_recoveryposition"}, {t: ". Betroffenen warm halten (Decke). Zustand kontrollieren, bis der Notarzt eintrifft."}]},
		{k: "step", p: [{t: "Bei Atemstillstand sofort mit "}, {t: "Wiederbelebung beginnen!", h: "#aid_resuscitation"}, {t: " (Ausfließenlassen von Wasser aus Lungen ist nutzlos.)"}]}
	],
	aid_electricityaccident: [
		{k: "title", t: "Elektrounfall"},
		{k: "step", p: [{t: "Zuerst Stromzuleitung unterbrechen!"}]},
		{k: "image", i: "aid045plug"},
		{k: "image", i: "aid045"},
		{k: "step", p: [{t: "Gefahr: Bewusstlosigkeit, Atemstillstand."}]},
		{k: "step", p: [{t: "A - Bewusstlosigkeit mit Atmung", h: "#aid_unconsciouswithbreath"}]},
		{k: "step", p: [{t: "B - Bewusstlosigkeit ohne Atmung", h: "#aid_unconsciouswithoutbreath"}]},
		{k: "image", i: "aid042"},
		{k: "image", i: "aid043"}
	],
	aid_emergencycall: [
		{k: "title", t: "Notruf"},
		{k: "step", p: [{t: "Wählen Sie mit dem nächst-verfügbaren Telefon 112. Immer möglich und kostenlos! Zögern Sie nie, den Notarzt zu rufen!"}]},
		{k: "step", p: [{t: "Am Telefon Folgendes durchgeben:"}]},
		{k: "step", p: [{t: "- Wo (Unfallort). "}]},
		{k: "step", p: [{t: "- Was ist passiert. "}]},
		{k: "step", p: [{t: "- Wie viele Verletzte. "}]},
		{k: "step", p: [{t: "- Welche Verletzungen. "}]},
		{k: "step", p: [{t: "Danach auf Rückfragen warten."}]}
	],
	aid_epilepsy: [
		{k: "title", t: "Epileptischer Anfall"},
		{k: "description", t: "Starrer Körper, geballte Fäuste, gepresster Kiefer, Zucken in Beinen oder Gesicht. Rollende Augen. Speichelfluss. Bewusstlosigkeit möglich."},
		{k: "image", i: "aid058"},
		{k: "step", p: [{t: "Betroffenen nicht halten oder in Bewegung einschränken."}]},
		{k: "step", p: [{t: "Betroffenen auf weiche Unterlage (Kissen) legen, Objekte in direkter Nähe entfernen, somit Selbstverletzungen vorbeugen."}]},
		{k: "step", p: [{t: "Beruhigend zum Betroffenen reden. Kleidung lockern, für Atemfreiheit sorgen."}]},
		{k: "step", p: [{t: "Falls Betroffener erbricht, Kopf zur Seite drehen, damit Erbrochenes abfließen kann."}]},
		{k: "step", p: [{t: "Atemwege freihalten. Gefahr, dass Zunge verschluckt wird."}]},
		{k: "step", p: [{t: "Stabile Seitenlage", h: "#aid_recoveryposition"}, {t: " + Notruf absetzen. Weiterhin Zustand des Betroffenen kontrollieren."}]},
		{k: "step", p: [{t: "Andere Leute auf Distanz halten."}]}
	],
	aid_eyeinjury: [
		{k: "title", t: "Augenverletzung"},
		{k: "step", p: [{t: "Fremdkörper im Auge belassen, nicht entfernen."}]},
		{k: "step", p: [{t: "Augen nicht bewegen, um weitere Verletzungen zu vermeiden. Auge nicht berühren."}]},
		{k: "step", p: [{t: "Bei Augen-Blutung mit Kompresse oder Verbandtuch bedecken."}]},
		{k: "image", i: "aid020"},
		{k: "step", p: [{t: "Auge mit kalter Auflage kühlen (verringert Schwellung, Blutung stoppt schneller)."}]},
		{k: "step", p: [{t: "Notruf absetzen oder selbst zum Krankenhaus fahren."}]}
	],
	aid_fracture: [
		{k: "title", t: "Knochenbruch"},
		{k: "description", t: "Anzeichen: Unnatürliche Lage und Beweglichkeit. Deformierung. Schmerzhafte Bewegung, berührungsempfindlich."},
		{k: "image", i: "aid104"},
		{k: "step", p: [{t: "Bewegungen vermeiden!"}]},
		{k: "step", p: [{t: "Notruf absetzen."}]},
		{k: "step", p: [{t: "Bruch ruhig stellen, d.h. Umpolstern mit dichtem Material. Position des gebrochenen Knochens beibehalten."}]},
		{k: "image", i: "aid107"},
		{k: "step", p: [{t: "Bei offenem Bruch die Wunde keimfrei abdecken."}]},
		{k: "image", i: "aid106"}
	],
	aid_frostbitemild: [
		{k: "title", t: "Erfrierung (leicht)"},
		{k: "description", t: "Blässe, Schwellen. Gefahr für Blutzufuhr."},
		{k: "step", p: [{t: "Warmen Bereich aufsuchen."}]},
		{k: "step", p: [{t: "Kälte beseitigen. Nasse Kleidung entfernen, abtrocknen."}]},
		{k: "step", p: [{t: "Aufwärmen mit lauwarmem Wasser und Körperwärme des Helfers."}]},
		{k: "step", p: [{t: "Warmes Getränk (Tee) geben. Keinen Alkohol!"}]},
		{k: "image", i: "aid040"}
	],
	aid_frostbitesevere: [
		{k: "title", t: "Erfrierung (stark)"},
		{k: "description", t: "Kalte harte Haut, grau-weiß, Blasenbildung, Gewebe stirbt ab. Gefahr für Blutzufuhr!"},
		{k: "image", i: "aid096"},
		{k: "step", p: [{t: "Warmen Bereich aufsuchen."}]},
		{k: "step", p: [{t: "Wunden versorgen/abdecken."}]},
		{k: "step", p: [{t: "Zuckerhaltiges Getränk verabreichen."}]},
		{k: "step", p: [{t: "Nicht warmreiben!"}]},
		{k: "step", p: [{t: "Notruf absetzen."}]}
	],
	aid_heartattack: [
		{k: "title", t: "Herzinfarkt"},
		{k: "description", t: "Schwere mehr als 5 min anhaltende Schmerzen + Druck im Brustkorb, besonders in Arme/Schultern ausstrahlend. Angstgefühl, Blässe, kalter Schweiß. Eventuell Übelkeit, Kurzatmigkeit."},
		{k: "image", i: "aid076"},
		{k: "image", i: "aid083"},
		{k: "step", p: [{t: "Notruf absetzen! Hinweis auf vermuteten Herzinfarkt."}]},
		{k: "step", p: [{t: "Oberkörper erhöht lagern. Enge Kleidung lockern. Keine Medikamente oder Getränke geben."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Beruhigend auf Betroffenen einreden."}]},
		{k: "step", p: [{t: "Bewusstsein und Atmung kontrollieren."}]},
		{k: "step", p: [{t: "Dem Betroffenen Aspirin verabreichen, falls verfügbar."}]},
		{k: "step", p: [{t: "Bei Bewusstlosigkeit die "}, {t: "Wiederbelebung einleiten", h: "#aid_resuscitation"}, {t: "."}]}
	],
	aid_hypoglycaemia: [
		{k: "title", t: "Unterzuckerung"},
		{k: "description", t: "Blutzuckerspiegel unter Mindestwert (aufgrund Überdosierung von Insulin oder ungenügender Nahrungsaufnahme)."},
		{k: "description", t: "Symptome: Blässe, Nervosität, Hunger, Zittern, Schweiß."},
		{k: "image", i: "aid018"},
		{k: "step", p: [{t: "Zuerst klären, ob der Betroffene Diabetiker ist (siehe Diabetiker-Ausweis)."}]},
		{k: "step", p: [{t: "Notruf absetzen."}]},
		{k: "step", p: [{t: "Dem Betroffenen gezuckerte Getränke und Traubenzucker geben (sofern keine Schluckschwierigkeiten)."}]},
		{k: "image", i: "aid017"},
		{k: "step", p: [{t: "Bei Bewusstlosigkeit und vorhandener Atmung: "}, {t: "Stabile Seitenlage", h: "#aid_recoveryposition"}, {t: " einnehmen und Atmung kontrollieren. Falls Atemstillstand eintritt, den Betroffenen beatmen."}]},
		{k: "step", p: [{t: "Wenn Atmung vorhanden, dem Bewusstlosen ein Stück Zucker in die Backentasche legen und von außen gegendrücken."}]}
	],
	aid_hyperthermia: [
		{k: "title", t: "Überhitzung"},
		{k: "description", t: "Durst, Schwäche, Desorientiertheit, Bewusstseinsstörung, starker Schweiß, heiße Haut."},
		{k: "image", i: "aid035"},
		{k: "step", p: [{t: "Notruf absetzen."}]},
		{k: "step", p: [{t: "Kühlen, schattigen Platz aufsuchen (Raum mit Klimaanlage sehr geeignet)."}]},
		{k: "step", p: [{t: "Betroffenen hinlegen, Beine hochlagern. Kleidung lockern."}]},
		{k: "image", i: "aid078"},
		{k: "step", p: [{t: "Haut mit Wasser kühlen oder kalte Handtücher auflegen."}]},
		{k: "step", p: [{t: "Viel Wasser oder Säfte trinken."}]}
	],
	aid_hypothermia: [
		{k: "title", t: "Unterkühlung"},
		{k: "description", t: "Kältezittern, Schläfrigkeit, Erschöpfung, bis hin zur Bewusstlosigkeit. Kalte, blasse Haut. Langsamer Puls, schwacher Herzschlag."},
		{k: "image", i: "aid014"},
		{k: "step", p: [{t: "Warmen Bereich aufsuchen."}]},
		{k: "step", p: [{t: "Notruf absetzen."}]},
		{k: "step", p: [{t: "Kälteeinwirkung beenden. Körpertemperatur erhöhen (Decke und Körper-zu-Körper-Kontakt)."}]},
		{k: "step", p: [{t: "Nasse Kleidung entfernen und trockene warme Kleidung anziehen. In Decken packen. Kopf bedecken."}]},
		{k: "step", p: [{t: "Heißen Tee, Brühe oder heißes Wasser zu trinken geben. Keinen Alkohol! Betroffenen wachhalten."}]},
		{k: "image", i: "aid039"},
		{k: "image", i: "aid040"},
		{k: "step", p: [{t: "Zustand bis zum Eintreffen des Notarztes kontrollieren. Bei Verlust des Bewusstseins Wiederbelebung einleiten."}]},
		{k: "step", p: [{t: "A - Bewusstlosigkeit mit Atmung", h: "#aid_unconsciouswithbreath"}]},
		{k: "step", p: [{t: "B - Bewusstlosigkeit ohne Atmung", h: "#aid_unconsciouswithoutbreath"}]}
	],
	aid_icerescue: [
		{k: "title", t: "Eisunfall"},
		{k: "description", t: "Eigenschutz beachten! Gefahr: Ertrinken, Unterkühlung."},
		{k: "step", p: [{t: "Rettung erfolgt via Leiter, Brett, Stange. Gewicht muss großflächig verteilt werden."}]},
		{k: "step", p: [{t: "Andere Personen um Mithilfe auffordern. Notruf absetzen lassen."}]},
		{k: "step", p: [{t: "Auf Bauch (möglichst angeseilt) mit Hilfsmittel vorsichtig zur Einbruchstelle robben."}]},
		{k: "image", i: "aid041"},
		{k: "step", p: [{t: "Verunglücktem auf Distanz das Hilfsmittel reichen (nicht die Hand!) und herausziehen."}]},
		{k: "step", p: [{t: "Rückwärts bis zum Ufer zurückrobben."}]},
		{k: "step", p: [{t: "Erste-Hilfe-Maßnahmen."}]},
		{k: "step", p: [{t: "Eigenrettung möglich: Bei festem Eis Gewicht auf Eis verteilen und sich selbst herausziehen. Flach auf Bauch zum Ufer zurückrobben. Bei brüchigem Eis versuchen Eis bis zum Ufer Stück für Stück abzubrechen."}]}
	],
	aid_insectstings: [
		{k: "title", t: "Insektenstich", i: "aid046"},
		{k: "description", t: "Schwellungen, Hautausschlag, brennendes Gefühl, Schwäche, Atemnot, Kreislaufprobleme, Herzrasen."},
		{k: "step", p: [{t: "Stachel vorsichtig entfernen (mit Pinzette). Nicht auf Stachel drücken, könnte noch mehr Gift injizieren."}]},
		{k: "step", p: [{t: "Kühlung der betroffenen Stelle (kalte Kompresse)."}]},
		{k: "step", p: [{t: "Betroffene Stelle niedriger als Herz-Höhe halten, damit Gift langsamer zirkuliert."}]},
		{k: "step", p: [{t: "Bei Stich im Mund-Rachen-Raum: Eis lutschen lassen, kalte Umschläge um Hals."}]},
		{k: "image", i: "aid046ice"},
		{k: "step", p: [{t: "Bei ernsten Beschwerden Notruf absetzen."}]}
	],
	aid_nosebleeding: [
		{k: "title", t: "Nasenbluten"},
		{k: "description", t: "Kleine Ader in Nasenspitze geplatzt."},
		{k: "step", p: [{t: "Blutenden leicht nach vorne gelehnt hinsetzen. Kopf gerade halten."}]},
		{k: "step", p: [{t: "Nicht flach lagern, da Kopf über Herz-Höhe Bluten verlangsamt."}]},
		{k: "step", p: [{t: "Kalter Nackenumschlag."}]},
		{k: "step", p: [{t: "Nasenspitze bis zum Stopp der Blutung zudrücken (für 10 min)."}]},
		{k: "step", p: [{t: "Anschließend Nase in keiner Weise anstrengen (kein Naseschnauben)."}]},
		{k: "step", p: [{t: "Bei ernsten Beschwerden oder wenn Blutung anhält Notruf absetzen."}]}
	],
	aid_poisining: [
		{k: "title", t: "Vergiftung", i: "aid052"},
		{k: "description", t: "Verwirrung, Halluzination, große Pupillen, Fieber, Krämpfe. Bewusstlosigkeit."},
		{k: "step", p: [{t: "Gegenmittel nur verabreichen, wenn medizinisch ausgebildete Person vor Ort."}]},
		{k: "image", i: "aid056"},
		{k: "step", p: [{t: "Keine Getränke geben. Kein Erbrechen auslösen."}]},
		{k: "step", p: [{t: "Notruf absetzen + auf Vergiftung hinweisen!"}]},
		{k: "step", p: [{t: "Giftreste und Erbrochenes sicherstellen!"}]},
		{k: "image", i: "aid054a"},
		{k: "step", p: [{t: "Sofern Betroffener bewusstlos ist und atmet: "}, {t: "Stabile Seitenlage", h: "#aid_recoveryposition"}, {t: " herstellen. Bewusstsein und Atmung kontrollieren bis Notarzt eintrifft."}]},
		{k: "step", p: [{t: "Sofern keine Atmung: Maßnahmen zur "}, {t: "Wiederbelebung einleiten", h: "#aid_resuscitation"}, {t: ". Mund vorher von eventuell Erbrochenem befreien."}]}
	],
	aid_recoveryposition: [
		{k: "title", t: "Stabile Seitenlage"},
		{k: "step", p: [{t: "Betroffenen in Rückenlage, Beine ausstrecken. Daneben knien."}]},
		{k: "step", p: [{t: "Nahen Arm im rechten Winkel zum Körper positionieren."}]},
		{k: "step", p: [{t: "Fernen Arm über Brust des Verletzten ziehen und Handrücken auf Wange platzieren."}]},
		{k: "image", i: "aid008"},
		{k: "step", p: [{t: "Entferntes Knie fassen, zu sich ziehen und auf Boden legen. Bein etwa im rechten Winkel positionieren. Hand des Betroffenen bleibt auf dessen Wange."}]},
		{k: "step", p: [{t: "Sicherstellen, dass Atemwege frei sind."}]},
		{k: "step", p: [{t: "Kopf in Nacken beugen, Kinn anheben. Mund leicht öffnen. Atmung kontrollieren."}]},
		{k: "image", i: "aid009"},
		{k: "step", p: [{t: "Bewusstsein und Atmung kontrollieren bis Notarzt eintrifft."}]},
		{k: "description", t: "Stabile Seitenlage (Baby):"},
		{k: "image", i: "aid028"}
	],
	aid_resuscitation: [
		{k: "title", t: "Wiederbelebung"},
		{k: "subsection", t: "# Herzdruckmassage"},
		{k: "step", p: [{t: "Betroffenen in Rückenlage. Daneben hinknien."}]},
		{k: "step", p: [{t: "Brustkorb freimachen."}]},
		{k: "step", p: [{t: "In der Mitte des Brustkorbs (kurz über Brustbein) einen Handballen platzieren."}]},
		{k: "image", i: "aid013"},
		{k: "step", p: [{t: "Anderen Handballen auf Handrücken der bereits platzierten Hand."}]},
		{k: "step", p: [{t: "Arme, Ellbogen durchdrücken."}]},
		{k: "image", i: "aid003"},
		{k: "step", p: [{t: "Brustkorb des Betroffenen 5 cm senkrecht eindrücken (aus dem Oberkörper arbeiten) und wieder entlasten."}]},
		{k: "step", p: [{t: "30-mal in Folge kurz und kräftig drücken."}]},
		{k: "subsection", t: "# Beatmung"},
		{k: "step", p: [{t: "Entfernen von Fremdkörpern aus Mund und Rachen. Überstrecken des Kopfes in den Nacken."}]},
		{k: "image", i: "aid067"},
		{k: "step", p: [{t: "Nasenflügel zusammendrücken, damit Nase geschlossen ist."}]},
		{k: "image", i: "aid010"},
		{k: "step", p: [{t: "Tief einatmen und Mund auf Mund des Betroffenen aufsetzen, sodass keine Luft entweichen kann."}]},
		{k: "image", i: "aid011"},
		{k: "step", p: [{t: "Zweimal Mund zu Mund beatmen (langsam, vollständig ausatmen)."}]},
		{k: "step", p: [{t: "Danach wieder Herzdruckmassage."}]},
		{k: "description", t: "Herzdruckmassage + Beatmung fortführen bis Rettungsdienst kommt."},
		{k: "image", i: "aid012"},
		{k: "subsection", t: "# Wiederbelebung (Baby)"},
		{k: "step", p: [{t: "Nur zwei Finger benutzen:"}]},
		{k: "image", i: "aid029"},
		{k: "step", p: [{t: "Nicht zu stark beatmen:"}]},
		{k: "image", i: "aid030"}
	],
	aid_safeguardaccident: [
		{k: "title", t: "Unfallstelle sichern"},
		{k: "step", p: [{t: "Eigenen Pkw 50-100 m hinter Unfallstelle halten (falls Autobahn oder Landstraße). Danach Warnblinker anschalten und Warnweste anziehen."}]},
		{k: "step", p: [{t: "Warndreieck vor Unfallstelle aufstellen. Achtung: Bei einem Unfall in der Kurve, Warndreieck vor der Kurve platzieren!"}]},
		{k: "image", i: "aid111"},
		{k: "step", p: [{t: "Andere Personen um Mithilfe auffordern."}]},
		{k: "step", p: [{t: "Tür des Unfall-Pkws öffnen (falls verklemmt, mittels Wagenheber aufstemmen). Zündung ausschalten."}]},
		{k: "step", p: [{t: "Unfallopfer bergen: Abschnallen, Sitz nach hinten schieben. Verletzten "}, {t: "mit Rettungsgriff", h: "#aid_dangerzone"}, {t: " aus Wagen befreien."}]},
		{k: "image", i: "aid001"},
		{k: "step", p: [{t: "Notruf absetzen."}]},
		{k: "step", p: [{t: "Erste-Hilfe-Maßnahmen."}]}
	],
	aid_shock: [
		{k: "title", t: "Schock"},
		{k: "description", t: "Kreislauf-Störung durch mangelhafte Sauerstoffversorgung im Körper."},
		{k: "description", t: "Ursache: Verlust von Flüssigkeit, reduzierte Blutmenge."},
		{k: "description", t: "Symptome: Blässe, kalte Haut, kalter Schweiß, Unruhe."},
		{k: "step", p: [{t: "Schockursache beseitigen (z.B. Flüssigkeitsverlust stoppen, Wunde abbinden)!"}]},
		{k: "step", p: [{t: "Betroffenen auf Decke legen, Beine hoch lagern. Beruhigen."}]},
		{k: "image", i: "aid078"},
		{k: "step", p: [{t: "Notruf absetzen."}]},
		{k: "step", p: [{t: "Bei Atem- und Herz-Kreislauf-Störungen "}, {t: "Wiederbelebung einleiten", h: "#aid_resuscitation"}, {t: "."}]}
	],
	aid_skullfracture: [
		{k: "title", t: "Schädelbasisbruch"},
		{k: "description", t: "Leichte Blutungen aus Nase, Mund oder Ohr. Oft offene Wunde am Schädel."},
		{k: "step", p: [{t: "Atemwege freihalten."}]},
		{k: "step", p: [{t: "Bei Bewusstsein: Verletzten nach vorne gebeugt hinsetzen. Weitere Bewegungen vermeiden!"}]},
		{k: "step", p: [{t: "Bei Bewusstlosigkeit: "}, {t: "Stabile Seitenlage", h: "#aid_recoveryposition"}, {t: " (keinen Druck auf Kopfwunde)."}]},
		{k: "step", p: [{t: "Notruf absetzen."}]},
		{k: "step", p: [{t: "Kopfverband anlegen."}]},
		{k: "step", p: [{t: "Bei Atem- und Herz-Kreislauf-Störungen "}, {t: "Wiederbelebung einleiten", h: "#aid_resuscitation"}, {t: "."}]}
	],
	aid_snakebite: [
		{k: "title", t: "Schlangenbiss", i: "aid051"},
		{k: "description", t: "Punktförmige Wunde in Stecknadelgröße, heftige Schmerzen, Schwellung, blaurote Verfärbung. Kreislaufstörung, Schockgefahr."},
		{k: "step", p: [{t: "Verletzten Körperteil ruhigstellen"}]},
		{k: "step", p: [{t: "Kalte Umschläge auf Bissstelle."}]},
		{k: "step", p: [{t: "Schockbekämpfung."}]},
		{k: "step", p: [{t: "Notruf absetzen."}]}
	],
	aid_sos: [
		{k: "title", t: "SOS"},
		{k: "step", p: [{t: "Signal: 3x kurz, 3x lang, 3x kurz."}]},
		{k: "step", p: [{t: "Optisch (Blitzlicht, Taschenlampe) oder Akustisch (Signalpfeife, Klopfen)."}]}
	],
	aid_sprain: [
		{k: "title", t: "Verstauchung + Verrenkung"},
		{k: "description", t: "Schmerzen, Schwellung (Bluterguss), Funktionsverlust, Verformung des Gliedes."},
		{k: "step", p: [{t: "Ruhigstellung des Gliedes ausschließlich in der für Betroffenen angenehmsten Position."}]},
		{k: "step", p: [{t: "Kühlen (mit Eisbeutel)."}]},
		{k: "step", p: [{t: "Falls möglich Glied hoch lagern."}]},
		{k: "step", p: [{t: "Krankenhaus aufsuchen oder Notruf absetzen."}]}
	],
	aid_stroke: [
		{k: "title", t: "Schlaganfall"},
		{k: "description", t: "Plötzliches Lähmungs- oder Taubheitsgefühl (Gesicht, Arm, Bein), gestörtes Sprachverständnis, Sehstörung, Bewusstseinstrübung, starke Kopfschmerzen. Probleme beim Atmen und Schlucken, Kontrollverlust über Blase und Darm."},
		{k: "image", i: "aid059"},
		{k: "step", p: [{t: "Notruf absetzen!"}]},
		{k: "step", p: [{t: "Enge Kleidung lockern, keine Medikamente oder Getränke geben."}]},
		{k: "step", p: [{t: "Betroffenen bequem hinsetzen oder hinlegen. Beruhigen!"}]},
		{k: "step", p: [{t: "Bewusstsein und Atmung kontrollieren."}]},
		{k: "step", p: [{t: "Bei Atem- und Herz-Kreislauf-Störungen "}, {t: "Wiederbelebung einleiten", h: "#aid_resuscitation"}, {t: "."}]}
	],
	aid_suffocation: [
		{k: "title", t: "Ersticken"},
		{k: "description", t: "Unzureichende Sauerstoffversorgung. Luftröhre verschlossen. Gefahr: Atemstillstand."},
		{k: "description", t: "Symptome: Pfeifendes Atemgeräusch, Hustenreiz, Atemnot, Hautverfärbung."},
		{k: "image", i: "aid066"},
		{k: "step", p: [{t: "Sofort handeln! Betroffenen kräftig Husten lassen."}]},
		{k: "step", p: [{t: "Mit flacher Hand auf Rücken zwischen Schulterblättern kräftig klopfen (Babys dabei auf Unterarm legen, Kopf nach unten halten)."}]},
		{k: "image", i: "aid068"},
		{k: "image", i: "aid031"},
		{k: "step", p: [{t: "Wenn ohne Erfolg: Hinter Person stellen, Arme um Taille legen, leicht nach vorne beugen."}]},
		{k: "step", p: [{t: "Hand zur Faust ballen, auf Magen-Höhe des Betroffenen positionieren und mit anderer Hand umfassen."}]},
		{k: "image", i: "aid069"},
		{k: "step", p: [{t: "Beide Hände in Umklammerung mit hartem Stoß in Richtung Magen nach oben/innen ziehen (als ob Sie die Person hochheben wollen)."}]},
		{k: "step", p: [{t: "Bis zu 5-mal wiederholen! Luftwege sollten vom Objekt befreit sein."}]},
		{k: "step", p: [{t: "Notruf absetzen."}]},
		{k: "step", p: [{t: "Falls Maßnahme nicht erfolgreich, trotzdem fortsetzen, bis Notarzt eintrifft."}]}
	],
	aid_sunburn: [
		{k: "title", t: "Sonnenbrand"},
		{k: "step", p: [{t: "Betroffenen aus direkter Sonneneinstrahlung nehmen. Weitere Sonne meiden."}]},
		{k: "step", p: [{t: "Viel Wasser trinken, um Dehydration entgegenzuwirken."}]},
		{k: "step", p: [{t: "Bei ernsthaftem Sonnenbrand (Blasenbildung, Rötung, Schmerzen) unbedingt Arzt aufsuchen."}]},
		{k: "step", p: [{t: "Leichte Hautrötungen mit feuchten Umschlägen kühlen. After-Sun-Lotion oder Gel auftragen."}]}
	],
	aid_sunstroke: [
		{k: "title", t: "Sonnenstich"},
		{k: "description", t: "Heißer roter Kopf, kühle Haut, Übelkeit, Kopfschmerz, Schwindelgefühl. Ursache: Reizung der Hirnhaut."},
		{k: "image", i: "aid035"},
		{k: "step", p: [{t: "Kühlen Ort aufsuchen (Schatten) und Oberkörper des Betroffenen erhöht lagern."}]},
		{k: "image", i: "aid061"},
		{k: "step", p: [{t: "Mit nassen Tüchern Kopf kühlen."}]},
		{k: "step", p: [{t: "Notruf absetzen, Atmung weiterhin kontrollieren."}]},
		{k: "step", p: [{t: "Bei Bewusstsein: Ggf. kühles Getränk geben."}]},
		{k: "step", p: [{t: "Bei Atemstillstand mit Beatmung beginnen:"}]},
		{k: "step", p: [{t: "Weiter mit Beatmung!", h: "#aid_apnoea"}]},
		{k: "image", i: "aid036"}
	],
	aid_unconsciouswithbreath: [
		{k: "title", t: "Bewusstlosigkeit mit Atmung"},
		{k: "description", t: "Keine Reaktion auf Ansprache und Schütteln. Atmung vorhanden."},
		{k: "image", i: "aid057"},
		{k: "step", p: [{t: "Falls Menschen in der Nähe, diese um Mithilfe bitten."}]},
		{k: "step", p: [{t: "Stabile Seitenlage", h: "#aid_recoveryposition"}, {t: ". Kopf nach hinten ziehen, Mund öffnen, damit bei Erbrechen dieses ablaufen kann."}]},
		{k: "image", i: "aid008"},
		{k: "image", i: "aid009"},
		{k: "step", p: [{t: "Notruf absetzen."}]}
	],
	aid_unconsciouswithoutbreath: [
		{k: "title", t: "Bewusstlosigkeit ohne Atmung"},
		{k: "step", p: [{t: "Keine Reaktion vorhanden, Atmung nicht feststellbar."}]},
		{k: "image", i: "aid057"},
		{k: "step", p: [{t: "Wiederbelebung einleiten!", h: "#aid_resuscitation"}]}
	],
	aid_vomiting: [
		{k: "title", t: "Erbrechen"},
		{k: "description", t: "Folge von Übelkeit. Magen befreit sich. Ursachen: Infektion, Vergiftung, Geschwür, Medikamente, falsche Nahrung, Schwangerschaft."},
		{k: "image", i: "aid054"},
		{k: "step", p: [{t: "Gefahr für Kreislauf aufgrund Flüssigkeits- und Salz-Verlustes!"}]},
		{k: "step", p: [{t: "Flüssigkeit zuführen (Tee, Wasser)."}]},
		{k: "step", p: [{t: "Bei starken Beschwerden, blutigem oder anhaltendem Erbrechen Arzt aufsuchen."}]}
	]
};
var langContinents=[
	{i: "Africa", t: "Afrika"},
	{i: "Asia", t: "Asien"},
	{i: "Europe", t: "Europa"},
	{i: "Northamerica", t: "Nord-/Zentralamerika"},
	{i: "Oceania", t: "Ozeanien"},
	{i: "Southamerica", t: "Südamerika"}
];
var langCountries=[
	{i: "afghanistan", t: "Afghanistan"},
	{i: "egypt", t: "Ägypten"},
	{i: "albania", t: "Albanien"},
	{i: "algeria", t: "Algerien"},
	{i: "andorra", t: "Andorra"},
	{i: "angola", t: "Angola"},
	{i: "antiguaandbarbuda", t: "Antigua und Barbuda"},
	{i: "equatorialguinea", t: "Äquatorialguinea"},
	{i: "argentina", t: "Argentinien"},
	{i: "armenia", t: "Armenien"},
	{i: "azerbaijan", t: "Aserbaidschan"},
	{i: "ethiopia", t: "Äthiopien"},
	{i: "australia", t: "Australien"},
	{i: "bahamas", t: "Bahamas"},
	{i: "bahrain", t: "Bahrain"},
	{i: "bangladesh", t: "Bangladesch"},
	{i: "barbados", t: "Barbados"},
	{i: "belgium", t: "Belgien"},
	{i: "belize", t: "Belize"},
	{i: "benin", t: "Benin"},
	{i: "bhutan", t: "Bhutan"},
	{i: "bolivia", t: "Bolivien"},
	{i: "bosniaandherzegovina", t: "Bosnien und Herzegowina"},
	{i: "botswana", t: "Botsuana"},
	{i: "brazil", t: "Brasilien"},
	{i: "brunei", t: "Brunei"},
	{i: "bulgaria", t: "Bulgarien"},
	{i: "burkinafaso", t: "Burkina Faso"},
	{i: "burundi", t: "Burundi"},
	{i: "caymanislands", t: "Cayman Islands"},
	{i: "chile", t: "Chile"},
	{i: "china", t: "China"},
	{i: "costarica", t: "Costa Rica"},
	{i: "denmark", t: "Dänemark"},
	{i: "germany", t: "Deutschland"},
	{i: "dominica", t: "Dominica"},
	{i: "dominicanrepublic", t: "Dominikanische Republik"},
	{i: "djibouti", t: "Dschibuti"},
	{i: "ecuador", t: "Ecuador"},
	{i: "ivorycoast", t: "Elfenbeinküste"},
	{i: "elsalvador", t: "El Salvador"},
	{i: "eritrea", t: "Eritrea"},
	{i: "estonia", t: "Estland"},
	{i: "fiji", t: "Fidschi"},
	{i: "finland", t: "Finnland"},
	{i: "france", t: "Frankreich"},
	{i: "gabon", t: "Gabun"},
	{i: "gambia", t: "Gambia"},
	{i: "georgia", t: "Georgien"},
	{i: "ghana", t: "Ghana"},
	{i: "grenada", t: "Grenada"},
	{i: "greece", t: "Griechenland"},
	{i: "greenland", t: "Grönland"},
	{i: "unitedkingdom", t: "Großbritannien"},
	{i: "guatemala", t: "Guatemala"},
	{i: "guinea", t: "Guinea"},
	{i: "guinea-bissau", t: "Guinea-Bissau"},
	{i: "guyana", t: "Guyana"},
	{i: "haiti", t: "Haiti"},
	{i: "honduras", t: "Honduras"},
	{i: "hongkong", t: "Hong Kong"},
	{i: "india", t: "Indien"},
	{i: "indonesia", t: "Indonesien"},
	{i: "iraq", t: "Irak"},
	{i: "iran", t: "Iran"},
	{i: "ireland", t: "Irland"},
	{i: "iceland", t: "Island"},
	{i: "israel", t: "Israel"},
	{i: "italy", t: "Italien"},
	{i: "jamaica", t: "Jamaika"},
	{i: "japan", t: "Japan"},
	{i: "yemen", t: "Jemen"},
	{i: "jordan", t: "Jordanien"},
	{i: "cambodia", t: "Kambodscha"},
	{i: "cameroon", t: "Kamerun"},
	{i: "canada", t: "Kanada"},
	{i: "capeverde", t: "Kap Verde"},
	{i: "kazakhstan", t: "Kasachstan"},
	{i: "qatar", t: "Katar"},
	{i: "kenya", t: "Kenia"},
	{i: "kyrgyzstan", t: "Kirgisistan"},
	{i: "kiribati", t: "Kiribati"},
	{i: "colombia", t: "Kolumbien"},
	{i: "comoros", t: "Komoren"},
	{i: "congodemocraticrepublic", t: "Kongo (Demokrat. Republik)"},
	{i: "congorepublic", t: "Kongo (Republik)"},
	{i: "kosovo", t: "Kosovo"},
	{i: "croatia", t: "Kroatien"},
	{i: "cuba", t: "Kuba"},
	{i: "kurdistan", t: "Kurdistan"},
	{i: "kuwait", t: "Kuwait"},
	{i: "laos", t: "Laos"},
	{i: "lesotho", t: "Lesotho"},
	{i: "latvia", t: "Lettland"},
	{i: "lebanon", t: "Libanon"},
	{i: "liberia", t: "Liberia"},
	{i: "libya", t: "Libyen"},
	{i: "liechtenstein", t: "Liechtenstein"},
	{i: "lithuania", t: "Litauen"},
	{i: "luxembourg", t: "Luxemburg"},
	{i: "macau", t: "Macao"},
	{i: "madagascar", t: "Madagaskar"},
	{i: "malawi", t: "Malawi"},
	{i: "malaysia", t: "Malaysia"},
	{i: "maldives", t: "Malediven"},
	{i: "mali", t: "Mali"},
	{i: "malta", t: "Malta"},
	{i: "morocco", t: "Marokko"},
	{i: "marshallislands", t: "Marshallinseln"},
	{i: "mauritania", t: "Mauretanien"},
	{i: "mauritius", t: "Mauritius"},
	{i: "mayotte", t: "Mayotte"},
	{i: "macedonia", t: "Mazedonien"},
	{i: "mexico", t: "Mexiko"},
	{i: "micronesia", t: "Mikronesien"},
	{i: "moldova", t: "Moldau (Moldawien)"},
	{i: "monaco", t: "Monaco"},
	{i: "mongolia", t: "Mongolei"},
	{i: "montenegro", t: "Montenegro"},
	{i: "mozambique", t: "Mosambik"},
	{i: "myanmar", t: "Myanmar"},
	{i: "namibia", t: "Namibia"},
	{i: "nauru", t: "Nauru"},
	{i: "nepal", t: "Nepal"},
	{i: "newzealand", t: "Neuseeland"},
	{i: "nicaragua", t: "Nicaragua"},
	{i: "netherlands", t: "Niederlande"},
	{i: "niger", t: "Niger"},
	{i: "nigeria", t: "Nigeria"},
	{i: "northkorea", t: "Nordkorea"},
	{i: "norway", t: "Norwegen"},
	{i: "oman", t: "Oman"},
	{i: "austria", t: "Österreich"},
	{i: "easttimor", t: "Osttimor"},
	{i: "pakistan", t: "Pakistan"},
	{i: "palau", t: "Palau"},
	{i: "panama", t: "Panama"},
	{i: "papuanewguinea", t: "Papua-Neuguinea"},
	{i: "paraguay", t: "Paraguay"},
	{i: "peru", t: "Peru"},
	{i: "philippines", t: "Philippinen"},
	{i: "poland", t: "Polen"},
	{i: "portugal", t: "Portugal"},
	{i: "reunion", t: "Réunion"},
	{i: "rwanda", t: "Ruanda"},
	{i: "romania", t: "Rumänien"},
	{i: "russia", t: "Russland"},
	{i: "sahrawiarabdemocraticrepublic", t: "Sahara (Demokrat. Arab. Republik)"},
	{i: "stkittsandnevis", t: "Saint Kitts und Nevis"},
	{i: "stlucia", t: "Saint Lucia"},
	{i: "saintpierreandmiquelon", t: "Saint Pierre und Miquelon"},
	{i: "stvincentandgrenadines", t: "Saint Vincent und Grenadinen"},
	{i: "solomonislands", t: "Salomonen"},
	{i: "zambia", t: "Sambia"},
	{i: "samoa", t: "Samoa"},
	{i: "sanmarino", t: "San Marino"},
	{i: "saotomeandprincipe", t: "Sao Tomé und Principe"},
	{i: "saudiarabia", t: "Saudi-Arabien"},
	{i: "sweden", t: "Schweden"},
	{i: "switzerland", t: "Schweiz"},
	{i: "senegal", t: "Senegal"},
	{i: "serbia", t: "Serbien"},
	{i: "seychelles", t: "Seychellen"},
	{i: "sierraleone", t: "Sierra Leone"},
	{i: "zimbabwe", t: "Simbabwe"},
	{i: "singapore", t: "Singapur"},
	{i: "slovakia", t: "Slowakei"},
	{i: "slovenia", t: "Slowenien"},
	{i: "somalia", t: "Somalia"},
	{i: "spain", t: "Spanien"},
	{i: "srilanka", t: "Sri Lanka"},
	{i: "southafrica", t: "Südafrika"},
	{i: "sudan", t: "Sudan"},
	{i: "southkorea", t: "Südkorea"},
	{i: "suriname", t: "Suriname"},
	{i: "swaziland", t: "Swasiland"},
	{i: "syria", t: "Syrien"},
	{i: "tajikistan", t: "Tadschikistan"},
	{i: "taiwan", t: "Taiwan"},
	{i: "tanzania", t: "Tansania"},
	{i: "thailand", t: "Thailand"},
	{i: "togo", t: "Togo"},
	{i: "tonga", t: "Tonga"},
	{i: "trinidadandtobago", t: "Trinidad und Tobago"},
	{i: "chad", t: "Tschad"},
	{i: "czechrepublic", t: "Tschechien"},
	{i: "tunisia", t: "Tunesien"},
	{i: "turkey", t: "Türkei"},
	{i: "turkmenistan", t: "Turkmenistan"},
	{i: "tuvalu", t: "Tuvalu"},
	{i: "uganda", t: "Uganda"},
	{i: "ukraine", t: "Ukraine"},
	{i: "hungary", t: "Ungarn"},
	{i: "uruguay", t: "Uruguay"},
	{i: "uzbekistan", t: "Usbekistan"},
	{i: "vanuatu", t: "Vanuatu"},
	{i: "vaticancity", t: "Vatikanstadt"},
	{i: "venezuela", t: "Venezuela"},
	{i: "unitedarabemirates", t: "Vereinigte Arabische Emirate"},
	{i: "unitedstatesofamerica", t: "Vereinigten Staaten von Amerika"},
	{i: "vietnam", t: "Vietnam"},
	{i: "belarus", t: "Weißrussland"},
	{i: "centralafricanrepublic", t: "Zentralafrikanische Republik"},
	{i: "cyprus", t: "Zypern"}
];
